import type { BilingualText } from "../hazardData";
import { phase4SceneLabel } from "./phase4SceneLabels.ts";

/** Interface labels only, not authored hazard advice. Unknown tokens fail closed. */
const translations = `
air-source=مصدر الانبعاث الهوائي
spill-source=مصدر الانسكاب
chemical-source=المصدر الكيميائي
exposed-material=المادة المكشوفة
ust=خزان تخزين تحت الأرض
leak-point=نقطة التسرب
soil-zone=منطقة التربة
excavation-zone=منطقة الحفر
soil-column=عمود التربة
water-table=منسوب المياه الجوفية
groundwater=المياه الجوفية
groundwater-plume=سحابة تلوث المياه الجوفية
migration-path=مسار الانتقال
soil-water-path=مسار التربة إلى المياه
surface-release=الانبعاث السطحي
storm-drain=مصرف مياه الأمطار
runoff-path=مسار الجريان السطحي
drift-runoff=الانجراف والجريان
outfall=المصب
surface-water=المياه السطحية
receptor-zone=منطقة المستقبل
treatment=المعالجة
control-device=جهاز التحكم
wastewater-source=مصدر مياه الصرف
rainfall=هطول المطر
site-boundary=حدود الموقع
application-path=مسار التطبيق
threat-source=مصدر التهديد
threat-zone=منطقة التهديد
credential-control=التحقق من الهوية
entry-point=نقطة الدخول
controlled-entry=الدخول المنضبط
perimeter=المحيط
alarm-communication=الإنذار والاتصال
protected-space=المكان المحمي
intrusion-path=مسار التسلل
responder-entry=دخول المستجيبين
response-zone=منطقة الاستجابة
hazmat-storage=تخزين المواد الخطرة
tamper-point=نقطة العبث
facility=المنشأة
critical-system=النظام الحرج
utility-impact=تأثير المرافق
suspicious-object=الجسم المشبوه
isolation-zone=منطقة العزل
affected-area=المنطقة المتأثرة
weather-hazard=خطر الطقس
threat-report=بلاغ التهديد
assembly-area=منطقة التجمع
accountability=حصر الأفراد
shelter-evacuation=الاحتماء أو الإخلاء
evacuation-route=مسار الإخلاء
exit-routes=مسارات الخروج
load-resistance=مقاومة الحمل
body-posture=وضعية الجسم
posture-angle=زاوية الوضعية
grip-zone=منطقة القبضة
reach-zone=منطقة الوصول
lift-origin=بداية الرفع
lift-destination=وجهة الرفع
force-vector=اتجاه القوة
neck-angle=زاوية الرقبة
spine-angle=زاوية العمود الفقري
spine-zone=منطقة العمود الفقري
static-body-zone=منطقة الجسم الثابتة
neutral-posture=الوضعية المحايدة
shoulder-elevation=ارتفاع الكتف
joint-deviation=انحراف المفصل
hand-arm=اليد والذراع
keyboard-reach=الوصول إلى لوحة المفاتيح
control-reach=الوصول إلى أدوات التحكم
hand-path=مسار اليد
overhead-reach=الوصول فوق الرأس
worker-envelope=حيز العامل
chair-support=دعم الكرسي
support-point=نقطة الدعم
padding-control=وسادة الحماية
adjustability=قابلية الضبط
vehicle-seat=مقعد المركبة
contact-edge=حافة التلامس
pressure-zone=منطقة الضغط
work-surface=سطح العمل
work-height=ارتفاع العمل
task-height=ارتفاع المهمة
display-height=ارتفاع الشاشة
clearance-zone=منطقة الخلوص
surface-condition=حالة السطح
vibration-path=مسار الاهتزاز
work-cycle=دورة العمل
repetition-cycle=دورة التكرار
duration-indicator=مؤشر المدة
task-rate=معدل المهمة
fatigue-level=مستوى التعب
performance-zone=منطقة الأداء
recovery-time=وقت التعافي
rest-cycle=دورة الراحة
noise-source=مصدر الضوضاء
source=المصدر
source-a=المصدر أ
source-b=المصدر ب
source-c=المصدر ج
impulse-source=مصدر الصوت النبضي
vibrating-tool=الأداة المهتزة
sound-field=المجال الصوتي
combined-field=المجال المشترك
worker-ear-zone=منطقة أذن العامل
hearing-threshold=عتبة السمع
hearing-protector=واقي السمع
fit-zone=منطقة الملاءمة
dose-meter=مقياس الجرعة
audiogram=مخطط السمع
noise-history=تاريخ الضوضاء
control-program=برنامج التحكم
sound-level=مستوى الصوت
exposure-time=مدة التعرض
time-pattern=النمط الزمني
noise-bursts=دفعات الضوضاء
quiet-period=فترة الهدوء
residual-exposure=التعرض المتبقي
peak-wave=موجة الذروة
reflected-paths=المسارات المنعكسة
hard-surfaces=الأسطح الصلبة
absorption-control=وسيلة الامتصاص
barrier-control=وسيلة الحاجز
isolation-control=وسيلة العزل
distance-control=التحكم بالمسافة
hand-arm-path=مسار اليد والذراع
hot-humid-zone=منطقة حارة ورطبة
cold-source=مصدر البرودة
cold-exposure=التعرض للبرودة
heat-load=الحمل الحراري
extreme-heat-load=الحمل الحراري الشديد
worker-heat-load=الحمل الحراري على العامل
work-capacity=القدرة على العمل
workload=عبء العمل
fatigue-zone=منطقة التعب
worker-cold-load=حمل البرودة على العامل
shivering=الارتعاش
core-temperature=حرارة الجسم الداخلية
thermoregulation-failure=فشل التنظيم الحراري
body-water=ماء الجسم
skin-zone=منطقة الجلد
sweat=العرق
sweating=التعرق
sweat-loss=فقد العرق
humidity=الرطوبة
wetness=البلل
extremity=الطرف
freezing-zone=منطقة التجمد
muscle-zone=منطقة العضلات
standing-worker=العامل الواقف
circulation=الدورة الدموية
wind-exposure=التعرض للرياح
wind-path=مسار الرياح
fluid-loss=فقد السوائل
fluid-intake=تناول السوائل
hydration=الترطيب
cool-area=منطقة باردة
rest-area=منطقة الراحة
cooling-response=استجابة التبريد
warm-shelter=مأوى دافئ
warming-control=وسيلة التدفئة
insulation-control=وسيلة العزل الحراري
drying-control=وسيلة التجفيف
emergency-zone=منطقة الطوارئ
alpha-source=مصدر ألفا
beta-source=مصدر بيتا
gamma-source=مصدر غاما
neutron-source=مصدر النيوترونات
xray-source=مصدر الأشعة السينية
uv-source=مصدر الأشعة فوق البنفسجية
infrared-source=مصدر الأشعة تحت الحمراء
visible-source=مصدر الضوء المرئي
rf-source=مصدر الترددات الراديوية
microwave-source=مصدر الموجات الدقيقة
antenna=الهوائي
field=المجال
field-zone=منطقة المجال
penetrating-field=المجال النافذ
near-field=المجال القريب
short-range=المدى القصير
beam=الحزمة
radiant-path=مسار الإشعاع
eye-path=مسار العين
skin-path=مسار الجلد
internal-route=المسار الداخلي
eye-zone=منطقة العين
glare-zone=منطقة الوهج
eye-skin-zone=منطقة العين والجلد
shield=الدرع
shielding=التدريع
filter-control=وسيلة الترشيح
access-control=التحكم بالدخول
controlled-area=المنطقة الخاضعة للتحكم
distance=المسافة
laser-source=مصدر الليزر
direct-beam=الحزمة المباشرة
reflection=الانعكاس
beam-stop=حاجز إيقاف الحزمة
reactor=المفاعل
vessel=الوعاء
process-unit=وحدة العملية
reaction-zone=منطقة التفاعل
pressure-zone=منطقة الضغط
temperature-zone=منطقة درجة الحرارة
temperature-rise=ارتفاع درجة الحرارة
reaction-rate=معدل التفاعل
hazardous-deviation=الانحراف الخطر
temperature-pressure-trigger=مسبب الحرارة أو الضغط
chemical-container=حاوية المواد الكيميائية
liquid-container=حاوية السائل
chemical-a=المادة الكيميائية أ
chemical-b=المادة الكيميائية ب
oxidizer-source=مصدر المؤكسد
reactive-material=المادة التفاعلية
peroxide-container=حاوية البيروكسيد
pyrophoric-source=المصدر التلقائي الاشتعال
gas-source=مصدر الغاز
cryogenic-container=حاوية التبريد العميق
unknown-material=مادة مجهولة
fuel-source=مصدر الوقود
waste-container=حاوية النفايات
inerting-control=التحكم بالغاز الخامل
cold-zone=منطقة البرودة
air-contact=ملامسة الهواء
water-contact=ملامسة الماء
release-source=مصدر الانبعاث
release-point=نقطة الانبعاث
failure-point=نقطة الفشل
corrosion-zone=منطقة التآكل
degradation-zone=منطقة التدهور
material-of-construction=مادة التصنيع
mixing-point=نقطة الخلط
process-introduction=إدخال العملية
decomposition-path=مسار التحلل
gas-release=انبعاث الغاز
plume=عمود الانبعاث
airborne-plume=عمود الانبعاث المحمول بالهواء
vapor-cloud=سحابة البخار
vapor-zone=منطقة البخار
splash-path=مسار التناثر
fire-path=مسار الحريق
spill-pool=بركة الانسكاب
splash-zone=منطقة التناثر
worker-contact-zone=منطقة ملامسة العامل
exposure-zone=منطقة التعرض
ignition-zone=منطقة الاشتعال
flash-zone=منطقة الوميض
containment=الاحتواء
containment-boundary=حد الاحتواء
containment-control=وسيلة الاحتواء
separation-control=وسيلة الفصل
segregation=الفصل
cooling-control=وسيلة التبريد
relief-system=نظام التنفيس
discharge-path=مسار التصريف
blocked-relief=تنفيس مسدود
blocked-flow=تدفق مسدود
sensor=المستشعر
interlock=القفل التعشيقي
alarm=الإنذار
process-variable=متغير العملية
shutdown-control=وسيلة الإيقاف
response-control=وسيلة الاستجابة
backup-system=النظام الاحتياطي
shutdown-path=مسار الإيقاف
bypass=التجاوز
missed-warning=تحذير فائت
utility-source=مصدر المرافق
utility-loss=فقد المرافق
process-fluid=مائع العملية
drain-path=مسار التصريف
change-request=طلب التغيير
hazard-review=مراجعة المخاطر
authorization=التصريح
implementation=التنفيذ
readiness-check=فحص الجاهزية
open-action=إجراء غير مكتمل
startup-sequence=تسلسل بدء التشغيل
storage-rack=رف التخزين
incompatible-storage=تخزين غير متوافق
storage-zone=منطقة التخزين
flammable-zone=منطقة قابلة للاشتعال
incompatible-zone=منطقة عدم التوافق
secondary-containment=الاحتواء الثانوي
labeling=وضع الملصقات
container-condition=حالة الحاوية
waste-area=منطقة النفايات
flame-zone=منطقة اللهب
blast-zone=منطقة موجة الضغط
bond-ground=الربط والتأريض
charge-build-up=تراكم الشحنة
spark-discharge=تفريغ الشرارة
self-heating-material=مادة ذاتية التسخين
heat-build-up=تراكم الحرارة
dust-cloud=سحابة الغبار
dust-layer=طبقة الغبار
explosion-zone=منطقة الانفجار
hot-work-source=مصدر العمل الساخن
torch-arc=الشعلة أو القوس
hot-metal=المعدن الساخن
spark-path=مسار الشرر
combustible-zone=منطقة المواد القابلة للاحتراق
fire-watch=مراقب الحريق
sprinkler-network=شبكة الرشاشات
closed-valve=صمام مغلق
detectors=أجهزة الكشف
impaired-detector=كاشف معطل
suppression-path=مسار الإخماد
alarm-path=مسار الإنذار
fire-class=فئة الحريق
extinguisher=طفاية الحريق
approach-path=مسار الاقتراب
escape-route=مسار الهروب
hazard-source=مصدر الخطر
control-point=نقطة التحكم
collapse-zone=منطقة الانهيار
soil-face=وجه التربة
protective-system=نظام الحماية
surcharge-load=الحمل الإضافي
surcharge-zone=منطقة الحمل الإضافي
spoil-pile=كومة ناتج الحفر
utility-lines=خطوط المرافق
strike-point=نقطة الاصطدام
water-level=منسوب المياه
inflow-path=مسار التدفق إلى الداخل
pump-zone=منطقة الضخ
atmosphere-volume=حجم الجو الداخلي
monitoring-point=نقطة المراقبة
ventilation-path=مسار التهوية
access-point=نقطة الوصول
blocked-exit=مخرج مسدود
egress-path=مسار الخروج
equipment-edge-zone=منطقة المعدات قرب الحافة
excavator-path=مسار الحفار
adjacent-structure=المنشأة المجاورة
soil-removal=إزالة التربة
wall-stress=إجهاد الجدار
support-zone=منطقة الدعم
oxygen-deficient-atmosphere=جو ناقص الأكسجين
oxygen-enriched-atmosphere=جو غني بالأكسجين
toxic-atmosphere=جو سام
flammable-atmosphere=جو قابل للاشتعال
monitor=جهاز الرصد
ventilation=التهوية
entrant=العامل الداخل
attendant=المراقب الخارجي
entry-supervisor=مشرف الدخول
source-release=انبعاث المصدر
ignition-source=مصدر الاشتعال
connected-line=الخط المتصل
isolation=العزل
isolation-point=نقطة العزل
engulfment-material=مادة الغمر
tapered-floor=الأرضية المتضيقة
converging-walls=الجدران المتقاربة
entrapment-zone=منطقة الاحتجاز
moving-equipment=المعدات المتحركة
inlet-path=مسار المدخل
permit=التصريح
electrical-source=المصدر الكهربائي
capacitor-battery=المكثف أو البطارية
mechanical-source=المصدر الميكانيكي
hydraulic-source=المصدر الهيدروليكي
accumulator=المراكم
stored-pressure=الضغط المختزن
pneumatic-source=مصدر الهواء المضغوط
air-line=خط الهواء
thermal-source=المصدر الحراري
hot-cold-zone=منطقة الحرارة أو البرودة
chemical-inventory=مخزون المواد الكيميائية
process-source=مصدر العملية
residual-sources=المصادر المتبقية
stored-energy=الطاقة المختزنة
multiple-energy-sources=مصادر طاقة متعددة
energy-sources=مصادر الطاقة
isolation-devices=أجهزة العزل
disconnect=جهاز الفصل
group-lock-box=صندوق القفل الجماعي
valve=الصمام
line-valves=صمامات الخطوط
drain-purge=التصريف والتطهير
verification=التحقق
verification-step=خطوة التحقق
worker-zone=منطقة العامل
worker-danger-zone=منطقة خطر العامل
restraint=التقييد
block-restraint=الصد والتقييد
elevated-component=المكون المرتفع
gravity-path=مسار الجاذبية
bleed-down=تنفيس الضغط
cooldown=التبريد
reaccumulation=إعادة التراكم
pressure-source=مصدر الضغط
pressure-vessel=وعاء الضغط
vacuum-vessel=وعاء التفريغ
pressure-rise=ارتفاع الضغط
relief-device=جهاز تنفيس الضغط
rupture-zone=منطقة التمزق
implosion-zone=منطقة الانهيار إلى الداخل
heat-zone=منطقة الحرارة
rupture-path=مسار التمزق
external-pressure-arrows=اتجاهات الضغط الخارجي
pressurized-hose=خرطوم مضغوط
hydraulic-line=الخط الهيدروليكي
hot-fluid-line=خط السائل الساخن
coupling-failure=فشل الوصلة
pinhole-leak=تسرب من ثقب دقيق
whip-path=مسار الارتداد السوطي
hand-zone=منطقة اليد
worker-face-zone=منطقة وجه العامل
injection-path=مسار الحقن
cylinder=الأسطوانة
release-path=مسار الانبعاث
release-cloud=سحابة الانبعاث
projectile-zone=منطقة المقذوفات
compressed-air-source=مصدر الهواء المضغوط
tool-source=مصدر الأداة
air-jet=نفث الهواء
flying-particles=الجسيمات المتطايرة
actuator-motion=حركة المشغل
`;
const labels = Object.fromEntries(translations.trim().split("\n").map(line => line.split("="))) as Record<string, string>;
export function finalSceneLabel(token: string): BilingualText {
  const ar = labels[token];
  if (!ar) return phase4SceneLabel(token);
  const en = token.replaceAll("-", " ");
  return { en: en.charAt(0).toUpperCase() + en.slice(1), ar };
}
