/**
 * Supplemental original ASP practice content aligned structurally to ASP11.
 * No item reproduces wording from an examination or commercial study bank.
 */

import type { ASPQuestion } from "./aspQuestionBankA";

export const ASP_QUESTION_BANK_EXTRA_SET1: readonly ASPQuestion[] = [
  {
    id: "A1-011",
    domainId: "A1",
    competency: "Incident-rate calculations",
    objective: "Calculate an exposure-normalized case rate using a stated formula.",
    difficulty: 1,
    stem: "Use rate = cases x 200,000 / hours worked. A facility records 6 cases during 300,000 work hours. What is the rate?",
    options: ["2.0", "4.0", "6.0", "9.0"],
    correctIndex: 1,
    rationale: "Rate = 6 x 200,000 / 300,000 = 4.0 cases per 200,000 work hours.",
    wrongRationales: [
      "This divides cases by hours but omits the stated 200,000-hour normalization factor.",
      "Correct. The normalized rate is 4.0.",
      "This repeats the raw case count rather than normalizing it for hours worked.",
      "This result does not follow the stated numerator and denominator.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Exposure-normalized incident rates",
    challengePrompt: "Explain why comparing raw case counts between facilities with very different work hours can reverse the apparent ranking.",
  },
  {
    id: "A1-012",
    domainId: "A1",
    competency: "Temperature conversion",
    objective: "Convert a Celsius temperature to Fahrenheit.",
    difficulty: 1,
    stem: "Using F = (9/5)C + 32, what Fahrenheit temperature corresponds to 35 degrees C?",
    options: ["63 degrees F", "67 degrees F", "95 degrees F", "104 degrees F"],
    correctIndex: 2,
    rationale: "(9/5) x 35 = 63, and 63 + 32 = 95 degrees F.",
    wrongRationales: [
      "This is only the multiplied Celsius term and omits the 32-degree offset.",
      "This adds 32 directly to 35 without applying the 9/5 factor.",
      "Correct. Thirty-five degrees C equals 95 degrees F.",
      "This is the conversion of 40 degrees C, not 35 degrees C.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Temperature scales and unit conversion",
    challengePrompt: "Convert 14 degrees F to Celsius and show how you know the sign of the result is reasonable.",
  },
  {
    id: "A1-013",
    domainId: "A1",
    competency: "Flow and duct calculations",
    objective: "Calculate volumetric flow from average velocity and circular duct area.",
    difficulty: 2,
    stem: "Air moves at an average 1,200 ft/min through a round duct 10 in. in diameter. Using area = pi x diameter squared / 4 and 1 ft = 12 in., what is the approximate flow?",
    options: ["654 cfm", "545 cfm", "785 cfm", "1,200 cfm"],
    correctIndex: 0,
    rationale: "Diameter = 10/12 = 0.833 ft. Area = pi x 0.833^2 / 4, approximately 0.545 ft2. Flow = 1,200 x 0.545, approximately 654 cfm.",
    wrongRationales: [
      "Correct. Multiplying the approximately 0.545 ft2 area by 1,200 ft/min gives about 654 cfm.",
      "This is approximately the duct area expressed with misplaced units, not velocity times area.",
      "This uses pi x radius-like terms incorrectly and overstates the circular area.",
      "This treats velocity as though it were already volumetric flow.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Circular area and ventilation flow",
    challengePrompt: "Determine the new average velocity if the same flow passes through an 8 in. diameter duct.",
  },
  {
    id: "A1-014",
    domainId: "A1",
    competency: "Excavation volume calculations",
    objective: "Calculate excavation volume from a trapezoidal cross-section.",
    difficulty: 2,
    stem: "A 40 ft long excavation has a uniform trapezoidal cross-section 6 ft deep, 4 ft wide at the bottom, and 10 ft wide at the top. What is the excavated volume?",
    options: ["960 ft3", "1,440 ft3", "1,680 ft3", "2,400 ft3"],
    correctIndex: 2,
    rationale: "Trapezoid area = (4 + 10)/2 x 6 = 42 ft2. Multiplying by 40 ft gives 1,680 ft3.",
    wrongRationales: [
      "This uses only the 4 ft bottom width and ignores the sloped sides.",
      "This applies an average width of 6 ft rather than the correct 7 ft.",
      "Correct. The 42 ft2 cross-section over 40 ft yields 1,680 ft3.",
      "This uses the full top width for the entire depth and overstates the trapezoidal area.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Trapezoidal areas and excavation volume",
    challengePrompt: "Convert the result to cubic yards and add a stated 20% swell factor for hauling estimates.",
  },
  {
    id: "A1-015",
    domainId: "A1",
    competency: "Static equilibrium and moments",
    objective: "Calculate a counterweight needed to balance an idealized lever system.",
    difficulty: 3,
    stem: "For an idealized stationary lifting beam, a 1,800 lb load acts 4 ft to the right of the pivot. A counterweight acts 6 ft to the left. Ignoring beam weight and any design factor, what counterweight balances the moments?",
    options: ["600 lb", "1,200 lb", "1,800 lb", "2,700 lb"],
    correctIndex: 1,
    rationale: "Moment balance requires 1,800 x 4 = W x 6. Thus W = 7,200/6 = 1,200 lb.",
    wrongRationales: [
      "This is half the required counterweight and would not balance the 7,200 ft-lb load moment.",
      "Correct. A 1,200 lb counterweight at 6 ft creates 7,200 ft-lb of opposing moment.",
      "This ignores the different lever-arm distances.",
      "This reverses the arm ratio and produces excessive opposing moment.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Moments and equilibrium",
    challengePrompt: "Explain why balancing static moments alone is insufficient for approving an actual lifting device.",
  },
  {
    id: "A1-016",
    domainId: "A1",
    competency: "Financial evaluation",
    objective: "Calculate simple payback and first-year return from stated cash flows.",
    difficulty: 3,
    stem: "A machine-guarding redesign costs $72,000 and is expected to avoid $24,000 in annual losses while adding $6,000 in annual maintenance. Ignoring discounting, what are the simple payback period and first-year net return on the initial investment?",
    options: [
      "3 years and 33.3%",
      "4 years and 25.0%",
      "6 years and 16.7%",
      "12 years and 8.3%",
    ],
    correctIndex: 1,
    rationale: "Annual net benefit = $24,000 - $6,000 = $18,000. Payback = $72,000/$18,000 = 4 years. First-year net return = $18,000/$72,000 = 25.0%.",
    wrongRationales: [
      "This uses gross avoided loss and ignores annual maintenance cost.",
      "Correct. The $18,000 annual net benefit gives 4 years and 25.0%.",
      "This understates the annual net benefit by treating more than the stated maintenance as recurring cost.",
      "These values use only the $6,000 maintenance figure as though it were the benefit.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Payback and return on investment",
    challengePrompt: "Describe two important benefits or uncertainties that this simple financial calculation does not capture.",
  },
  {
    id: "A1-017",
    domainId: "A1",
    competency: "Statistical estimation",
    objective: "Calculate and interpret a confidence interval for a mean using a stated approximation.",
    difficulty: 4,
    stem: "A sample of 64 measurements has mean 48 and standard deviation 8. Using the approximation 95% confidence interval = mean plus or minus 1.96(s/square root of n), what interval results?",
    options: ["40.0 to 56.0", "46.0 to 50.0", "47.0 to 49.0", "47.8 to 48.2"],
    correctIndex: 1,
    rationale: "Standard error = 8/sqrt(64) = 1. The margin is 1.96 x 1 = 1.96, so the interval is approximately 46.0 to 50.0.",
    wrongRationales: [
      "This adds and subtracts one standard deviation rather than the stated confidence margin based on standard error.",
      "Correct. The interval is 48 plus or minus approximately 2.",
      "This uses a margin of one standard error and omits the 1.96 multiplier.",
      "This divides by the sample size rather than by its square root when calculating standard error.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Standard error and confidence intervals",
    challengePrompt: "Explain what becomes narrower if sample size quadruples while variability stays constant, and why.",
  },
  {
    id: "A1-018",
    domainId: "A1",
    competency: "Gas-law calculations",
    objective: "Apply the combined gas law using absolute temperature.",
    difficulty: 4,
    stem: "A sealed flexible gas sample occupies 20 L at 100 kPa and 300 K. It changes to 125 kPa and 330 K with no gas lost. Using P1V1/T1 = P2V2/T2, what is the final volume?",
    options: ["14.5 L", "17.6 L", "22.0 L", "27.5 L"],
    correctIndex: 1,
    rationale: "V2 = P1 x V1 x T2 /(T1 x P2) = 100 x 20 x 330 /(300 x 125) = 17.6 L.",
    wrongRationales: [
      "This overstates the pressure-driven contraction and does not include the temperature increase correctly.",
      "Correct. Increased pressure reduces volume while increased absolute temperature partly offsets that reduction.",
      "This applies only the temperature ratio and ignores the pressure change.",
      "This reverses the pressure ratio, predicting expansion despite the larger final pressure.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Combined gas law",
    challengePrompt: "Explain why substituting temperatures in degrees Celsius would invalidate this proportional calculation.",
  },
  {
    id: "A1-019",
    domainId: "A1",
    competency: "Radiation attenuation calculations",
    objective: "Determine shielding thickness from half-value layers.",
    difficulty: 5,
    stem: "A source produces 320 units/hour at a location. Shielding material has a half-value layer of 1.5 cm. Ignoring buildup and leakage, what thickness reduces the rate to 20 units/hour?",
    options: ["3.0 cm", "4.5 cm", "6.0 cm", "7.5 cm"],
    correctIndex: 2,
    rationale: "The required reduction is 320/20 = 16 = 2^4, so four half-value layers are needed. Thickness = 4 x 1.5 = 6.0 cm.",
    wrongRationales: [
      "Two half-value layers reduce the rate by a factor of 4, leaving 80 units/hour.",
      "Three layers reduce by a factor of 8, leaving 40 units/hour.",
      "Correct. Four half-value layers provide the stated factor-of-16 reduction.",
      "Five layers would reduce the idealized rate to 10 units/hour, more shielding than the calculation requests.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Half-value layers and exponential attenuation",
    challengePrompt: "State why scattering, penetrations, source geometry, and measurement uncertainty still matter in a real shielding design.",
  },
  {
    id: "A1-020",
    domainId: "A1",
    competency: "Voting-system reliability",
    objective: "Calculate reliability for a two-out-of-three sensor vote in series with an actuator.",
    difficulty: 5,
    stem: "Three independent sensors each succeed on demand with probability 0.90. A two-out-of-three vote succeeds if at least two sensors succeed. The voted signal then requires an independent actuator with success probability 0.95. What is the approximate overall success probability?",
    options: ["0.7290", "0.8550", "0.9234", "0.9720"],
    correctIndex: 2,
    rationale: "Voting success = 3(0.90^2 x 0.10) + 0.90^3 = 0.243 + 0.729 = 0.972. Series success with the actuator is 0.972 x 0.95 = 0.9234.",
    wrongRationales: [
      "This is the probability that all three sensors succeed and omits both valid two-sensor combinations and the actuator.",
      "This multiplies one sensor probability by actuator reliability and ignores the voting logic.",
      "Correct. The two-out-of-three subsystem reliability is 0.972, and the actuator reduces overall success to 0.9234.",
      "This is only the voted sensor-subsystem success probability and omits the series actuator.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Redundancy, voting logic, and series reliability",
    challengePrompt: "Explain why common-cause sensor failure would make the independence-based result optimistic.",
  },

  {
    id: "A3-011",
    domainId: "A3",
    competency: "Ergonomic risk-factor recognition",
    objective: "Recognize contact stress as a distinct ergonomic exposure.",
    difficulty: 1,
    stem: "An employee rests the inside of the wrist against a sharp metal bench edge while entering data for several hours. Which ergonomic risk factor is most directly present?",
    options: ["Contact stress", "Whole-body vibration", "Thermal strain", "Glare"],
    correctIndex: 0,
    rationale: "Localized pressure from a hard or sharp edge against soft tissue is contact stress. Duration and constrained posture may add risk, but the edge-tissue interaction is the factor described most directly.",
    wrongRationales: [
      "Correct. The bench edge concentrates pressure on the wrist tissues.",
      "No vibrating seat, platform, or vehicle exposure is described.",
      "The scenario does not identify heat-producing environmental or metabolic conditions.",
      "Visual discomfort may affect computer work, but no lighting or reflection problem is stated.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Contact stress and workstation edges",
    challengePrompt: "Propose one design correction and one observation that would verify the wrist no longer bears concentrated pressure.",
  },
  {
    id: "A3-012",
    domainId: "A3",
    competency: "Vibration exposure control",
    objective: "Prioritize source and task controls for hand-arm vibration.",
    difficulty: 2,
    stem: "Employees report tingling after prolonged use of aging handheld grinders. Which initial control strategy is strongest?",
    options: [
      "Tell employees to grip the tool as tightly as possible",
      "Measure and compare vibration under representative use, maintain or replace high-vibration tools, improve tooling and process conditions, limit exposure as needed, and evaluate reported symptoms",
      "Issue thicker gloves and assume vibration is controlled",
      "Wait until a permanent impairment is diagnosed",
    ],
    correctIndex: 1,
    rationale: "Effective management combines exposure characterization with source reduction, correct tool-process matching, maintenance, work design, and health follow-up. Grip force can increase transmitted loading, and gloves alone do not establish adequate attenuation.",
    wrongRationales: [
      "Excessive grip can increase muscular demand and vibration transmission rather than reduce risk.",
      "Correct. The approach controls the source and duration while responding to possible early health effects.",
      "Gloves may address cold or grip conditions but cannot be assumed to provide meaningful vibration control without evidence.",
      "Delayed action permits potentially progressive exposure and ignores early warning symptoms.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Hand-arm vibration assessment and control",
    challengePrompt: "List three operating variables that could make the same grinder produce different vibration exposures across tasks.",
  },
  {
    id: "A3-013",
    domainId: "A3",
    competency: "Metabolic workload",
    objective: "Calculate time-weighted average metabolic demand over a work cycle.",
    difficulty: 3,
    stem: "A repeating 40-minute work cycle includes 30 minutes at 6 kcal/min and 10 minutes at 2 kcal/min. What is the cycle's time-weighted average metabolic rate?",
    options: ["2.0 kcal/min", "4.0 kcal/min", "5.0 kcal/min", "8.0 kcal/min"],
    correctIndex: 2,
    rationale: "Energy per cycle = (30 x 6) + (10 x 2) = 200 kcal. Dividing by 40 minutes gives 5.0 kcal/min.",
    wrongRationales: [
      "This represents only the lower-demand recovery segment.",
      "This is the unweighted mean of 6 and 2 and ignores their unequal durations.",
      "Correct. The duration-weighted metabolic rate is 5.0 kcal/min.",
      "This adds the two rates rather than weighting them over the cycle.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Time-weighted metabolic demand",
    challengePrompt: "Calculate the recovery duration needed to reduce the cycle average to 4.0 kcal/min if task duration and both rates stay unchanged.",
  },
  {
    id: "A3-014",
    domainId: "A3",
    competency: "Hand-tool biomechanics",
    objective: "Compare wrist moments for two tool configurations.",
    difficulty: 3,
    stem: "For a simplified comparison, wrist moment equals applied force times perpendicular moment arm. An old tool requires 70 N at 0.12 m from the wrist; a redesigned tool requires 50 N at 0.04 m. Approximately what percent reduction in wrist moment does the redesign provide?",
    options: ["24%", "50%", "67%", "76%"],
    correctIndex: 3,
    rationale: "Old moment = 70 x 0.12 = 8.4 N-m. New moment = 50 x 0.04 = 2.0 N-m. Reduction = (8.4 - 2.0)/8.4 x 100, approximately 76%.",
    wrongRationales: [
      "This is close to the remaining fraction, not the percent reduction.",
      "This considers the force reduction alone and not the much shorter moment arm.",
      "This does not follow the before-and-after moment calculation.",
      "Correct. The moment falls by 6.4 N-m from an 8.4 N-m baseline, approximately 76%.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Moment arms in hand-tool design",
    challengePrompt: "Name two usability factors that must still be tested before selecting the redesigned tool.",
  },
  {
    id: "A3-015",
    domainId: "A3",
    competency: "Fatigue and work organization",
    objective: "Control fatigue risk created by scheduling and task design.",
    difficulty: 4,
    stem: "A maintenance outage uses rapidly rotating day and night shifts, frequent 14-hour duties, unpredictable call-backs, and safety-critical troubleshooting near the end of shifts. Coffee is freely available. What is the strongest fatigue-risk response?",
    options: [
      "Treat caffeine access as sufficient control",
      "Tell workers to obtain more sleep without changing the schedule",
      "Redesign staffing and schedules to protect recovery and limit high-risk work at circadian lows or after extended duty, assess fitness and commute risk, provide controlled breaks and handoffs, and monitor fatigue indicators",
      "Use injury counts after the outage as the only evaluation",
    ],
    correctIndex: 2,
    rationale: "Fatigue is shaped by duty duration, timing, rotation, sleep opportunity, task criticality, and recovery. A system approach changes these determinants, adds operational checks, and monitors precursors rather than relying on stimulants or retrospective injuries.",
    wrongRationales: [
      "Caffeine may temporarily alter alertness but does not restore sleep or correct unsafe duty patterns.",
      "Personal advice cannot create adequate sleep opportunity when organizational scheduling removes it.",
      "Correct. The plan addresses schedule, task timing, recovery, handoff, individual state, and learning together.",
      "Injuries are sparse, delayed outcomes and cannot reveal many fatigue-related errors or near misses.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Fatigue risk management systems",
    challengePrompt: "Propose two leading indicators that could warn of fatigue degradation before an injury occurs.",
  },
  {
    id: "A3-016",
    domainId: "A3",
    competency: "Low-back biomechanics",
    objective: "Estimate extensor-muscle force needed to balance external moments.",
    difficulty: 5,
    stem: "In a simplified static model, a 200 N box acts 0.40 m in front of the low back and a 350 N upper-body segment acts 0.25 m in front. If the back-extensor muscle moment arm is 0.050 m, what muscle force is required to balance the external moment? Ignore other forces.",
    options: ["838 N", "1,675 N", "3,350 N", "8,375 N"],
    correctIndex: 2,
    rationale: "External moment = (200 x 0.40) + (350 x 0.25) = 80 + 87.5 = 167.5 N-m. Muscle force = 167.5/0.050 = 3,350 N.",
    wrongRationales: [
      "This effectively divides by 0.20 m rather than the stated 0.050 m muscle moment arm.",
      "This is half the force needed to balance the calculated external moment.",
      "Correct. A short 0.050 m internal moment arm requires approximately 3,350 N of muscle force.",
      "This result treats the moment-arm relationship incorrectly and substantially overstates the stated model result.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Static biomechanical equilibrium",
    challengePrompt: "Explain why actual spinal compression is not determined by simply adding the box weight to this muscle-force estimate.",
  },

  {
    id: "A4-011",
    domainId: "A4",
    competency: "Fire detection",
    objective: "Match detection technology to the expected fire signature and desired response.",
    difficulty: 1,
    stem: "For an office area where a slowly developing, smoldering fire is credible, which device generally offers earlier warning of that fire signature than a fixed-temperature heat detector?",
    options: ["A suitable smoke detector", "A pressure gauge", "A manual sprinkler valve", "A fire pump churn timer"],
    correctIndex: 0,
    rationale: "A suitable smoke detector is intended to respond to combustion products that may develop before enough heat reaches a fixed-temperature detector. Actual selection and placement must fit the environment and nuisance sources.",
    wrongRationales: [
      "Correct. Smoke detection generally targets the earlier smoldering-fire signature described.",
      "A pressure gauge indicates system pressure and does not sense smoke or fire.",
      "A valve controls water-system configuration but does not provide automatic fire detection.",
      "A churn timer relates to pump operation and cannot detect a developing office fire.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Smoke and heat detection principles",
    challengePrompt: "Give one environment where a heat detector might be more reliable than a smoke detector and explain the tradeoff.",
  },
  {
    id: "A4-012",
    domainId: "A4",
    competency: "Passive fire protection",
    objective: "Preserve the protective function of a fire door.",
    difficulty: 1,
    stem: "A rated corridor door is routinely wedged open for convenience even though it is intended to close automatically during a fire. What is the primary concern?",
    options: [
      "The wedge may make the door paint fade",
      "The open door can allow smoke and fire to spread through the barrier before occupants reach safety",
      "The door will increase sprinkler pressure",
      "The wedge will make smoke detectors too sensitive",
    ],
    correctIndex: 1,
    rationale: "The door is part of a compartmentation system. Defeating closure creates an opening through which heat and smoke can spread, undermining egress and fire separation.",
    wrongRationales: [
      "Cosmetic wear is not the life-safety function at issue.",
      "Correct. A blocked-open door defeats the intended compartment boundary.",
      "Door position does not create greater sprinkler pressure.",
      "A wedge has no direct mechanism for increasing detector sensitivity.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Fire doors and compartmentation",
    challengePrompt: "Describe a convenience-friendly design that can hold the door open normally without defeating automatic closure during fire conditions.",
  },
  {
    id: "A4-013",
    domainId: "A4",
    competency: "Means of egress",
    objective: "Recognize continuity of an unobstructed exit path as a life-safety requirement.",
    difficulty: 1,
    stem: "Pallets temporarily narrow the only path from a production room to its exit door. What is the best immediate action?",
    options: [
      "Leave them until the next scheduled inspection",
      "Remove the obstruction and restore the required exit route before the room remains occupied",
      "Dim the exit sign so employees notice the pallets",
      "Add a warning label to each pallet and continue work",
    ],
    correctIndex: 1,
    rationale: "An exit route must remain usable when an emergency occurs. Labels and later inspections do not restore present egress capacity or protect against delay, congestion, and trip hazards.",
    wrongRationales: [
      "Emergency need is unpredictable, so deferring correction leaves occupants exposed now.",
      "Correct. Restoring the route addresses the immediate life-safety deficiency.",
      "Reducing exit-sign visibility worsens wayfinding and does not remove the blockage.",
      "Warning labels do not create adequate clear passage.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Exit-route continuity and obstruction control",
    challengePrompt: "Identify one management-system change that would prevent temporary storage from recurring in the route.",
  },
  {
    id: "A4-014",
    domainId: "A4",
    competency: "Flammable-liquid properties",
    objective: "Interpret flash point without confusing it with automatic ignition.",
    difficulty: 2,
    stem: "What does a liquid's flash point most directly describe?",
    options: [
      "The temperature at which the liquid must ignite without an external source",
      "The lowest test-condition temperature at which it produces enough vapor to form an ignitable mixture near its surface when an ignition source is applied",
      "The temperature at which all liquid instantly becomes vapor",
      "The maximum temperature a storage tank can structurally withstand",
    ],
    correctIndex: 1,
    rationale: "Flash point concerns formation of an ignitable vapor-air mixture under a defined test and with an ignition source. It is distinct from autoignition temperature, boiling point, and equipment design temperature.",
    wrongRationales: [
      "Ignition without an external source describes autoignition behavior, not flash point.",
      "Correct. Flash point is a test-based indication of ignitable vapor generation.",
      "Complete vaporization relates more closely to boiling behavior and is not required for flash.",
      "Tank structural limits are equipment design properties rather than liquid flash point.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Flash point, boiling point, and autoignition",
    challengePrompt: "Explain why operating below flash point can reduce risk but does not prove that no ignitable vapor can exist anywhere in a process.",
  },
  {
    id: "A4-015",
    domainId: "A4",
    competency: "Flammable-vapor behavior",
    objective: "Use relative vapor density to anticipate accumulation locations.",
    difficulty: 2,
    stem: "A solvent vapor has relative density 2.5 compared with air. During a leak in a still room, where should initial monitoring and ventilation assessment give special attention?",
    options: [
      "Only at the ceiling because all vapors rise",
      "Low points, pits, drains, and poorly mixed floor-level areas, while still checking the full release geometry",
      "Only outdoors, regardless of the indoor source",
      "Inside sealed electrical panels that have no connection to the room",
    ],
    correctIndex: 1,
    rationale: "A vapor substantially denser than air can migrate and collect in low or poorly ventilated areas. Turbulence, temperature, source momentum, and ventilation can alter the pattern, so density guides rather than replaces measurement.",
    wrongRationales: [
      "Denser vapor tends toward low areas under quiescent conditions rather than only the ceiling.",
      "Correct. It targets credible accumulation zones without assuming perfect stratification.",
      "Outdoor monitoring cannot characterize the indoor leak and worker exposure by itself.",
      "An isolated enclosure with no pathway is not the priority accumulation location described.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Vapor density and dispersion",
    challengePrompt: "Name two conditions that could defeat a simple assumption that the densest vapor concentration will always be at floor level.",
  },
  {
    id: "A4-016",
    domainId: "A4",
    competency: "Incipient-stage fire response",
    objective: "Apply safe go/no-go criteria before attempting portable-extinguisher use.",
    difficulty: 2,
    stem: "A trained employee sees a small wastebasket fire. Which condition set best supports a limited extinguisher attempt?",
    options: [
      "The employee can identify a suitable extinguisher, the alarm or notification has been initiated, the fire remains small and not rapidly spreading, smoke is tolerable, and a clear exit stays behind the employee",
      "The employee must pass through heavy smoke to reach the extinguisher",
      "The fire involves an unknown pressurized cylinder",
      "The employee's exit can be cut off as long as the extinguisher is full",
    ],
    correctIndex: 0,
    rationale: "Portable-extinguisher action is appropriate only within training and plan limits, with a suitable agent, early notification, manageable fire conditions, and protected escape. Deteriorating or uncertain conditions require withdrawal.",
    wrongRationales: [
      "Correct. These conditions preserve early warning, agent suitability, tenability, and escape.",
      "Heavy smoke signals unacceptable exposure and loss of tenable access.",
      "Unknown cylinder involvement creates escalation and rupture hazards beyond a routine incipient attempt.",
      "A protected exit is fundamental; extinguisher capacity does not guarantee control or escape.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Portable-extinguisher decision criteria",
    challengePrompt: "Identify two observations that should make the employee abandon an attempt already in progress.",
  },
  {
    id: "A4-017",
    domainId: "A4",
    competency: "Fire-resistance integrity",
    objective: "Maintain rated barriers when services penetrate them.",
    difficulty: 3,
    stem: "A contractor runs new cable through a rated wall and fills the oversized opening with ordinary packing foam. What is the strongest corrective response?",
    options: [
      "Paint the foam the same color as the wall",
      "Verify the barrier and penetration requirements, remove the unsuitable fill, and install a listed or otherwise approved firestop system matching the assembly and penetrating item, with inspection and records",
      "Leave the opening because cables do not burn",
      "Add a smoke detector beside the penetration instead of restoring the wall",
    ],
    correctIndex: 1,
    rationale: "A penetration can compromise the tested barrier unless restored with a compatible system installed within its conditions of use. Detection does not replace containment, and appearance is not evidence of rating.",
    wrongRationales: [
      "Color matching does not establish fire resistance, adhesion, movement capability, or compatibility.",
      "Correct. It restores and verifies the barrier as a complete rated system.",
      "Cables and their jackets can contribute to fire and leave a path for heat and smoke even if the conductor itself is not combustible.",
      "Detection may provide warning but cannot close the physical path through the fire barrier.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Firestopping and penetrations",
    challengePrompt: "Explain why a product labeled firestop is not automatically acceptable for every wall, annular space, and penetrating item.",
  },
  {
    id: "A4-018",
    domainId: "A4",
    competency: "Flammable-spill fire control",
    objective: "Integrate ignition control, containment, and compatible recovery for a flammable spill.",
    difficulty: 3,
    stem: "A volatile, water-immiscible flammable liquid spills near a floor drain and operating nonsuitable electrical equipment. No fire has started. What is the best response strategy?",
    options: [
      "Wash the liquid into the drain with a high-pressure water stream",
      "Control access and ignition sources safely, stop the release if feasible, protect drains, ventilate and monitor appropriately, and recover the liquid with compatible equipment under the spill plan",
      "Turn ordinary electrical fans on at the spill edge without evaluating their suitability",
      "Cover the spill with cardboard and resume work",
    ],
    correctIndex: 1,
    rationale: "The response must prevent ignition, limit environmental migration, control the source, manage vapor, and use compatible recovery equipment. Uncontrolled water or electrical equipment can spread the liquid or ignite vapor.",
    wrongRationales: [
      "Water can spread an immiscible floating liquid and carry it into drainage systems without controlling vapor.",
      "Correct. This layered response addresses source, ignition, vapor, containment, and recovery.",
      "Nonsuitable electrical equipment may become the ignition source the plan is meant to control.",
      "Cardboard is combustible, does not seal vapors, and does not provide controlled recovery.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Flammable-liquid spill response",
    challengePrompt: "Name two properties beyond flammability that determine compatible absorbent and recovery-equipment selection.",
  },
  {
    id: "A4-019",
    domainId: "A4",
    competency: "Fire-load calculations",
    objective: "Calculate fire-load energy per unit floor area.",
    difficulty: 3,
    stem: "A 400 m2 compartment contains 600 kg of material with heat of combustion 18 MJ/kg and 200 kg with heat of combustion 40 MJ/kg. Ignoring other contents, what is the fire-load density?",
    options: ["27 MJ/m2", "40 MJ/m2", "47 MJ/m2", "67 MJ/m2"],
    correctIndex: 2,
    rationale: "Total energy = (600 x 18) + (200 x 40) = 10,800 + 8,000 = 18,800 MJ. Dividing by 400 m2 gives 47 MJ/m2.",
    wrongRationales: [
      "This includes only the first material's energy divided by floor area.",
      "This copies the second material's 40 MJ/kg heat of combustion as though it were the compartment fire-load density.",
      "Correct. The combined 18,800 MJ over 400 m2 equals 47 MJ/m2.",
      "This adds the two heat-of-combustion values without weighting by mass.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Fire load and heat of combustion",
    challengePrompt: "Explain why equal fire-load density does not guarantee equal fire growth or suppression demand for different materials and arrangements.",
  },
  {
    id: "A4-020",
    domainId: "A4",
    competency: "Sprinkler discharge calculations",
    objective: "Calculate sprinkler flow from discharge coefficient and pressure.",
    difficulty: 4,
    stem: "For a sprinkler, use Q = K square root of P, where Q is gpm and P is psi. If K = 5.6 and pressure is 25 psi, what is the approximate discharge?",
    options: ["11.2 gpm", "28.0 gpm", "31.4 gpm", "140 gpm"],
    correctIndex: 1,
    rationale: "The square root of 25 is 5. Therefore Q = 5.6 x 5 = 28.0 gpm.",
    wrongRationales: [
      "This applies an unsupported factor of two rather than the square root of pressure.",
      "Correct. The stated discharge relationship yields 28.0 gpm.",
      "This resembles multiplying 5.6 by a circular constant and does not use the stated pressure relationship.",
      "This multiplies K directly by pressure instead of its square root.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Sprinkler K-factor relationship",
    challengePrompt: "Calculate the pressure required to obtain 35 gpm from the same sprinkler.",
  },
  {
    id: "A4-021",
    domainId: "A4",
    competency: "Fire-system pressure calculations",
    objective: "Combine remote pressure, elevation head, and friction loss.",
    difficulty: 4,
    stem: "A remote fire-system point needs 42 psi while flowing. It is 80 ft above the pump, and calculated pipe friction loss is 23 psi. Using 0.433 psi per foot of elevation, what minimum pump discharge pressure is required before other margins?",
    options: ["57 psi", "77 psi", "100 psi", "145 psi"],
    correctIndex: 2,
    rationale: "Elevation loss = 80 x 0.433 = 34.64 psi. Required discharge = 42 + 34.64 + 23 = 99.64 psi, approximately 100 psi.",
    wrongRationales: [
      "This does not include both the elevation and stated friction losses.",
      "This is close to remote pressure plus elevation only and omits the 23 psi friction loss.",
      "Correct. Adding remote, elevation, and friction requirements gives approximately 100 psi.",
      "This overstates the sum and appears to apply elevation in the wrong units or more than once.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Elevation head and friction loss",
    challengePrompt: "State why pump selection still requires a flow-pressure curve rather than only this single pressure sum.",
  },
  {
    id: "A4-022",
    domainId: "A4",
    competency: "Detection-system reliability",
    objective: "Calculate probability that at least one independent detector succeeds.",
    difficulty: 4,
    stem: "Two independent detectors each have a 0.90 probability of detecting a defined test fire. The alarm activates if either detector responds. Under the independence assumption, what is the detection probability?",
    options: ["0.81", "0.90", "0.95", "0.99"],
    correctIndex: 3,
    rationale: "Both fail with probability 0.10 x 0.10 = 0.01. Therefore at least one detects with probability 1 - 0.01 = 0.99.",
    wrongRationales: [
      "This is the probability both detectors succeed, which is not required by the OR logic.",
      "This is the success probability of only one detector and ignores redundancy.",
      "This averages one success and one failure probability without valid event logic.",
      "Correct. The complement of both independent detectors failing is 0.99.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Parallel detection reliability",
    challengePrompt: "Identify two common-cause conditions that could make the 0.99 result overstate field reliability.",
  },
  {
    id: "A4-023",
    domainId: "A4",
    competency: "Energy-storage fire risk",
    objective: "Develop layered controls for thermal-runaway propagation and emergency response.",
    difficulty: 5,
    stem: "A facility plans a large indoor rechargeable-battery charging and storage area beside critical operations. The vendor proposes ordinary smoke detection and portable extinguishers as the entire fire strategy. What should the ASP recommend?",
    options: [
      "Accept the proposal because all fires have identical behavior",
      "Evaluate cell and system hazards, failure propagation, separation and exposure, charging controls, early warning, ventilation and gas concerns, compatible fixed protection or cooling, emergency isolation, responder tactics, damaged-unit handling, and validated testing as an integrated design",
      "Rely only on employee odor recognition",
      "Place more batteries together so an incident occupies less floor space",
    ],
    correctIndex: 1,
    rationale: "Energy-storage failures can involve internal heat generation, re-ignition, propagation, gas release, and difficult access. A hazard-specific, tested combination of prevention, detection, separation, control, isolation, and response is needed rather than generic portable protection alone.",
    wrongRationales: [
      "Fuel chemistry, heat release, gas generation, propagation, and extinguishing needs vary materially by system.",
      "Correct. It treats the installation as a system and requires evidence that protective layers match credible failure behavior.",
      "Odor is neither a reliable early detector nor a safe basis for emergency action.",
      "Greater concentration can increase propagation potential and consequence unless specifically engineered and protected.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Battery thermal runaway and layered protection",
    challengePrompt: "Write one performance-based acceptance test for propagation control and one for emergency isolation.",
  },
  {
    id: "A4-024",
    domainId: "A4",
    competency: "Combustible-dust explosion protection",
    objective: "Select layered controls that prevent both primary and propagated dust explosions.",
    difficulty: 5,
    stem: "A mill handles explosible powder. Dust escapes at transfer points, a collector is connected to indoor equipment by ductwork, and deposits are visible on elevated surfaces. Which strategy is strongest?",
    options: [
      "Increase compressed-air cleaning so dust becomes airborne and leaves surfaces faster",
      "Confirm material explosibility data; minimize release and accumulation; use suitable capture, equipment, bonding, and ignition control; provide engineered explosion protection and isolation where needed; use safe housekeeping; and verify performance and change control",
      "Install one additional exit sign and leave the process unchanged",
      "Depend on workers to smell overheating before ignition",
    ],
    correctIndex: 1,
    rationale: "Dust risk requires prevention of hazardous clouds and deposits, control of ignition, protection against pressure and flame, and isolation that prevents propagation through connected equipment. Verification and change control keep these interdependent safeguards effective.",
    wrongRationales: [
      "Compressed air can disperse settled dust into an ignitable cloud and spread it to hidden surfaces.",
      "Correct. This package addresses fuel, dispersion, ignition, explosion consequence, and propagation as a system.",
      "Wayfinding is useful but does not control the explosion mechanisms described.",
      "Odor cannot reliably detect many ignition sources and places prevention on an uncertain human sense.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Dust-hazard analysis, explosion protection, and isolation",
    challengePrompt: "Explain how an indoor dust collector can turn a local ignition into a facility-wide event if isolation is missing.",
  },
];
