import type { ASPQuestion } from "./aspQuestionBankA";

/**
 * Original ASP11 practice content. The blueprint and named study references are
 * used only as structural lenses; no examination or commercial-bank wording is
 * reproduced here.
 */
export const ASP_QUESTION_BANK_EXTRA_SET2 = [
  {
    id: "A5-011",
    domainId: "A5",
    competency: "Evacuation and accountability",
    objective: "Select an accountability method that identifies unresolved status without delaying evacuation.",
    difficulty: 1,
    stem: "After an evacuation alarm, what is the primary purpose of accounting for people at assembly areas?",
    options: [
      "To decide who may leave work early",
      "To identify people whose status is unresolved and give responders reliable information without sending employees back inside",
      "To replace the need to notify emergency services",
      "To permit supervisors to reenter and search immediately",
    ],
    correctIndex: 1,
    rationale: "Accountability determines who is safe, absent, assigned elsewhere, or potentially still exposed. The result supports responder priorities while preventing untrained reentry.",
    wrongRationales: [
      "Accountability is a life-safety control, not a timekeeping or release process.",
      "Correct. It resolves personnel status and communicates credible gaps to the incident organization.",
      "Accounting complements emergency notification and response; it does not replace them.",
      "Employees and supervisors should not self-deploy into a hazardous area to search unless assigned, trained, equipped, and authorized.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Evacuation accountability",
    challengePrompt: "Design an accountability method for visitors and mobile employees that still works during a power and network outage.",
  },
  {
    id: "A5-012",
    domainId: "A5",
    competency: "Emergency medical readiness",
    objective: "Recognize the response sequence for a suspected sudden cardiac arrest.",
    difficulty: 1,
    stem: "A worker collapses, is unresponsive, and is not breathing normally. After confirming the scene is safe, what response is most appropriate?",
    options: [
      "Wait several minutes to see whether normal breathing returns",
      "Activate the emergency response system, begin trained resuscitation measures, and obtain an AED as quickly as possible",
      "Give the worker food and water",
      "Move the worker to a private room before calling for help",
    ],
    correctIndex: 1,
    rationale: "Rapid activation, high-quality trained care, and early defibrillation are time-critical links in response to suspected cardiac arrest. Site procedures and the responder's training govern the precise actions.",
    wrongRationales: [
      "Delay reduces the chance that time-sensitive resuscitation and defibrillation will succeed.",
      "Correct. It mobilizes professional help while trained immediate care and AED retrieval occur.",
      "An unresponsive person should not be given anything by mouth, and this does not address cardiac arrest.",
      "Privacy concerns do not justify delaying emergency activation and lifesaving care.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Medical emergency response",
    challengePrompt: "Identify four program elements needed to keep an AED program reliable between rare actual uses.",
  },
  {
    id: "A5-013",
    domainId: "A5",
    competency: "Severe-weather protective actions",
    objective: "Choose shelter locations based on the hazard rather than using one location for every emergency.",
    difficulty: 2,
    stem: "A tornado warning is issued for a single-story facility. Which location is generally the best available shelter choice?",
    options: [
      "An interior room on the lowest level, away from windows and large unsupported roof spans",
      "A glass-walled lobby where conditions can be observed",
      "A vehicle parked beside power lines",
      "The center of a wide-span warehouse beneath suspended loads",
    ],
    correctIndex: 0,
    rationale: "For wind and debris hazards, an interior low-level location away from glazing, exterior walls, and large roof spans is generally preferred, subject to site-specific structural and emergency guidance.",
    wrongRationales: [
      "Correct. It reduces exposure to glazing, windborne debris, and vulnerable wide-span roof areas.",
      "Glass and exterior exposure increase the hazard from wind and debris.",
      "Vehicles and nearby utility lines generally provide poorer protection than a suitable building refuge.",
      "Wide-span roofs and suspended objects can create collapse and struck-by hazards during severe wind.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Natural-hazard sheltering",
    challengePrompt: "Explain why the best location for a tornado may be a poor choice for an outdoor toxic release.",
  },
  {
    id: "A5-014",
    domainId: "A5",
    competency: "Exercise design and evaluation",
    objective: "Use an exercise to test capability and generate verifiable improvements.",
    difficulty: 2,
    stem: "Which practice makes an emergency drill most useful for program improvement?",
    options: [
      "Announce every inject and expected answer in advance so no gap can appear",
      "Measure only total evacuation time",
      "Set capability-based objectives, observe critical actions, conduct a structured debrief, assign corrective actions, and verify closure in a later test",
      "Treat participant confusion as misconduct and exclude it from the report",
    ],
    correctIndex: 2,
    rationale: "A drill should generate evidence about defined capabilities, reveal system gaps, and drive owned corrective work whose effectiveness is retested. One aggregate time cannot explain communication, accountability, or command performance.",
    wrongRationales: [
      "Over-scripting can demonstrate rehearsal while concealing whether people and systems can respond to realistic variation.",
      "Evacuation time is useful but cannot by itself evaluate warning, assistance, accountability, decision quality, or communications.",
      "Correct. This closes the loop from objective through observation, improvement, and verification.",
      "Confusion is valuable performance evidence and should be analyzed without reflexive blame.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Emergency exercise evaluation",
    challengePrompt: "Write three observable evaluation criteria for a chemical-release shelter-in-place drill.",
  },
  {
    id: "A5-015",
    domainId: "A5",
    competency: "Incident command",
    objective: "Apply unity of command while retaining access to technical expertise.",
    difficulty: 3,
    stem: "During a spill response, two managers give a response-team member conflicting assignments. What incident-management principle should correct the problem?",
    options: [
      "Each responder should choose whichever instruction seems faster",
      "Unity of command: each individual reports to one designated supervisor while technical specialists advise through the established structure",
      "All technical specialists should command field operations independently",
      "The most senior person on site should personally direct every task",
    ],
    correctIndex: 1,
    rationale: "Unity of command gives each responder one clear supervisory line, reducing conflicting orders and accountability gaps. Technical expertise remains available through defined command and advisory roles.",
    wrongRationales: [
      "Self-selection creates inconsistent priorities and can defeat coordinated risk control.",
      "Correct. It preserves clear authority without excluding specialist input.",
      "Independent field commands reproduce the conflict and fragment operational control.",
      "Effective command delegates within a scalable structure; one person directing every detail can become a bottleneck.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Incident command organization",
    challengePrompt: "Differentiate unity of command from unified command using a multi-agency emergency example.",
  },
  {
    id: "A5-016",
    domainId: "A5",
    competency: "Security threat response",
    objective: "Respond to a suspicious package without increasing exposure or destroying information.",
    difficulty: 3,
    stem: "An employee finds an unexpected package with oily staining, protruding wires, and no credible return information. What is the best immediate action?",
    options: [
      "Carry it outdoors to protect the building",
      "Open it carefully to identify the sender",
      "Do not touch or move it, isolate the immediate area, avoid actions that could trigger it, and notify site security or emergency authorities under the plan",
      "Place it in a desk drawer until the end of the shift",
    ],
    correctIndex: 2,
    rationale: "The safest initial approach avoids handling, controls access, limits potential triggering actions, and activates qualified assessment under the emergency and security plan.",
    wrongRationales: [
      "Moving a suspicious item exposes the carrier and others and may initiate a device or disperse material.",
      "Opening the package directly increases exposure and can destroy evidence.",
      "Correct. It controls immediate exposure while bringing appropriate expertise to the scene.",
      "Concealment leaves the hazard uncontrolled and delays response.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Human-caused emergency recognition",
    challengePrompt: "List the information a caller should be prepared to provide without approaching the package again.",
  },
  {
    id: "A5-017",
    domainId: "A5",
    competency: "Business continuity",
    objective: "Use impact analysis to prioritize restoration of dependent processes.",
    difficulty: 4,
    stem: "A business impact analysis sets a four-hour recovery time objective for customer dispatch, but dispatch depends on a server assigned a twelve-hour objective and on backup power tested only for two hours. What is the strongest conclusion?",
    options: [
      "The four-hour dispatch objective is credible because it appears in an approved document",
      "The dependency objectives and backup capability are inconsistent with dispatch recovery and must be reconciled and tested end to end",
      "Each department may set objectives independently because continuity plans do not share resources",
      "Recovery time objectives measure only financial insurance limits",
    ],
    correctIndex: 1,
    rationale: "A process cannot reliably recover before essential upstream services and resources. The mismatched server objective and unproven power duration make the four-hour commitment unsupported until dependencies are redesigned or objectives revised and validated.",
    wrongRationales: [
      "Approval does not overcome incompatible technical dependencies or insufficient tested endurance.",
      "Correct. Continuity claims must reflect dependency sequencing and demonstrated capability.",
      "Shared technology, utilities, people, and vendors make independent departmental assumptions unreliable.",
      "A recovery time objective defines a target duration for restoring a process or service, not an insurance amount.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Business impact analysis and recovery dependencies",
    challengePrompt: "Map the minimum recovery sequence and identify one single point of failure that the current objectives hide.",
  },
  {
    id: "A5-018",
    domainId: "A5",
    competency: "Protective-action decision making",
    objective: "Select evacuation or sheltering based on release behavior and route conditions.",
    difficulty: 4,
    stem: "A short-duration toxic gas release occurs outside an occupied building. The plume crosses the normal evacuation route, the building can rapidly shut outdoor-air intake, and indoor concentrations are currently below action criteria. What is the best initial protective-action decision?",
    options: [
      "Evacuate everyone immediately through the visible plume",
      "Shelter in place, shut and control air pathways, account for occupants, monitor conditions, and prepare for controlled relocation if the decision criteria change",
      "Open all doors to equalize pressure",
      "Allow each occupant to choose independently without communication",
    ],
    correctIndex: 1,
    rationale: "When evacuation would cross the hazard and the building can temporarily reduce infiltration, controlled sheltering may provide lower immediate exposure. The decision remains dynamic and depends on monitoring, plume duration, building protection, and alternate routes.",
    wrongRationales: [
      "Evacuating through the plume can create greater exposure than temporary sheltering.",
      "Correct. It selects the lower-exposure initial action while preserving monitoring and transition criteria.",
      "Opening doors increases contaminant entry and defeats the available protective feature.",
      "Uncoordinated individual action prevents accountability and may direct people into the release.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Evacuation versus shelter-in-place",
    challengePrompt: "State four measurable triggers that could shift the decision from sheltering to relocation.",
  },
  {
    id: "A5-019",
    domainId: "A5",
    competency: "Workplace violence prevention",
    objective: "Use behavior-based multidisciplinary threat assessment rather than profiling.",
    difficulty: 5,
    stem: "A recently disciplined employee makes an ambiguous grievance, coworkers report escalating fixation on a supervisor, and social-media posts show access to weapons but no explicit threat. What is the most defensible organizational response?",
    options: [
      "Ignore the information because no direct threat was spoken",
      "Immediately publicize a diagnosis and accuse the employee of a crime",
      "Activate a trained multidisciplinary threat-assessment process, preserve and corroborate facts, evaluate behaviors and access, protect potential targets, coordinate lawful interventions, and monitor changes",
      "Rely only on whether the employee matches a demographic profile",
    ],
    correctIndex: 2,
    rationale: "Threat assessment evaluates concerning behavior, context, capability, stressors, protective factors, and change over time. It should support proportionate safety action while protecting privacy, due process, and lawful reporting.",
    wrongRationales: [
      "Concerning patterns may warrant assessment before an explicit threat; waiting can forfeit prevention opportunities.",
      "Public accusation and unsupported diagnosis can harm people, compromise assessment, and violate legitimate rights.",
      "Correct. It integrates safety, security, human resources, legal, behavioral, and law-enforcement considerations proportionately.",
      "Demographic profiling is neither a reliable nor fair substitute for evidence-based behavioral assessment.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Behavioral threat assessment",
    challengePrompt: "Distinguish a concerning communication from evidence of intent, capability, and imminence, and explain why all four matter.",
  },
  {
    id: "A5-020",
    domainId: "A5",
    competency: "Lone-worker emergency safeguards",
    objective: "Design a resilient response system for a remote high-consequence task.",
    difficulty: 5,
    stem: "A technician works alone at a remote pump station where hydrogen sulfide could be released. Cellular coverage is intermittent, travel time for rescue is 35 minutes, and the proposed control is a text message at the end of the shift. What is the best redesign?",
    options: [
      "Keep the end-of-shift text because lone workers are responsible for their own rescue",
      "Add a sign warning the technician to be careful",
      "Use task-specific entry criteria and gas controls, reliable personal detection, redundant timed check-ins or automatic distress/location signaling, missed-contact escalation, trained rescue capability matched to response time, and authority to suspend work when safeguards fail",
      "Ask a family member to call the site if the technician is late",
    ],
    correctIndex: 2,
    rationale: "A delayed single-channel check cannot detect or respond to rapid incapacitation. The control system must prevent exposure, detect changing conditions and loss of worker status, communicate despite coverage limits, and deliver a realistic rescue response.",
    wrongRationales: [
      "The organization retains responsibility for foreseeable work hazards, and an end-of-shift message is too late for an acute toxic emergency.",
      "A warning does not detect gas, worker incapacity, or communication failure and cannot provide rescue.",
      "Correct. It treats prevention, detection, communications, escalation, rescue, and degraded-mode authority as one system.",
      "Family notification is delayed, unreliable, and outside the controlled emergency-response system.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Remote and lone-worker response design",
    challengePrompt: "Perform a barrier review for simultaneous loss of cellular service and personal monitor telemetry.",
  },

  {
    id: "A6-011",
    domainId: "A6",
    competency: "Industrial hygiene process",
    objective: "Sequence anticipation, recognition, evaluation, control, and confirmation activities.",
    difficulty: 1,
    stem: "Before a new resin process starts, what is the most preventive industrial-hygiene action?",
    options: [
      "Wait for workers to report symptoms after production begins",
      "Anticipate agents and exposure pathways from process information, then design the evaluation and controls before startup",
      "Purchase respirators without determining the contaminants",
      "Collect only area samples after the first incident",
    ],
    correctIndex: 1,
    rationale: "Anticipation uses materials, tasks, energy sources, conditions, and credible failure modes before exposure begins. It enables source controls and a targeted exposure-assessment plan before workers become the detector.",
    wrongRationales: [
      "Symptom waiting is reactive, insensitive, and potentially harmful.",
      "Correct. Early anticipation supports prevention and efficient, hypothesis-driven evaluation.",
      "Respirator selection requires hazard, concentration, atmosphere, task, and program information.",
      "Area sampling alone after harm neither anticipates risk nor necessarily represents personal exposure.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Anticipation and recognition of health hazards",
    challengePrompt: "List the process information you would request to build a pre-startup qualitative exposure assessment.",
  },
  {
    id: "A6-012",
    domainId: "A6",
    competency: "Routes of entry",
    objective: "Identify a route of entry and match controls to it.",
    difficulty: 1,
    stem: "A solvent can pass readily through intact skin and has low airborne concentration during a hand-wiping task. Which conclusion is most appropriate?",
    options: [
      "Low airborne concentration proves total exposure is negligible",
      "Dermal absorption may be important, so substitution, closed handling, splash prevention, compatible gloves, and hygiene practices should be evaluated",
      "Only hearing protection is needed",
      "Skin contact matters only when a visible burn occurs",
    ],
    correctIndex: 1,
    rationale: "Occupational dose can enter through routes other than inhalation. A material capable of skin absorption requires route-specific source, engineering, work-practice, and protective controls even when air results are low.",
    wrongRationales: [
      "Air measurements do not quantify dermal uptake and cannot establish total dose by themselves.",
      "Correct. It recognizes the relevant route and applies a layered control strategy.",
      "Hearing protection does not address solvent skin absorption.",
      "Systemic absorption may occur without immediate visible skin damage.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Dermal exposure and routes of entry",
    challengePrompt: "Explain why glove breakthrough time, permeation rate, task duration, and reuse practice must be evaluated together.",
  },
  {
    id: "A6-013",
    domainId: "A6",
    competency: "Biological hazards and universal precautions",
    objective: "Apply standard precautions to potentially infectious blood.",
    difficulty: 1,
    stem: "A first-aid responder encounters blood on a worker whose infection status is unknown. What assumption should guide controls?",
    options: [
      "Treat the blood as potentially infectious and use the required barrier, hygiene, sharps, cleanup, and exposure-response procedures",
      "Use precautions only if the worker reports a diagnosed infection",
      "Dilute the blood with bare hands because the volume is small",
      "Ask a coworker without training to clean it after the shift",
    ],
    correctIndex: 0,
    rationale: "Standard or universal precaution principles avoid relying on known diagnosis. They require planned controls for blood and specified body fluids, including post-exposure response when an incident occurs.",
    wrongRationales: [
      "Correct. Unknown status does not remove the need for infection-control precautions.",
      "Many infections are unknown or undisclosed, so diagnosis-based precautions are unreliable.",
      "Bare-hand contact creates avoidable exposure, and dilution does not replace controlled cleanup.",
      "Cleanup requires trained, equipped personnel and timely control of the contaminated area.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Bloodborne-pathogen precautions",
    challengePrompt: "Outline the immediate and follow-up steps after an unprotected splash to a responder's eyes.",
  },
  {
    id: "A6-014",
    domainId: "A6",
    competency: "Toxicology",
    objective: "Distinguish acute effects from chronic effects and latency.",
    difficulty: 2,
    stem: "Which statement best distinguishes an acute toxic effect from a chronic toxic effect?",
    options: [
      "Acute effects always involve skin, while chronic effects always involve lungs",
      "Acute effects generally follow short-term exposure or appear rapidly; chronic effects often develop after repeated or long-duration exposure and may have latency",
      "Chronic effects are always reversible",
      "Exposure concentration is irrelevant to both types",
    ],
    correctIndex: 1,
    rationale: "Acute and chronic describe exposure/effect time patterns, not a fixed organ or reversibility. Dose, duration, frequency, susceptibility, and latency influence the observed outcome.",
    wrongRationales: [
      "Either pattern can affect many organs depending on the agent and dose.",
      "Correct. It captures the general temporal distinction without claiming a universal outcome.",
      "Chronic effects may be reversible, persistent, progressive, or fatal depending on the hazard.",
      "Concentration and cumulative dose are central determinants of toxic response.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Dose-response and effect timing",
    challengePrompt: "Give one example in which a single high exposure causes a delayed effect and explain why the simple labels require care.",
  },
  {
    id: "A6-015",
    domainId: "A6",
    competency: "Atmospheric hazards",
    objective: "Interpret oxygen concentration as one component of atmospheric assessment.",
    difficulty: 2,
    stem: "A direct-reading instrument reports 20.9% oxygen at the opening of a tank. What is the best conclusion about entry conditions?",
    options: [
      "The atmosphere is proven safe at every depth and time",
      "Normal oxygen at one point does not rule out toxic or flammable contaminants, stratification, or changing conditions; calibrated representative testing and controls are still required",
      "No ventilation or monitoring can ever be needed",
      "The reading proves no chemical process occurred in the tank",
    ],
    correctIndex: 1,
    rationale: "Oxygen is only one atmospheric parameter, and a single location and moment may miss other agents or layers. Instrument capability, calibration, sampling locations, sequence, interference, and continuous change all matter.",
    wrongRationales: [
      "A point reading cannot represent the entire space or future conditions.",
      "Correct. It treats the reading as limited evidence within a complete atmospheric assessment.",
      "Ventilation and continued monitoring may be needed based on hazards and entry conditions.",
      "Normal oxygen does not exclude toxic vapor, flammable material below an alarm threshold, or prior chemical activity.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Atmospheric testing limitations",
    challengePrompt: "Develop a vertical and temporal sampling plan for a vapor denser than air in a deep vessel.",
  },
  {
    id: "A6-016",
    domainId: "A6",
    competency: "Heat stress",
    objective: "Recognize interacting contributors to heat strain and select layered controls.",
    difficulty: 2,
    stem: "Two employees perform the same outdoor task, but one wears impermeable protective clothing and recently returned after two weeks away. Why may that employee need additional heat controls?",
    options: [
      "Protective clothing always cools the body by trapping sweat",
      "The clothing can impair evaporative cooling, and reduced acclimatization can increase physiologic strain",
      "Heat risk depends only on air temperature",
      "Acclimatization is permanent once achieved",
    ],
    correctIndex: 1,
    rationale: "Heat strain reflects environment, metabolic workload, clothing, health, hydration, and acclimatization. Impermeable ensembles impede heat loss, while an absence can reduce prior adaptation.",
    wrongRationales: [
      "Trapped moisture without evaporation limits an important heat-loss mechanism.",
      "Correct. Both the clothing correction and acclimatization status can increase risk at the same ambient conditions.",
      "Radiant heat, humidity, air movement, workload, clothing, and individual factors also matter.",
      "Adaptation can diminish after time away and should be reassessed during return.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Heat balance and acclimatization",
    challengePrompt: "Build a return-to-heat-work plan that distinguishes workload controls from individual medical decisions.",
  },
  {
    id: "A6-017",
    domainId: "A6",
    competency: "Exposure assessment strategy",
    objective: "Design representative sampling for a nonuniform workforce.",
    difficulty: 3,
    stem: "A facility has 80 workers across four tasks, two shifts, and variable use of local exhaust. Resources allow only twelve personal samples. What is the strongest initial strategy?",
    options: [
      "Sample the first twelve volunteers and apply the mean to everyone",
      "Define similar exposure groups from task, agent, conditions, controls, and shift; prioritize plausible worst cases and uncertain groups; document selection; and use results to refine later sampling",
      "Collect only one outdoor background sample",
      "Sample only managers because they can explain the process",
    ],
    correctIndex: 1,
    rationale: "Exposure grouping and risk-based selection use limited samples to test meaningful hypotheses. Transparent selection and iterative refinement reduce the false confidence created by convenience sampling.",
    wrongRationales: [
      "Volunteers may not represent high-exposure tasks, shifts, or degraded controls.",
      "Correct. It structures representative coverage while deliberately targeting uncertainty and potential high exposure.",
      "Background information cannot substitute for breathing-zone exposure during work.",
      "Managers' descriptions may inform recognition, but their exposures usually do not represent production tasks.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Similar exposure groups and sampling design",
    challengePrompt: "Explain how you would respond if results within one proposed group span an order of magnitude.",
  },
  {
    id: "A6-018",
    domainId: "A6",
    competency: "Noise control",
    objective: "Select a source-path-receiver control strategy for excessive noise.",
    difficulty: 3,
    stem: "A compressor exposes an operator above the site's criterion. The operator must remain nearby, and a removable acoustic enclosure can reduce sound without impairing cooling or access. Which action should receive priority?",
    options: [
      "Install and verify the engineered enclosure while controlling residual exposure through the hearing-conservation system",
      "Rely only on annual audiograms",
      "Shorten the operator's breaks so the task ends sooner",
      "Post a sign stating that the compressor is loud",
    ],
    correctIndex: 0,
    rationale: "A properly designed enclosure interrupts the transmission path and can reduce exposure independent of perfect individual behavior. Residual risk still requires measurement, maintenance, and applicable administrative and protective measures.",
    wrongRationales: [
      "Correct. It prioritizes a feasible engineering control and verifies performance while retaining necessary program layers.",
      "Audiometry detects possible change; it does not reduce sound energy reaching the worker.",
      "Reduced recovery time may increase fatigue and does not reliably control the source or dose.",
      "A warning communicates the hazard but does not reduce exposure.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Source-path-receiver noise controls",
    challengePrompt: "Identify enclosure design failures that could reduce acoustic benefit or create thermal and maintenance hazards.",
  },
  {
    id: "A6-019",
    domainId: "A6",
    competency: "Ionizing-radiation fundamentals",
    objective: "Apply the inverse-square relationship to a point-source screening estimate.",
    difficulty: 3,
    stem: "A small point source produces a dose rate of 16 microsieverts per hour at 1 meter. Ignoring shielding and scatter, what dose rate is expected at 2 meters?",
    options: ["4 microsieverts per hour", "8 microsieverts per hour", "16 microsieverts per hour", "32 microsieverts per hour"],
    correctIndex: 0,
    rationale: "For an ideal point source, intensity varies inversely with distance squared. Doubling distance reduces the rate by 2 squared, so 16/4 = 4 microsieverts per hour.",
    wrongRationales: [
      "Correct. Doubling distance produces one-fourth the idealized point-source dose rate.",
      "This applies an inverse-distance rather than inverse-square relationship.",
      "This assumes distance has no effect.",
      "This reverses the direction of the distance effect.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Time, distance, shielding, and inverse square",
    challengePrompt: "Explain two field conditions that can make the ideal inverse-square estimate inaccurate.",
  },
  {
    id: "A6-020",
    domainId: "A6",
    competency: "Local exhaust ventilation",
    objective: "Diagnose loss of capture from task and hood geometry.",
    difficulty: 4,
    stem: "Airflow at a welding hood's face meets its design value, yet smoke repeatedly crosses the welder's breathing zone before entering the hood. What is the most likely control issue?",
    options: [
      "Adequate face velocity proves exposure is controlled",
      "The hood is positioned so the contaminant travels through the breathing zone; source-receptor-hood geometry and cross-drafts must be corrected and performance retested",
      "The contaminant cannot be airborne because it is visible",
      "Increasing room temperature is the only valid correction",
    ],
    correctIndex: 1,
    rationale: "Capture depends on distance, orientation, plume momentum, cross-drafts, and whether the hood draws contamination away from the worker. A face reading alone does not demonstrate effective source capture.",
    wrongRationales: [
      "A design-point measurement does not prove the actual contaminant path avoids the breathing zone.",
      "Correct. Effective geometry captures at the source before the plume reaches the worker.",
      "Visible fume is airborne particulate and its visibility does not make it harmless.",
      "Temperature adjustment does not directly correct poor hood placement or cross-draft interference.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Capture velocity and hood placement",
    challengePrompt: "Describe a smoke-test and exposure-sampling plan that would verify the redesigned capture system under representative work.",
  },
  {
    id: "A6-021",
    domainId: "A6",
    competency: "Mixture exposure assessment",
    objective: "Calculate an additive mixture index from fractions of exposure limits.",
    difficulty: 4,
    stem: "Two solvents have similar additive health effects. Measured concentrations are 30 ppm and 20 ppm; their applicable limits are 50 ppm and 40 ppm, respectively. Using an additive index C1/L1 + C2/L2, what is the result?",
    options: ["0.50", "0.60", "1.00", "1.10"],
    correctIndex: 3,
    rationale: "The fractions are 30/50 = 0.60 and 20/40 = 0.50. Their sum is 1.10, which exceeds unity under the stated additive screening model.",
    wrongRationales: [
      "This is only the second agent's fraction.",
      "This is only the first agent's fraction.",
      "This appears to round or cap the result before adding the two fractions.",
      "Correct. The additive index is 0.60 + 0.50 = 1.10.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Additive exposure indices",
    challengePrompt: "State why this simple index may be inappropriate when health endpoints, sampling periods, or interaction mechanisms differ.",
  },
  {
    id: "A6-022",
    domainId: "A6",
    competency: "Exposure-limit interpretation",
    objective: "Use a skin notation without treating it as a separate airborne limit.",
    difficulty: 4,
    stem: "An occupational exposure limit includes a skin notation. Air monitoring is below the airborne limit, but workers immerse gloved hands in the liquid repeatedly. What does the notation imply?",
    options: [
      "Air results alone establish acceptable total uptake",
      "Significant dermal contribution may occur, so task-specific skin exposure and control effectiveness must be evaluated in addition to inhalation",
      "The material can harm only unbroken skin and cannot be inhaled",
      "Any glove material provides permanent protection",
    ],
    correctIndex: 1,
    rationale: "A skin notation warns that cutaneous uptake can materially contribute to systemic dose. It does not replace the airborne value, specify a safe contact duration, or validate the glove selection.",
    wrongRationales: [
      "Air monitoring does not quantify uptake through skin.",
      "Correct. The notation triggers a route-specific evaluation alongside inhalation assessment.",
      "It does not state that inhalation is impossible or limit concern to one skin condition.",
      "Glove resistance varies by chemical, material, thickness, temperature, flexing, contact time, and reuse.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Exposure limits and skin notation",
    challengePrompt: "Create a glove-change rule using permeation data, task contact time, observed degradation, and contamination during removal.",
  },
  {
    id: "A6-023",
    domainId: "A6",
    competency: "Respiratory protection",
    objective: "Select protection for an unknown potentially immediately dangerous atmosphere.",
    difficulty: 5,
    stem: "A tanker contains an unknown solvent vapor after a process upset. The concentration and oxygen level cannot be characterized from outside, and entry is proposed for rescue standby setup. Which respiratory approach is most defensible for entry under the stated uncertainty?",
    options: [
      "A disposable filtering facepiece",
      "An air-purifying respirator with any organic-vapor cartridge",
      "A positive-pressure atmosphere-supplying configuration approved for the potential IDLH condition, within a complete entry and rescue system",
      "No respirator if the entrant holds their breath while crossing the opening",
    ],
    correctIndex: 2,
    rationale: "Unknown concentration and oxygen status must be treated conservatively as potentially IDLH until reliably characterized. Air-purifying devices depend on adequate oxygen, known contaminants, and use within established limits.",
    wrongRationales: [
      "A particulate filter does not supply oxygen or remove unknown vapor.",
      "Cartridge selection and service-life controls require a known atmosphere that is not oxygen-deficient or IDLH.",
      "Correct. The protection and operational system must be suitable for the worst credible unknown atmosphere and rescue demands.",
      "Breath holding is not respiratory protection and cannot prevent skin or accidental inhalation exposure.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "IDLH respiratory selection",
    challengePrompt: "Identify the conditions that would need to be established before an air-purifying respirator could even be considered for later nonentry work.",
  },
  {
    id: "A6-024",
    domainId: "A6",
    competency: "Fitness for duty and Total Worker Health",
    objective: "Integrate individual capability, work design, privacy, and population prevention.",
    difficulty: 5,
    stem: "Night-shift vehicle incidents rise after mandatory overtime increases. Management proposes screening out every worker who reports fatigue and sharing diagnoses with supervisors. What is the strongest occupational-health response?",
    options: [
      "Use diagnosis disclosure and exclusion as the only controls",
      "Treat fatigue solely as a personal lifestyle failure",
      "Control scheduling, workload, recovery opportunity, commute and task risk at the system level; provide confidential evidence-based health support and fitness decisions; give supervisors only necessary work restrictions; and monitor equitable outcomes",
      "Stop collecting any fatigue or incident information",
    ],
    correctIndex: 2,
    rationale: "Fatigue risk emerges from work organization and individual factors. A strong response reduces upstream exposure, supports health confidentially, applies qualified fitness processes, limits disclosure, and checks whether controls work without unfairly shifting all responsibility to workers.",
    wrongRationales: [
      "Blanket exclusion can be discriminatory, discloses more than necessary, and leaves the overtime hazard unchanged.",
      "The timing of the increase points to system conditions that must be evaluated along with individual contributors.",
      "Correct. It integrates prevention, occupational health, privacy, accommodation, and effectiveness evaluation.",
      "Eliminating information prevents diagnosis and monitoring while doing nothing to reduce fatigue exposure.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Total Worker Health and fitness-for-duty governance",
    challengePrompt: "Define a dashboard that detects both fatigue-risk reduction and unintended inequity in work assignment.",
  },

  {
    id: "A7-011",
    domainId: "A7",
    competency: "Materials and waste hierarchy",
    objective: "Prioritize prevention over downstream waste handling.",
    difficulty: 1,
    stem: "A process generates 500 kg of solvent waste each month. Which action is generally highest in the environmental hierarchy?",
    options: [
      "Redesign the process so less solvent is required and less waste is generated",
      "Send all waste to energy recovery without evaluating prevention",
      "Store the waste indefinitely",
      "Dilute the waste before disposal",
    ],
    correctIndex: 0,
    rationale: "Source reduction avoids material use and waste generation before reuse, recycling, recovery, treatment, or disposal become necessary. Feasibility and risk tradeoffs still require evaluation.",
    wrongRationales: [
      "Correct. Preventing generation addresses impacts before downstream management is needed.",
      "Recovery may be preferable to disposal but remains below feasible source prevention.",
      "Storage transfers the issue in time and can add fire, release, and compliance risk.",
      "Dilution does not eliminate pollutant mass and may create a larger waste stream.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Pollution prevention and waste hierarchy",
    challengePrompt: "Name two lifecycle tradeoffs that should be checked before approving the process redesign.",
  },
  {
    id: "A7-012",
    domainId: "A7",
    competency: "Water and land impact pathways",
    objective: "Trace a pollutant pathway and select controls at source and along the route.",
    difficulty: 2,
    stem: "Outdoor drums are stored beside an uncovered storm drain that discharges to a creek. Which control package most directly reduces the release pathway?",
    options: [
      "Label the creek after a spill occurs",
      "Use compatible closed containers, inspected secondary containment and weather protection, separate them from drainage, protect or isolate the drain, and maintain a tested spill response",
      "Rely on rain to dilute any leak",
      "Move the drums closer to the drain for easier observation",
    ],
    correctIndex: 1,
    rationale: "The package reduces failure likelihood, contains a release, interrupts transport to surface water, and prepares response. It controls both source and pathway rather than relying on dilution.",
    wrongRationales: [
      "Downstream labeling after release does not prevent or contain contamination.",
      "Correct. It combines prevention, containment, pathway interruption, inspection, and response readiness.",
      "Dilution does not remove pollutant mass and can spread contamination.",
      "Closer placement shortens the pathway and increases the chance that a leak enters the drain.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Stormwater and spill pathways",
    challengePrompt: "Draw a source-pathway-receptor model for the scenario and place one monitoring point at each boundary.",
  },
  {
    id: "A7-013",
    domainId: "A7",
    competency: "Environmental management systems",
    objective: "Use lifecycle perspective and change control when evaluating an apparently beneficial substitution.",
    difficulty: 4,
    stem: "A site plans to replace a high-VOC coating with a water-based product. Direct air emissions should fall, but the new product uses more energy for curing and creates contaminated wash water. What should the environmental review do?",
    options: [
      "Approve automatically because one air metric improves",
      "Reject automatically because every substitution creates tradeoffs",
      "Compare significant lifecycle aspects and legal or operational requirements, quantify material tradeoffs, select controls and objectives, approve through change management, and monitor actual performance",
      "Exclude water and energy impacts because they belong to other departments",
    ],
    correctIndex: 2,
    rationale: "A lifecycle perspective helps prevent burden shifting across media or stages. The decision should compare material impacts and requirements, manage new controls, and verify whether expected improvement occurs in operation.",
    wrongRationales: [
      "A lower VOC value can coexist with significant water, energy, waste, quality, or safety impacts.",
      "Tradeoffs require evaluation, not automatic rejection of potentially beneficial change.",
      "Correct. It supports an informed, controlled, and verifiable environmental decision.",
      "Organizational ownership does not erase environmental interactions or shared obligations.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Lifecycle thinking and environmental change",
    challengePrompt: "Create a normalized before-and-after scorecard that avoids hiding burden transfer as production changes.",
  },
  {
    id: "A7-014",
    domainId: "A7",
    competency: "Environmental performance and ESG",
    objective: "Evaluate an environmental claim for boundary, denominator, and data-integrity weaknesses.",
    difficulty: 5,
    stem: "A company claims a 40% reduction in landfill waste after outsourcing a manufacturing step. Total product output is unchanged, but supplier waste is excluded, measurement methods changed, and returned products increased. What is the strongest EHS conclusion?",
    options: [
      "The claim proves a 40% lifecycle improvement",
      "Outsourced impacts never belong in environmental evaluation",
      "Reconstruct comparable boundaries and methods, include material upstream and downstream effects, normalize to meaningful activity, verify data controls, and restate or qualify the claim before using it",
      "Use only the most favorable year because environmental reports are promotional",
    ],
    correctIndex: 2,
    rationale: "Changing organizational boundaries, methods, and lifecycle flows can create apparent improvement without reducing total impact. Comparable definitions, relevant scope, normalization, verification, and transparent qualification are necessary for a defensible claim.",
    wrongRationales: [
      "The reported percentage does not account for boundary transfer, changed methods, or increased returns.",
      "Supplier impacts can be material to lifecycle risk, commitments, continuity, and value-chain reporting.",
      "Correct. It restores comparability and tests whether the claimed performance change is real.",
      "Selective baselines undermine data integrity and can materially mislead decision-makers.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Environmental data integrity and value-chain impacts",
    challengePrompt: "Specify the evidence needed to distinguish true source reduction from transfer of waste across the reporting boundary.",
  },

  {
    id: "A8-011",
    domainId: "A8",
    competency: "Learning objectives",
    objective: "Select an observable objective aligned to an emergency communication task.",
    difficulty: 1,
    stem: "Which is the strongest learning objective for radio use during an emergency?",
    options: [
      "Know radios",
      "Understand communication",
      "Given a charged site radio and an emergency scenario, transmit location, hazard, and assistance needed in the required sequence with no omitted critical element",
      "Appreciate clear speech",
    ],
    correctIndex: 2,
    rationale: "The selected objective specifies conditions, an observable performance, content requirements, and a criterion. These features support aligned practice and assessment.",
    wrongRationales: [
      "The statement lacks a defined behavior, conditions, and criterion.",
      "Understanding is not directly observable as written.",
      "Correct. It defines what the learner must do and how success will be judged.",
      "Appreciation is an attitude and is not translated into assessable task performance.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Performance-based learning objectives",
    challengePrompt: "Add a retention test and a realistic noise or stress condition without making the objective ambiguous.",
  },
  {
    id: "A8-012",
    domainId: "A8",
    competency: "Adult learning",
    objective: "Use relevant experience and active problem solving in instruction.",
    difficulty: 1,
    stem: "Experienced maintenance employees are learning a revised energy-control procedure. Which approach best supports adult learning?",
    options: [
      "Read every slide aloud and prohibit questions",
      "Connect the revision to incidents and familiar tasks, elicit existing knowledge, practice realistic isolations, and give timely feedback",
      "Require memorization of section numbers without application",
      "Replace all practice with an attendance signature",
    ],
    correctIndex: 1,
    rationale: "Adults benefit from relevant, problem-centered learning that uses prior experience and permits active practice and feedback. Familiarity should be tested rather than assumed.",
    wrongRationales: [
      "Passive delivery and suppressed questions limit diagnosis, engagement, and application.",
      "Correct. It links relevance, experience, authentic practice, and feedback.",
      "Section recall does not establish safe procedure execution.",
      "Attendance documents presence, not learning or competence.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Andragogy and active learning",
    challengePrompt: "Explain how you would use experienced workers' knowledge without allowing outdated shortcuts to become the taught standard.",
  },
  {
    id: "A8-013",
    domainId: "A8",
    competency: "Role qualification",
    objective: "Distinguish familiarity, competence, and role-specific qualification.",
    difficulty: 1,
    stem: "A worker attends a crane-signal awareness class. What does the attendance record alone establish?",
    options: [
      "That the worker is qualified for every signaling situation",
      "Only that the worker was recorded as present; role authorization still requires the defined knowledge, skill, evaluation, and other applicable criteria",
      "That practical evaluation is unnecessary",
      "That the employer transferred all responsibility to the instructor",
    ],
    correctIndex: 1,
    rationale: "Attendance is an administrative record, not evidence of task performance or satisfaction of role-specific qualification criteria. Authorization should follow the applicable competence and evaluation process.",
    wrongRationales: [
      "A general awareness class cannot establish performance across all conditions or satisfy every qualification requirement.",
      "Correct. Presence is one record, while qualification depends on defined and demonstrated criteria.",
      "Practical tasks commonly require observed performance or other authentic evidence.",
      "The organization retains responsibility for appropriate selection, evaluation, and authorization.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Competent and qualified roles",
    challengePrompt: "Build a role matrix that separates awareness, task competence, designation authority, and refresher triggers.",
  },
  {
    id: "A8-014",
    domainId: "A8",
    competency: "Training needs assessment",
    objective: "Identify a knowledge gap using performance and task evidence.",
    difficulty: 2,
    stem: "Operators can perform normal startup but consistently misidentify the first action after a high-pressure alarm. Equipment and procedures are available and usable. What is the best next training step?",
    options: [
      "Repeat the entire orientation program without diagnosis",
      "Provide targeted instruction and scenario practice on alarm recognition and response, then verify performance under representative conditions",
      "Remove the alarm from the procedure",
      "Assume the problem is deliberate misconduct",
    ],
    correctIndex: 1,
    rationale: "The evidence identifies a specific capability gap rather than a broad orientation failure or resource barrier. Targeted practice and authentic reassessment are more efficient and diagnostic.",
    wrongRationales: [
      "A full generic course dilutes attention from the demonstrated response gap.",
      "Correct. It aligns remediation and evaluation to the failed critical behavior.",
      "Removing a valid warning step weakens the control system instead of building capability.",
      "Repeated misunderstanding under otherwise supportive conditions warrants diagnosis before attributing intent.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Gap analysis and targeted remediation",
    challengePrompt: "State what evidence would cause you to shift the diagnosis from knowledge to interface design or workload.",
  },
  {
    id: "A8-015",
    domainId: "A8",
    competency: "Procedural skill development",
    objective: "Select practice conditions that produce safe task performance.",
    difficulty: 2,
    stem: "Employees must learn to use a spill kit for three different liquid hazards. Which design is strongest?",
    options: [
      "A single lecture describing all kit contents",
      "Demonstration followed by supervised scenario practice selecting compatible materials, controlling approach, containing a simulated release, and receiving checklist-based feedback",
      "A poster with no opportunity to handle equipment",
      "A quiz that asks only for product colors",
    ],
    correctIndex: 1,
    rationale: "The learning target is conditional procedural performance. Demonstration, varied practice, safe simulation, observation, and specific feedback provide evidence that learners can select and execute the correct response.",
    wrongRationales: [
      "Lecture can introduce concepts but cannot establish selection and physical response skill.",
      "Correct. It aligns the method and evidence to realistic task decisions and actions.",
      "A visual reminder does not provide motor practice or test compatibility decisions.",
      "Color recall is not the critical performance needed to control a spill safely.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Demonstration and deliberate practice",
    challengePrompt: "Design one scenario that tests the learner's decision not to respond because the release exceeds training or equipment limits.",
  },
  {
    id: "A8-016",
    domainId: "A8",
    competency: "Feedback and communication",
    objective: "Deliver corrective feedback that supports learning and preserves reporting.",
    difficulty: 2,
    stem: "During a practice inspection, a learner misses a damaged sling tag. Which instructor response is most effective?",
    options: [
      "Call the learner careless in front of the group",
      "Ignore the miss so confidence remains high",
      "Pause safely, point to the observable inspection step and consequence, ask the learner to reassess, then confirm the corrected method and future cue",
      "Complete the inspection for the learner without explanation",
    ],
    correctIndex: 2,
    rationale: "Timely, behavior-specific feedback connects the missed cue to risk, engages the learner in correction, and reinforces a repeatable strategy without personal labeling.",
    wrongRationales: [
      "Personal humiliation can suppress questions and reporting while failing to teach the missing discrimination.",
      "Uncorrected critical errors can become practiced errors.",
      "Correct. It is specific, participative, actionable, and tied to the task standard.",
      "Taking over removes the chance to diagnose and practice the correct inspection behavior.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Behavior-specific formative feedback",
    challengePrompt: "Write a two-sentence feedback script that distinguishes the observed action from assumptions about attitude.",
  },
  {
    id: "A8-017",
    domainId: "A8",
    competency: "Retention and retrieval",
    objective: "Use spaced retrieval and varied practice to strengthen durable learning.",
    difficulty: 3,
    stem: "Workers pass a one-time chemical-label lesson but forget key distinctions three months later. Which redesign is most likely to improve retention?",
    options: [
      "Add more text to the original lecture only",
      "Use brief spaced retrieval, interleave realistic label and task examples, correct errors promptly, and retest after increasing intervals",
      "Show the answer before every question indefinitely",
      "Measure satisfaction immediately after class and stop evaluation",
    ],
    correctIndex: 1,
    rationale: "Effortful retrieval distributed over time, with varied examples and feedback, strengthens access and discrimination better than massed passive exposure. Delayed tests provide evidence of durability.",
    wrongRationales: [
      "More passive content does not necessarily create retrieval strength or transfer.",
      "Correct. Spacing, retrieval, interleaving, feedback, and delayed assessment support durable learning.",
      "Permanent answer cueing prevents independent retrieval and can inflate apparent fluency.",
      "Immediate reaction does not measure long-term retention or application.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Spacing, retrieval, and interleaving",
    challengePrompt: "Build a four-touch review schedule and state how question difficulty should change at each touch.",
  },
  {
    id: "A8-018",
    domainId: "A8",
    competency: "Training evaluation",
    objective: "Separate knowledge gain from workplace transfer and operational outcomes.",
    difficulty: 3,
    stem: "A lockout course raises average test scores from 65% to 92%. What additional evidence is most important before claiming the program reduced hazardous-energy risk?",
    options: [
      "The instructor's speaking time",
      "Representative observations of complete field isolations, verification quality, correction of system barriers, and relevant exposure or event trends over time",
      "The number of certificates printed",
      "A single learner's favorable comment",
    ],
    correctIndex: 1,
    rationale: "Knowledge improvement is useful but does not prove transfer, enabling conditions, or risk reduction. Field behavior and control-performance evidence, combined with relevant outcomes, support a stronger causal claim.",
    wrongRationales: [
      "Speaking time is an instructional input and does not establish learning or field control.",
      "Correct. It extends evaluation from test performance to workplace execution and risk-relevant effects.",
      "Certificate count reflects administration rather than isolation quality.",
      "One reaction comment cannot establish representative transfer or operational change.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Learning, transfer, and results evaluation",
    challengePrompt: "Name two confounders that could make field isolation performance improve even if the course had no effect.",
  },
  {
    id: "A8-019",
    domainId: "A8",
    competency: "Psychological safety",
    objective: "Create conditions for questions and error reporting without weakening accountability.",
    difficulty: 4,
    stem: "New technicians stop asking questions after a supervisor mocks one employee for reporting uncertainty. Which response best strengthens learning culture?",
    options: [
      "Tell employees to be tougher and keep the supervisor's behavior unchanged",
      "Set and model respectful response norms, address the supervisor's conduct, invite specific concerns, make stop-and-ask routes safe, close the loop on reports, and retain fair accountability for deliberate misconduct",
      "Promise that no reported action will ever be reviewed",
      "Require all questions to be anonymous even during urgent field work",
    ],
    correctIndex: 1,
    rationale: "Psychological safety supports speaking up, learning, and early hazard detection; it is compatible with clear standards and fair accountability. Leadership behavior and visible response to reports determine whether stated openness is credible.",
    wrongRationales: [
      "Dismissal reinforces silence and hides uncertainty until it becomes an error or incident.",
      "Correct. It changes leadership behavior and reporting conditions while preserving principled accountability.",
      "A no-review promise can prevent learning and is unnecessary for a fair, nonretaliatory process.",
      "Anonymous routes can help, but exclusive anonymity is impractical for immediate clarification and can obstruct feedback.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Psychological safety and just accountability",
    challengePrompt: "Define one measure that can detect silence without rewarding a raw increase in low-quality reports.",
  },
  {
    id: "A8-020",
    domainId: "A8",
    competency: "Accessible risk communication",
    objective: "Design communication for different sensory, language, and literacy needs.",
    difficulty: 4,
    stem: "A facility introduces a critical alarm response for workers who speak four primary languages; several workers are deaf or hard of hearing. What is the strongest implementation?",
    options: [
      "Use one spoken announcement in the language used by management",
      "Use tested redundant audible, visual, and where needed tactile cues; concise translated and pictorial instructions; demonstrations and drills; teach-back; and verification across locations and shifts",
      "Rely on coworkers to improvise every message during an emergency",
      "Distribute a technical manual and treat signatures as proof of capability",
    ],
    correctIndex: 1,
    rationale: "Critical communication should be perceivable, understandable, actionable, and reliable under actual conditions. Redundant channels, accessible content, practice, teach-back, and field testing address different failure modes.",
    wrongRationales: [
      "One audible language excludes foreseeable users and provides no redundancy.",
      "Correct. It combines accessible warning, instruction, practice, and operational verification.",
      "Improvised relay is vulnerable to absence, delay, translation error, and role ambiguity.",
      "A signature documents receipt, not perception, comprehension, or response performance.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Multimodal and multilingual communication",
    challengePrompt: "Create a drill observation plan that tests alarm perception separately from understanding and action.",
  },
  {
    id: "A8-021",
    domainId: "A8",
    competency: "Human performance",
    objective: "Redesign work and learning after a predictable mode error.",
    difficulty: 5,
    stem: "Operators choose the wrong pump because two touchscreen modes use nearly identical displays. Training records are current, and the error occurs mostly during abnormal startups under time pressure. What is the strongest intervention?",
    options: [
      "Repeat the same lecture and label anyone who errs as inattentive",
      "Analyze the task and error-likely conditions, redesign mode and equipment identification, add confirmation or forcing functions for critical selections, practice abnormal scenarios, and measure error recovery under realistic workload",
      "Remove all abnormal-startup content from training",
      "Add a policy requiring perfect attention without changing the interface",
    ],
    correctIndex: 1,
    rationale: "The pattern implicates interface similarity, mode awareness, workload, and weak error defenses. Training should support redesigned work and realistic recognition/recovery, not substitute for correcting predictable system traps.",
    wrongRationales: [
      "Repetition of unchanged content does not repair the interface or high-pressure error pathway.",
      "Correct. It combines human-factors design, robust verification, scenario learning, and effectiveness evidence.",
      "Removing the difficult condition prevents preparation for the situation in which the error actually occurs.",
      "An attention rule provides no new cue, constraint, or recovery mechanism.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Error-likely situations and resilient design",
    challengePrompt: "Construct an error chain showing how mode confusion becomes wrong-pump activation and place a control before, during, and after selection.",
  },
  {
    id: "A8-022",
    domainId: "A8",
    competency: "Assessment governance",
    objective: "Set a defensible competence decision when question-bank exposure threatens validity.",
    difficulty: 5,
    stem: "Employees repeatedly practice a small online bank until they memorize answer positions. The system reports 95% mastery, but novel field scenarios reveal weak reasoning. What is the best redesign?",
    options: [
      "Keep the score because repetition always proves transfer",
      "Randomize only the color of the answer buttons",
      "Expand blueprint-mapped item and scenario coverage, control repeat exposure, use parallel novel forms and authentic performance tasks, analyze item leakage and discrimination, require domain-level evidence, and recalibrate the mastery rule against job performance",
      "Replace assessment with self-reported confidence alone",
    ],
    correctIndex: 2,
    rationale: "Memorized positions create construct-irrelevant score gains. Broader mapped content, secure parallel evidence, authentic transfer tasks, psychometric review, coverage constraints, and criterion calibration are needed before interpreting a score as competence.",
    wrongRationales: [
      "Repetition can improve recall of item cues without improving the reasoning needed for new situations.",
      "Cosmetic randomization does not create new content or prevent recognition of stems and keyed concepts.",
      "Correct. It addresses coverage, exposure, item quality, transfer, domain masking, and the validity of the cut rule.",
      "Confidence can remain high despite shallow or cue-dependent knowledge and cannot replace performance evidence.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Item exposure, transfer, and mastery validity",
    challengePrompt: "Define an adaptive stopping rule that requires both statistical precision and minimum novel coverage in every critical objective cluster.",
  },
] as const satisfies readonly ASPQuestion[];
