import type { ASPQuestion } from "./aspQuestionBankA";

/** Forty independently authored ASP11 Domain A2 practice items. */
function item(
  id: string,
  competency: string,
  objective: string,
  difficulty: ASPQuestion["difficulty"],
  stem: string,
  options: ASPQuestion["options"],
  correctIndex: ASPQuestion["correctIndex"],
  rationale: string,
  wrongRationales: ASPQuestion["wrongRationales"],
  referenceFramework: ASPQuestion["referenceFramework"],
  referenceTopic: string,
  challengePrompt: string,
): ASPQuestion {
  return {
    id,
    domainId: "A2",
    competency,
    objective,
    difficulty,
    stem,
    options,
    correctIndex,
    rationale,
    wrongRationales,
    referenceFramework,
    referenceTopic,
    challengePrompt,
  };
}

export const ASP_QUESTION_BANK_EXTRA_A2: ASPQuestion[] = [
  item(
    "A2-011",
    "Safety management systems",
    "Recognize continual improvement within a management-system cycle.",
    1,
    "A site implements a new inspection process, reviews performance data, and revises the process based on findings. Which management-system concept is illustrated?",
    ["Continual improvement", "Risk transfer", "Emergency evacuation", "Medical diagnosis"],
    0,
    "Implementing a process, evaluating results, and adjusting it form a continual-improvement loop. The cycle depends on objectives, evidence, corrective action, and leadership review rather than one-time implementation.",
    [
      "Correct. Performance evidence is used to improve the managed process.",
      "Risk transfer allocates certain consequences and is not the activity described.",
      "Evacuation is an emergency action, not the broader improvement concept.",
      "Medical diagnosis is outside the described program cycle.",
    ],
    "BCSP Blueprint",
    "Safety management systems and continual improvement",
    "Give one example of the Plan, Do, Check, and Act stages for machine inspections.",
  ),
  item(
    "A2-012",
    "Hierarchy of hazard controls",
    "Identify elimination of a recurring exposure.",
    1,
    "Employees climb a fixed ladder daily only to read a tank level. Which proposal best eliminates that routine fall exposure?",
    [
      "Install a reliable remote level display at grade",
      "Require three points of contact",
      "Issue new climbing gloves",
      "Post a ladder-use reminder",
    ],
    0,
    "A reliable grade-level indication removes the need to climb for the reading task. The other options may support safer climbing but leave the recurring exposure in place.",
    [
      "Correct. The routine task at height is designed out.",
      "Three-point contact is a work practice and does not eliminate climbing.",
      "Gloves are PPE and do not remove the fall hazard.",
      "A reminder depends on behavior and retains the hazardous task.",
    ],
    "Yates",
    "Elimination and remote monitoring",
    "Identify one maintenance task that remote indication would not eliminate and how to control it.",
  ),
  item(
    "A2-013",
    "Globally Harmonized System",
    "Distinguish hazard communication from chemical compatibility.",
    1,
    "Two chemical containers display the same GHS signal word. What can be concluded about storing them together?",
    [
      "They are automatically compatible",
      "The signal word alone does not establish compatibility",
      "They must be the same chemical",
      "Neither chemical needs a label",
    ],
    1,
    "A signal word communicates relative hazard severity within the label system; it does not describe reaction compatibility. Storage requires product-specific physical, chemical, and incompatibility information.",
    [
      "Shared signal wording does not rule out a dangerous reaction.",
      "Correct. Compatibility needs a separate chemical evaluation.",
      "Many different substances use the same signal word.",
      "Hazardous products still require appropriate hazard communication.",
    ],
    "Nito",
    "GHS labels and chemical compatibility",
    "Name two SDS data elements more useful than the signal word for segregation planning.",
  ),
  item(
    "A2-014",
    "Hazardous energy control programs",
    "Recognize thermal energy as part of energy control.",
    1,
    "A steam line is valved off, but trapped condensate remains above its boiling point at atmospheric pressure. Which energy hazard still requires control?",
    ["Thermal and pressure energy", "Magnetic energy only", "Static lighting", "Noise dose only"],
    0,
    "Hot, pressurized condensate can flash to steam when containment is opened. Isolation, cooling, draining, venting, blocking, and verification must address both temperature and pressure.",
    [
      "Correct. The trapped fluid can release heat, pressure, and expanding vapor.",
      "The scenario does not identify a magnetic source.",
      "Lighting is unrelated to the stored process energy.",
      "Noise is not the principal energy-release mechanism described.",
    ],
    "ASP/CSP Exam Book",
    "Thermal and pressure energy isolation",
    "Explain why a zero-reading pressure gauge may not prove the line is safe to open.",
  ),
  item(
    "A2-015",
    "General electrical principles",
    "Recognize the condition required for current flow.",
    1,
    "In a simple direct-current circuit, what condition is necessary for sustained current to flow through a load?",
    [
      "A complete conductive path with a potential difference",
      "An open switch with no alternate path",
      "Zero voltage across every component",
      "A warning label on the source",
    ],
    0,
    "Current requires a complete path and an electrical potential difference. Opening the circuit interrupts the intended path, though stored energy or unintended paths may remain hazardous.",
    [
      "Correct. Both continuity and potential difference are required.",
      "An open switch normally interrupts current in the simple circuit.",
      "With zero potential difference, the stated circuit has no driving force for current.",
      "A label communicates but does not create electrical current.",
    ],
    "Yates",
    "Basic circuits and current flow",
    "Give one example of an unintended conductive path through a worker.",
  ),
  item(
    "A2-016",
    "Scaffolding safety",
    "Select a safe access method for a scaffold platform.",
    1,
    "Workers are climbing scaffold cross braces to reach a platform. What is the strongest correction?",
    [
      "Provide and require a designed, secured access system",
      "Paint the braces a brighter color",
      "Allow climbing only during daylight",
      "Require workers to climb faster",
    ],
    0,
    "Cross braces are not a substitute for designed access. A suitable ladder, stair tower, integral access, or other approved means should provide stable entry without defeating guard systems.",
    [
      "Correct. The access method is designed for climbing and integrated with the scaffold.",
      "Visibility does not make cross braces suitable access.",
      "Daylight does not correct the geometry or footing problem.",
      "Higher speed can increase instability and does not provide safe access.",
    ],
    "Nito",
    "Scaffold access",
    "What inspection evidence would show that the new access remains secure after scaffold modification?",
  ),
  item(
    "A2-017",
    "Process safety fundamentals",
    "Recognize the core purpose of pressure relief.",
    1,
    "What is the primary function of a correctly designed pressure-relief device on process equipment?",
    [
      "Limit pressure before equipment exceeds its allowable condition",
      "Prevent every process deviation",
      "Replace routine maintenance",
      "Measure worker exposure",
    ],
    0,
    "A relief device protects equipment against specified overpressure scenarios by providing a discharge path. It does not prevent all causes, guarantee safe disposal, or replace design and maintenance controls.",
    [
      "Correct. It limits equipment pressure for the scenarios it is designed to handle.",
      "Relief is mitigative and cannot prevent every initiating deviation.",
      "Inspection and maintenance remain necessary for reliable operation.",
      "The device manages process pressure rather than personal exposure measurement.",
    ],
    "ASP/CSP Exam Book",
    "Pressure-relief fundamentals",
    "Why must the discharge location be evaluated separately from device capacity?",
  ),
  item(
    "A2-018",
    "Leading and lagging indicators",
    "Classify an outcome indicator.",
    1,
    "Which measure is primarily lagging?",
    [
      "Number of lost-workday injuries that occurred",
      "Percentage of critical controls verified effective",
      "Percentage of planned inspections completed on time",
      "Percentage of corrective actions checked for effectiveness",
    ],
    0,
    "Lost-workday injuries are realized adverse outcomes. The other choices measure current preventive or assurance activities, although completion alone does not establish quality.",
    [
      "Correct. The measure records harm after it occurs.",
      "Critical-control verification is a leading assurance measure.",
      "Planned inspection completion is generally a leading process measure.",
      "Effectiveness checking is a forward-looking improvement measure.",
    ],
    "BCSP Blueprint",
    "Leading and lagging measures",
    "Explain why an injury-free month can coexist with deteriorating risk controls.",
  ),
  item(
    "A2-019",
    "Hazard and risk analysis methods",
    "Select a structured what-if/checklist review for a modest process change.",
    2,
    "A team will change the delivery pressure and hose arrangement for a familiar chemical-transfer operation. Which analysis is a practical way to prompt deviations while checking known requirements?",
    [
      "A structured what-if/checklist review by a knowledgeable team",
      "An employee popularity survey",
      "A payroll variance analysis",
      "A medical diagnosis of the driver",
    ],
    0,
    "A what-if/checklist method combines imaginative deviation prompts with experience-based requirements and can be proportionate for a defined change. The team still needs accurate process information and action follow-up.",
    [
      "Correct. It tests new deviations and established safeguards together.",
      "Popularity does not identify transfer failure scenarios.",
      "Payroll variance does not assess chemical-transfer hazards.",
      "Driver diagnosis is neither the stated need nor a process hazard analysis.",
    ],
    "Yates",
    "What-if and checklist analysis",
    "Write two what-if prompts addressing pressure and connection error.",
  ),
  item(
    "A2-020",
    "Risk matrix methodology",
    "Distinguish initial from residual risk.",
    2,
    "A team rates a scenario before considering safeguards, then rates it again after verified controls. What do the two ratings represent?",
    [
      "Initial and residual risk",
      "Direct and indirect cost",
      "Voltage and current",
      "Prevalence and incidence",
    ],
    0,
    "Initial risk describes the selected baseline before credited controls; residual risk is what remains after controls and their effectiveness are considered. Both depend on clearly stated assumptions.",
    [
      "Correct. The second assessment reflects the remaining risk after controls.",
      "Cost categories do not describe the two risk ratings.",
      "Electrical quantities are unrelated to this matrix sequence.",
      "These are epidemiologic frequency concepts, not risk-control states.",
    ],
    "Nito",
    "Initial and residual risk",
    "How should uncertainty about control reliability be represented in the residual rating?",
  ),
  item(
    "A2-021",
    "Hazardous energy control programs",
    "Verify isolation before servicing begins.",
    2,
    "After locks and tags are applied to a mixer, what step most directly confirms that isolation is effective?",
    [
      "Perform the approved zero-energy verification, including a controlled start attempt and checks for stored energy",
      "Read the procedure title",
      "Count the number of locks in storage",
      "Ask production whether the mixer usually stops",
    ],
    0,
    "Verification tests whether the identified isolations actually prevent hazardous motion or energy release. It should address controls, electrical state where applicable, and residual energy using approved methods.",
    [
      "Correct. The isolation is tested rather than assumed.",
      "A title does not establish the equipment's energy state.",
      "Inventory count does not prove correct application to this mixer.",
      "Past behavior cannot verify the current isolation configuration.",
    ],
    "ASP/CSP Exam Book",
    "Energy-isolation verification",
    "Why must controls be returned to a neutral position after a start attempt?",
  ),
  item(
    "A2-022",
    "General electrical principles",
    "Apply Ohm's Law to recognize current change.",
    2,
    "A 24 V source is connected across a 12 ohm resistance. Under the ideal relationship I = V/R, what current flows?",
    ["0.5 A", "2 A", "12 A", "288 A"],
    1,
    "Current equals 24 V divided by 12 ohms, or 2 A. Real circuits may include source impedance, component tolerances, temperature effects, and transient conditions.",
    [
      "This incorrectly divides resistance by voltage.",
      "Correct. Twenty-four divided by twelve equals two amperes.",
      "This uses the resistance value as current.",
      "This multiplies voltage and resistance rather than dividing.",
    ],
    "Yates",
    "Ohm's Law",
    "If resistance doubles while voltage stays constant, explain how current changes.",
  ),
  item(
    "A2-023",
    "Confined-space safety",
    "Require atmospheric testing that represents the entrant's exposure.",
    2,
    "A 20 ft deep vessel may contain a heavy solvent vapor, but the attendant samples only at the top opening. What is the key concern?",
    [
      "One top sample may miss stratified hazards at lower elevations",
      "Heavy vapors always rise above the opening",
      "Atmospheric testing is unnecessary when ventilation is planned",
      "The entrant's sense of smell is more reliable than instruments",
    ],
    0,
    "Vapors and oxygen conditions can vary by elevation and location. Pre-entry and continuous testing should represent the space and work areas using suitable instruments and a planned sampling sequence.",
    [
      "Correct. The measurement location may not represent the entrant's breathing zone.",
      "Dense vapors commonly settle or accumulate in low areas.",
      "Ventilation performance must be verified and conditions can change.",
      "Odor can fatigue, be absent, or occur above harmful concentrations.",
    ],
    "Nito",
    "Confined-space atmospheric testing",
    "Design a vertical and horizontal sampling plan for the vessel.",
  ),
  item(
    "A2-024",
    "Fleet and driver safety",
    "Recognize a safety-critical pre-trip defect.",
    2,
    "A delivery driver finds a tire with exposed reinforcing material during the pre-trip check. What is the best response?",
    [
      "Remove the vehicle from service until the tire is evaluated and corrected",
      "Drive only on straight roads",
      "Reduce tire pressure to hide the damage",
      "Complete the route and report it next month",
    ],
    0,
    "Exposed reinforcement indicates material damage that can lead to rapid tire failure. A defined defect-reporting and maintenance-release process should prevent dispatch until qualified correction.",
    [
      "Correct. The potential failure is controlled before road exposure.",
      "Route geometry does not restore tire integrity.",
      "Changing pressure can worsen performance and conceals the condition.",
      "Delay exposes the driver and public to a known critical defect.",
    ],
    "BCSP Blueprint",
    "Fleet inspections and defect control",
    "What system control prevents dispatch software from assigning a vehicle with an open critical defect?",
  ),
  item(
    "A2-025",
    "Incident investigation",
    "Conduct witness interviews without contaminating accounts.",
    2,
    "Several witnesses observed an equipment failure. Which interview approach best preserves independent recollection?",
    [
      "Interview witnesses separately as soon as practical using open questions before specific prompts",
      "Have all witnesses agree on one account before interviews",
      "Tell each witness the investigator's conclusion first",
      "Ask only yes-or-no questions from the start",
    ],
    0,
    "Separate, timely interviews and open prompts reduce memory contamination and allow the witness's own sequence and observations to emerge. Specific follow-up can then clarify details.",
    [
      "Correct. It limits cross-influence and leading information.",
      "Group consensus can overwrite meaningful differences in perception.",
      "Providing a conclusion can anchor and bias recall.",
      "Closed questions can miss unexpected evidence and encourage acquiescence.",
    ],
    "ASP/CSP Exam Book",
    "Witness interviewing",
    "Write one open question and one neutral follow-up for a witness who saw a valve move.",
  ),
  item(
    "A2-026",
    "Emerging safety technology",
    "Plan drone use around new operational hazards.",
    2,
    "A facility wants to inspect a roof with a drone instead of sending a worker aloft. What is the best initial conclusion?",
    [
      "The drone can reduce fall exposure, but flight, people below, battery, weather, data, and operating-area risks still require planning",
      "Drones eliminate every inspection risk",
      "The drone should fly directly over occupied work without controls",
      "Remote video automatically proves structural integrity",
    ],
    0,
    "Remote inspection can substitute technology for routine work at height, but it introduces aviation, dropped-object, collision, ignition, privacy, and data-interpretation issues that need proportionate control.",
    [
      "Correct. A major exposure can be reduced without ignoring new hazards.",
      "Risk changes rather than disappearing.",
      "Uncontrolled overflight creates struck-by and distraction exposure.",
      "Image quality and inspection scope may not reveal hidden structural defects.",
    ],
    "BCSP Blueprint",
    "Drones and remote inspection",
    "Identify one defect a drone image could miss and an alternate verification method.",
  ),
  item(
    "A2-027",
    "Safety management systems",
    "Integrate worker participation into program design.",
    3,
    "A manager drafts a lifting program without consulting the employees who perform lifts on three shifts. What is the strongest improvement?",
    [
      "Involve representative workers in task analysis, control design, trials, feedback, and review while preserving accountable decisions",
      "Release the program unchanged because participation reduces authority",
      "Ask for feedback only after an injury",
      "Let a vote replace technical risk criteria",
    ],
    0,
    "Worker participation contributes operating knowledge, reveals workarounds, improves usability, and supports learning. It complements rather than replaces technical expertise and accountable approval.",
    [
      "Correct. Participation spans design through evaluation.",
      "Excluding users loses critical work-as-performed information.",
      "Post-injury input is reactive and too late for prevention.",
      "Participation informs decisions but does not substitute preference for risk requirements.",
    ],
    "Nito",
    "Worker participation in safety systems",
    "Describe how to include night-shift workers without asking them to attend an unpaid daytime meeting.",
  ),
  item(
    "A2-028",
    "Failure modes and effects analysis",
    "Calculate and interpret a risk-priority number.",
    3,
    "An FMEA assigns severity 7, occurrence 5, and detection 3. What RPN results under the stated multiplication method?",
    ["15", "35", "105", "735"],
    2,
    "RPN = severity x occurrence x detection = 7 x 5 x 3 = 105. The result aids prioritization but should not conceal a high-severity mode or uncertainty in the ratings.",
    [
      "Fifteen omits the severity factor.",
      "Thirty-five omits the detection factor.",
      "Correct. The three ratings multiply to 105.",
      "This multiplies by severity a second time.",
    ],
    "Yates",
    "FMEA prioritization",
    "Explain why two failure modes with RPN 105 may warrant different actions.",
  ),
  item(
    "A2-029",
    "Globally Harmonized System",
    "Maintain hazard communication for a workplace secondary container.",
    3,
    "A cleaning solution is transferred into a durable spray bottle used by several workers across shifts. What is the best hazard-communication approach?",
    [
      "Apply the workplace's compliant secondary-container identification and keep product information accessible",
      "Leave it unmarked because the original drum has a label",
      "Identify it only by liquid color",
      "Write 'safe' on the bottle if it is diluted",
    ],
    0,
    "A shared, durable workplace container needs reliable product and hazard identification under the site's program. Color and informal safety claims do not communicate composition, precautions, or response information.",
    [
      "Correct. The container and supporting information remain identifiable to all users.",
      "The original drum label does not identify a separate bottle at point of use.",
      "Color is ambiguous and can change with lighting, contamination, or formulation.",
      "Dilution may change hazard but does not justify an unsupported safe claim.",
    ],
    "ASP/CSP Exam Book",
    "Secondary-container hazard communication",
    "How would the decision differ for a container filled and immediately used only by the employee who filled it?",
  ),
  item(
    "A2-030",
    "Machine guarding",
    "Respond to an interlock that is routinely defeated for production.",
    3,
    "Operators hold a guard interlock closed with a magnet because the machine stops during frequent adjustments. What is the strongest corrective direction?",
    [
      "Remove the bypass, control immediate exposure, analyze adjustment needs, and redesign safeguarding and the task so production does not require defeat",
      "Issue stronger magnets only to experienced operators",
      "Post a reminder while allowing the bypass",
      "Count bypasses only after an injury",
    ],
    0,
    "Routine defeat signals a conflict between production and safe task design. Immediate control plus engineering review should provide safe adjustment, fault resistance, authorization, and validation rather than normalize bypass behavior.",
    [
      "Correct. It controls the current hazard and removes the system incentive for defeat.",
      "Stronger bypass tools make safeguard defeat more reliable, not safer.",
      "A reminder cannot compensate for an intentionally disabled protective function.",
      "Waiting for harm discards clear precursor evidence.",
    ],
    "Nito",
    "Interlock defeat and task redesign",
    "Propose one safeguard design that permits adjustment without full-speed automatic operation.",
  ),
  item(
    "A2-031",
    "Management of change",
    "Recognize a raw-material specification change as safety-relevant.",
    3,
    "Purchasing proposes a lower-cost powder with the same product name but a finer particle-size distribution. What should occur before process use?",
    [
      "Review dust generation, explosibility, exposure, handling, equipment, quality, and safeguard effects through the change process",
      "Approve because the product name is unchanged",
      "Use it for one shift without telling operators",
      "Compensate by increasing transfer speed",
    ],
    0,
    "Particle size can change airborne exposure, ignition sensitivity, dispersion, flow, static generation, collection performance, and product behavior. A specification change can therefore alter several safeguards.",
    [
      "Correct. The review addresses physical-property and process consequences before introduction.",
      "A common name does not establish equivalent particle behavior.",
      "An uncommunicated production trial exposes people and equipment before risks are resolved.",
      "Higher transfer speed may increase dust generation and does not establish compatibility.",
    ],
    "Yates",
    "Material changes and process hazards",
    "Identify three supplier data fields that should become controlled purchase specifications.",
  ),
  item(
    "A2-032",
    "Leading and lagging indicators",
    "Normalize incident counts by relevant exposure.",
    3,
    "Warehouse A records 6 vehicle contacts during 300,000 vehicle movements; Warehouse B records 8 during 800,000 movements. Which comparison is strongest?",
    [
      "A has 20 contacts per million movements and B has 10, so A's observed rate is higher despite fewer events",
      "B is worse because eight exceeds six",
      "Both rates are equal",
      "The counts prove which drivers were negligent",
    ],
    0,
    "A's rate is 6/300,000 x 1,000,000 = 20; B's is 8/800,000 x 1,000,000 = 10. Task mix, definitions, reporting, severity, and statistical uncertainty still require review.",
    [
      "Correct. A relevant exposure denominator changes the comparison.",
      "Raw counts ignore that B had far more vehicle movements.",
      "The calculated exposure-normalized rates differ by a factor of two.",
      "Aggregate rates identify a system signal and do not establish individual negligence.",
    ],
    "BCSP Blueprint",
    "Exposure-normalized safety indicators",
    "Name one reason vehicle movements may be a better denominator than labor hours and one limitation.",
  ),
  item(
    "A2-033",
    "General electrical principles",
    "Calculate electrical power in a resistive load.",
    3,
    "An ideal resistive heater draws 10 A at 120 V. Using P = VI, what power does it consume?",
    ["12 W", "120 W", "1,200 W", "12,000 W"],
    2,
    "Power equals voltage times current: 120 V x 10 A = 1,200 W. Circuit capacity, conductor rating, duty, temperature, grounding, and overcurrent protection remain separate design considerations.",
    [
      "This divides current by voltage rather than multiplying.",
      "This omits the factor of ten from current.",
      "Correct. The load consumes 1.2 kilowatts under the stated ideal conditions.",
      "This adds an extra factor of ten.",
    ],
    "ASP/CSP Exam Book",
    "Electrical power",
    "Explain why knowing power alone does not establish that an extension cord is suitable.",
  ),
  item(
    "A2-034",
    "Personal protective equipment",
    "Select PPE from task-specific hazard and compatibility evidence.",
    3,
    "A worker will handle a chemical mixture that can permeate some glove materials. What is the best glove-selection basis?",
    [
      "Manufacturer compatibility data for the actual mixture, concentration, temperature, contact type, duration, and glove construction",
      "Glove color",
      "The thickest glove regardless of material",
      "Another worker's preference alone",
    ],
    0,
    "Chemical resistance depends on material, formulation, concentration, temperature, exposure mode, breakthrough, degradation, and task demands. Thickness alone does not establish resistance.",
    [
      "Correct. Selection matches the real exposure and the glove's tested performance.",
      "Color is not a chemical-resistance specification.",
      "A thick incompatible material may permeate or degrade quickly.",
      "Preference can inform usability but cannot replace hazard and performance data.",
    ],
    "Nito",
    "Chemical protective gloves",
    "Distinguish permeation, penetration, and degradation using this task.",
  ),
  item(
    "A2-035",
    "Safety management systems",
    "Close corrective actions through effectiveness verification.",
    4,
    "An audit finding is closed when a revised procedure is uploaded, but field observation shows workers still use the old method. What is the key system failure?",
    [
      "Document upload was mistaken for implemented and effective corrective action",
      "Workers should never be observed after training",
      "Audit findings require no follow-up",
      "The old method becomes acceptable when it is common",
    ],
    0,
    "Correction exists on paper but was not translated into controlled field performance. Closeout should verify communication, competence, availability, supervision, execution, and whether the original risk is reduced.",
    [
      "Correct. Completion evidence did not demonstrate implementation or effectiveness.",
      "Observation is essential for testing work-as-performed.",
      "Follow-up determines whether the finding's cause and consequence are addressed.",
      "Prevalence of a practice does not establish its acceptability.",
    ],
    "BCSP Blueprint",
    "Corrective-action effectiveness",
    "Write one implementation check and one outcome check for this procedural change.",
  ),
  item(
    "A2-036",
    "Hierarchy of hazard controls",
    "Avoid treating risk transfer as a physical hazard control.",
    4,
    "A company outsources confined-space cleaning and says the contract eliminates the confined-space risk. What is the strongest response?",
    [
      "Contracting may allocate some liability, but entry hazards still require prevention, qualification, coordination, control, and oversight",
      "The contractor's insurance removes the hazardous atmosphere",
      "Outsourcing always equals elimination",
      "The host should withhold process-hazard information",
    ],
    0,
    "Financial or contractual transfer does not remove atmospheric, engulfment, energy, access, or rescue hazards. The host-contractor interface remains part of operational risk control.",
    [
      "Correct. Financing and physical risk control are kept distinct.",
      "Insurance responds to covered loss and cannot change the atmosphere.",
      "Elimination would remove the entry need or hazard, not merely change employer.",
      "Withholding information undermines hazard assessment and coordination.",
    ],
    "Yates",
    "Hierarchy of controls and outsourcing",
    "Name three host-contractor interface controls needed before entry.",
  ),
  item(
    "A2-037",
    "Fault tree analysis",
    "Calculate an exact OR-gate probability for independent events.",
    4,
    "A top event occurs if independent event X or event Y occurs. Their probabilities are 0.10 and 0.20. What is the exact top-event probability?",
    ["0.02", "0.28", "0.30", "0.80"],
    1,
    "For independent events, P(X or Y) = 0.10 + 0.20 - (0.10 x 0.20) = 0.28. Simply adding double-counts the overlap where both occur.",
    [
      "This is the AND probability that both occur.",
      "Correct. The intersection is subtracted once from the sum.",
      "This is a useful rare-event approximation but not the exact result requested.",
      "This is the probability that Y does not occur.",
    ],
    "ASP/CSP Exam Book",
    "Fault-tree OR gates",
    "Explain why independence should not be assumed when both events depend on the same utility.",
  ),
  item(
    "A2-038",
    "Risk matrix methodology",
    "Interpret equal matrix scores with different risk profiles.",
    4,
    "Two scenarios receive the same matrix product. One is a rare multiple-fatality event; the other is a frequent minor equipment-damage event. What is the best decision approach?",
    [
      "Examine severity, likelihood, uncertainty, barriers, exposure, and acceptance rules rather than treating the products as identical",
      "Choose alphabetically",
      "Ignore the high-severity scenario because it is rare",
      "Average the two consequences into one event",
    ],
    0,
    "A single ordinal product can hide materially different severity-likelihood combinations. Decision rules may require action for catastrophic potential even when a scalar score ties another scenario.",
    [
      "Correct. The underlying risk dimensions remain visible.",
      "Alphabetic order has no safety meaning.",
      "Low likelihood does not make catastrophic consequence irrelevant.",
      "Combining unrelated outcomes destroys the scenario logic.",
    ],
    "Nito",
    "Risk matrix limitations",
    "Design one tie-break rule that preserves attention to catastrophic potential.",
  ),
  item(
    "A2-039",
    "Hazardous energy control programs",
    "Coordinate group lockout during shift change.",
    4,
    "A group lockout continues into a new shift while equipment remains disassembled. Which transfer practice is strongest?",
    [
      "Ensure incoming authorized employees establish protection before outgoing employees relinquish theirs, with status and accountability formally transferred",
      "Remove all locks and rely on a note",
      "Restart the machine briefly between shifts",
      "Give one personal-lock key to every supervisor",
    ],
    0,
    "A documented transfer prevents a gap in energy control and preserves individual protection, equipment status, and responsibility. Verification should remain valid across the transition.",
    [
      "Correct. Protection and accountability remain continuous.",
      "A note provides no physical isolation during the gap.",
      "Restarting can expose workers and incomplete machinery.",
      "Routine shared control defeats the personal-control principle.",
    ],
    "ASP/CSP Exam Book",
    "Group energy control and shift transfer",
    "How should the procedure address an outgoing employee who cannot be located?",
  ),
  item(
    "A2-040",
    "Trenching and excavation safety",
    "Control excavation risk near an unidentified underground service.",
    4,
    "Records show an old utility near a proposed excavation, but its exact location and depth are uncertain. What is the strongest plan?",
    [
      "Use locating information, mark and verify the service with a controlled exposure method, coordinate isolation/protection, and define stop criteria",
      "Assume the record is inaccurate and excavate at full speed",
      "Ask the equipment operator to listen for contact",
      "Drive a probe randomly until it strikes something",
    ],
    0,
    "Unknown utility position requires progressive location and controlled verification. The plan should manage equipment approach, service ownership, energy/material consequence, emergency response, and changed conditions.",
    [
      "Correct. Uncertainty is reduced before high-energy excavation reaches the service.",
      "Record uncertainty does not justify ignoring a credible hazard.",
      "Contact may cause electrocution, fire, flooding, release, or service loss before sound provides warning.",
      "Uncontrolled probing can damage the service and exposes the worker.",
    ],
    "Yates",
    "Underground utility location",
    "Describe how the plan changes if the line could contain flammable gas.",
  ),
  item(
    "A2-041",
    "Fleet and driver safety",
    "Interpret telematics without confusing association and individual fault.",
    4,
    "One route shows high harsh-braking alerts and high collision frequency. Management wants automatic discipline for every alert. What should the ASP recommend?",
    [
      "Validate alert accuracy and context, analyze route and schedule conditions, coach verified behaviors, and use fair review before individual action",
      "Assume every alert proves reckless intent",
      "Disable telematics because data are imperfect",
      "Reward drivers who produce no alerts even if devices are unplugged",
    ],
    0,
    "Alerts can reveal a useful precursor but may reflect traffic, route design, load, sensors, avoidance maneuvers, or driving behavior. Validation and contextual analysis support prevention and procedural fairness.",
    [
      "Correct. The data guide system and individual interventions without unsupported causal claims.",
      "A sensor event does not prove intent or even unsafe choice in every context.",
      "Imperfect data can still support learning when limitations are managed.",
      "This incentive invites data tampering and hides exposure.",
    ],
    "BCSP Blueprint",
    "Fleet telematics and fair performance management",
    "Name two route variables to stratify before comparing drivers.",
  ),
  item(
    "A2-042",
    "Incident investigation",
    "Preserve digital evidence and distinguish immediate acts from contributing systems.",
    4,
    "After an automated-vehicle near miss, its event buffer will overwrite in 30 minutes. The operator admits pressing the wrong control. What should happen first after immediate safety is secured?",
    [
      "Preserve the time-synchronized event data and configuration under controlled custody while documenting the scene and accounts",
      "Stop the investigation because the operator admitted error",
      "Reconfigure the vehicle before copying data",
      "Publish the operator's name to establish accountability",
    ],
    0,
    "The admission identifies an action, not why the interface, training, conditions, and safeguards permitted it. Volatile electronic evidence should be preserved promptly and traceably before alteration.",
    [
      "Correct. Perishable evidence is secured for a systems-based investigation.",
      "The final act does not explain design or organizational contributors.",
      "Reconfiguration can destroy the as-event state and relevant logs.",
      "Public identification is unnecessary, potentially harmful, and does not preserve evidence.",
    ],
    "Nito",
    "Digital evidence and causal depth",
    "List four timestamps or data streams that should be synchronized during reconstruction.",
  ),
  item(
    "A2-043",
    "Safety management systems",
    "Respond when production incentives conflict with stated safety policy.",
    5,
    "A company policy grants stop-work authority, but bonus rules penalize crews whenever production stops, even for verified critical hazards. Reports and stops are declining. What is the strongest system response?",
    [
      "Align incentives and leader decisions with stop-work policy, protect good-faith use, investigate declining reports, and monitor both use and resolution quality",
      "Keep both systems because written policy always dominates incentives",
      "Set a quota requiring exactly five stops per crew",
      "Delete stop-work data from management review",
    ],
    0,
    "Formal policy is undermined when practical consequences punish its use. Governance must remove the conflict, demonstrate fair response, and distinguish high-quality intervention from gaming or indiscriminate stopping.",
    [
      "Correct. The operating system is realigned with the stated commitment.",
      "Workers often respond to experienced consequences more than written intent.",
      "A quota invites artificial stops and does not measure decision quality.",
      "Removing data conceals the conflict and prevents learning.",
    ],
    "Yates",
    "Leadership, incentives, and safety management systems",
    "Propose two measures that distinguish healthy stop-work use from quota-driven behavior.",
  ),
  item(
    "A2-044",
    "Hazard and risk analysis methods",
    "Identify common-cause failure hidden by an independence assumption.",
    5,
    "A fault tree treats two emergency pumps as independent, but both use the same electrical feeder, cooling-water source, and maintenance procedure. What is the critical correction?",
    [
      "Model the shared dependencies and reassess joint failure before crediting redundant risk reduction",
      "Multiply their individual failure probabilities without further review",
      "Delete the pumps from the analysis",
      "Assume different equipment tags guarantee independence",
    ],
    0,
    "Shared utilities and maintenance create single paths that can disable both pumps. Redundancy provides less risk reduction than an independent-product model predicts unless dependencies are controlled and represented.",
    [
      "Correct. Common-cause pathways are added to the model and design review.",
      "Simple multiplication can severely understate joint failure when independence is false.",
      "The pumps remain relevant safeguards; their actual dependency must be modeled.",
      "Identifiers do not create functional, physical, or organizational independence.",
    ],
    "ASP/CSP Exam Book",
    "Common-cause failure",
    "Propose one physical and one organizational change that improve independence.",
  ),
  item(
    "A2-045",
    "Management of change",
    "Integrate cybersecurity actions with physical process safety.",
    5,
    "IT proposes automatically rebooting every controller when malware is detected. Some controllers maintain ventilation and safe valve positions. What should occur before automating the response?",
    [
      "Jointly analyze safe states, loss-of-control effects, sequencing, manual fallback, restart prevention, segmentation, and tested recovery",
      "Approve because cyber actions cannot create physical hazards",
      "Disable ventilation first in every scenario",
      "Allow automatic production restart after each reboot",
    ],
    0,
    "A cyber response can remove safeguards or initiate hazardous transitions. Cross-functional change analysis should define safe degraded states, contain the threat, preserve critical functions, and prevent unverified restart.",
    [
      "Correct. Cyber containment and physical safety are treated as interacting requirements.",
      "Controller actions can directly affect containment, motion, ventilation, and ignition control.",
      "Universal ventilation loss may create toxic, flammable, or heat hazards.",
      "Automatic restart can expose personnel and equipment before state verification.",
    ],
    "BCSP Blueprint",
    "Cyber-physical management of change",
    "Give one example where fail-off is less safe than a controlled degraded mode.",
  ),
  item(
    "A2-046",
    "Globally Harmonized System",
    "Control hazard information when a supplier formulation changes.",
    5,
    "A supplier changes a coating formulation but retains the trade name. The new SDS shows a different sensitizer and flash point, while the site inventory system still links the old SDS. What is the best response?",
    [
      "Hold or control introduction, review the change, update identity and SDS links, reassess controls, communicate, and train affected users before release",
      "Use the old SDS because the trade name is unchanged",
      "Remove all product labels to avoid conflict",
      "Mix old and new formulations without compatibility review",
    ],
    0,
    "A stable trade name can conceal material changes in health, fire, process, PPE, storage, and emergency information. Receiving, change control, document systems, and field communication must maintain traceability to the actual formulation.",
    [
      "Correct. The new hazard profile is controlled before workplace use.",
      "The old SDS no longer represents the received product.",
      "Removing labels worsens identification and response.",
      "Unreviewed mixing can create quality, reaction, exposure, or waste hazards.",
    ],
    "Nito",
    "SDS revision and formulation change",
    "Design a receiving control that detects safety-significant formulation changes despite unchanged trade names.",
  ),
  item(
    "A2-047",
    "General electrical principles",
    "Recognize how protective-device changes can alter incident energy and equipment duty.",
    5,
    "A larger transformer and new upstream breaker settings are installed, but downstream labels and equipment ratings are not reviewed. What is the strongest concern?",
    [
      "Available fault current and clearing time may change equipment duty, boundaries, and incident energy, invalidating prior assumptions",
      "Only the electricity bill can change",
      "A larger transformer always lowers fault current",
      "Old PPE automatically covers any new condition",
    ],
    0,
    "Source impedance and protective-device response determine fault magnitude and duration. A system modification can affect interrupting ratings, coordination, shock boundaries, incident energy, maintenance, and labeling.",
    [
      "Correct. The changed electrical system requires qualified reassessment before reliance on old information.",
      "The modification has direct protection and equipment consequences.",
      "Greater source capacity can increase available fault current, though actual behavior requires analysis.",
      "PPE has finite performance and must follow a valid current assessment.",
    ],
    "Yates",
    "Electrical system modifications",
    "Explain why higher fault current can sometimes shorten clearing time yet still require a full review.",
  ),
  item(
    "A2-048",
    "Process safety fundamentals",
    "Evaluate independence of two credited protective layers.",
    5,
    "A high-level alarm and high-high shutdown use the same sensor, logic solver, power supply, and final valve. The analysis credits them as two independent layers because set points differ. What is the best conclusion?",
    [
      "Shared components create common failure paths, so separate independent credit is not justified without redesign and dependency analysis",
      "Different set points guarantee independence",
      "Two display icons create two protection layers",
      "Operator presence eliminates sensor failure",
    ],
    0,
    "Independent credit requires adequate separation in sensing, logic, utilities, final action, testing, and failure modes. Different thresholds on one chain do not protect against failure of that shared chain.",
    [
      "Correct. Risk reduction must reflect actual functional dependence.",
      "Set-point diversity does not overcome shared hardware and utilities.",
      "Interface labels do not create independent physical functions.",
      "An operator cannot respond to information the failed shared sensor never provides.",
    ],
    "ASP/CSP Exam Book",
    "Independent protection layers",
    "Redesign the functions to remove three shared failure paths.",
  ),
  item(
    "A2-049",
    "Emerging safety technology",
    "Validate human-robot collaborative safeguards under foreseeable faults.",
    5,
    "A collaborative robot slows when its camera detects a person. The vendor demo used ideal lighting, one body type, no reflective clothing, and no obscured lens. What should be required before relying on the function?",
    [
      "Validate representative users and conditions, fault responses, stopping performance, diagnostics, bypass resistance, maintenance, and a safe fallback",
      "Accept the demo because the robot slowed once",
      "Remove physical boundaries before testing",
      "Treat the camera as infallible artificial intelligence",
    ],
    0,
    "Safety performance must be demonstrated across foreseeable variation and single faults, with verified stopping and a defined response to degraded sensing. A favorable demonstration does not establish robust protection.",
    [
      "Correct. Validation tests the complete safety function and its limits.",
      "One ideal trial provides little evidence about coverage or failure behavior.",
      "Removing other controls before validation creates unnecessary exposure.",
      "All sensors and models have detection limits, failure modes, and maintenance needs.",
    ],
    "BCSP Blueprint",
    "Robotics and safety-function validation",
    "Name one false-negative and one false-positive test case and the safe expected response.",
  ),
  item(
    "A2-050",
    "Incident indicators and program evaluation",
    "Challenge causal claims when exposure and reporting change simultaneously.",
    5,
    "A dashboard shows injuries fell 30% after a program launch. Labor hours fell 20%, high-risk tasks moved to contractors whose data are excluded, and anonymous reporting also fell sharply. What is the strongest conclusion?",
    [
      "Program effect is not established; rebuild comparable exposure and population data, examine reporting climate, contractor outcomes, and critical-control performance",
      "The program caused exactly a 30% risk reduction",
      "Lower anonymous reporting proves hazards disappeared",
      "Raw counts are sufficient whenever they decline",
    ],
    0,
    "Reduced exposure, transferred work, missing contractor outcomes, and possible reporting suppression are alternative explanations. Evaluation requires comparable denominators and populations plus valid preventive-control evidence.",
    [
      "Correct. The analysis tests plausible rival explanations before attributing causation.",
      "The raw change is confounded and cannot isolate program effect.",
      "Fewer reports may indicate less trust or access rather than fewer hazards.",
      "Accurate counts can still mislead when exposure and surveillance change.",
    ],
    "Nito",
    "Program evaluation and reporting bias",
    "Design a four-measure dashboard that distinguishes true improvement from hidden or transferred risk.",
  ),
];
