/**
 * Original ASP11 practice content. These are not BCSP examination questions
 * and do not reproduce wording from BCSP, Pocket Prep, Yates, Nito, or any
 * commercial study bank.
 *
 * Official sources checked 2026-08-12:
 * - ASP11 blueprint (V.2024.04.24; domains and weights):
 *   https://www.bcsp.org/hubfs/Website/Blueprints-References/ASP-Blueprint.pdf?hsLang=en
 * - BCSP ASP credential and examination page:
 *   https://www.bcsp.org/associate-safety-professional-asp
 * - BCSP current examination time listing:
 *   https://www.bcsp.org/credentials-at-a-glance
 * - BCSP Complete Guide to Safety Certification (ASP format: 200 items,
 *   four options, one best answer, and five hours):
 *   https://online.fliphtml5.com/pbcyp/ijfs/
 * - BCSP examination experience and item-format guidance:
 *   https://www.bcsp.org/bcsp-news/about/bcsp-news/what-to-expect-when-sitting-for-a-bcsp-exam
 */

export type ASPDomainId = "A1" | "A2" | "A3" | "A4" | "A5" | "A6" | "A7" | "A8" | "A9";
export type ASPDifficulty = 1 | 2 | 3 | 4 | 5;
export type ASPOptionIndex = 0 | 1 | 2 | 3;
export type ASPReferenceFramework = "Yates" | "Nito" | "ASP/CSP Exam Book" | "BCSP Blueprint" | "NWS";

export interface ASPDomain {
  id: ASPDomainId;
  number: number;
  name: string;
  short: string;
  color: string;
  /** Fractional ASP11 blueprint weight; all nine domains sum to 1. */
  weight: number;
  competencies: readonly string[];
}

export interface ASPQuestion {
  id: string;
  domainId: ASPDomainId;
  competency: string;
  objective: string;
  difficulty: ASPDifficulty;
  stem: string;
  options: [string, string, string, string];
  correctIndex: ASPOptionIndex;
  rationale: string;
  /** Entries correspond positionally to options; the keyed option is marked Correct. */
  wrongRationales: [string, string, string, string];
  referenceFramework: ASPReferenceFramework;
  referenceTopic: string;
  challengePrompt: string;
}

export const ASP_DOMAINS = [
  {
    id: "A1",
    number: 1,
    name: "Mathematical Calculations",
    short: "A1",
    color: "#2563eb",
    weight: 0.10,
    competencies: [
      "Arithmetic, algebra, scientific notation, conversions, geometry, and trigonometry",
      "Mechanics, motion, energy, moments, friction, rigging, and fall-clearance calculations",
      "Hydraulic, fire-flow, capacity, excavation, and material-handling calculations",
      "Industrial-hygiene sampling, gases, mixtures, exposure, and ventilation calculations",
      "Noise, heat- and cold-stress, radiation, and nonionizing-radiation calculations",
      "Statistics, probability, incident rates, reliability, and risk calculations",
      "Engineering-economy, return, present/future worth, and capital-recovery calculations",
      "Ergonomic recommended-weight-limit and lifting-index calculations",
    ],
  },
  {
    id: "A2",
    number: 2,
    name: "Safety Programs and Concepts",
    short: "A2",
    color: "#0f766e",
    weight: 0.25,
    competencies: [
      "Safety management systems and hierarchy of controls",
      "Hazard analysis, risk matrices, and change management",
      "GHS, hazardous-energy control, and electrical principles",
      "Core workplace, process, fleet, and equipment safety",
      "Incident investigation, indicators, and emerging technology",
    ],
  },
  {
    id: "A3",
    number: 3,
    name: "Ergonomics",
    short: "A3",
    color: "#7c3aed",
    weight: 0.08,
    competencies: [
      "Ergonomics program elements and musculoskeletal outcomes",
      "Force, repetition, posture, contact, vibration, and environmental stressors",
      "Workspace and manual-material-handling design",
      "Work-practice controls and early intervention",
      "Qualitative, quantitative, and anthropometric analysis",
    ],
  },
  {
    id: "A4",
    number: 4,
    name: "Fire Prevention and Protection",
    short: "A4",
    color: "#dc2626",
    weight: 0.12,
    competencies: [
      "Fire science and flammable-material properties",
      "Electrical ignition, bonding, grounding, and hazardous locations",
      "Hot work and combustible-dust hazards",
      "Detection, suppression, and portable extinguishers",
      "Separation, housekeeping, signs, and labels",
    ],
  },
  {
    id: "A5",
    number: 5,
    name: "Emergency Preparedness and Response",
    short: "A5",
    color: "#d97706",
    weight: 0.10,
    competencies: [
      "Emergency-plan roles, communication, evacuation, and accountability",
      "Natural, human-caused, and biological emergencies",
      "Drills, security, life safety, and medical readiness",
      "Incident command, recovery, and business continuity",
      "Workplace violence prevention and lone-worker safeguards",
    ],
  },
  {
    id: "A6",
    number: 6,
    name: "Industrial Hygiene and Occupational Health",
    short: "A6",
    color: "#0891b2",
    weight: 0.12,
    competencies: [
      "Industrial-hygiene programs and exposure-control strategy",
      "Chemistry, anatomy, physiology, and toxicologic fundamentals",
      "Physical, chemical, and biological exposure assessment",
      "Exposure limits, routes of entry, and acute/chronic effects",
      "Universal precautions, radiation, fitness for duty, and Total Worker Health",
    ],
  },
  {
    id: "A7",
    number: 7,
    name: "Environmental Management",
    short: "A7",
    color: "#16a34a",
    weight: 0.07,
    competencies: [
      "Environmental hazards and impact pathways",
      "Water, air, land, spill, and conservation practices",
      "Reduce, reuse, recycle, and energy-recovery hierarchy",
      "Environmental management systems and continual improvement",
      "Waste lifecycle and EHS contributions to ESG",
    ],
  },
  {
    id: "A8",
    number: 8,
    name: "Training, Education, and Communication",
    short: "A8",
    color: "#4f46e5",
    weight: 0.11,
    competencies: [
      "Learning theory and task-appropriate delivery tools",
      "Safety culture, feedback, and psychological safety",
      "Needs, gap, and baseline-competency assessment",
      "Training effectiveness, retention, and transfer",
      "Human performance and competent-versus-qualified roles",
    ],
  },
  {
    id: "A9",
    number: 9,
    name: "Legal",
    short: "A9",
    color: "#475569",
    weight: 0.05,
    competencies: [
      "Compliance and professional-practice liability",
      "Contractors and multi-employer worksites",
      "Contracts and contract lifecycle",
      "Records, retention, chain of custody, and privacy",
      "Scope limitations, risk transfer, and impairment liability",
    ],
  },
] as const satisfies readonly ASPDomain[];

export const ASP_QUESTION_BANK_A = [
  {
    id: "A1-001",
    domainId: "A1",
    competency: "Storage capacity",
    objective: "Calculate usable rectangular-vessel capacity from dimensions and a fill restriction.",
    difficulty: 1,
    stem: "A rectangular process-water tank is 12 ft long, 8 ft wide, and 5 ft deep. Operations limits filling to 80% of geometric volume. What is the maximum planned liquid volume?",
    options: ["96 ft3", "384 ft3", "480 ft3", "600 ft3"],
    correctIndex: 1,
    rationale: "Geometric volume is 12 x 8 x 5 = 480 ft3. Applying the 0.80 operating fraction gives 384 ft3.",
    wrongRationales: [
      "This is 20% of the geometric volume, the unfilled allowance rather than usable volume.",
      "Correct. Multiplying 480 ft3 by 0.80 gives 384 ft3.",
      "This is the full geometric volume and ignores the stated fill restriction.",
      "This divides by 0.80 and therefore increases volume beyond the tank's geometry.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Volume and capacity",
    challengePrompt: "Convert the usable volume to gallons using 7.48 gal/ft3 and state one real operating allowance the simple geometry omits.",
  },
  {
    id: "A1-002",
    domainId: "A1",
    competency: "Rigging and load calculations",
    objective: "Resolve sling-leg tension from load and sling angle.",
    difficulty: 2,
    stem: "A symmetrical two-leg sling supports a 4,000 lb load. Each leg is 60 degrees above horizontal. Ignoring dynamics and sling weight, what is the approximate tension in each leg? Use T = W/[2 sin(theta)].",
    options: ["1,155 lb", "2,000 lb", "2,309 lb", "4,619 lb"],
    correctIndex: 2,
    rationale: "T = 4,000/[2 sin(60 degrees)] = 4,000/(2 x 0.866), approximately 2,309 lb per leg.",
    wrongRationales: [
      "This applies an extra division by two after resolving the vertical components.",
      "Half the load would be correct only for vertical sling legs; angled legs require more tension.",
      "Correct. Each leg's vertical component is about 2,000 lb, requiring about 2,309 lb of tension.",
      "This doubles the required per-leg tension after the two-leg relationship was already included.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Sling-angle mechanics",
    challengePrompt: "Predict the direction and practical significance of the tension change if the angle falls to 30 degrees.",
  },
  {
    id: "A1-003",
    domainId: "A1",
    competency: "Noise exposure calculations",
    objective: "Calculate combined fractional noise dose from stated allowable durations.",
    difficulty: 3,
    stem: "For a screening calculation, use dose fraction = C1/T1 + C2/T2. A worker spends 4 hours where the stated allowable duration is 8 hours, then 4 hours where the stated allowable duration is 16 hours. What is the combined dose percentage?",
    options: ["25%", "50%", "75%", "125%"],
    correctIndex: 2,
    rationale: "The fractions are 4/8 = 0.50 and 4/16 = 0.25. Their sum is 0.75, or 75% of the stated criterion dose.",
    wrongRationales: [
      "This includes only the second exposure period.",
      "This includes only the first exposure period.",
      "Correct. The two exposure fractions sum to 0.75, or 75%.",
      "This incorrectly adds hours and divides by only one allowable duration.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Combined noise dose",
    challengePrompt: "Explain why the calculation cannot be reused with exposure limits having a different exchange-rate convention unless the allowable durations are recalculated.",
  },
  {
    id: "A1-004",
    domainId: "A1",
    competency: "Fall-protection calculations",
    objective: "Calculate total clearance and compare it with available space.",
    difficulty: 4,
    stem: "A fall-arrest setup requires accounting for a 6 ft connecting device, 3.5 ft maximum deceleration, 1 ft harness/D-ring movement, and a 2 ft safety margin below the D-ring. The available unobstructed distance is 12.2 ft. What is the best conclusion?",
    options: [
      "Required clearance is 10.5 ft, so the setup is adequate",
      "Required clearance is 11.5 ft, so the setup is adequate",
      "Required clearance is 12.5 ft, so the setup is deficient by 0.3 ft",
      "Required clearance is 14.5 ft, so the setup is deficient by 2.3 ft",
    ],
    correctIndex: 2,
    rationale: "The stated components sum to 6 + 3.5 + 1 + 2 = 12.5 ft. Available clearance is 12.2 ft, leaving a 0.3 ft deficiency.",
    wrongRationales: [
      "This omits the 2 ft safety margin.",
      "This omits the 1 ft harness/D-ring movement allowance.",
      "Correct. All components total 12.5 ft, which exceeds the available distance by 0.3 ft.",
      "This double-counts the safety margin.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Fall-arrest clearance",
    challengePrompt: "Identify two dynamic or geometric factors that would still require validation before approving a redesigned system with exactly 12.5 ft available.",
  },
  {
    id: "A1-005",
    domainId: "A1",
    competency: "Probability of failure",
    objective: "Calculate scenario frequency using conditional independent barrier failures and recognize model limits.",
    difficulty: 5,
    stem: "A hazardous initiating event has an annual probability of 0.02. Harm occurs only if two independent safeguards both fail on demand; their failure probabilities are 0.10 and 0.05. Under the stated independence assumption, what is the annual harm probability?",
    options: ["0.0001", "0.001", "0.003", "0.15"],
    correctIndex: 0,
    rationale: "The path probability is 0.02 x 0.10 x 0.05 = 0.0001, or 1 x 10^-4 per year. This result depends critically on genuine independence and valid demand data.",
    wrongRationales: [
      "Correct. Multiplying the initiating probability by both conditional failure probabilities gives 0.0001.",
      "This is the product of the two safeguard failures without the initiating-event probability.",
      "This adds the safeguard failure probabilities before multiplying, which does not represent an AND condition.",
      "This simply adds the safeguard failure probabilities and omits the initiating event.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Event-path probability and independence",
    challengePrompt: "Describe one shared dependency that would invalidate the product and how you would add it to the model.",
  },

  {
    id: "A2-001",
    domainId: "A2",
    competency: "Hierarchy of controls",
    objective: "Select a source-level control over administrative and PPE measures.",
    difficulty: 1,
    stem: "Workers manually clean parts with a highly volatile solvent in open trays. Testing identifies a water-based product that performs the task without the volatile hazard. Which proposed action ranks highest in the hierarchy of controls?",
    options: [
      "Substitute the validated water-based product",
      "Post a sign reminding workers to close trays",
      "Rotate workers through the cleaning station",
      "Issue thicker gloves while keeping the original process",
    ],
    correctIndex: 0,
    rationale: "A validated substitution removes the original volatile material from the task. Signs, rotation, and PPE leave the source substantially unchanged.",
    wrongRationales: [
      "Correct. Replacing the hazardous material is a source-level substitution control.",
      "A reminder depends on behavior and does not eliminate the solvent.",
      "Rotation redistributes exposure rather than controlling the source.",
      "Gloves may reduce dermal contact but do not address vapor generation and are lower in the hierarchy.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Hierarchy of hazard controls",
    challengePrompt: "Name two compatibility or lifecycle checks required before the substitution is approved.",
  },
  {
    id: "A2-002",
    domainId: "A2",
    competency: "Hazardous-energy control",
    objective: "Recognize and control stored energy after primary isolation.",
    difficulty: 2,
    stem: "A conveyor's electrical disconnect is locked open, but a raised counterweight can still drive belt motion. What must occur before an employee enters the pinch zone?",
    options: [
      "Wait until the employee believes the motor has cooled",
      "Block or lower the counterweight to a safe state and verify that all energy is controlled",
      "Place an emergency-stop button within the employee's reach",
      "Ask a spotter to watch the belt while servicing continues",
    ],
    correctIndex: 1,
    rationale: "Energy control covers gravitational and stored mechanical energy as well as electricity. The counterweight must be restrained or brought to a safe state, followed by verification.",
    wrongRationales: [
      "Motor temperature does not control the counterweight's gravitational energy.",
      "Correct. It addresses the residual energy source and confirms effective isolation.",
      "An emergency stop is reactive and does not isolate or restrain stored energy.",
      "Observation cannot prevent unintended motion and is not energy isolation.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Stored-energy isolation",
    challengePrompt: "Explain how you would verify isolation if the counterweight is hidden from the servicing position.",
  },
  {
    id: "A2-003",
    domainId: "A2",
    competency: "Common workplace hazards",
    objective: "Respond correctly to evidence of changed excavation conditions.",
    difficulty: 3,
    stem: "After heavy rain, workers observe new tension cracks parallel to an excavation edge and water collecting at the toe. The excavation was acceptable the previous day. What should the supervisor do first?",
    options: [
      "Let the crew finish one short task before conditions worsen",
      "Send one worker down to measure crack depth",
      "Remove workers from exposure and obtain a competent reassessment before re-entry",
      "Cover the cracks with dry soil so the surface appears stable",
    ],
    correctIndex: 2,
    rationale: "Rain, tension cracking, and water accumulation signal changed stability conditions. Exposure should stop before a competent reassessment and any protective-system correction.",
    wrongRationales: [
      "Continuing work exposes the crew during evidence of an evolving collapse hazard.",
      "This deliberately exposes a worker to characterize a condition that already requires withdrawal.",
      "Correct. Immediate removal precedes technical reassessment and corrective work.",
      "Concealing surface evidence neither drains water nor stabilizes the soil mass.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Excavation changing conditions",
    challengePrompt: "Explain how surcharge loading and water can interact to reduce excavation stability.",
  },
  {
    id: "A2-004",
    domainId: "A2",
    competency: "Management of change",
    objective: "Apply proportionate change control to a temporary protective-system modification.",
    difficulty: 4,
    stem: "Maintenance proposes forcing a high-temperature trip input to its normal state for one shift while a sensor is replaced. Which response best applies management-of-change principles?",
    options: [
      "Treat the bypass as routine because it lasts less than one day",
      "Allow it if an operator promises to watch the temperature display",
      "Require a documented review of necessity, scenario risk, compensating safeguards, authority, communication, time limit, and verified restoration",
      "Raise the alarm setting so operators receive fewer nuisance alerts",
    ],
    correctIndex: 2,
    rationale: "A temporary bypass impairs an engineered safeguard. Its short duration increases the need for explicit authorization, compensating measures, shift communication, expiry, and restoration verification.",
    wrongRationales: [
      "Temporary changes can create acute risk and are not exempt merely because they are brief.",
      "Human monitoring may be considered in a review but cannot by itself establish an equivalent, reliable protective layer.",
      "Correct. This governs the impairment from approval through restoration.",
      "Raising an alarm threshold further reduces warning and does not repair the failed sensor.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Temporary change and safeguard impairment",
    challengePrompt: "State one condition that should make the proposed bypass unacceptable regardless of production impact.",
  },
  {
    id: "A2-005",
    domainId: "A2",
    competency: "Emerging safety technology",
    objective: "Evaluate an AI safety system without confusing model output with validated control performance.",
    difficulty: 5,
    stem: "A camera model flags missing eye protection with 94% overall accuracy in a vendor test. At one site, glare is common, contractors use different helmet colors, and supervisors plan to trigger automatic discipline from each alert. What should the safety professional require before deployment?",
    options: [
      "Deploy immediately because accuracy above 90% proves fairness and reliability",
      "Use alerts only for discipline so workers take the system seriously",
      "Validate performance on representative site conditions, examine false positives and false negatives by relevant groups, define human review and appeal, protect data, and monitor drift",
      "Reject all computer vision because technology can never support safety work",
    ],
    correctIndex: 2,
    rationale: "A single aggregate vendor metric does not establish local validity, error consequences, equitable performance, privacy, or stability. Representative validation and governed human use are required before consequential decisions.",
    wrongRationales: [
      "Aggregate accuracy can hide severe class imbalance, local-domain shift, and unequal error rates.",
      "Automatic punishment magnifies false-positive harm and discourages reporting without validating the system.",
      "Correct. It tests local validity and establishes safeguards for consequential use and changing performance.",
      "A categorical ban ignores legitimate uses such as trend screening when technology is properly validated and governed.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Emerging technology assurance",
    challengePrompt: "Construct a confusion matrix and explain which error type is more dangerous for a coaching-only use versus automatic discipline.",
  },

  {
    id: "A3-001",
    domainId: "A3",
    competency: "Ergonomic risk factors",
    objective: "Identify a basic awkward-posture risk factor.",
    difficulty: 1,
    stem: "An assembler works for long periods with the wrist bent sharply toward the little-finger side. Which ergonomic risk factor is most directly described?",
    options: ["Neutral posture", "Awkward posture", "Whole-body vibration", "Thermal acclimatization"],
    correctIndex: 1,
    rationale: "Sustained deviation of the wrist from a neutral alignment is an awkward-posture exposure that can increase tissue loading, especially when combined with force or repetition.",
    wrongRationales: [
      "Neutral posture keeps joints near their midrange rather than sharply deviated.",
      "Correct. The described wrist deviation is an awkward posture.",
      "No vibration source or transmission to the whole body is described.",
      "Acclimatization concerns physiologic adaptation to heat, not wrist alignment.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Postural risk factors",
    challengePrompt: "Name two task variables that would determine how serious this posture is.",
  },
  {
    id: "A3-002",
    domainId: "A3",
    competency: "Workspace design",
    objective: "Select an adjustable design that accommodates a broad worker population.",
    difficulty: 2,
    stem: "A packing bench will be shared by workers with widely different statures and by both seated and standing users. Which design is strongest?",
    options: [
      "Fix the surface at the mean worker's elbow height",
      "Make the surface height adjustable and provide compatible reach, clearance, and support adjustments",
      "Set the bench for the tallest worker and give shorter workers boxes to stand on",
      "Set the bench for the shortest worker and require taller workers to bend",
    ],
    correctIndex: 1,
    rationale: "Adjustability accommodates a range of bodies and task demands while preserving reach, clearance, and support. Designing to the mean excludes many users.",
    wrongRationales: [
      "An average dimension does not reliably fit people near either end of the distribution.",
      "Correct. Coordinated adjustability is the best way to accommodate shared use and task variation.",
      "Improvised boxes can create instability and do not solve reach or support mismatches.",
      "A fixed low surface transfers the mismatch to taller workers through trunk flexion.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Anthropometry and adjustability",
    challengePrompt: "Give one clearance dimension commonly designed for a large user and one reach dimension commonly designed for a small user.",
  },
  {
    id: "A3-003",
    domainId: "A3",
    competency: "Ergonomic analysis methods",
    objective: "Match an assessment method to the exposure being evaluated.",
    difficulty: 3,
    stem: "A task consists mainly of frequent two-handed floor-to-waist lifts of uniform cartons. The team wants a quantitative screening estimate of recommended load under the task geometry. Which tool is the best primary match?",
    options: [
      "A revised lifting-equation analysis",
      "A hearing-conservation dosimeter",
      "A fire-hazard checklist",
      "A worker-satisfaction survey alone",
    ],
    correctIndex: 0,
    rationale: "A lifting-equation analysis is designed to screen specified two-handed lifting conditions using load and geometry multipliers. It must still be checked against its applicability limits.",
    wrongRationales: [
      "Correct. The method directly addresses manual-lift load and geometry.",
      "A noise dosimeter measures sound exposure, not manual-lifting demand.",
      "Fire-hazard review does not quantify biomechanical lifting conditions.",
      "Worker feedback is useful but cannot alone provide the requested quantitative load screen.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Ergonomic tool selection",
    challengePrompt: "List three task features that could make a lifting-equation result inapplicable or incomplete.",
  },
  {
    id: "A3-004",
    domainId: "A3",
    competency: "Work-practice controls",
    objective: "Recognize when job rotation fails to reduce cumulative ergonomic loading.",
    difficulty: 4,
    stem: "To address shoulder complaints, a supervisor rotates employees every two hours among drilling, overhead inspection, and high-shelf picking. All three tasks require sustained arm elevation. What is the principal flaw?",
    options: [
      "Rotation always increases exposure because workers perform more jobs",
      "The schedule changes task names but may not provide recovery to the same loaded tissues",
      "Two-hour rotations eliminate the need to evaluate force and posture",
      "Rotation is an engineering control that removes arm elevation",
    ],
    correctIndex: 1,
    rationale: "Useful rotation varies the tissues and demands involved or provides recovery. Moving among tasks that share the same dominant shoulder exposure may only redistribute continuous loading.",
    wrongRationales: [
      "Rotation can help when alternated tasks genuinely differ in demand and recovery; it is not inherently harmful.",
      "Correct. The common arm-elevation demand defeats the intended recovery effect.",
      "Timing alone does not erase the need to characterize posture, force, repetition, and duration.",
      "Rotation is administrative and does not physically remove the posture from any task.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Job rotation and tissue recovery",
    challengePrompt: "Redesign the sequence using one low-shoulder-load task and specify how you would verify recovery rather than assume it.",
  },
  {
    id: "A3-005",
    domainId: "A3",
    competency: "Ergonomic intervention evaluation",
    objective: "Evaluate an exoskeleton as a system change with transferred and residual risks.",
    difficulty: 5,
    stem: "A passive shoulder exoskeleton lowers measured deltoid activity during overhead work, but workers report trunk pressure, restricted emergency egress, and difficulty using fall-arrest equipment. What is the most defensible next step?",
    options: [
      "Mandate the device because one muscle-activity measure improved",
      "Discard worker reports because they are subjective",
      "Prefer redesign that removes overhead work where feasible; meanwhile conduct task-specific trials assessing total biomechanical load, fit, compatibility, escape, new hazards, and sustained outcomes",
      "Use the exoskeleton to justify longer overhead-work periods",
    ],
    correctIndex: 2,
    rationale: "A local reduction in one muscle signal does not establish lower total risk. The device may transfer load or interfere with critical systems, so source-level redesign remains preferable and any interim use requires whole-task validation.",
    wrongRationales: [
      "A single surrogate outcome cannot outweigh unassessed transferred loads and safety-system interference.",
      "Structured worker reports are important evidence about fit, usability, discomfort, and task conflict.",
      "Correct. It preserves hierarchy-of-controls reasoning and evaluates benefits, transfers, compatibility, and durability.",
      "Extending duration can consume any benefit and increase exposure to residual or transferred risk.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Wearable ergonomic controls",
    challengePrompt: "Define one biomechanical, one usability, and one operational effectiveness measure for the trial.",
  },

  {
    id: "A4-001",
    domainId: "A4",
    competency: "Fire science fundamentals",
    objective: "Identify the combustion element removed by a cooling agent.",
    difficulty: 1,
    stem: "Water applied to an ordinary solid-fuel fire primarily interrupts combustion by removing which element?",
    options: ["Heat", "Fuel", "Oxygen from the entire room", "The chemical identity of the fuel"],
    correctIndex: 0,
    rationale: "Water's principal effect on an ordinary solid-fuel fire is heat absorption, cooling the fuel below the temperature needed to sustain combustion.",
    wrongRationales: [
      "Correct. Cooling removes heat from the combustion process.",
      "The combustible material generally remains present after water application.",
      "Water does not normally remove all oxygen from the room.",
      "Cooling does not change the fuel into a different chemical substance as its primary mechanism.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Fire tetrahedron and cooling",
    challengePrompt: "Explain why the same tactic can be inappropriate when the burning material reacts dangerously with water.",
  },
  {
    id: "A4-002",
    domainId: "A4",
    competency: "Electrostatic ignition control",
    objective: "Differentiate bonding from grounding during liquid transfer.",
    difficulty: 2,
    stem: "A flammable liquid is transferred between two conductive metal containers. Which arrangement most directly limits a spark from potential difference between the containers and allows charge to dissipate to earth?",
    options: [
      "Bond the containers to each other and ground the conductive system",
      "Place both containers on dry plastic pallets without conductors",
      "Increase transfer velocity to shorten exposure time",
      "Ground only the employee's footwear and leave the containers isolated",
    ],
    correctIndex: 0,
    rationale: "Bonding equalizes electrical potential between conductive containers; grounding provides a path for charge to dissipate to earth. Both functions address the stated transfer scenario.",
    wrongRationales: [
      "Correct. Bonding controls container-to-container potential while grounding dissipates system charge.",
      "Insulation can permit charge accumulation rather than provide a controlled dissipation path.",
      "Higher velocity can increase splashing and charge generation.",
      "Footwear control does not equalize or ground the two conductive containers.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Bonding and grounding",
    challengePrompt: "Describe how you would verify continuity without assuming that physical contact through paint is conductive.",
  },
  {
    id: "A4-003",
    domainId: "A4",
    competency: "Combustible dust",
    objective: "Recognize the confinement and dispersion conditions that transform a dust fire into an explosion hazard.",
    difficulty: 3,
    stem: "A fine organic powder burns when piled, and layers have accumulated on beams inside an enclosed room. Which observation creates the strongest concern for a secondary dust explosion?",
    options: [
      "The powder is stored in labeled bags",
      "A small primary event could suspend accumulated dust into a confined cloud near ignition sources",
      "The room has painted walls",
      "Employees can see the settled layers from the floor",
    ],
    correctIndex: 1,
    rationale: "A primary event can disperse settled combustible dust, creating a cloud with fuel, oxygen, confinement, and ignition. Secondary explosions can involve far more material than the initiating event.",
    wrongRationales: [
      "Labels communicate identity but do not control dispersion, confinement, or ignition.",
      "Correct. It describes the credible sequence that adds dispersion and confinement to the combustion conditions.",
      "Paint color or presence does not establish control of the dust cloud hazard.",
      "Visibility helps recognition but does not itself explain the explosive escalation mechanism.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Dust explosion pentagon",
    challengePrompt: "Propose one source-control measure and one ignition-control measure, then explain why housekeeping method matters.",
  },
  {
    id: "A4-004",
    domainId: "A4",
    competency: "Hot work and suppression impairment",
    objective: "Coordinate simultaneous ignition work and reduced fire protection.",
    difficulty: 4,
    stem: "A contractor requests hot-work authorization in a warehouse zone whose automatic suppression system will be impaired for repairs. Combustible packaging remains nearby. What is the best decision framework?",
    options: [
      "Issue the permit because a portable extinguisher replaces any fixed system",
      "Proceed if the welder has performed the task before",
      "Postpone or relocate the work where feasible; otherwise use formal impairment and hot-work reviews with combustible control, compensating protection, monitoring, fire watch, communication, and restoration criteria",
      "Turn off fire detection so alarms do not interrupt the repair",
    ],
    correctIndex: 2,
    rationale: "The work adds ignition while fixed protection is degraded. Avoiding the overlap is strongest; any justified exception requires coordinated impairment controls, not a hot-work permit in isolation.",
    wrongRationales: [
      "A portable extinguisher does not reproduce the coverage, automatic operation, or capacity of the impaired system.",
      "Experience does not control surrounding fuel or the loss of automatic protection.",
      "Correct. It first seeks to remove the overlap and then governs any necessary residual risk comprehensively.",
      "Disabling detection removes another protective layer and delays recognition.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Hot work during protection impairment",
    challengePrompt: "Name two objective conditions that should terminate the permit immediately after work begins.",
  },
  {
    id: "A4-005",
    domainId: "A4",
    competency: "Flammable-vapor control",
    objective: "Interpret vapor concentration relative to flammable limits and prioritize prevention.",
    difficulty: 5,
    stem: "A solvent has a lower flammable limit of 1% by volume and an upper flammable limit of 7%. A direct-reading instrument reports 1.4% in a poorly ventilated enclosure with normal oxygen. Which interpretation is strongest?",
    options: [
      "The atmosphere is too rich to burn because it exceeds the lower limit",
      "The atmosphere lies within the stated flammable range; entry and ignition must be controlled while the source is stopped and ventilation or other engineered control is established",
      "The atmosphere is safe because 1.4% is below the upper limit",
      "Only respiratory toxicity matters because flammability begins above 7%",
    ],
    correctIndex: 1,
    rationale: "A concentration between the lower and upper limits can propagate flame under the stated oxygen condition. Immediate priorities include exposure control, ignition prevention, source control, and suitable engineering measures.",
    wrongRationales: [
      "A mixture becomes too rich only above the upper limit under the stated conditions.",
      "Correct. 1.4% is above 1% and below 7%, placing it within the stated flammable range.",
      "Being below the upper limit does not imply safety when the concentration also exceeds the lower limit.",
      "The interval from 1% to 7% is the stated flammable range; toxicity may be an additional concern.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Lower and upper flammable limits",
    challengePrompt: "Explain why a reading below the lower limit at one location cannot establish that the entire enclosure is safe.",
  },

  {
    id: "A5-001",
    domainId: "A5",
    competency: "Emergency plan elements",
    objective: "Identify the essential accountability function following evacuation.",
    difficulty: 1,
    stem: "After an evacuation alarm, which action most directly helps determine whether anyone may remain in danger?",
    options: [
      "Count only vehicles in the parking lot",
      "Use the site's planned accountability process for employees, contractors, and visitors",
      "Wait for each person to post on social media",
      "Assume all trained employees evacuated successfully",
    ],
    correctIndex: 1,
    rationale: "A planned accountability process covers everyone known to be on site and provides responders with actionable information about potentially missing people.",
    wrongRationales: [
      "Vehicle counts do not map reliably to people and omit passengers, transit users, contractors, and visitors.",
      "Correct. The process is designed to identify who was present and who is accounted for.",
      "Social-media posts are uncontrolled, incomplete, and unsuitable as the primary accountability method.",
      "Training does not prove that every person escaped or reached the assembly point.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Evacuation accountability",
    challengePrompt: "Describe one redundant accountability method for a site whose electronic badge system may fail during a power outage.",
  },
  {
    id: "A5-002",
    domainId: "A5",
    competency: "Lone-worker safeguards",
    objective: "Design a check-in system with automatic escalation for a remote high-risk task.",
    difficulty: 2,
    stem: "A technician performs remote inspections where cellular coverage is intermittent. Which lone-worker arrangement is strongest?",
    options: [
      "Tell the technician to call if something goes wrong",
      "Use scheduled check-ins with a suitable communication method, missed-check escalation, location/task information, and defined rescue actions",
      "Rely on the technician's experience and remove reporting requirements",
      "Ask the technician to leave a handwritten note at home",
    ],
    correctIndex: 1,
    rationale: "A viable lone-worker system anticipates incapacitation and communication gaps. It defines contact intervals, missed-contact triggers, responder information, and action rather than depending on self-initiation after harm.",
    wrongRationales: [
      "An incapacitated worker may be unable to initiate a call, and cellular coverage is known to be unreliable.",
      "Correct. It creates a monitored, actionable process matched to the task and communication environment.",
      "Experience does not eliminate delayed discovery or the need for emergency coordination.",
      "A note that is not actively monitored cannot trigger timely response.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Remote and lone work",
    challengePrompt: "Set a defensible check-in interval for one chosen hazard and explain the link between onset time and escalation time.",
  },
  {
    id: "A5-003",
    domainId: "A5",
    competency: "Drills and preparedness",
    objective: "Convert drill observations into verified plan improvements.",
    difficulty: 3,
    stem: "During a drill, one assembly area becomes inaccessible and supervisors use conflicting headcounts. No one is injured. What is the best follow-up?",
    options: [
      "Declare success because everyone eventually appeared",
      "Repeat the same drill without changing anything",
      "Capture evidence in a structured debrief, analyze plan and execution gaps, assign corrective actions, update alternatives, and retest the changes",
      "Discipline the last person counted without reviewing the system",
    ],
    correctIndex: 2,
    rationale: "Drills are tests of assumptions and system performance. A closed improvement loop analyzes the observed failure modes, changes the plan and resources, and verifies effectiveness in a later exercise.",
    wrongRationales: [
      "The inaccessible area and conflicting counts are significant weaknesses even without actual harm.",
      "Repetition without learning preserves the same failure mechanisms.",
      "Correct. It turns observations into controlled improvements and evidence of effectiveness.",
      "Blaming one participant ignores the inaccessible location and inconsistent accountability process.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Exercise evaluation and corrective action",
    challengePrompt: "Write one measurable performance objective for the next accountability drill.",
  },
  {
    id: "A5-004",
    domainId: "A5",
    competency: "Incident command and continuity",
    objective: "Preserve life-safety command while activating continuity functions.",
    difficulty: 4,
    stem: "A fire disables the primary data center and disrupts customer operations. Executives begin directing fireground tactics while the incident commander manages evacuation. What organizational correction is best?",
    options: [
      "Let every executive issue tactical orders because they own the business",
      "Keep life-safety response under a clear incident-command structure while activating a coordinated continuity team with defined interfaces and information flow",
      "Delay evacuation decisions until the continuity team estimates revenue loss",
      "Merge all roles into one person regardless of event scale",
    ],
    correctIndex: 1,
    rationale: "Emergency command and business continuity must coordinate without competing tactical authority. Clear roles protect life safety while a parallel continuity function manages restoration, stakeholders, and business priorities.",
    wrongRationales: [
      "Multiple uncontrolled command channels create conflicting direction and can endanger responders and occupants.",
      "Correct. It preserves command unity and establishes a managed interface with continuity work.",
      "Life-safety decisions should not be subordinated to an uncompleted financial estimate.",
      "Incident scale may require delegated functions and manageable spans rather than role collapse.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Incident command and business continuity",
    challengePrompt: "Define three information exchanges needed between the incident command and continuity teams during the first hour.",
  },
  {
    id: "A5-005",
    domainId: "A5",
    competency: "Protective-action decision making",
    objective: "Use scenario-specific triggers to choose and adapt shelter or evacuation during compound hazards.",
    difficulty: 5,
    stem: "A hurricane warning coincides with a nearby toxic release. Roads may flood within an hour, while the current plume forecast crosses the site's normal evacuation route. What is the strongest protective-action approach?",
    options: [
      "Always evacuate because evacuation is universally safer than sheltering",
      "Always shelter because travel creates some risk",
      "Use current plume, weather, route, building-protection, population, and timing data to select a protective action, define decision authority and triggers, communicate it, and reassess as conditions change",
      "Let each employee independently choose a route without coordination",
    ],
    correctIndex: 2,
    rationale: "Compound emergencies make static rules dangerous. The decision must compare time-dependent risks of movement and shelter, identify authoritative triggers, account for vulnerable populations, and adapt as forecasts and routes change.",
    wrongRationales: [
      "Evacuation can move people into a plume or flood and is not universally superior.",
      "Shelter quality and plume duration vary, so sheltering is not universally superior either.",
      "Correct. It uses scenario evidence, authority, communication, and adaptive thresholds.",
      "Uncoordinated choices undermine accountability and can direct people into higher-risk areas.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Compound-emergency protective actions",
    challengePrompt: "Propose one quantitative trigger for abandoning shelter and one for closing the normal evacuation route.",
  },

  {
    id: "A6-001",
    domainId: "A6",
    competency: "Routes of entry",
    objective: "Identify dermal absorption as an exposure route.",
    difficulty: 1,
    stem: "A liquid contaminant passes through intact skin and enters systemic circulation. Which route of entry is described?",
    options: ["Inhalation", "Ingestion", "Dermal absorption", "Injection by pressure only"],
    correctIndex: 2,
    rationale: "Movement through intact skin into the body is dermal absorption. Skin contact can therefore be a systemic as well as a local exposure concern.",
    wrongRationales: [
      "Inhalation involves entry through the respiratory tract.",
      "Ingestion involves swallowing material through the gastrointestinal tract.",
      "Correct. The substance crosses the skin barrier into systemic circulation.",
      "Injection involves penetration through a wound or high-pressure event, neither of which is described.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Routes of occupational exposure",
    challengePrompt: "Explain why a low airborne measurement cannot rule out significant total exposure for a skin-absorbed substance.",
  },
  {
    id: "A6-002",
    domainId: "A6",
    competency: "Acute and chronic exposure",
    objective: "Differentiate acute effects from chronic outcomes.",
    difficulty: 2,
    stem: "Which description best represents a chronic occupational health effect?",
    options: [
      "Eye irritation immediately after a splash",
      "Dizziness during a single short solvent release",
      "Progressive hearing loss after repeated unprotected noise exposure over years",
      "A skin burn occurring seconds after contact with a corrosive",
    ],
    correctIndex: 2,
    rationale: "A chronic effect develops or persists over an extended period, often after repeated exposure. Progressive noise-induced hearing loss fits that pattern.",
    wrongRationales: [
      "Immediate splash irritation is an acute effect.",
      "Symptoms during one short release describe an acute response.",
      "Correct. The effect develops progressively across repeated exposure over years.",
      "A rapid corrosive burn is an acute effect even if its consequences persist.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Exposure duration and health effects",
    challengePrompt: "Give an example in which the same agent can cause both an acute and a chronic effect.",
  },
  {
    id: "A6-003",
    domainId: "A6",
    competency: "Occupational exposure limits",
    objective: "Distinguish ceiling limits from time-weighted limits.",
    difficulty: 3,
    stem: "A substance has a ceiling exposure limit because brief peaks can rapidly cause serious irritation. Which sampling strategy is most aligned with evaluating that limit?",
    options: [
      "Use only an eight-hour average that can hide short peaks",
      "Measure or otherwise characterize peak concentrations during the highest-exposure tasks with suitable time resolution",
      "Sample a quiet office on another floor",
      "Rely only on the annual quantity purchased",
    ],
    correctIndex: 1,
    rationale: "A ceiling is intended to constrain concentration at any time, so the evaluation needs sufficient temporal resolution and targeting of plausible peaks rather than only a long-duration average.",
    wrongRationales: [
      "A long averaging period can dilute a dangerous short-duration excursion.",
      "Correct. Peak-focused, time-resolved evaluation matches the ceiling concept.",
      "A remote low-exposure area does not represent the task or worst credible concentration.",
      "Purchase volume is an inventory indicator, not a measurement of airborne peak exposure.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Ceiling, short-term, and time-weighted limits",
    challengePrompt: "Explain how instrument response time can bias a peak-exposure conclusion.",
  },
  {
    id: "A6-004",
    domainId: "A6",
    competency: "Radiation principles",
    objective: "Apply the inverse-square relationship to a point-source exposure rate.",
    difficulty: 4,
    stem: "Treat a small radiation source as a point source with no shielding. The dose rate is 8 mrem/h at 1 m. What dose rate is expected at 2 m?",
    options: ["2 mrem/h", "4 mrem/h", "8 mrem/h", "16 mrem/h"],
    correctIndex: 0,
    rationale: "Under the inverse-square law, intensity changes by (1/2)^2 when distance doubles. Eight multiplied by one-quarter equals 2 mrem/h.",
    wrongRationales: [
      "Correct. Doubling distance reduces point-source intensity to one-quarter.",
      "This applies a simple inverse relationship rather than the inverse square.",
      "This assumes distance has no effect.",
      "This reverses the direction of the distance effect.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Time, distance, shielding, and inverse square",
    challengePrompt: "State two conditions under which this ideal point-source calculation would not accurately predict a worker's dose.",
  },
  {
    id: "A6-005",
    domainId: "A6",
    competency: "Exposure assessment and control",
    objective: "Integrate environmental, metabolic, clothing, and worker factors in heat-risk control.",
    difficulty: 5,
    stem: "A new crew performs heavy outdoor work during the first hot week of the season while wearing vapor-resistant suits. A manager proposes using ambient temperature alone to set one work/rest schedule for everyone. What is the best response?",
    options: [
      "Accept the plan because clothing does not affect heat exchange",
      "Use thirst as the only trigger for rest",
      "Assess relevant environmental heat, workload, clothing burden, acclimatization, and individual factors; then layer engineering, administrative, hydration, observation, and response controls",
      "Increase work pace so exposure ends sooner",
    ],
    correctIndex: 2,
    rationale: "Heat strain reflects environment, metabolic demand, clothing, acclimatization, health, and recovery. Vapor-resistant clothing can sharply impair heat loss, making an ambient-temperature-only plan inadequate.",
    wrongRationales: [
      "Low-permeability clothing can restrict evaporative cooling and materially increase physiologic burden.",
      "Thirst may lag need and does not address workload, clothing, environment, or acclimatization.",
      "Correct. It characterizes total heat burden and applies layered controls with early response.",
      "Faster work raises metabolic heat production and can worsen heat strain.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Heat stress and acclimatization",
    challengePrompt: "Explain why two workers in the same air temperature may require different controls without assuming either is unfit.",
  },

  {
    id: "A7-001",
    domainId: "A7",
    competency: "Conservation hierarchy",
    objective: "Prioritize source reduction over downstream waste handling.",
    difficulty: 1,
    stem: "A facility can prevent 10 tons of scrap from being generated by improving cut patterns, or recycle the same 10 tons after generation. Which action generally ranks higher in the conservation hierarchy?",
    options: ["Prevent the scrap through improved cut patterns", "Recycle the generated scrap", "Send the scrap to disposal", "Store the scrap indefinitely"],
    correctIndex: 0,
    rationale: "Source reduction avoids material use and waste generation before collection and processing are needed, so it generally precedes reuse, recycling, recovery, and disposal.",
    wrongRationales: [
      "Correct. Preventing generation is source reduction and normally ranks highest.",
      "Recycling is preferable to disposal but still requires the scrap to be generated and processed.",
      "Disposal recovers less value and retains environmental burdens.",
      "Indefinite storage delays management and can create accumulation and release risks.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Waste and conservation hierarchy",
    challengePrompt: "Identify one quality or production constraint that must be checked before changing the cut pattern.",
  },
  {
    id: "A7-002",
    domainId: "A7",
    competency: "Spill prevention and water protection",
    objective: "Select immediate controls that interrupt an environmental release pathway.",
    difficulty: 2,
    stem: "A small oil leak is moving across pavement toward an open storm drain. No worker exposure prevents safe response. What priority action best protects the environment?",
    options: [
      "Wash the oil into the drain before it spreads sideways",
      "Stop the source if safe, protect or block the drain, contain the oil, and initiate the response and reporting process",
      "Wait for rain to dilute the oil",
      "Photograph the leak and take no physical action",
    ],
    correctIndex: 1,
    rationale: "The response should safely stop ongoing release and interrupt the pathway to surface water, then contain, recover, and manage notification under the site's plan.",
    wrongRationales: [
      "Washing accelerates transport into the environmental receptor and increases contaminated volume.",
      "Correct. It controls source and pathway before recovery and required communication.",
      "Rain can spread contamination and does not make the release acceptable.",
      "Documentation is useful but does not prevent the oil from entering the drain.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Source-pathway-receptor spill control",
    challengePrompt: "Describe how your priorities would change if stopping the source required entering an unsafe atmosphere.",
  },
  {
    id: "A7-003",
    domainId: "A7",
    competency: "Waste characterization",
    objective: "Base waste decisions on process knowledge and representative evidence rather than appearance.",
    difficulty: 3,
    stem: "A drum is labeled 'nonhazardous rinse water,' but process records show the upstream formulation changed and no characterization followed. What is the best action before shipment?",
    options: [
      "Ship it under the old description because the liquid looks clear",
      "Mix it with known nonhazardous waste to reduce concentration",
      "Hold the shipment, investigate the generating process, obtain representative characterization as needed, and update classification and records",
      "Remove the label so the transporter can decide",
    ],
    correctIndex: 2,
    rationale: "Waste identity follows the generating process and defensible characterization, not color or an outdated label. The process change creates uncertainty that must be resolved before selection of handling and destination.",
    wrongRationales: [
      "Appearance cannot establish chemical identity or hazard, and the old basis may no longer apply.",
      "Dilution can increase volume, create incompatibility, and does not substitute for correct characterization.",
      "Correct. It restores a defensible link between process, evidence, classification, and documentation.",
      "Removing information transfers uncertainty without meeting the generator's responsibility to characterize the material.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Waste identification and process knowledge",
    challengePrompt: "Design a sampling approach that addresses stratification or settling within the drum.",
  },
  {
    id: "A7-004",
    domainId: "A7",
    competency: "Environmental management systems",
    objective: "Connect significant aspects to operational controls and effectiveness evaluation.",
    difficulty: 4,
    stem: "An environmental-aspect review identifies solvent loss to air as significant, yet the annual objective merely says 'raise awareness.' What improvement makes the objective operationally useful?",
    options: [
      "Keep the phrase broad so no department can be held accountable",
      "Define a measurable outcome, baseline, owner, controls, resources, milestones, monitoring method, and review criteria tied to solvent loss",
      "Measure only the number of posters distributed",
      "Remove the aspect from the register because it is difficult to quantify",
    ],
    correctIndex: 1,
    rationale: "A significant aspect should connect to actionable control and evaluation. A defined baseline, target, responsibility, plan, and monitoring method allows the organization to determine whether environmental performance actually improves.",
    wrongRationales: [
      "Vagueness prevents accountability and objective evaluation.",
      "Correct. It converts intent into managed action and measurable performance.",
      "Poster count is an activity measure and does not establish reduced solvent loss.",
      "Analytical difficulty is not a reason to hide a significant aspect.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Objectives, operational control, and evaluation",
    challengePrompt: "Write one leading and one outcome indicator for this objective, each normalized to production.",
  },
  {
    id: "A7-005",
    domainId: "A7",
    competency: "Waste lifecycle and ESG",
    objective: "Evaluate outsourced waste management beyond paperwork and financial transfer.",
    difficulty: 5,
    stem: "A low-cost waste contractor provides complete manifests, but satellite images and community complaints suggest material may be dumped near its facility. Procurement says the signed contract transfers all risk. What should EHS recommend?",
    options: [
      "Continue shipments because complete paperwork proves proper final disposition",
      "Ignore off-site practices because ownership always ends at pickup",
      "Pause or restrict shipments as warranted, preserve evidence, investigate through qualified due diligence and downstream traceability, engage legal/compliance expertise, and arrange verified alternatives",
      "Delete the complaints because they are not internal records",
    ],
    correctIndex: 2,
    rationale: "Documents and contracts do not prove physical disposition or erase legal, environmental, continuity, and reputation exposure. Credible contrary evidence requires preservation, escalation, traceability, and verified corrective decisions.",
    wrongRationales: [
      "Manifests support traceability but can be inaccurate or incomplete and do not override credible field evidence.",
      "Contract allocation does not automatically eliminate the generator's duties or nonfinancial exposure.",
      "Correct. It treats the evidence, lifecycle, expertise, and continuity needs as one risk decision.",
      "Deleting potentially relevant evidence undermines investigation, records integrity, and governance.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Environmental due diligence and downstream risk",
    challengePrompt: "Build a four-part contractor assurance scorecard that tests actual disposition rather than document presence alone.",
  },

  {
    id: "A8-001",
    domainId: "A8",
    competency: "Learning objectives",
    objective: "Recognize an observable, criterion-based training objective.",
    difficulty: 1,
    stem: "Which learning objective is most measurable?",
    options: [
      "Understand emergency exits",
      "Appreciate evacuation safety",
      "Given a site map, identify the two assigned evacuation routes and assembly area with no errors",
      "Know more about alarms",
    ],
    correctIndex: 2,
    rationale: "The objective specifies conditions, observable performance, and a success criterion. Those elements support aligned instruction and assessment.",
    wrongRationales: [
      "'Understand' is not directly observable and lacks a criterion.",
      "Appreciation may be desirable but is not defined as assessable task performance.",
      "Correct. The conditions, behavior, and criterion are explicit.",
      "The statement is vague about both content and acceptable performance.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Measurable learning objectives",
    challengePrompt: "Add a realistic retention interval to the objective without changing the required behavior.",
  },
  {
    id: "A8-002",
    domainId: "A8",
    competency: "Learning methods",
    objective: "Select practice and feedback appropriate to a procedural skill.",
    difficulty: 2,
    stem: "Employees must learn to inspect and don a new harness correctly. Which primary method provides the strongest evidence of initial skill?",
    options: [
      "A lecture with no equipment present",
      "A poster displayed near the storeroom",
      "Instructor demonstration followed by each learner's hands-on performance with feedback against a checklist",
      "An attendance signature alone",
    ],
    correctIndex: 2,
    rationale: "A procedural skill requires modeling, realistic practice, observation, and corrective feedback. A performance checklist supplies evidence aligned to the actual task.",
    wrongRationales: [
      "Lecture may introduce concepts but cannot demonstrate each learner's physical performance.",
      "A poster can cue recall but does not establish fitting and inspection skill.",
      "Correct. Demonstration, practice, feedback, and observed performance match the learning target.",
      "Attendance establishes presence, not competence.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Demonstration, practice, and feedback",
    challengePrompt: "Name one critical error that should require immediate stop and retraining during the assessment.",
  },
  {
    id: "A8-003",
    domainId: "A8",
    competency: "Training effectiveness",
    objective: "Measure transfer to workplace behavior rather than reaction alone.",
    difficulty: 3,
    stem: "Participants rate a pre-job-brief course highly and pass its quiz. Management wants to know whether brief quality improved on the job. What evidence is strongest?",
    options: [
      "The number of presentation slides",
      "Instructor confidence in the course",
      "Repeated structured observations of real briefs over time, supported by coaching and relevant work outcomes",
      "End-of-class satisfaction scores alone",
    ],
    correctIndex: 2,
    rationale: "Reaction and knowledge measures do not establish transfer. Reliable observations of the target behavior in context, repeated over time and triangulated with related evidence, directly evaluate workplace performance.",
    wrongRationales: [
      "Slide count is an instructional input, not a measure of learner behavior.",
      "Instructor confidence does not establish what learners do at work.",
      "Correct. It measures the intended behavior in context and checks persistence.",
      "Satisfaction can improve delivery but cannot establish transfer.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Training transfer and evaluation",
    challengePrompt: "Define three observable rubric elements that two independent observers could score consistently.",
  },
  {
    id: "A8-004",
    domainId: "A8",
    competency: "Needs and gap analysis",
    objective: "Distinguish a capability gap from an environmental barrier to performance.",
    difficulty: 4,
    stem: "Night-shift employees correctly describe and demonstrate atmospheric testing during assessment, yet field audits show tests are skipped because the only calibrated instrument is locked in the day-shift office. What should the needs analysis conclude first?",
    options: [
      "Assign a longer refresher course to all employees",
      "Treat instrument access and work-system design as the primary gap, then verify performance after correcting them",
      "Lower the testing standard to match available resources",
      "Assume the employees lack motivation and begin discipline",
    ],
    correctIndex: 1,
    rationale: "The employees have demonstrated the required knowledge and skill. The immediate barrier is opportunity and resources, which training cannot supply; correction should target access and then confirm field execution.",
    wrongRationales: [
      "More instruction does not make the calibrated instrument accessible.",
      "Correct. The diagnosed cause is environmental rather than a demonstrated capability deficit.",
      "Weakening a necessary control conceals the resource failure and accepts risk.",
      "The evidence identifies a concrete system barrier and does not support a motivation diagnosis.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Training need versus performance barrier",
    challengePrompt: "Apply a knowledge-skill-motivation-environment diagnostic to one additional safety-performance example.",
  },
  {
    id: "A8-005",
    domainId: "A8",
    competency: "Adaptive learning assurance",
    objective: "Govern adaptive question selection and competence decisions using validity evidence.",
    difficulty: 5,
    stem: "An adaptive course serves easier items after errors and declares competence once self-reported confidence reaches 80%. Its items are not mapped to job objectives, and rationales are generated without expert review. What is the best response?",
    options: [
      "Accept the result because adaptivity automatically creates a valid assessment",
      "Use confidence alone because it is more current than performance",
      "Require objective mapping, expert content review, calibrated item data, coverage rules, confidence-versus-accuracy checks, privacy controls, and independent job-performance verification",
      "Replace the course with attendance-only lectures",
    ],
    correctIndex: 2,
    rationale: "Adaptive sequencing does not guarantee accurate content, representative coverage, calibrated difficulty, or criterion validity. Confidence can be miscalibrated, so competence needs mapped and reviewed items plus authentic performance evidence.",
    wrongRationales: [
      "Adaptivity changes sequencing; it does not establish validity, fairness, accuracy, or coverage.",
      "Confidence can be high when knowledge is shallow and must be tested against performance.",
      "Correct. These controls address content, measurement, coverage, privacy, calibration, and real-world transfer.",
      "Attendance-only delivery also fails to establish competence and discards useful adaptive practice.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Adaptive training and assessment validity",
    challengePrompt: "Write one difficulty-escalation rule and one rule that detects confident guessing across multiple items.",
  },

  {
    id: "A9-001",
    domainId: "A9",
    competency: "Worker privacy",
    objective: "Apply minimum-necessary access to sensitive occupational records.",
    difficulty: 1,
    stem: "A supervisor asks for an employee's complete medical file to decide whether the employee can perform one task. What is the best general response?",
    options: [
      "Provide the complete file because supervisors manage work",
      "Share only authorized, minimum-necessary work-status information through the applicable privacy and occupational-health process",
      "Post the file where the whole team can review it",
      "Delete the medical file immediately",
    ],
    correctIndex: 1,
    rationale: "Work decisions usually require defined restrictions or fitness status, not unrestricted clinical detail. Access and disclosure should follow authorization, privacy, retention, and professional processes.",
    wrongRationales: [
      "Supervisory responsibility does not create unlimited access to sensitive medical information.",
      "Correct. It supports the work decision while limiting disclosure to authorized need.",
      "Broad posting violates confidentiality and is not necessary for task assignment.",
      "Deletion may violate retention duties and destroys information without addressing the legitimate work-status question.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Privacy and minimum-necessary disclosure",
    challengePrompt: "Distinguish a functional restriction from a diagnosis and explain which one the supervisor normally needs.",
  },
  {
    id: "A9-002",
    domainId: "A9",
    competency: "Risk transfer",
    objective: "Recognize the residual risks that remain after insurance or indemnification.",
    difficulty: 2,
    stem: "A company insures a hazardous delivery operation and includes indemnification in the carrier contract. Which statement is most accurate?",
    options: [
      "The physical probability of a crash is now zero",
      "Some financial consequences may be transferred, while operational, legal, continuity, and reputation risks may remain",
      "The carrier alone may decide what risk the company accepts",
      "Insurance eliminates the need to qualify and monitor the carrier",
    ],
    correctIndex: 1,
    rationale: "Insurance and contracts can allocate specified financial consequences, but they do not physically prevent incidents or necessarily transfer every duty and secondary consequence.",
    wrongRationales: [
      "Financial arrangements do not control vehicles, routes, packaging, or driver behavior.",
      "Correct. Transfer is partial and must be paired with prevention and oversight.",
      "The organization retains its own governance and acceptance responsibilities.",
      "Carrier selection and oversight are operational controls even when loss financing exists.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Insurance, indemnity, and residual risk",
    challengePrompt: "Name three carrier-qualification criteria that reduce event likelihood rather than merely finance loss.",
  },
  {
    id: "A9-003",
    domainId: "A9",
    competency: "Multi-employer worksites",
    objective: "Coordinate hazards created by simultaneous contractor activities.",
    difficulty: 3,
    stem: "One contractor performs hot work above another contractor opening a solvent line. Each contractor's standalone task analysis appears adequate. What critical step is still needed?",
    options: [
      "Nothing, because separate employers create separate hazards",
      "Only compare the contractors' historical injury rates",
      "Conduct a coordinated interface review covering sequence, permits, boundaries, communication, authority, and stop-work triggers",
      "Ask each contractor to buy more insurance",
    ],
    correctIndex: 2,
    rationale: "Separate analyses can miss hazards caused by coactivity. A coordinated interface review addresses the combined ignition-release scenario and defines control across employer boundaries.",
    wrongRationales: [
      "Hazards cross contractual and employer boundaries when work occurs in the same physical system.",
      "Historical rates do not control the immediate interaction between ignition and solvent release.",
      "Correct. It evaluates and controls the combined scenario neither standalone analysis captures.",
      "Insurance funds some consequences but does not prevent vapor ignition.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Contractor interface and simultaneous operations",
    challengePrompt: "Write one observable stop-work trigger that either contractor can invoke without waiting for management approval.",
  },
  {
    id: "A9-004",
    domainId: "A9",
    competency: "Chain of custody",
    objective: "Preserve sample identity and integrity through documented control.",
    difficulty: 4,
    stem: "A sample may become evidence in litigation. The laboratory receives an unsealed container with a mismatched identifier and no transfer signatures. What should the safety professional do?",
    options: [
      "Relabel it from memory and proceed without comment",
      "Discard the discrepancy so the report remains clean",
      "Document the condition and discrepancy, preserve the sample, notify the appropriate parties, and determine through the defined process whether resampling or qualified analysis is defensible",
      "Assume the laboratory caused the mismatch and alter the field log",
    ],
    correctIndex: 2,
    rationale: "Chain of custody requires traceable identity, transfers, seals, and condition. A gap should be preserved and transparently evaluated rather than repaired through undocumented assumptions.",
    wrongRationales: [
      "Memory-based relabeling creates unsupported evidence and hides the break.",
      "Suppressing a material discrepancy undermines record integrity and later interpretation.",
      "Correct. It preserves facts, prevents further compromise, and routes admissibility and resampling decisions appropriately.",
      "Altering contemporaneous records destroys their integrity and assigns blame without evidence.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Evidence records and chain of custody",
    challengePrompt: "List five fields a defensible chain-of-custody record should capture from collection through laboratory receipt.",
  },
  {
    id: "A9-005",
    domainId: "A9",
    competency: "Professional scope limitations",
    objective: "Escalate outside-scope legal and cybersecurity issues while preserving relevant evidence and immediate safety.",
    difficulty: 5,
    stem: "After a ransomware event, a safety instrumented system shows unexplained configuration changes. An executive asks the safety professional to certify that no legal reporting duty exists and to restore code personally, although the professional lacks legal and control-system cybersecurity expertise. What is the best response?",
    options: [
      "Provide both assurances because urgency expands professional competence",
      "Delete logs before restarting so the system runs faster",
      "Protect people and place the system in a known safe state, preserve evidence, state the scope limitation, and engage authorized legal, cybersecurity, and controls specialists through the incident process",
      "Ignore the change because no injury has yet occurred",
    ],
    correctIndex: 2,
    rationale: "Urgency does not create competence or authority. Immediate safety, evidence integrity, transparent scope limits, and qualified interdisciplinary escalation address both operational risk and potentially consequential legal decisions.",
    wrongRationales: [
      "A deadline does not qualify someone to give legal conclusions or modify specialized control software.",
      "Deleting logs can destroy critical forensic and legal evidence while doing nothing to establish a safe configuration.",
      "Correct. It acts within safety competence and promptly engages the expertise needed for the remaining decisions.",
      "Absence of injury is not evidence that the configuration is safe or that duties are absent.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Scope, cyber incidents, and expert escalation",
    challengePrompt: "Define the boundary between the safety professional's immediate authority and the decisions reserved for each specialist.",
  },
] as const satisfies readonly ASPQuestion[];
