/**
 * Original ASP practice content aligned structurally to the ASP11 blueprint.
 * These items do not reproduce examination or commercial study-bank wording.
 */

import type { ASPQuestion } from "./aspQuestionBankA";

export const ASP_QUESTION_BANK_B: readonly ASPQuestion[] = [
  {
    id: "A1-006",
    domainId: "A1",
    competency: "Applied geometry and unit conversion",
    objective: "Calculate containment capacity from dimensions and convert cubic feet to gallons.",
    difficulty: 1,
    stem: "A rectangular containment area is 20 ft long, 12 ft wide, and can hold liquid to a uniform depth of 0.50 ft. Using 7.48 gal/ft3, what is its theoretical capacity before displacement and freeboard are considered?",
    options: ["120 gal", "240 gal", "449 gal", "898 gal"],
    correctIndex: 3,
    rationale: "Volume is 20 x 12 x 0.50 = 120 ft3. Multiplying by 7.48 gal/ft3 gives 897.6 gal, which rounds to 898 gal.",
    wrongRationales: [
      "This is the volume in cubic feet, not the converted capacity in gallons.",
      "This result does not apply the stated cubic-foot-to-gallon conversion.",
      "This uses only half of the calculated 120 ft3 volume and is not supported by the dimensions.",
      "Correct. The geometric volume is 120 ft3, which converts to approximately 898 gal.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Geometry, volume, and dimensional analysis",
    challengePrompt: "Recalculate usable capacity if equipment displaces 70 ft3 and 10% of the remaining volume must be retained as freeboard.",
  },
  {
    id: "A1-007",
    domainId: "A1",
    competency: "Time-weighted calculations",
    objective: "Compute a full-shift time-weighted average from changing concentrations.",
    difficulty: 2,
    stem: "A worker is exposed to 40 ppm for 2 hours, 20 ppm for 4 hours, and 0 ppm for the final 2 hours of an 8-hour shift. What is the 8-hour time-weighted average concentration?",
    options: ["15 ppm", "20 ppm", "25 ppm", "30 ppm"],
    correctIndex: 1,
    rationale: "The concentration-time sum is (40 x 2) + (20 x 4) + (0 x 2) = 160 ppm-hours. Dividing by the full 8-hour averaging period gives 20 ppm.",
    wrongRationales: [
      "This understates the concentration-time sum; the zero-exposure period is included through the 8-hour denominator, not by averaging the three concentration values equally.",
      "Correct. The 160 ppm-hours divided by 8 hours equals 20 ppm.",
      "This exceeds the duration-weighted result; concentration values cannot be averaged without applying their time intervals.",
      "This does not account correctly for the four hours at 20 ppm and two hours at zero.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Time-weighted averages",
    challengePrompt: "Explain why dividing by only the six hours with nonzero exposure would answer a different question.",
  },
  {
    id: "A1-008",
    domainId: "A1",
    competency: "Probability and reliability",
    objective: "Calculate the union probability of independent events without double-counting overlap.",
    difficulty: 3,
    stem: "During a production run, independent initiating event A has probability 0.03 and independent initiating event B has probability 0.04. A shutdown occurs if either event occurs. What is the shutdown probability?",
    options: ["0.0012", "0.0688", "0.0700", "0.9988"],
    correctIndex: 1,
    rationale: "For an OR condition, P(A or B) = P(A) + P(B) - P(A)P(B). Thus 0.03 + 0.04 - (0.03 x 0.04) = 0.0688.",
    wrongRationales: [
      "This is the probability that both independent events occur, which represents an AND condition.",
      "Correct. Subtracting the 0.0012 overlap prevents counting simultaneous occurrence twice.",
      "Simple addition is only an approximation here because it double-counts the overlap.",
      "This is the complement of both events occurring and does not represent the stated OR condition.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Probability unions and fault-tree logic",
    challengePrompt: "State how the calculation changes if the two initiating events share a common cause and are not independent.",
  },
  {
    id: "A1-009",
    domainId: "A1",
    competency: "Vectors and trigonometry",
    objective: "Determine the magnitude and direction of a resultant force.",
    difficulty: 4,
    stem: "Two perpendicular cable forces act at a lifting point: 300 N east and 400 N north. What are the magnitude of the resultant and its direction measured north of east?",
    options: ["500 N at 53.1 degrees", "500 N at 36.9 degrees", "700 N at 53.1 degrees", "100 N at 45 degrees"],
    correctIndex: 0,
    rationale: "The magnitude is sqrt(300^2 + 400^2) = 500 N. The angle north of east is arctan(400/300) = approximately 53.1 degrees.",
    wrongRationales: [
      "Correct. The 3-4-5 relationship gives 500 N, and the larger north component produces a 53.1-degree angle from east.",
      "This angle would result from measuring east of north; it uses the complementary reference direction.",
      "Perpendicular vectors are combined by the Pythagorean relationship, not by adding their magnitudes directly.",
      "Subtracting components ignores that they act along perpendicular axes rather than opposite directions.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Force vectors and right-triangle trigonometry",
    challengePrompt: "Resolve a 650 N resultant at 25 degrees north of east into horizontal and vertical components.",
  },
  {
    id: "A1-010",
    domainId: "A1",
    competency: "Logarithmic calculations",
    objective: "Combine unequal sound levels on a logarithmic energy basis.",
    difficulty: 5,
    stem: "At one location, two independent machines produce sound levels of 92 dB and 89 dB. Using Ltotal = 10 log10(10^(L1/10) + 10^(L2/10)), what is the combined level, rounded to the nearest 0.1 dB?",
    options: ["92.0 dB", "93.8 dB", "95.0 dB", "181.0 dB"],
    correctIndex: 1,
    rationale: "Factoring out 10^(92/10) gives 92 + 10 log10(1 + 10^(-3/10)). Since 10^-0.3 is about 0.501, the increment is about 1.76 dB, yielding 93.8 dB.",
    wrongRationales: [
      "The second source adds acoustic energy, so the total must exceed 92 dB even though it cannot be added arithmetically.",
      "Correct. Logarithmic energy addition produces approximately 93.8 dB.",
      "A 3 dB increase would apply to two equal 92 dB sources; the second source here is 3 dB lower.",
      "Decibel values are logarithmic and must not be added as ordinary linear quantities.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Logarithms and sound-level addition",
    challengePrompt: "Estimate the new total if a third independent 92 dB machine is added, and explain why the increments are not constant.",
  },

  {
    id: "A2-006",
    domainId: "A2",
    competency: "Hierarchy of risk controls",
    objective: "Select the highest-order feasible control for a recurring hazard.",
    difficulty: 1,
    stem: "Employees manually clear sharp metal offcuts from beneath a press after every batch. Which proposal most directly eliminates the hand-contact hazard?",
    options: [
      "Issue thicker cut-resistant gloves",
      "Post a warning at the press",
      "Redesign the discharge so offcuts fall into a removable bin without hand clearing",
      "Retrain employees annually on careful handling",
    ],
    correctIndex: 2,
    rationale: "An engineered discharge removes the need for hands to enter the offcut area during routine work. It addresses the hazardous interaction at its source and is less dependent on repeated perfect behavior.",
    wrongRationales: [
      "Gloves may reduce injury severity but leave exposure to sharp material and may introduce dexterity limitations.",
      "A warning communicates risk but does not prevent contact during the required task.",
      "Correct. Redesigning the process removes the recurring manual contact from normal operation.",
      "Training supports a control system but cannot eliminate the exposure created by the process design.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Hierarchy of controls and prevention through design",
    challengePrompt: "Identify one new hazard the bin design could create and one design feature that would control it.",
  },
  {
    id: "A2-007",
    domainId: "A2",
    competency: "Performance measurement",
    objective: "Pair leading and lagging measures to evaluate a critical safety process.",
    difficulty: 2,
    stem: "A site is strengthening its hazardous-energy program. Which measure set gives the most useful balanced view of performance?",
    options: [
      "Number of locks purchased and number of posters displayed",
      "Percentage of sampled isolations verified effective, quality of corrective-action closure, and exposure-adjusted hazardous-energy events or credible near misses",
      "Training attendance and total facility payroll",
      "Days since the last injury as the sole measure",
    ],
    correctIndex: 1,
    rationale: "The selected set tests current control execution and corrective-action quality while also monitoring relevant outcomes. It is more diagnostic than counting inputs or relying on a statistically sparse lagging measure alone.",
    wrongRationales: [
      "Locks and posters are inputs; their counts do not show whether energy sources are identified and isolated correctly.",
      "Correct. These measures connect control performance, improvement work, and relevant outcomes.",
      "Attendance does not prove competence or field execution, and payroll is not a control-performance measure.",
      "A long injury-free period can coexist with serious uncontrolled exposure and provides little diagnostic direction.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Leading, lagging, and effectiveness indicators",
    challengePrompt: "Describe a sampling rule that prevents supervisors from selecting only the easiest isolations for verification.",
  },
  {
    id: "A2-008",
    domainId: "A2",
    competency: "Management of change",
    objective: "Recognize safety-relevant organizational and software changes.",
    difficulty: 3,
    stem: "A warehouse keeps the same equipment but replaces its inventory software and removes one night-shift coordinator. The new system automatically changes pick sequencing. What is the best safety-management response before launch?",
    options: [
      "Skip review because no physical equipment changed",
      "Review changed tasks, workload, traffic interactions, competencies, failure modes, procedures, and transition controls through a proportionate change process",
      "Wait for the first injury to identify the important effects",
      "Treat the change only as an information-technology issue",
    ],
    correctIndex: 1,
    rationale: "Software logic and staffing can change work pace, travel routes, decision authority, fatigue, and error recovery. A proportionate management-of-change review identifies these pathways and establishes readiness and post-launch monitoring.",
    wrongRationales: [
      "Safety-relevant change includes organizational, procedural, and software changes, not only new hardware.",
      "Correct. It evaluates how the combined changes alter exposure and safeguards before activation.",
      "Waiting for harm is reactive and forfeits the purpose of change control.",
      "Technical ownership by IT does not remove operational safety consequences.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Organizational and technology management of change",
    challengePrompt: "Name three leading indicators to monitor during the first month after launch.",
  },
  {
    id: "A2-009",
    domainId: "A2",
    competency: "Incident investigation and corrective action",
    objective: "Develop system-level causal conclusions from interacting evidence.",
    difficulty: 4,
    stem: "A mechanic opens the wrong line during a rushed restart. Two valves carry nearly identical labels, the electronic permit truncates equipment identifiers, a second-person check was informally suspended, and restart bonuses reward speed. Which conclusion best supports prevention?",
    options: [
      "The mechanic's inattention is the single root cause",
      "The event resulted from interacting identification, interface, verification, and incentive conditions that made the error likely and allowed it to pass unchecked",
      "The label vendor alone caused the event",
      "No conclusion is possible unless the mechanic admits negligence",
    ],
    correctIndex: 1,
    rationale: "A useful investigation explains both why the action was locally plausible and why safeguards failed. The evidence supports several latent conditions that should be corrected and verified rather than ending analysis at the worker's final act.",
    wrongRationales: [
      "Calling the final error a root cause does not explain the confusing conditions or missing verification.",
      "Correct. This conclusion preserves causal depth and points toward stronger, testable corrective actions.",
      "Label similarity contributed, but it does not account for display design, suspended checking, or production pressure.",
      "Physical, documentary, system, and interview evidence can support causal findings without an admission of fault.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Systems-based incident investigation",
    challengePrompt: "Propose one forcing-function correction and an effectiveness measure that could reveal whether it actually works.",
  },
  {
    id: "A2-010",
    domainId: "A2",
    competency: "Program evaluation and decision quality",
    objective: "Evaluate apparent improvement without confusing reporting and exposure changes with risk reduction.",
    difficulty: 5,
    stem: "A division reports a 35% lower injury count after a safety campaign. During the same period, labor hours fell 25%, contractor work replaced several high-risk employee tasks, near-miss reporting declined sharply, and audit sampling shifted to low-risk offices. What should the ASP conclude?",
    options: [
      "The campaign caused a 35% risk reduction",
      "The program failed because near-miss counts declined",
      "Causation is not established; normalize for exposure, include contractor outcomes, assess reporting climate and audit comparability, and examine critical-control performance before judging effectiveness",
      "Raw injury counts are sufficient because they are objective",
    ],
    correctIndex: 2,
    rationale: "The apparent change is entangled with reduced exposure, transferred work, possible reporting suppression, and biased sampling. A defensible evaluation reconstructs comparable denominators and populations and triangulates outcomes with valid control-performance evidence.",
    wrongRationales: [
      "The raw decrease cannot isolate the campaign effect from major changes in hours, work allocation, reporting, and sampling.",
      "Lower near-miss reporting may reflect fewer events or weaker reporting trust; the count alone cannot distinguish them.",
      "Correct. This approach addresses plausible alternative explanations before attributing improvement.",
      "Counts may be accurately recorded yet still be misleading when exposure and surveillance change.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Program evaluation, normalization, and bias",
    challengePrompt: "Design a four-measure dashboard that could distinguish true risk reduction from transferred or hidden risk.",
  },

  {
    id: "A3-006",
    domainId: "A3",
    competency: "Workstation design",
    objective: "Apply neutral-posture principles to an adjustable workstation.",
    difficulty: 1,
    stem: "An assembler repeatedly works with raised shoulders because the bench is too high. Which change most directly improves the primary ergonomic mismatch?",
    options: [
      "Tell the assembler to relax more often",
      "Provide an adjustable work surface or platform that permits neutral shoulder and elbow posture",
      "Increase the production target so the exposure ends sooner",
      "Require thicker gloves",
    ],
    correctIndex: 1,
    rationale: "Adjusting the worker-workstation relationship reduces the sustained shoulder elevation at its source. The change should be fitted to the worker and task and verified during actual production.",
    wrongRationales: [
      "Relaxation reminders do not resolve a workstation dimension that forces the posture.",
      "Correct. Adjustability accommodates worker variation and allows a more neutral working posture.",
      "A higher pace can increase repetition and muscle loading rather than control them.",
      "Gloves do not correct bench height and may add grip-force or dexterity demands.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Neutral posture and workstation adjustability",
    challengePrompt: "List two task observations that would confirm the adjustment improved exposure rather than merely moving it elsewhere.",
  },
  {
    id: "A3-007",
    domainId: "A3",
    competency: "Anthropometry and design",
    objective: "Choose appropriate population percentiles for clearance and reach design.",
    difficulty: 2,
    stem: "A team is setting an overhead clearance and locating a frequently used control. Which general anthropometric approach is most appropriate?",
    options: [
      "Use a small-person percentile for clearance and a large-person percentile for reach",
      "Use a large-person percentile for clearance and a small-person percentile for reach, then verify adjustability and the actual user population",
      "Use the population average for both because averages accommodate most people",
      "Use the designer's own body dimensions for both",
    ],
    correctIndex: 1,
    rationale: "Clearance must generally accommodate larger users, while reachable placement must accommodate smaller users. Real designs also consider clothing, posture, mobility, task frequency, and the intended population rather than blindly applying one percentile.",
    wrongRationales: [
      "This reverses the protective design logic and could exclude both larger and smaller users.",
      "Correct. The percentile directions match the distinct clearance and reach constraints.",
      "Designing to the mean can disadvantage substantial portions of the population at both tails.",
      "One individual's dimensions are not a valid representation of the user population.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Anthropometric accommodation",
    challengePrompt: "Explain when adjustable design is preferable to designing for fixed percentile limits.",
  },
  {
    id: "A3-008",
    domainId: "A3",
    competency: "Manual material handling",
    objective: "Calculate and interpret a lifting index from a stated recommended weight limit.",
    difficulty: 3,
    stem: "A task assessment yields a recommended weight limit of 32 lb under the observed conditions. The actual two-handed load is 48 lb. Using LI = load/recommended weight limit, what is the lifting index and best interpretation?",
    options: [
      "0.67; the load is necessarily safe for every worker",
      "1.00; no redesign is needed",
      "1.50; the task deserves closer evaluation and redesign because demand exceeds the modeled recommended limit",
      "16.0; immediately diagnose a specific injury",
    ],
    correctIndex: 2,
    rationale: "LI = 48/32 = 1.50. A value above 1 indicates demand beyond the modeled recommended limit and supports prioritizing task improvement, but the index does not predict a specific person's injury.",
    wrongRationales: [
      "This reverses the ratio, and even a low index would not guarantee safety for every individual.",
      "The actual load and recommended limit are not equal.",
      "Correct. The calculation is 1.50 and should trigger risk-reduction analysis within the model's assumptions.",
      "This result does not follow the stated ratio, and an index is not a medical diagnosis.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Lifting index interpretation",
    challengePrompt: "Name two task changes that could increase the recommended weight limit without simply asking the worker to try harder.",
  },
  {
    id: "A3-009",
    domainId: "A3",
    competency: "Cognitive ergonomics and human-machine interfaces",
    objective: "Redesign alarms to support detection, diagnosis, and response under stress.",
    difficulty: 4,
    stem: "A control room produces dozens of identical audible alarms during process upsets. Operators silence the panel while trying to determine which condition matters first. What is the strongest redesign?",
    options: [
      "Make every alarm louder",
      "Add more alarms for completeness",
      "Rationalize alarms by consequence and required action, suppress predictable cascades, use distinguishable priorities, display diagnostic context, and validate the design in realistic scenarios",
      "Discipline any operator who uses the silence function",
    ],
    correctIndex: 2,
    rationale: "Alarm systems should direct limited attention to actionable priorities. Rationalization, cascade management, meaningful differentiation, context, and scenario validation reduce overload while preserving critical cues.",
    wrongRationales: [
      "Greater loudness does not resolve ambiguity and can worsen stress and communication.",
      "More undifferentiated signals increase attentional competition and nuisance-alarm behavior.",
      "Correct. It redesigns information around human decision needs and tests performance under credible workload.",
      "Punishment does not repair an interface that overwhelms operators and may discourage reporting of design problems.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Alarm management and cognitive workload",
    challengePrompt: "Define one performance measure for alarm detection and one for correct diagnosis during validation.",
  },
  {
    id: "A3-010",
    domainId: "A3",
    competency: "Biomechanics",
    objective: "Compare low-back moments for two load-handling configurations.",
    difficulty: 5,
    stem: "For a simplified comparison, ignore upper-body weight and calculate external low-back moment as load force times horizontal distance. A 180 N load is initially held 0.45 m from the low back. A lift table reduces the distance to 0.20 m but adds a 30 N tool held at 0.35 m. How much does the total external moment decrease?",
    options: ["10.5 N-m", "34.5 N-m", "45.0 N-m", "81.0 N-m"],
    correctIndex: 1,
    rationale: "Initial moment = 180 x 0.45 = 81 N-m. Redesigned moment = (180 x 0.20) + (30 x 0.35) = 36 + 10.5 = 46.5 N-m. The decrease is 81 - 46.5 = 34.5 N-m.",
    wrongRationales: [
      "This is only the added tool's moment and does not compare total before-and-after loading.",
      "Correct. Including both redesigned load moments yields a 34.5 N-m reduction.",
      "This subtracts the primary-load moments but omits the added tool's 10.5 N-m contribution.",
      "This is the entire initial moment, not the amount of reduction after redesign.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Moment arms and biomechanical loading",
    challengePrompt: "Explain why this external-moment comparison is useful but insufficient for predicting individual injury risk.",
  },

  {
    id: "A4-006",
    domainId: "A4",
    competency: "Fire fundamentals",
    objective: "Identify the additional element represented by the fire tetrahedron.",
    difficulty: 1,
    stem: "The fire tetrahedron expands the traditional fire triangle by adding which element?",
    options: ["Pressure", "A sustaining chemical chain reaction", "Smoke", "An ignition permit"],
    correctIndex: 1,
    rationale: "The tetrahedron consists of fuel, oxygen, heat, and a sustaining chemical chain reaction. Suppression can act by removing or interrupting one or more of these elements.",
    wrongRationales: [
      "Pressure may influence some fire scenarios but is not the fourth tetrahedron element.",
      "Correct. The chain reaction distinguishes the tetrahedron from the triangle model.",
      "Smoke is a product of combustion, not a required tetrahedron element.",
      "A permit is an administrative prevention control and is not part of the combustion model.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Combustion fundamentals and the fire tetrahedron",
    challengePrompt: "Give one suppression method that primarily affects each of the four tetrahedron elements.",
  },
  {
    id: "A4-007",
    domainId: "A4",
    competency: "Portable fire extinguishing",
    objective: "Select an extinguishing approach that accounts for energized equipment and the underlying fuel.",
    difficulty: 2,
    stem: "A small fire involves insulation on an energized electric motor. What is the best initial extinguisher-selection principle?",
    options: [
      "Use water immediately because all motor fires are ordinary combustibles",
      "Select an agent suitable for energized electrical equipment, de-energize safely if possible, and then address the remaining fuel class",
      "Use any extinguisher as long as it is the nearest one",
      "Apply cooking-oil extinguishing agent because the motor contains lubricants",
    ],
    correctIndex: 1,
    rationale: "While equipment remains energized, the agent must not create an unacceptable electrical-conduction hazard. Safe de-energization changes the electrical condition, after which the burning material determines continued extinguishing needs.",
    wrongRationales: [
      "Water may create an electrical hazard while the equipment is energized; the electrical condition cannot be ignored.",
      "Correct. It accounts for both energy status and the actual combustible material.",
      "Proximity does not establish agent compatibility, adequate rating, or user safety.",
      "A specialized cooking-media agent is not selected merely because machinery may contain lubricant.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Fire classes and extinguisher selection",
    challengePrompt: "Explain why de-energizing equipment changes the classification decision but does not necessarily extinguish the fire.",
  },
  {
    id: "A4-008",
    domainId: "A4",
    competency: "Water-based fire protection",
    objective: "Calculate total fire-water demand from density-area and hose-stream components.",
    difficulty: 3,
    stem: "A design basis calls for sprinkler discharge density of 0.20 gpm/ft2 over a 1,500 ft2 remote area plus a 250 gpm hose-stream allowance. Ignoring other adjustments, what total flow must the supply support?",
    options: ["300 gpm", "450 gpm", "550 gpm", "1,750 gpm"],
    correctIndex: 2,
    rationale: "Sprinkler demand is 0.20 x 1,500 = 300 gpm. Adding the 250 gpm hose allowance produces a total demand of 550 gpm.",
    wrongRationales: [
      "This is only the calculated sprinkler demand and omits the hose-stream allowance.",
      "This adds only 150 gpm rather than the stated 250 gpm allowance.",
      "Correct. The two simultaneous demand components total 550 gpm.",
      "This adds area directly to flow, which is dimensionally invalid.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Sprinkler density-area demand",
    challengePrompt: "Calculate required usable storage if this demand must be sustained for 75 minutes and a separate 50 gpm process draw continues.",
  },
  {
    id: "A4-009",
    domainId: "A4",
    competency: "Fire-water supply",
    objective: "Evaluate usable tank volume against a sustained design demand.",
    difficulty: 4,
    stem: "A fire-water system must supply 550 gpm for 60 minutes. A tank contains 38,000 gal, but 2,000 gal lies below the reliable suction level. Ignoring refill, what is the result?",
    options: [
      "It is deficient by 2,000 gal",
      "It exactly meets demand",
      "It has 3,000 gal of usable margin",
      "It has 5,000 gal of usable margin",
    ],
    correctIndex: 2,
    rationale: "Required volume is 550 x 60 = 33,000 gal. Usable tank volume is 38,000 - 2,000 = 36,000 gal, leaving a 3,000 gal margin.",
    wrongRationales: [
      "This compares the unusable heel directly with demand rather than calculating total usable supply.",
      "Usable volume exceeds the 33,000 gal requirement.",
      "Correct. Thirty-six thousand usable gallons minus 33,000 required gallons leaves 3,000 gal.",
      "This uses the gross tank volume and ignores the 2,000 gal below reliable suction.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Fire-water duration and usable storage",
    challengePrompt: "Identify three real system factors, beyond nominal tank volume, that must be verified before declaring the supply adequate.",
  },
  {
    id: "A4-010",
    domainId: "A4",
    competency: "Fire-protection impairment management",
    objective: "Control risk during loss of an automatic suppression system.",
    difficulty: 5,
    stem: "A forklift damages a sprinkler main serving a high-piled storage area. Repairs will take most of the shift, and operations asks to continue receiving goods because smoke detection remains active. What is the strongest response?",
    options: [
      "Continue normally because detection is equivalent to suppression",
      "Close the sprinkler valve, keep the impairment informal, and rely on employees to notice smoke",
      "Activate the impairment process: define affected protection, notify responsible parties, control ignition and fuel-loading activities, establish suitable temporary protection and fire watch, restrict or stop operations that cannot be acceptably controlled, expedite repair, and verify restoration",
      "Evacuate and permanently abandon the entire building regardless of scope",
    ],
    correctIndex: 2,
    rationale: "An impairment removes a critical layer and requires deliberate risk control, communication, compensatory measures, operational restrictions, rapid restoration, and documented return to service. Detection alerts occupants but does not control fire growth.",
    wrongRationales: [
      "Detection and suppression perform different functions; warning alone may not prevent rapid fire development.",
      "An undocumented valve closure and informal observation create additional failure paths and weak accountability.",
      "Correct. This is a risk-based impairment response that scales operations to the protection actually available.",
      "Full permanent abandonment is not automatically required; the response should be proportionate to the assessed impairment and controllability.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Fire-protection impairments and compensatory controls",
    challengePrompt: "State two objective restoration checks required before the impairment can be closed.",
  },

  {
    id: "A5-006",
    domainId: "A5",
    competency: "Emergency planning",
    objective: "Identify the foundation for scenario-based emergency planning.",
    difficulty: 1,
    stem: "What should primarily determine which emergencies a facility plans and drills for?",
    options: [
      "Only events experienced in the previous year",
      "A credible hazard and vulnerability assessment covering people, operations, neighbors, infrastructure, and available capabilities",
      "The easiest scenarios for employees to practice",
      "A generic plan copied from an unrelated facility",
    ],
    correctIndex: 1,
    rationale: "Emergency planning begins with credible hazards, exposed populations and assets, vulnerabilities, consequences, dependencies, and response capabilities. Historical experience informs the assessment but does not define its entire scope.",
    wrongRationales: [
      "Rare or emerging credible events may not appear in one year of local history.",
      "Correct. The assessment connects planning priorities to site-specific risk and capability gaps.",
      "Ease of practice does not establish scenario importance.",
      "A generic plan may omit local hazards, roles, resources, and external interfaces.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Hazard vulnerability analysis",
    challengePrompt: "Name one low-frequency, high-consequence scenario that might deserve inclusion despite no local history.",
  },
  {
    id: "A5-007",
    domainId: "A5",
    competency: "Incident organization and command",
    objective: "Establish scalable command and accountability during an evolving incident.",
    difficulty: 2,
    stem: "During a warehouse fire, operations, security, and maintenance issue conflicting directions over separate radio channels. What should be corrected first?",
    options: [
      "Allow each department to retain independent command",
      "Establish a clearly identified incident command structure, shared objectives, role assignments, communication plan, and resource/accountability process",
      "Stop documenting decisions until the emergency ends",
      "Ask the most senior remote executive to approve every tactical action",
    ],
    correctIndex: 1,
    rationale: "A scalable command structure aligns objectives, authority, information, resources, and accountability. It reduces conflicting directions while preserving appropriate tactical decision-making close to the incident.",
    wrongRationales: [
      "Independent command can create incompatible tactics and expose responders to unrecognized actions.",
      "Correct. Unified organization and communications address the coordination failure directly.",
      "Contemporaneous logs support resource tracking, handoffs, learning, and later recovery.",
      "Centralizing every tactical choice with a remote executive can delay urgent decisions and bypass qualified incident roles.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Incident command and unified coordination",
    challengePrompt: "Describe how command should transfer at a shift change without losing situational awareness.",
  },
  {
    id: "A5-008",
    domainId: "A5",
    competency: "Protective-action decision making",
    objective: "Choose protective actions based on the evolving hazard rather than a fixed default.",
    difficulty: 3,
    stem: "A toxic release occurs outside a building. The plume is moving across the main evacuation route, the building can temporarily isolate outdoor air, and responders expect better plume information within minutes. What is the best immediate approach?",
    options: [
      "Evacuate everyone through the plume because evacuation is always safest",
      "Use a preplanned, monitored shelter-in-place action while evaluating plume direction, building protection, duration, and a safe route; transition if conditions require",
      "Take no action until the chemical identity is perfectly confirmed",
      "Let each occupant independently choose a route",
    ],
    correctIndex: 1,
    rationale: "Protective action is hazard- and time-dependent. When evacuation would cross the plume and temporary building protection is viable, monitored sheltering may reduce immediate exposure while information and safe routes are evaluated.",
    wrongRationales: [
      "Evacuation can increase exposure when routes cross the hazard; it is not universally preferable.",
      "Correct. The action is provisional, monitored, and linked to explicit transition criteria.",
      "Waiting for perfect information can squander the window for meaningful protection.",
      "Uncoordinated movement undermines accountability and may direct people into higher exposure.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Evacuation and shelter-in-place decisions",
    challengePrompt: "List four trigger conditions that would cause incident command to reconsider sheltering.",
  },
  {
    id: "A5-009",
    domainId: "A5",
    competency: "Business continuity and recovery",
    objective: "Distinguish recovery time and recovery point requirements.",
    difficulty: 4,
    stem: "An order-entry system has a recovery time objective (RTO) of 4 hours and a recovery point objective (RPO) of 15 minutes. Testing restores the application in 3 hours, but backups occur only once per hour. What does the test show?",
    options: [
      "Both objectives are met",
      "The RTO is met, but the backup design may lose up to about an hour of data and therefore does not meet the 15-minute RPO",
      "The RPO is met, but the RTO fails",
      "Neither objective can ever be tested",
    ],
    correctIndex: 1,
    rationale: "Restoring service within 3 hours meets the 4-hour RTO. Hourly recovery points can leave much more than 15 minutes of lost transactions, so backup or replication frequency must improve to meet the RPO.",
    wrongRationales: [
      "Application restoration met its target, but data-loss tolerance did not.",
      "Correct. RTO concerns downtime; RPO concerns how far data may roll back.",
      "This reverses the two results.",
      "Both objectives can be exercised using timed restoration and validated recovery-point data.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Recovery time and recovery point objectives",
    challengePrompt: "Design a test that validates not only restoration time but also data integrity and dependent-service readiness.",
  },
  {
    id: "A5-010",
    domainId: "A5",
    competency: "Exercise evaluation and continuous improvement",
    objective: "Judge emergency readiness using critical failures rather than average drill results.",
    difficulty: 5,
    stem: "A drill meets its average evacuation-time target. However, a visitor is never accounted for, an accessible exit route is blocked, the notification system misses one noisy area, and controllers prompt responders through two key decisions. Leaders want to mark the drill successful. What should the ASP recommend?",
    options: [
      "Pass the drill because the average time met target",
      "Fail every participant personally",
      "Treat the critical gaps and controller assistance as evidence that independent capability was not demonstrated; assign causal corrective actions, verify interim controls, and repeat targeted and integrated exercises",
      "Delete the outlying results before reporting",
    ],
    correctIndex: 2,
    rationale: "An average can hide failures affecting life safety, equitable egress, warning reach, and accountability. Prompted performance also overstates independent readiness. Improvement should address causes and demonstrate corrected performance under credible conditions.",
    wrongRationales: [
      "Meeting one aggregate target cannot outweigh unaccounted people, inaccessible egress, and notification failure.",
      "The purpose is capability improvement; indiscriminate blame does not diagnose system and plan weaknesses.",
      "Correct. It preserves the validity of the exercise and requires evidence that the critical capabilities now work.",
      "Removing adverse evidence corrupts evaluation and prevents risk reduction.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Emergency exercise design and after-action improvement",
    challengePrompt: "Define pass-fail criteria for accountability that cannot be masked by a favorable average evacuation time.",
  },

  {
    id: "A6-006",
    domainId: "A6",
    competency: "Exposure recognition and control",
    objective: "Control airborne contaminant generation at its source.",
    difficulty: 1,
    stem: "A dry powder transfer releases a visible dust cloud at the bag-dumping point. Which proposal is the strongest primary control?",
    options: [
      "Rotate workers through the task",
      "Install effective source enclosure and local exhaust at the dumping interface",
      "Require workers to stand farther away when convenient",
      "Post the chemical name near the hopper",
    ],
    correctIndex: 1,
    rationale: "Enclosure and source capture prevent contaminant migration into the breathing zone and workroom. Administrative measures and communication may supplement but do not provide equivalent source control.",
    wrongRationales: [
      "Rotation redistributes dose among workers and leaves the emission uncontrolled.",
      "Correct. It acts at the point of generation before the contaminant disperses.",
      "Unspecified distance is unreliable and may interfere with task execution without controlling the plume.",
      "A label communicates identity but does not reduce airborne concentration.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Industrial hygiene hierarchy and source capture",
    challengePrompt: "Name two field observations or measurements that would verify capture performance after installation.",
  },
  {
    id: "A6-007",
    domainId: "A6",
    competency: "Exposure assessment strategy",
    objective: "Design representative sampling for variable exposure groups.",
    difficulty: 2,
    stem: "A facility wants one personal sample from its lowest-exposure office worker to represent all employees who mix solvents across three shifts. What should the ASP recommend?",
    options: [
      "Accept it because any employee sample represents the facility",
      "Define similar exposure groups, identify variable and worst-credible tasks and shifts, collect task and full-shift personal data as appropriate, and document uncertainty",
      "Use an outdoor area sample only",
      "Skip sampling and rely solely on odor complaints",
    ],
    correctIndex: 1,
    rationale: "Representative assessment follows tasks, agents, controls, duration, and exposure variability. Similar exposure groups and risk-informed sampling provide defensible inference; an unrelated low-exposure worker does not.",
    wrongRationales: [
      "Physical employment at the same facility does not make exposure profiles equivalent.",
      "Correct. The strategy maps sampling to actual exposure determinants and uncertainty.",
      "Outdoor background data cannot substitute for personal breathing-zone assessment of solvent mixing.",
      "Odor is agent- and person-dependent and is not a quantitative exposure assessment.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Similar exposure groups and sampling plans",
    challengePrompt: "Explain how you would select workers for sampling without always choosing the same apparently worst-exposed individual.",
  },
  {
    id: "A6-008",
    domainId: "A6",
    competency: "Noise exposure calculations",
    objective: "Calculate cumulative noise dose using stated allowable durations.",
    difficulty: 3,
    stem: "Use dose fraction = actual duration/allowable duration for each level. A worker spends 2 hours where 8 hours is allowable, 3 hours where 4 hours is allowable, and 1 hour where 2 hours is allowable. What is the total dose?",
    options: ["50%", "100%", "150%", "175%"],
    correctIndex: 2,
    rationale: "The fractions are 2/8 = 0.25, 3/4 = 0.75, and 1/2 = 0.50. Their sum is 1.50, or 150% of the stated allowable daily dose.",
    wrongRationales: [
      "This includes only the final segment's fraction.",
      "This omits one-half of the cumulative fractional exposure.",
      "Correct. Dose fractions add to 1.50, which is 150%.",
      "This arithmetic overstates the sum of the three stated fractions.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Cumulative noise dose",
    challengePrompt: "Identify the source-control data needed before choosing hearing protection as the primary response.",
  },
  {
    id: "A6-009",
    domainId: "A6",
    competency: "Industrial ventilation",
    objective: "Calculate airflow and room air-change rate while recognizing their limits for source capture.",
    difficulty: 4,
    stem: "A hood has a 4 ft2 opening with average face velocity of 100 ft/min. It exhausts from a 10,000 ft3 room. Assuming equal makeup air and steady flow, what are the nominal exhaust flow and room air changes per hour (ACH)?",
    options: ["25 cfm and 0.15 ACH", "400 cfm and 2.4 ACH", "2,500 cfm and 4 ACH", "40,000 cfm and 240 ACH"],
    correctIndex: 1,
    rationale: "Flow Q = velocity x area = 100 x 4 = 400 cfm. ACH = 400 cfm x 60 min/hr / 10,000 ft3 = 2.4 per hour. Neither value alone proves effective contaminant capture at the source.",
    wrongRationales: [
      "This divides where multiplication is required for hood flow and does not follow the ACH relationship.",
      "Correct. The calculations give 400 cfm and 2.4 ACH, subject to the stated ideal assumptions.",
      "These values do not follow from the opening area, velocity, and room volume.",
      "This treats room volume as though it were flow and inflates both results.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Ventilation flow and air changes",
    challengePrompt: "Explain why acceptable room ACH can coexist with poor hood capture in a worker's breathing zone.",
  },
  {
    id: "A6-010",
    domainId: "A6",
    competency: "Occupational epidemiology",
    objective: "Calculate relative risk and attributable fraction without claiming causation from one comparison.",
    difficulty: 5,
    stem: "In a cohort, 36 of 600 exposed workers develop an outcome, compared with 12 of 800 unexposed workers. What are the relative risk (RR) and attributable fraction among the exposed, using AF = (RR - 1)/RR?",
    options: [
      "RR 0.25 and AF -300%",
      "RR 2.0 and AF 50%",
      "RR 4.0 and AF 75%",
      "RR 6.0 and AF 83%",
    ],
    correctIndex: 2,
    rationale: "Exposed risk is 36/600 = 0.06; unexposed risk is 12/800 = 0.015. RR = 0.06/0.015 = 4.0. AF = (4 - 1)/4 = 0.75, or 75%, assuming the association is causal.",
    wrongRationales: [
      "This reverses the risk ratio, and the resulting fraction is not the requested exposed attributable fraction.",
      "The exposed risk is four, not two, times the unexposed risk.",
      "Correct. RR is 4.0 and the corresponding attributable fraction is 75%, conditional on causality.",
      "The exposed incidence is 6%, but 6 is not the relative risk; the denominator risk must be included.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Relative risk and attributable fraction",
    challengePrompt: "Name two biases or confounders that could change the causal interpretation even though the arithmetic is correct.",
  },

  {
    id: "A7-006",
    domainId: "A7",
    competency: "Pollution prevention",
    objective: "Prioritize source reduction over downstream waste handling.",
    difficulty: 1,
    stem: "A coating process generates excess hazardous overspray. Which option is the strongest pollution-prevention measure?",
    options: [
      "Ship more overspray waste off site for treatment",
      "Improve transfer efficiency and process control so less coating becomes overspray",
      "Store the waste in larger containers",
      "Dilute the waste before disposal",
    ],
    correctIndex: 1,
    rationale: "Improving transfer efficiency prevents waste and associated exposure at the source while conserving material. Treatment and storage manage waste after generation, and dilution does not reduce pollutant mass.",
    wrongRationales: [
      "Off-site treatment may manage generated waste but does not prevent its creation.",
      "Correct. The process change reduces raw-material loss and pollutant generation together.",
      "Larger containers change storage logistics, not the mass of waste generated.",
      "Dilution lowers concentration while leaving pollutant mass essentially unchanged and may enlarge the waste stream.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Pollution-prevention hierarchy",
    challengePrompt: "Name one metric that captures environmental improvement and one that captures production benefit from the transfer-efficiency change.",
  },
  {
    id: "A7-007",
    domainId: "A7",
    competency: "Hazardous-material and waste management",
    objective: "Use characterization and compatibility information before consolidating wastes.",
    difficulty: 2,
    stem: "Two partially filled waste drums have similar color and odor, so a supervisor proposes combining them to save space. Labels are incomplete. What should happen first?",
    options: [
      "Combine a small amount as an informal compatibility test",
      "Characterize the contents through process knowledge and appropriate analysis, restore identification, assess compatibility, and keep them segregated until the decision is supported",
      "Open both drums and compare odor more closely",
      "Add water to both drums before mixing",
    ],
    correctIndex: 1,
    rationale: "Appearance and odor do not establish identity or compatibility. Controlled characterization, traceable identification, and segregation prevent reactions, exposures, and an even more difficult unknown waste mixture.",
    wrongRationales: [
      "An uncontrolled field mixture can itself cause a violent reaction or release.",
      "Correct. It establishes evidence before making a consolidation decision.",
      "Direct odor assessment can expose the worker and is not reliable chemical identification.",
      "Water can be incompatible with unknown materials and increases waste volume without resolving identity.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Waste characterization and chemical compatibility",
    challengePrompt: "Describe how process knowledge and analytical testing complement rather than replace each other.",
  },
  {
    id: "A7-008",
    domainId: "A7",
    competency: "Environmental mass balance",
    objective: "Calculate an unmeasured output using a defined process boundary.",
    difficulty: 3,
    stem: "Over one month, a process receives 12,000 kg of fresh material, ships 10,800 kg in product, and increases material inventory inside the defined boundary by 400 kg. Assuming no other inputs, what mass left the boundary as waste or release?",
    options: ["400 kg", "800 kg", "1,200 kg", "1,600 kg"],
    correctIndex: 1,
    rationale: "Input equals product output plus accumulation plus waste/release. Thus waste/release = 12,000 - 10,800 - 400 = 800 kg.",
    wrongRationales: [
      "This is the inventory accumulation, which remains inside the boundary rather than leaving it.",
      "Correct. The residual after product and accumulation is 800 kg.",
      "This ignores the 400 kg inventory increase and treats all non-product material as an output.",
      "This adds accumulation to the output residual instead of subtracting it from available input.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Material balances and environmental releases",
    challengePrompt: "Explain how measurement uncertainty in input, product, and inventory could dominate the calculated residual.",
  },
  {
    id: "A7-009",
    domainId: "A7",
    competency: "Life-cycle and sustainability analysis",
    objective: "Avoid burden shifting when evaluating a material substitution.",
    difficulty: 4,
    stem: "A proposed cleaner lowers on-site volatile emissions by 70%, but requires twice the energy in use, contains a persistent aquatic toxicant, and has a shorter service life. What is the best evaluation approach?",
    options: [
      "Approve it based only on the on-site emission reduction",
      "Reject every substitution that increases any single impact",
      "Compare alternatives for an equivalent functional service across sourcing, worker exposure, use, energy, releases, durability, and end-of-life impacts, then control material risks and uncertainty",
      "Count purchase price as the only sustainability measure",
    ],
    correctIndex: 2,
    rationale: "A functional, life-cycle comparison reveals whether an improvement in one category shifts harm to other stages or receptors. The decision should make tradeoffs and uncertainty explicit rather than relying on one local metric.",
    wrongRationales: [
      "A single favorable site metric can hide increased energy, toxicity, replacement frequency, or upstream burden.",
      "Most alternatives involve tradeoffs; automatic rejection prevents reasoned comparison of material significance.",
      "Correct. It uses comparable service and a broad boundary to identify and manage burden shifting.",
      "Price omits environmental, health, resource, and performance consequences.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Life-cycle thinking and burden shifting",
    challengePrompt: "Define a functional unit that would make the current cleaner and proposed substitute meaningfully comparable.",
  },
  {
    id: "A7-010",
    domainId: "A7",
    competency: "Wastewater loading calculations",
    objective: "Calculate contaminant mass loading and removal efficiency.",
    difficulty: 5,
    stem: "Use load (lb/day) = concentration (mg/L) x flow (MGD) x 8.34. A treatment system receives 2.0 MGD at 250 mg/L and discharges at 25 mg/L. Assuming flow is unchanged through treatment, what are the approximate influent load and percent removal?",
    options: [
      "417 lb/day and 10%",
      "4,170 lb/day and 90%",
      "8,340 lb/day and 50%",
      "41,700 lb/day and 99%",
    ],
    correctIndex: 1,
    rationale: "Influent load = 250 x 2.0 x 8.34 = 4,170 lb/day. With unchanged flow, removal = (250 - 25)/250 x 100 = 90%.",
    wrongRationales: [
      "This is one-tenth of the influent load and reverses the meaning of the concentration reduction.",
      "Correct. The stated conversion gives 4,170 lb/day and the concentration falls by 90%.",
      "This doubles the calculated influent load and does not reflect the influent-to-effluent ratio.",
      "This adds a factor of ten to load and overstates removal; 25 mg/L is 10% of 250 mg/L, not 1%.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Wastewater mass loading and treatment efficiency",
    challengePrompt: "Explain why a 90% removal result may still be environmentally inadequate when receiving-flow conditions or toxicity change.",
  },

  {
    id: "A8-006",
    domainId: "A8",
    competency: "Learning objectives",
    objective: "Recognize an observable, criterion-based learning objective.",
    difficulty: 1,
    stem: "Which statement is the strongest learning objective for energy-control training?",
    options: [
      "Understand hazardous energy",
      "Appreciate the importance of lockout",
      "Given a training machine and procedure, identify, isolate, dissipate, and verify every energy source with no missed source",
      "Know how to work safely",
    ],
    correctIndex: 2,
    rationale: "The selected objective states conditions, observable actions, and a performance criterion. It can guide realistic practice and a valid performance assessment.",
    wrongRationales: [
      "Understand is not directly observable and supplies neither conditions nor a success criterion.",
      "Appreciation may support motivation but is too vague to demonstrate task competence.",
      "Correct. The behavior and acceptable result are explicit.",
      "This is broad, unobservable, and not anchored to a defined task.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Performance-based learning objectives",
    challengePrompt: "Add a retention criterion that tests whether the skill persists after training.",
  },
  {
    id: "A8-007",
    domainId: "A8",
    competency: "Adult learning and instructional methods",
    objective: "Select active, job-relevant instruction for experienced adult learners.",
    difficulty: 2,
    stem: "Experienced maintenance employees must learn a revised permit process. Which instructional design is strongest?",
    options: [
      "Read every policy paragraph aloud without practice",
      "Connect the change to familiar jobs, let learners analyze realistic permits, practice decisions, receive feedback, and explain how their experience applies or no longer applies",
      "Give only a vocabulary list",
      "Avoid questions so the instructor can finish faster",
    ],
    correctIndex: 1,
    rationale: "Adult learning is strengthened by relevance, use of prior experience, active problem solving, realistic practice, and feedback. The design also surfaces where old habits conflict with the revised process.",
    wrongRationales: [
      "Passive reading may communicate content but gives weak evidence that learners can apply the changed process.",
      "Correct. It respects experience while building and testing changed job performance.",
      "Terminology recall alone does not establish permit decisions or execution.",
      "Suppressing questions removes feedback about misconceptions and weakens learner engagement.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Adult learning and active practice",
    challengePrompt: "Design one scenario that exposes a plausible old habit and requires the revised decision.",
  },
  {
    id: "A8-008",
    domainId: "A8",
    competency: "Training effectiveness",
    objective: "Measure transfer of learning to workplace behavior.",
    difficulty: 3,
    stem: "Supervisors give a course high satisfaction ratings and score well on its quiz. Leaders need to know whether pre-job briefs have actually improved. Which evidence is strongest?",
    options: [
      "The number of slides presented",
      "Course satisfaction alone",
      "Repeated structured observations of brief quality in the field, supported by coaching records and relevant work outcomes",
      "The instructor's years of service",
    ],
    correctIndex: 2,
    rationale: "Reaction and knowledge results do not prove workplace transfer. Reliable observation of the target behavior over time directly tests whether supervisors use the skill and whether performance persists.",
    wrongRationales: [
      "Slide count is an instructional input and has no necessary relationship to behavior change.",
      "Satisfaction helps assess learner reaction but cannot establish job performance.",
      "Correct. It measures the intended behavior where it must occur and triangulates the finding.",
      "Instructor experience does not demonstrate learner transfer.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Learning transfer and evaluation levels",
    challengePrompt: "Write three observable rubric criteria that two independent observers could score consistently.",
  },
  {
    id: "A8-009",
    domainId: "A8",
    competency: "Risk communication",
    objective: "Communicate urgent risk accessibly across language and literacy differences.",
    difficulty: 4,
    stem: "A multilingual temporary workforce must act on a new chemical-release alarm. Some workers have limited reading proficiency. What is the best communication plan?",
    options: [
      "Email a technical safety data sheet in one language",
      "Use a distinctive tested alarm plus concise translated and pictorial instructions, demonstrations and practice, teach-back, accessible reporting routes, and checks across shifts",
      "Ask bilingual workers to improvise translations during an emergency",
      "Require signatures as the sole evidence of understanding",
    ],
    correctIndex: 1,
    rationale: "Accessible, redundant communication must support recognition and action under stress. Translation, visuals, demonstration, practice, teach-back, and field verification address both comprehension and operational reliability.",
    wrongRationales: [
      "A technical document in one language is neither accessible to all workers nor sufficient for rapid alarm response.",
      "Correct. It combines accessible content with practice and evidence of comprehension.",
      "Improvised emergency translation is slow, inconsistent, and unfairly transfers a critical organizational duty.",
      "A signature documents acknowledgment, not understanding or ability to act.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Accessible and multilingual risk communication",
    challengePrompt: "Define a teach-back prompt that tests action without merely asking whether workers understand.",
  },
  {
    id: "A8-010",
    domainId: "A8",
    competency: "Assessment validity and adaptive learning",
    objective: "Govern adaptive testing using blueprint coverage, calibrated items, and independent competence evidence.",
    difficulty: 5,
    stem: "An adaptive training system declares users competent after three correct answers, but its items are unmapped to objectives, several questions cue the answer through wording, and high-confidence guesses receive the largest score increase. What should the ASP require before relying on its result?",
    options: [
      "Accept the result because adaptive software is automatically objective",
      "Increase the number of easy questions without changing the scoring rule",
      "Map items to competencies, conduct expert and bias review, analyze item difficulty and discrimination, calibrate stopping rules with adequate domain coverage, detect confidence miscalibration, and verify transfer through authentic performance",
      "Use learner confidence as the sole passing criterion",
    ],
    correctIndex: 2,
    rationale: "Adaptivity changes item selection; it does not create validity. Competence claims require representative content, sound items, defensible calibration and stopping, fair operation, and evidence that scores relate to real performance.",
    wrongRationales: [
      "Software can implement invalid content or scoring consistently; automation is not proof of objectivity or validity.",
      "More weak or easy items do not repair construct undercoverage, cueing, or flawed scoring.",
      "Correct. These controls address content validity, measurement quality, calibration, fairness, and job transfer.",
      "Confidence can be inaccurate and should be analyzed alongside, not substituted for, demonstrated competence.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Adaptive assessment, item analysis, and validity",
    challengePrompt: "Write a stopping rule that prevents mastery in one narrow topic from masking untested weakness elsewhere in the domain.",
  },

  {
    id: "A9-006",
    domainId: "A9",
    competency: "Legal and consensus requirements",
    objective: "Distinguish mandatory legal requirements from voluntary standards and internal rules.",
    difficulty: 1,
    stem: "Which statement most accurately describes how a consensus standard should be treated?",
    options: [
      "It is always legally binding in every jurisdiction",
      "It is never relevant to legal duties",
      "Its legal effect depends on adoption, incorporation, contracts, and circumstances; even when not mandatory, it may inform recognized practice and risk-control decisions",
      "It automatically overrides applicable statutes and regulations",
    ],
    correctIndex: 2,
    rationale: "Consensus standards do not have one universal legal status. They may be adopted or incorporated, required by contract, or used as evidence of recognized practice, while applicable law retains its governing role.",
    wrongRationales: [
      "A standard's binding effect varies with adoption, jurisdiction, and contractual context.",
      "Nonmandatory guidance may still inform feasibility, recognized practice, contracts, and professional judgment.",
      "Correct. It avoids both treating every standard as law and dismissing its legal and technical relevance.",
      "Private standards do not categorically displace governing law.",
    ],
    referenceFramework: "Nito",
    referenceTopic: "Sources of legal and professional obligations",
    challengePrompt: "Give three ways a nominally voluntary standard can become consequential to an employer.",
  },
  {
    id: "A9-007",
    domainId: "A9",
    competency: "Civil liability concepts",
    objective: "Recognize the basic elements generally evaluated in a negligence claim.",
    difficulty: 2,
    stem: "Which set lists the core concepts generally examined when alleging negligence?",
    options: [
      "Duty, breach, causation, and damages",
      "Intent, criminal sentence, and incarceration",
      "Policy, training hours, and insurance premium",
      "Hazard count, audit score, and seniority",
    ],
    correctIndex: 0,
    rationale: "Negligence analysis generally examines whether a duty existed, whether conduct breached the applicable standard, whether the breach caused the harm, and whether legally recognized damages resulted.",
    wrongRationales: [
      "Correct. These are the commonly evaluated negligence elements, though application varies by jurisdiction and facts.",
      "Negligence is generally distinct from proving criminal intent and punishment.",
      "These facts may be evidence in a case but are not the core analytical elements.",
      "These management data do not replace duty, breach, causal connection, and harm.",
    ],
    referenceFramework: "ASP/CSP Exam Book",
    referenceTopic: "Negligence and liability fundamentals",
    challengePrompt: "Explain why proving a breached rule without causal connection to the injury may be insufficient for this theory.",
  },
  {
    id: "A9-008",
    domainId: "A9",
    competency: "Records and legal preservation",
    objective: "Preserve relevant information when a dispute or investigation is reasonably anticipated.",
    difficulty: 3,
    stem: "After a serious incident, a routine system is scheduled to delete old inspection messages overnight. A claim is reasonably anticipated. What is the best immediate records action?",
    options: [
      "Let routine deletion continue so no one changes normal practice",
      "Issue and document an appropriately scoped preservation hold with counsel or authorized leadership, suspend conflicting deletion, protect relevant physical and electronic evidence, and track custodians and collection",
      "Delete duplicate unfavorable messages first",
      "Tell employees to save whatever they personally think is important without coordination",
    ],
    correctIndex: 1,
    rationale: "Once preservation is required, routine disposition that could destroy relevant information must be suspended in a controlled, scoped, and traceable way. Coordinated preservation protects authenticity and completeness without indiscriminately freezing everything.",
    wrongRationales: [
      "Routine deletion does not excuse loss of information that should now be preserved.",
      "Correct. It establishes controlled preservation and defensible evidence handling.",
      "Selective destruction is unethical and can seriously compromise legal and factual review.",
      "Uncoordinated personal judgment leads to gaps, duplication, privacy problems, and weak chain of custody.",
    ],
    referenceFramework: "Yates",
    referenceTopic: "Legal holds and evidence preservation",
    challengePrompt: "Distinguish a preservation copy from an ordinary working copy and explain why metadata can matter.",
  },
  {
    id: "A9-009",
    domainId: "A9",
    competency: "Contractor legal-risk management",
    objective: "Manage contractor risk without assuming contractual allocation eliminates operational duties.",
    difficulty: 4,
    stem: "A contract states that a contractor is solely responsible for safety. The host controls site access, process isolations, and simultaneous operations, and knows the contractor's plan conflicts with an active process. What is the most defensible host response?",
    options: [
      "Ignore the conflict because the contract transfers every possible duty",
      "Coordinate the shared hazards and controls, communicate process information, verify required interfaces and competence, stop work if necessary, and document actions while preserving appropriate contractor supervision boundaries",
      "Direct every detail of the contractor's craft work regardless of expertise",
      "Wait for an incident and then cite the contract",
    ],
    correctIndex: 1,
    rationale: "Contract language does not erase hazards within the host's knowledge or control. The host should manage interfaces and retained controls without unnecessarily taking over specialized means and methods, with legal duties evaluated for the actual jurisdiction and facts.",
    wrongRationales: [
      "A private allocation does not automatically eliminate duties arising from control, knowledge, coordination, or applicable law.",
      "Correct. It addresses shared risk while maintaining deliberate boundaries of operational responsibility.",
      "Unnecessary micromanagement can blur responsibilities and exceed the host's competence without resolving the core interface risk.",
      "Known incompatible work should be addressed before harm rather than reserved as a post-incident defense.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Contractor coordination, control, and due diligence",
    challengePrompt: "Identify two facts that would help determine whether the host retained control over the hazardous activity.",
  },
  {
    id: "A9-010",
    domainId: "A9",
    competency: "Professional ethics and reporting",
    objective: "Respond ethically to pressure to suppress material risk information.",
    difficulty: 5,
    stem: "An executive directs the ASP to remove validated exposure results from a board report because disclosure could delay an acquisition. The executive suggests reporting only the facility average, which hides a highly exposed group. What is the strongest response?",
    options: [
      "Comply because executives own all technical conclusions",
      "Leak every employee record publicly, including personal identifiers",
      "Explain the material distortion, preserve accurate analysis and records, report through authorized governance and ethics channels, protect confidential personal information, seek qualified legal guidance where appropriate, and escalate if the misleading report is not corrected",
      "Replace the results with an unsupported estimate closer to the average",
    ],
    correctIndex: 2,
    rationale: "Professional integrity requires accurate, nonmisleading communication of material risk while maintaining confidentiality and using authorized escalation. Neither obedience nor uncontrolled disclosure resolves the competing duties responsibly.",
    wrongRationales: [
      "Management authority does not justify a materially misleading professional report.",
      "Public release of identifiable records can violate privacy, harm workers, and bypass appropriate reporting processes.",
      "Correct. It protects truthfulness, evidence, confidentiality, due process, and necessary escalation.",
      "Inventing a favorable estimate compounds the ethical breach and destroys analytical integrity.",
    ],
    referenceFramework: "BCSP Blueprint",
    referenceTopic: "Ethical reporting, confidentiality, and escalation",
    challengePrompt: "Draft a concise written objection that distinguishes confidential detail from material risk information decision-makers need.",
  },
];
