/**
 * Source-backed authored practice for course chapters 14-26.
 *
 * Drawn from W. David Yates, Safety Professional's Reference and Study Guide,
 * 4th ed., chapters 14-26. Each item is independently authored rather than
 * transformed from a homework stem.
 */
export type AuthoredPracticeQuestion = {
  readonly level: "foundation" | "homework-level" | "application";
  readonly stem: string;
  readonly options: readonly [string, string, string, string];
  readonly correctIndex: 0 | 1 | 2 | 3;
  readonly explanation: string;
};

export const AUTHORED_PRACTICE_14_TO_26 = {
  "ch-14": [
    {
      level: "foundation",
      stem: "Before choosing eye, hand, or foot protection for a new maintenance task, what should the safety professional do first?",
      options: [
        "Issue the most protective equipment available to every worker.",
        "Ask employees which PPE brand they prefer.",
        "Wait for the first injury to identify the needed equipment.",
        "Complete a job hazard assessment to identify the task-specific hazards.",
      ],
      correctIndex: 3,
      explanation: "PPE selection begins with a thorough job hazard assessment. It identifies the hazards the equipment must address; selection is not based on preference or on a prior injury.",
    },
    {
      level: "homework-level",
      stem: "A worker could face incidental contact with an electrical source up to 13.8 kV. Which hard-hat classification from the chapter provides the greatest electrical protection?",
      options: [
        "Class C, because conductive helmets dissipate electrical energy.",
        "Class G, because it is rated to 2,200 V.",
        "Any class, because hard-hat classifications concern impact only.",
        "Class E, because it is rated to 20,000 V.",
      ],
      correctIndex: 3,
      explanation: "The chapter distinguishes Class E (20,000 V), Class G (2,200 V), and Class C (conductive and not intended for protection from electrical conductors).",
    },
    {
      level: "application",
      stem: "A team proposes gloves as the only response to recurring solvent splash at a filling station. Which concern best explains why this is incomplete control planning?",
      options: [
        "Gloves always eliminate the hazardous substance.",
        "Solvent work never requires a hazard assessment once gloves are issued.",
        "PPE should be selected before the task and exposure are understood.",
        "PPE leaves the source hazard in place and depends on correct fit, use, and maintenance.",
      ],
      correctIndex: 3,
      explanation: "PPE can be necessary, but it does not remove the source hazard. The chapter's hazard-assessment approach supports considering task and exposure controls before relying solely on PPE.",
    },
    {
      level: "foundation",
      stem: "During a PPE inventory review, which pairing of protection category and OSHA general-industry citation is correct?",
      options: [
        "Eye and face protection — 29 CFR 1910.133",
        "Head protection — 29 CFR 1910.133",
        "Foot protection — 29 CFR 1910.134",
        "Respiratory protection — 29 CFR 1910.136",
      ],
      correctIndex: 0,
      explanation: "The chapter identifies 29 CFR 1910.133 for eye and face protection. The cited sections for head, respiratory, and foot protection are 1910.135, 1910.134, and 1910.136, respectively.",
    },
    {
      level: "homework-level",
      stem: "A supervisor is matching PPE to a task with flying particles and a separate task with a foot-crush hazard. Which selection is most defensible?",
      options: [
        "Use a respirator for flying particles and a hard hat for foot hazards.",
        "Use eye/face protection for flying particles and protective footwear for the foot hazard.",
        "Use hearing protection for both tasks because it is required whenever PPE is used.",
        "Use one glove selection for both tasks without evaluating the different hazards.",
      ],
      correctIndex: 1,
      explanation: "PPE must address the hazard found in the assessment. The chapter separately identifies eye and face protection and foot and leg protection; one category is not a substitute for another.",
    },
  ],

  "ch-15": [
    {
      level: "foundation",
      stem: "A department records 3, 5, 8, and 12 near misses in four consecutive months. What is the arithmetic mean?",
      options: ["6", "8", "28", "7"],
      correctIndex: 3,
      explanation: "Add the observations (28) and divide by four months. The mean, also called the arithmetic average, is 7.",
    },
    {
      level: "homework-level",
      stem: "Two independent components must both operate for a ventilation alarm to function. Their reliabilities are 0.96 and 0.90. What is the series-system reliability?",
      options: ["0.864", "0.940", "0.960", "0.996"],
      correctIndex: 0,
      explanation: "In a series system, failure of either component fails the system, so multiply the component reliabilities: 0.96 × 0.90 = 0.864.",
    },
    {
      level: "application",
      stem: "A report states that a result has p = 0.03. Which description best matches the chapter's definition of a p value?",
      options: [
        "The probability that the null hypothesis is certainly false.",
        "The percentage of data that must lie within one standard deviation.",
        "The probability of obtaining a result at least as extreme as observed if the null hypothesis is true.",
        "The reliability of the measurement instrument over its service life.",
      ],
      correctIndex: 2,
      explanation: "A p value is the probability of observing a result as extreme as the one obtained, assuming the null hypothesis is true.",
    },
    {
      level: "foundation",
      stem: "A standby alarm contains two independent units wired so that the alarm still functions if either one unit fails. What reliability arrangement is this?",
      options: [
        "A series system",
        "A parallel system",
        "A single-path system",
        "A failure-only system",
      ],
      correctIndex: 1,
      explanation: "In a parallel system, one component can fail and the system can still function. In a series system, failure of any component fails the system.",
    },
    {
      level: "homework-level",
      stem: "Two independent protective devices are arranged in parallel with reliabilities of 0.80 and 0.90. What is the reliability that at least one device functions?",
      options: ["0.72", "0.90", "0.98", "1.70"],
      correctIndex: 2,
      explanation: "For independent parallel components, Rsystem = 1 − (1 − R1)(1 − R2). Here, 1 − (0.20 × 0.10) = 0.98.",
    },
    {
      level: "homework-level",
      stem: "A system has a calculated reliability of 0.92 for its required mission. What is its probability of failure for that mission?",
      options: ["0.08", "0.92", "1.00", "1.92"],
      correctIndex: 0,
      explanation: "The chapter gives Pf = 1 − Ps. With probability of success or reliability of 0.92, the probability of failure is 0.08.",
    },
    {
      level: "application",
      stem: "An engineer can place two high-reliability switches in either a single required path or two redundant paths. Why can the redundant arrangement be preferable?",
      options: [
        "It makes the reliability of each individual switch equal to 1.00.",
        "One switch can fail without necessarily preventing the function.",
        "It eliminates the need to evaluate component failure probabilities.",
        "It turns every electrical connection into a series connection.",
      ],
      correctIndex: 1,
      explanation: "Arrangement matters as much as component reliability. A parallel arrangement can maintain system function when one independent component fails.",
    },
    {
      level: "application",
      stem: "Three independent components with reliabilities 0.99, 0.97, and 0.95 must all operate for a monitoring system to work. Which result is closest to the system reliability?",
      options: ["0.912", "0.950", "0.970", "2.910"],
      correctIndex: 0,
      explanation: "This is a series arrangement, so multiply the component reliabilities: 0.99 × 0.97 × 0.95 = 0.912285, or about 0.912.",
    },
  ],

  "ch-16": [
    {
      level: "foundation",
      stem: "A series circuit contains three components. Which statement about current is correct?",
      options: [
        "Current divides independently among the components.",
        "No current flows until a parallel branch is added.",
        "The same current flows through each component along the single path.",
        "Current is measured in volts at each component.",
      ],
      correctIndex: 2,
      explanation: "A series circuit has one path, so the same current passes through every component. Separate current paths characterize a parallel circuit.",
    },
    {
      level: "homework-level",
      stem: "What must an arc-flash risk assessment estimate in addition to identifying potential arc-flash hazards?",
      options: [
        "Only the equipment purchase price.",
        "Only the number of employees assigned to the area.",
        "The electrical utility's annual operating budget.",
        "The likelihood of injury or health damage and the severity of the potential consequence.",
      ],
      correctIndex: 3,
      explanation: "The source says the arc-flash assessment should identify the hazard and estimate both likelihood and severity so appropriate protective measures can be determined.",
    },
    {
      level: "application",
      stem: "A worker needs to enter the restricted approach boundary of exposed energized equipment. Which condition is required by the chapter's description?",
      options: [
        "The worker may enter if a coworker is nearby.",
        "The worker may enter without PPE if the task lasts less than one minute.",
        "The worker need only wear ordinary work gloves.",
        "The worker must be qualified, trained, use proper PPE, and have the required written permit.",
      ],
      correctIndex: 3,
      explanation: "The restricted approach boundary is closest to exposed live equipment. Entry requires a qualified worker with appropriate training and PPE, plus the written permit described in the chapter.",
    },
    {
      level: "foundation",
      stem: "Which electrical quantity is the flow of electric charge and is measured in amperes?",
      options: ["Voltage", "Resistance", "Current", "Power factor"],
      correctIndex: 2,
      explanation: "Current is the flow of electric charge and is measured in amperes (A). Voltage is measured in volts, and resistance is measured in ohms.",
    },
    {
      level: "foundation",
      stem: "A component is selected specifically to oppose the flow of steady electrical current by a known amount. What component is being described?",
      options: ["A capacitor", "A resistor", "An inductor", "A circuit breaker"],
      correctIndex: 1,
      explanation: "A resistor is designed to intentionally resist electrical current at a known measurement. Capacitors and inductors instead store energy in electrical and magnetic fields, respectively.",
    },
    {
      level: "homework-level",
      stem: "A technician adds a second branch to a circuit so two loads have separate current paths from the source. How is the circuit arranged?",
      options: [
        "In series, because the same current must flow through both loads",
        "In parallel, because current to each element is separate",
        "As an open circuit, because branching stops current",
        "As a purely resistive circuit, regardless of its paths",
      ],
      correctIndex: 1,
      explanation: "In a parallel circuit, the current to each element follows a separate path. A series circuit has one path and the same current through each component.",
    },
    {
      level: "homework-level",
      stem: "Which statement correctly distinguishes the energy-storage behavior of an inductor from that of a capacitor?",
      options: [
        "An inductor stores energy in a magnetic field; a capacitor stores energy in an electrical field.",
        "An inductor stores energy only as heat; a capacitor cannot store energy.",
        "A capacitor stores energy in a magnetic field; an inductor stores it in a chemical reaction.",
        "Both components are designed only to measure voltage.",
      ],
      correctIndex: 0,
      explanation: "The chapter describes inductors as storing energy in a magnetic field produced by current. A capacitor uses separated conductors and dielectric insulation to create an electrical field.",
    },
    {
      level: "application",
      stem: "During an energized-equipment review, a high-amperage current arcs through air and creates a violent pressure event. Which electrical hazard term best fits the event?",
      options: ["A normal voltage drop", "An arc blast", "A low-resistance ground", "A static circuit"],
      correctIndex: 1,
      explanation: "An arc blast occurs when powerful, high-amperage currents arc through the air. It is distinct from an ordinary voltage drop or a normal circuit condition.",
    },
  ],

  "ch-17": [
    {
      level: "foundation",
      stem: "A 6 kg tool cart accelerates at 3 m/s² on a level path. Ignoring friction, what net force is required?",
      options: ["2 N", "9 N", "18 N", "54 N"],
      correctIndex: 2,
      explanation: "Newton's second law is F = ma. Multiplying 6 kg by 3 m/s² gives 18 N.",
    },
    {
      level: "homework-level",
      stem: "A 4 kg suspended load moves at 5 m/s. What is its kinetic energy?",
      options: ["10 J", "25 J", "50 J", "100 J"],
      correctIndex: 2,
      explanation: "Kinetic energy is energy of motion. KE = 1/2 mv² = 1/2 × 4 × 5² = 50 J.",
    },
    {
      level: "application",
      stem: "A forklift travels 12 m/s due east. Which term captures both the rate of motion and its direction?",
      options: ["Speed", "Velocity", "Mass", "Potential energy"],
      correctIndex: 1,
      explanation: "Speed is scalar and tells how fast an object moves. Velocity is a vector, so it includes both rate of movement and direction.",
    },
    {
      level: "foundation",
      stem: "A loaded cart remains at rest until an employee applies an unbalanced push. Which Newton law is illustrated?",
      options: ["Newton's first law", "Newton's second law", "Newton's third law", "The law of gravitation only"],
      correctIndex: 0,
      explanation: "Newton's first law says a body maintains its state of rest or motion unless acted on by an external, unbalanced force.",
    },
    {
      level: "foundation",
      stem: "When a worker pushes a wall, the wall pushes back on the worker with an equal force in the opposite direction. Which principle explains this pair?",
      options: ["Conservation of mass", "Newton's first law", "Newton's third law", "Bernoulli's principle"],
      correctIndex: 2,
      explanation: "Newton's third law states that for every action there is an equal and opposite reaction.",
    },
    {
      level: "homework-level",
      stem: "Which statement best describes the difference between mass and weight when the same object is moved from Earth to a location with weaker gravity?",
      options: [
        "Its mass increases and its weight stays constant.",
        "Its mass stays constant while its weight changes with gravitational force.",
        "Both mass and weight become zero.",
        "Weight becomes a vector only when mass changes.",
      ],
      correctIndex: 1,
      explanation: "Mass is constant regardless of location. Weight varies because it depends on gravitational force.",
    },
    {
      level: "homework-level",
      stem: "A compressed spring is held in place before it is released. What kind of energy does it primarily possess while held?",
      options: ["Kinetic energy", "Potential energy", "Velocity", "Displacement"],
      correctIndex: 1,
      explanation: "Potential energy is stored energy. The spring gains kinetic energy only when it begins moving.",
    },
    {
      level: "application",
      stem: "A 12 kg machine part must accelerate at 2.5 m/s² during a controlled lift. Ignoring other forces, what net force is required?",
      options: ["4.8 N", "14.5 N", "30 N", "120 N"],
      correctIndex: 2,
      explanation: "Apply Newton's second law, F = ma. Multiplying 12 kg by 2.5 m/s² gives 30 N.",
    },
  ],

  "ch-18": [
    {
      level: "foundation",
      stem: "Which field studies fluids at rest?",
      options: ["Hydraulics", "Aerodynamics", "Thermodynamics", "Hydrostatics"],
      correctIndex: 3,
      explanation: "Hydrostatics is fluid statics: the study of fluids at rest. Hydraulics concerns fluids in motion.",
    },
    {
      level: "homework-level",
      stem: "A 300 lbf force acts uniformly on an area of 6 in². What pressure does it exert?",
      options: ["18 psi", "294 psi", "1,800 psi", "50 psi"],
      correctIndex: 3,
      explanation: "Pressure is force per unit area. Divide 300 lbf by 6 in² to obtain 50 psi.",
    },
    {
      level: "application",
      stem: "At two points along a horizontal, inviscid flow path, the fluid moves faster at Point B than at Point A. Under Bernoulli's principle, what change is expected at Point B?",
      options: [
        "Pressure increases because speed increases.",
        "Pressure must stay the same regardless of speed.",
        "Pressure decreases as speed increases.",
        "The fluid becomes static at the faster point.",
      ],
      correctIndex: 2,
      explanation: "For the inviscid-flow relationship stated in the chapter, an increase in fluid speed occurs with a decrease in pressure or potential energy.",
    },
    {
      level: "foundation",
      stem: "Approximately how much does 20 gal of water weigh, using the chapter's water-weight value?",
      options: ["20 lb", "62.4 lb", "166.8 lb", "1,248 lb"],
      correctIndex: 2,
      explanation: "Water weighs about 8.34 lb per gallon. Therefore, 20 gal weighs 20 × 8.34 = 166.8 lb.",
    },
    {
      level: "foundation",
      stem: "A flow has a Reynolds number of 1,500. How should it be classified using the chapter's ranges?",
      options: ["Laminar", "Transitional", "Turbulent", "Static"],
      correctIndex: 0,
      explanation: "The chapter identifies Reynolds numbers below 2,000 as laminar flow.",
    },
    {
      level: "homework-level",
      stem: "A process line has a Reynolds number of 3,100. Which flow regime should a safety professional identify?",
      options: ["Laminar", "Transitional", "Turbulent", "Hydrostatic"],
      correctIndex: 1,
      explanation: "The chapter identifies the range between 2,000 and 4,000 as transitional flow. Turbulent flow is above 4,000.",
    },
    {
      level: "homework-level",
      stem: "A tank has a small opening below the liquid surface. Which principle relates the speed of liquid leaving that opening to the height of liquid above it?",
      options: ["Torricelli's law", "Newton's third law", "Ohm's law", "Maslow's hierarchy"],
      correctIndex: 0,
      explanation: "Torricelli's law relates the speed of fluid flowing out of an opening to the height of the fluid above the opening.",
    },
    {
      level: "application",
      stem: "An engineer expresses a flowing liquid's velocity as the static pressure or head needed to produce that velocity. What quantity is being described?",
      options: ["Elevation head", "Velocity head", "Specific gravity", "Asymmetry angle"],
      correctIndex: 1,
      explanation: "Velocity head expresses velocity in terms of the head or static pressure required to produce that velocity.",
    },
  ],

  "ch-19": [
    {
      level: "foundation",
      stem: "Which design choice best respects a core adult-learning principle?",
      options: [
        "Connect instruction to realistic job goals and the learner's existing experience.",
        "Avoid allowing learners to ask questions.",
        "Use only abstract material with no workplace relevance.",
        "Treat all prior work experience as an obstacle to learning.",
      ],
      correctIndex: 0,
      explanation: "The chapter describes adult learners as self-directed, goal- and relevance-oriented, practical, experienced, and deserving of respect.",
    },
    {
      level: "homework-level",
      stem: "What is the first step in developing a safety training program according to the chapter?",
      options: [
        "Select a slide template.",
        "Conduct a training needs analysis.",
        "Administer a posttest.",
        "Choose the longest available course.",
      ],
      correctIndex: 1,
      explanation: "A training needs analysis is the first step. It establishes whether training is needed and what performance gap the program must address.",
    },
    {
      level: "application",
      stem: "A course's final assessment is intended to show whether participants can carry out its stated objectives. What type of assessment is it?",
      options: ["Pretest", "Review test", "Posttest", "Informal attendance record"],
      correctIndex: 2,
      explanation: "Pretests identify starting knowledge before instruction, review tests support longer courses, and posttests should determine whether participants can perform the learning objectives.",
    },
    {
      level: "foundation",
      stem: "Which option is one of the three basic training-delivery methods identified in the chapter?",
      options: [
        "Structured on-the-job training",
        "Randomized equipment purchasing",
        "Unsupervised policy enforcement",
        "Incident-only instruction",
      ],
      correctIndex: 0,
      explanation: "The chapter lists instructor-led training, self-paced learning, and structured on-the-job training as the three basic delivery methods.",
    },
    {
      level: "homework-level",
      stem: "Before a new confined-space course begins, an instructor gives a short knowledge check to identify participants' starting point. What is the purpose of this assessment?",
      options: [
        "To replace course evaluation",
        "To provide the starting point of learner knowledge before instruction",
        "To certify that participants can already perform every objective",
        "To measure final transfer to the job",
      ],
      correctIndex: 1,
      explanation: "Pretests are administered before course information is presented and are designed to establish learners' starting knowledge.",
    },
  ],

  "ch-20": [
    {
      level: "foundation",
      stem: "A safety project borrows $24,000 at simple interest of 5% per year for two years. What is the interest cost?",
      options: ["$1,200", "$2,400", "$12,000", "$26,400"],
      correctIndex: 1,
      explanation: "Use simple interest I = Pni: $24,000 × 2 × 0.05 = $2,400. This is interest only, not the total amount repaid.",
    },
    {
      level: "homework-level",
      stem: "An organization invests $10,000 at 4% annually for two years, compounded annually. Which future value is closest?",
      options: ["$10,400", "$10,800", "$10,816", "$11,600"],
      correctIndex: 2,
      explanation: "Use F = P(1 + i)^n: 10,000(1.04)^2 = $10,816. Compounding applies interest to the growing balance.",
    },
    {
      level: "application",
      stem: "Why should a safety professional not compare a dollar available today directly with the same nominal dollar available one year from now?",
      options: [
        "Money today has investment potential and must be adjusted for time value.",
        "All future expenditures are prohibited.",
        "Interest applies only to personal purchases, not safety projects.",
        "A dollar's purchasing power is permanently fixed.",
      ],
      correctIndex: 0,
      explanation: "The chapter's engineering-economics premise is that money generates money. Comparing present and future amounts requires accounting for investment potential or the cost of money.",
    },
    {
      level: "foundation",
      stem: "A safety improvement is financed with $15,000 at simple interest of 4% per year for three years. What interest accrues over the loan period?",
      options: ["$600", "$1,800", "$2,400", "$16,800"],
      correctIndex: 1,
      explanation: "For simple interest, I = P × n × i. The interest is $15,000 × 3 × 0.04 = $1,800.",
    },
    {
      level: "application",
      stem: "A project manager needs a simple display that shows inspection, procurement, installation, and verification activities against calendar time. Which tool best serves that purpose?",
      options: [
        "A Gantt chart",
        "A workers' compensation modifier",
        "A fault tree",
        "A safety data sheet",
      ],
      correctIndex: 0,
      explanation: "A Gantt chart displays planned project activities against a timeline. It helps safety professionals communicate schedule and sequencing for a project.",
    },
  ],

  "ch-21": [
    {
      level: "foundation",
      stem: "Which sequence correctly orders Maslow's needs from lower to higher in the chapter?",
      options: [
        "Safety, physiological, esteem, belonging, self-actualization",
        "Physiological, belonging, safety, self-actualization, esteem",
        "Physiological, safety, belonging, esteem, self-actualization",
        "Belonging, esteem, physiological, safety, self-actualization",
      ],
      correctIndex: 2,
      explanation: "The chapter lists physiological, safety, belonging, esteem, and self-actualization. Maslow's theory treats lower unsatisfied needs as motivators before higher-level needs.",
    },
    {
      level: "homework-level",
      stem: "A supervisor assumes employees dislike work and will respond only to money and close control. Which McGregor view does this reflect?",
      options: ["Theory X", "Theory Y", "Herzberg's motivation factors", "The Deming cycle"],
      correctIndex: 0,
      explanation: "Theory X assumes employees do not want to work and are motivated only by money. Theory Y takes the contrasting view that people can enjoy work and seek responsibility when needs are met.",
    },
    {
      level: "application",
      stem: "After checking whether a new safety process achieved its target, a management team revises the process and begins the next improvement cycle. Which Deming step is it performing?",
      options: ["Plan", "Do", "Check", "Act"],
      correctIndex: 3,
      explanation: "PDCA is Plan, Do, Check, Act. Revising or standardizing after evaluation is the Act step, which feeds continuous improvement.",
    },
    {
      level: "foundation",
      stem: "Which pair names the two categories in Herzberg's Motivation Theory?",
      options: [
        "Hygiene factors and motivation factors",
        "Fixed factors and random factors",
        "Physiological factors and electrical factors",
        "Hazard factors and exposure factors",
      ],
      correctIndex: 0,
      explanation: "The chapter says Herzberg classifies factors into hygiene factors and motivation factors.",
    },
    {
      level: "application",
      stem: "A manager announces a safety-process decision without seeking employee participation in making it. What leadership style is being demonstrated?",
      options: ["Permissive", "Autocratic", "Theory Y", "Democratic sampling"],
      correctIndex: 1,
      explanation: "Autocratic leaders make decisions unilaterally. The chapter contrasts this with permissive leaders, who permit participation in decision-making.",
    },
  ],

  "ch-22": [
    {
      level: "foundation",
      stem: "What is the primary purpose of an accident investigation?",
      options: [
        "Assign personal blame as quickly as possible.",
        "Prevent recurrence of the event.",
        "Determine the highest available insurance payment.",
        "Replace corrective action with a written report.",
      ],
      correctIndex: 1,
      explanation: "The chapter makes prevention of recurrence the primary purpose. Fact finding and analysis should support corrective action, not merely assign blame.",
    },
    {
      level: "homework-level",
      stem: "Which accident-causation theory portrays accidents in terms of energy and its transfer?",
      options: ["Systems Theory", "Behavior Theory", "Energy Release Theory", "Epidemiological Theory"],
      correctIndex: 2,
      explanation: "William Haddon developed the Energy Release Theory, which frames accidents in terms of energy and transference.",
    },
    {
      level: "application",
      stem: "A complex event has equipment, work-practice, and management contributors. The investigator intentionally uses useful parts of several causation models rather than forcing one model to explain everything. Which approach is being used?",
      options: [
        "The Combination Theory",
        "The Domino Theory only",
        "A pretest",
        "The hierarchy of needs",
      ],
      correctIndex: 0,
      explanation: "Combination Theory allows an investigator to use parts or all of available accident-causation theories to solve a problem.",
    },
    {
      level: "foundation",
      stem: "Which set names Heinrich's “Three E's” for accident prevention?",
      options: [
        "Engineering, Education, and Enforcement",
        "Exposure, Elimination, and Evaluation",
        "Economics, Ergonomics, and Emergency response",
        "Environment, Equipment, and Energy",
      ],
      correctIndex: 0,
      explanation: "The chapter identifies Heinrich's Three E's as Engineering, Education, and Enforcement.",
    },
    {
      level: "homework-level",
      stem: "An investigator explains an event as arising from workload beyond a worker's capacity, an unsuitable response, or an unsuitable activity. Which causation model is being applied?",
      options: [
        "The Human Factors Theory",
        "The Energy Release Theory",
        "The Epidemiological Theory",
        "The Domino Theory only",
      ],
      correctIndex: 0,
      explanation: "The Human Factors Theory attributes accidents to human error and groups it as overload, inappropriate worker response, or inappropriate activities.",
    },
    {
      level: "homework-level",
      stem: "A review finds that a worker made what appeared to be a logical choice under poorly designed conditions, and the analyst also identifies an ergonomic trap. Which theory adds those ideas to Human Factors Theory?",
      options: [
        "Petersen's Accident/Incident Theory",
        "Maslow's Hierarchy of Needs",
        "Bernoulli's principle",
        "The Deming cycle",
      ],
      correctIndex: 0,
      explanation: "Petersen's Accident/Incident Theory extends Human Factors Theory by adding ergonomic traps and recognizing that a decision to err may be based on logic.",
    },
    {
      level: "application",
      stem: "A safety professional is studying exposure and disease patterns rather than focusing chiefly on behavior or mechanical energy. Which accident-causation theory most directly fits that lens?",
      options: [
        "Epidemiological Theory",
        "Behavior Theory",
        "Energy Release Theory",
        "Domino Theory",
      ],
      correctIndex: 0,
      explanation: "The Epidemiological Theory focuses primarily on industrial-hygiene aspects, making it appropriate for analyzing exposure and disease patterns.",
    },
    {
      level: "application",
      stem: "In the modern causation model, which factor occurs earliest in the chain that leads to a mishap and results?",
      options: [
        "Safety management error",
        "Operating error",
        "Mishap",
        "Results",
      ],
      correctIndex: 0,
      explanation: "The modern model begins with safety management error, followed by safety-program defect, command error, system defect, operating error, mishap, and results.",
    },
  ],

  "ch-23": [
    {
      level: "foundation",
      stem: "Which set contains the four broad classifications of work-related injury described in the chapter?",
      options: [
        "Direct, indirect, acute, chronic",
        "Partial, total, temporary, permanent",
        "Recordable, reportable, restricted, first aid",
        "Physical, chemical, biological, ergonomic",
      ],
      correctIndex: 1,
      explanation: "The chapter classifies work-related injuries into partial, total, temporary, and permanent categories.",
    },
    {
      level: "homework-level",
      stem: "Which factor is explicitly part of the basis for workers' compensation insurance premiums in the chapter?",
      options: [
        "Dollars of payroll per $100 and an experience modification rate or factor",
        "The number of safety posters displayed",
        "The age of the organization's safety manual",
        "Only the price of employee uniforms",
      ],
      correctIndex: 0,
      explanation: "The source identifies payroll dollars per $100 and an EMR or EMF as the premium basis. The other items are not the stated premium factors.",
    },
    {
      level: "application",
      stem: "A company wants to reduce the duration and cost of covered injuries while returning employees to productive work within restrictions. Which program most directly supports that goal?",
      options: [
        "A written return-to-work/light-duty program",
        "A policy of delaying reports until the end of the year",
        "Eliminating communication with medical providers",
        "Requiring all injured workers to remain off work indefinitely",
      ],
      correctIndex: 0,
      explanation: "The chapter identifies return-to-work/light-duty programs as one of the most effective tools for reducing workers’ compensation premiums and experience modification rates.",
    },
    {
      level: "foundation",
      stem: "According to the chapter's general summary, most states require an employer to carry workers' compensation insurance or self-insure once it has at least how many employees?",
      options: ["One", "Three", "Five", "Twenty-five"],
      correctIndex: 2,
      explanation: "The chapter states that most states require employers with five or more employees to maintain workers' compensation insurance or be self-insured. Requirements still depend on the governing jurisdiction.",
    },
    {
      level: "application",
      stem: "For an illustrative rating calculation, an employer has $850,000 in payroll, a manual rate of $2.00 per $100 of payroll, and an experience modifier of 0.80. What is the experience-modified premium before other adjustments?",
      options: ["$1,360", "$13,600", "$17,000", "$21,250"],
      correctIndex: 1,
      explanation: "The base is $850,000 ÷ 100 × $2.00 = $17,000. Applying the 0.80 experience modifier gives $13,600. Actual premiums can include additional jurisdictional and classification adjustments.",
    },
  ],

  "ch-24": [
    {
      level: "foundation",
      stem: "What does the recommended weight limit (RWL) represent for a defined lifting task?",
      options: [
        "The heaviest load any individual worker can lift once.",
        "The load nearly all healthy workers can perform for up to 8 hours without increased low-back-injury risk under those task conditions.",
        "A legal maximum weight for every workplace task.",
        "The worker's body weight plus the load weight.",
      ],
      correctIndex: 1,
      explanation: "RWL is task-specific. It describes a weight that nearly all healthy workers can handle over a substantial period, up to 8 hours, without increased risk of lifting-related low-back pain or injury.",
    },
    {
      level: "homework-level",
      stem: "A box weighs 36 lb and the calculated RWL for the task is 24 lb. What is the lifting index?",
      options: ["0.67", "1.00", "1.50", "12.0"],
      correctIndex: 2,
      explanation: "The lifting index is actual load divided by RWL: 36 ÷ 24 = 1.5. It estimates the relative physical stress of the manual lifting task.",
    },
    {
      level: "application",
      stem: "A worker must rotate the torso to place a container off to the side rather than directly in front. Which lifting variable describes this displacement from the midsagittal plane?",
      options: ["Coupling classification", "Asymmetry angle", "Vertical location", "Lifting duration"],
      correctIndex: 1,
      explanation: "Asymmetry angle measures how far the object is displaced from the front (midsagittal plane) of the body at the start or end of a lift.",
    },
    {
      level: "foundation",
      stem: "A package weighs 18 lb and the recommended weight limit for its task is 24 lb. What is the lifting index?",
      options: ["0.25", "0.75", "1.33", "6.00"],
      correctIndex: 1,
      explanation: "The lifting index is actual load divided by RWL. Here, 18 ÷ 24 = 0.75.",
    },
    {
      level: "foundation",
      stem: "When assessing a lift, what does horizontal location measure?",
      options: [
        "The distance of the hands from the midpoint between the ankles",
        "The height of the hands above the floor",
        "The number of lifts in a 15-minute period",
        "The quality of the hand-to-object grip",
      ],
      correctIndex: 0,
      explanation: "Horizontal location is the distance of the hands away from the midpoint between the ankles. Vertical location is measured from the floor.",
    },
    {
      level: "homework-level",
      stem: "A worker lifts a tote from a hand height of 18 in. to a shelf height of 54 in. What is the vertical travel distance?",
      options: ["18 in.", "36 in.", "54 in.", "72 in."],
      correctIndex: 1,
      explanation: "Vertical travel distance is the absolute difference between the vertical heights at the origin and destination: |54 − 18| = 36 in.",
    },
    {
      level: "homework-level",
      stem: "Which set lists all coupling classifications used in the chapter's lifting-task terminology?",
      options: [
        "Good, fair, and poor",
        "Low, medium, and high",
        "Static, dynamic, and mixed",
        "Primary, secondary, and tertiary",
      ],
      correctIndex: 0,
      explanation: "The chapter classifies coupling as good, fair, or poor. Coupling describes the hand-to-object interface relevant to the lift.",
    },
    {
      level: "application",
      stem: "A container must be aligned precisely into a narrow fixture at the end of each lift. Which task feature does the chapter call this?",
      options: [
        "Significant control",
        "Horizontal location",
        "Lifting duration",
        "A parallel system",
      ],
      correctIndex: 0,
      explanation: "Significant control is the condition in which precision placement of the load is required at the destination of the lift.",
    },
  ],

  "ch-25": [
    {
      level: "foundation",
      stem: "Under the chapter's cave-in protection summary, a trench 5 ft deep requires what action?",
      options: [
        "Provide protection from cave-in.",
        "No protection because it is below 6 ft.",
        "Only issue hard hats.",
        "Wait until water enters the trench.",
      ],
      correctIndex: 0,
      explanation: "The source states that an excavation more than 4 ft deep must be protected from cave-in. A 5-ft trench is above that threshold.",
    },
    {
      level: "homework-level",
      stem: "A crane will work near a 70 kV overhead line. Using the chapter's clearance rule, what is the minimum clearance?",
      options: ["10 ft", "10 ft 8 in.", "11 ft 8 in.", "18 ft"],
      correctIndex: 1,
      explanation: "For voltage above 50 kV, add 0.4 in. for each kV over 50. The excess is 20 kV, so add 8 in. to 10 ft: 10 ft 8 in.",
    },
    {
      level: "application",
      stem: "Which statement distinguishes bonding from grounding?",
      options: [
        "Bonding connects conductive objects together; grounding connects conductive objects directly to earth.",
        "Bonding is limited to wood structures; grounding is limited to plastic equipment.",
        "Grounding joins two conductive objects, while bonding requires a ground rod only.",
        "They are identical terms with no practical distinction.",
      ],
      correctIndex: 0,
      explanation: "The chapter defines bonding as connecting conductive objects with a conductor. Grounding connects conductive objects directly to earth through a ground rod, cold pipe, or building steel.",
    },
    {
      level: "foundation",
      stem: "Which soil type has the highest compressive strength in the chapter's excavation-soil summary?",
      options: ["Type A", "Type B", "Type C", "Type D"],
      correctIndex: 0,
      explanation: "Type A is described as good cohesive soil with high compressive strength. Type B is moderate and Type C is low.",
    },
    {
      level: "foundation",
      stem: "The chapter cautions that electrical current as low as what value can cause death?",
      options: ["0.75 mA", "7.5 mA", "75 mA", "750 mA"],
      correctIndex: 2,
      explanation: "The chapter identifies 75 mA as a potentially fatal current level. Electrical exposure should be controlled well before a potentially lethal level is reached.",
    },
    {
      level: "homework-level",
      stem: "A fall-arrest system is being planned for two workers, each using an independent anchorage. What capacity should each personal-fall-arrest anchor point be capable of holding?",
      options: ["500 lb total", "1,000 lb per crew", "2,500 lb per worker", "5,000 lb per person"],
      correctIndex: 3,
      explanation: "The construction-safety chapter states that anchor points for personal fall arrest should be capable of holding 5,000 lb per person.",
    },
    {
      level: "homework-level",
      stem: "Which compressed-air cleaning practice aligns with the chapter's stated limit?",
      options: [
        "Use 29 psi air for cleaning operations.",
        "Use 35 psi air if the nozzle is small.",
        "Use any pressure when workers wear gloves.",
        "Use 50 psi air only outdoors.",
      ],
      correctIndex: 0,
      explanation: "Only compressed air less than 30 psi may be used for cleaning operations under the chapter's summary. A 29 psi example is below that limit.",
    },
    {
      level: "application",
      stem: "Before mounting an abrasive grinding wheel, which pre-use verification does the chapter require?",
      options: [
        "Perform either a ring test or a vibration test on the wheel.",
        "Submerge the wheel in water for ten minutes.",
        "Run the wheel at full speed while unguarded.",
        "Replace the wheel's guard with a cloth cover.",
      ],
      correctIndex: 0,
      explanation: "The chapter requires either the ring test or the vibration test before using an abrasive grinder wheel. This check helps identify an unsound wheel before operation.",
    },
  ],

  "ch-26": [
    {
      level: "foundation",
      stem: "Which sequence correctly orders the five basic risk-management steps described in the chapter?",
      options: [
        "Hazard assessment, implementation, hazard identification, supervision, decision-making",
        "Hazard identification, hazard assessment, development of controls and decision-making, implementation, supervision and evaluation",
        "Inspection, citation, abatement, appeal, closure",
        "Plan, purchase PPE, respond, recover, audit",
      ],
      correctIndex: 1,
      explanation: "The five steps begin with hazard identification and assessment, then controls/decision-making, implementation, and supervision/evaluation.",
    },
    {
      level: "homework-level",
      stem: "After controls are selected, residual risk remains unacceptably high for a high-hazard task. What is the most defensible decision?",
      options: [
        "Proceed because a control has been selected.",
        "Add controls, limit the high-risk scope, or discontinue the project after balancing risk and benefit.",
        "Remove the hazard from the written analysis so the risk is no longer documented.",
        "Transfer all responsibility to the worker performing the task.",
      ],
      correctIndex: 1,
      explanation: "Residual risk is the risk remaining after controls. If it is too high, leaders can add controls, limit the scope, or discontinue the project based on the risk-benefit decision.",
    },
    {
      level: "application",
      stem: "A control plan says only “use safe practices.” What essential implementation detail is missing?",
      options: [
        "A clear statement of who, what, when, where, and how the control will be used.",
        "A promise that residual risk is always zero.",
        "A requirement to use PPE for every hazard.",
        "A substitute for supervision and evaluation.",
      ],
      correctIndex: 0,
      explanation: "The chapter says control measures should specify who, what, when, where, and how they will be used. They must then be converted into simple instructions understood at all levels.",
    },
    {
      level: "foundation",
      stem: "Which description best matches risk in the chapter's terminology?",
      options: [
        "The chance or probability that an injury, loss, or hazard event will occur",
        "A condition that always causes injury",
        "A control already put into service",
        "Only the monetary cost of an accident",
      ],
      correctIndex: 0,
      explanation: "Risk is defined as the chance or probability of occurrence of an injury, loss, hazard, or potential hazard.",
    },
    {
      level: "foundation",
      stem: "A corroded guardrail has the potential to fail and injure a worker, even though no failure has occurred. In risk-management terms, what is it?",
      options: ["A hazard", "Residual risk only", "A posttest", "A control measure"],
      correctIndex: 0,
      explanation: "A hazard is a condition with the potential to cause injury, illness, death, property damage or loss, or mission degradation.",
    },
    {
      level: "homework-level",
      stem: "A risk-ranking team records both the likelihood of an event and the seriousness of its undesired result. Which two risk terms is it evaluating?",
      options: [
        "Probability and severity",
        "Frequency and coupling",
        "Voltage and resistance",
        "Payroll and experience modifier",
      ],
      correctIndex: 0,
      explanation: "Probability is the likelihood an event will occur; severity is the degree of undesired consequences. Both are essential to a risk assessment.",
    },
    {
      level: "homework-level",
      stem: "Which option correctly groups the three broad categories of controls described in the chapter?",
      options: [
        "Educational, physical, and avoidance controls",
        "Temporary, permanent, and partial controls",
        "Engineering, payroll, and insurance controls",
        "Hazard, probability, and severity controls",
      ],
      correctIndex: 0,
      explanation: "The chapter groups controls as educational, physical, and avoidance controls. Specific measures may vary widely within those categories.",
    },
    {
      level: "application",
      stem: "After a control is introduced, workers interpret it differently across shifts. What should the oversight stage do to correct this implementation weakness?",
      options: [
        "Convert the control into clear, simple instructions understood at all levels and evaluate its use.",
        "Assume the written title of the control is enough.",
        "Remove the control from the risk assessment.",
        "Skip supervision because implementation has begun.",
      ],
      correctIndex: 0,
      explanation: "Supervision and evaluation continue after implementation. The chapter stresses that controls must become clear, simple instructions understood at all levels.",
    },
  ],
} as const satisfies Readonly<Record<string, readonly AuthoredPracticeQuestion[]>>;
