export type AuthoredPracticeQuestion = {
  level: "foundation" | "homework-level" | "application";
  stem: string;
  options: readonly [string, string, string, string];
  correctIndex: number;
  explanation: string;
};

// Independently authored from the supplied 4th-edition reference. The
// question sets are intentionally separate from homework and study items.
export const AUTHORED_PRACTICE_01_13: Readonly<Record<string, readonly AuthoredPracticeQuestion[]>> = {
  "ch-01": [
    {
      level: "foundation",
      stem: "On a four-choice certification-exam item, a candidate can eliminate two clearly wrong options but is unsure between the other two. What is the sound next step?",
      options: [
        "Leave the item blank to avoid losing points.",
        "Select the more plausible remaining option after eliminating the implausible choices.",
        "Assume the item cannot be answered until a later item is solved.",
        "Mark every option that might be correct.",
      ],
      correctIndex: 1,
      explanation: "The book advises intelligent guessing when the answer is uncertain: eliminate choices known to be wrong or less plausible, then choose from those remaining. Wrong answers do not carry a penalty.",
    },
    {
      level: "homework-level",
      stem: "A candidate spends several minutes on the first difficult calculation while many later items are likely straightforward. Which testing strategy best uses the available examination time?",
      options: [
        "Continue until the first item is solved before viewing any later item.",
        "Skip every calculation because calculations consume too much time.",
        "Answer items that can be completed quickly first, then return to marked difficult items.",
        "Submit the examination after completing only the first pass.",
      ],
      correctIndex: 2,
      explanation: "The source recommends building the score efficiently by completing known or quick items first, then returning to difficult or time-consuming marked items.",
    },
    {
      level: "application",
      stem: "What calculator preparation is most consistent with the current test-center conditions described in the reference?",
      options: [
        "Practice with the on-screen TI-30XS-style calculator before the examination.",
        "Bring two personal scientific calculators as backups.",
        "Plan to borrow a calculator from the test center.",
        "Avoid using calculator functions because only handwritten computation is allowed.",
      ],
      correctIndex: 0,
      explanation: "The reference states that the test center provides an on-screen calculator that emulates a TI-30XS, while physical calculators are not permitted. Practicing with that tool prevents avoidable time loss.",
    },
    {
      level: "foundation",
      stem: "A candidate's self-assessment shows strong knowledge of legal topics but weak knowledge of trigonometry. Which study-plan choice follows the reference's advice?",
      options: [
        "Spend most of the available study time on legal topics because they feel productive.",
        "Allocate the extra study time to trigonometry and other weaker domains.",
        "Delay reviewing weak topics until the final week before the examination.",
        "Study only questions that reproduce past examination wording.",
      ],
      correctIndex: 1,
      explanation: "The reference recommends using self-assessment to identify strengths and weaknesses, then building a schedule that focuses on weaker areas rather than repeatedly studying the material that already feels easiest.",
    },
    {
      level: "application",
      stem: "An examination item uses an unfamiliar manufacturing scenario. What is the sound way to interpret the item?",
      options: [
        "Treat the item as unanswerable because the industry is unfamiliar.",
        "Assume facts that are not stated so the scenario feels more familiar.",
        "Identify the underlying area of knowledge being tested instead of dismissing the context.",
        "Ignore the stem and select the longest answer choice.",
      ],
      correctIndex: 2,
      explanation: "The chapter advises candidates to identify the item focus and use the information actually provided. An unfamiliar industry context can still test knowledge the candidate already has; it should not be dismissed for that reason.",
    },
  ],
  "ch-02": [
    {
      level: "foundation",
      stem: "A state legislature passes a workplace-safety reporting statute. What broad type of law is that enactment?",
      options: [
        "Administrative law",
        "Case law",
        "Statutory law",
        "Common-law tort doctrine",
      ],
      correctIndex: 2,
      explanation: "The book distinguishes statutory law as law created by federal or state legislators. Administrative agencies create administrative law, while judicial decisions create case law.",
    },
    {
      level: "homework-level",
      stem: "Two residents of different states dispute a $90,000 injury claim governed by state law. According to the jurisdiction overview, which fact can support federal-court jurisdiction even without a federal question?",
      options: [
        "The plaintiff prefers a federal judge.",
        "The parties are diverse and the amount in controversy exceeds $75,000.",
        "The case concerns a workplace rather than a home.",
        "The defendant has insurance coverage.",
      ],
      correctIndex: 1,
      explanation: "The source identifies a federal question or diversity of parties as routes to federal court; for diversity, it gives an amount-in-controversy threshold greater than $75,000.",
    },
    {
      level: "application",
      stem: "While traveling to meet a client, a sales employee makes a brief lunch detour and injures a pedestrian with the company vehicle. Which doctrine most directly explains why the employer may also face liability?",
      options: [
        "Assumption of risk",
        "Stare decisis",
        "Strict product liability",
        "Vicarious liability",
      ],
      correctIndex: 3,
      explanation: "Vicarious, or imputed, liability can hold an employer responsible for an employee's acts. The chapter specifically discusses a sales representative's slight deviation while traveling to a client.",
    },
    {
      level: "foundation",
      stem: "According to the chapter's jurisdiction overview, what authority must a court have before it can hear a case?",
      options: [
        "Subject-matter jurisdiction or personal jurisdiction over the parties",
        "An OSHA inspection report",
        "A request for punitive damages",
        "A signed employer safety policy",
      ],
      correctIndex: 0,
      explanation: "The legal-aspects chapter identifies subject-matter jurisdiction and personal jurisdiction over the parties as the jurisdictional bases discussed before a court may hear a case.",
    },
    {
      level: "homework-level",
      stem: "A state appellate decision becomes a precedent used to interpret a later legal dispute. What body of law does that decision represent?",
      options: [
        "Administrative law",
        "Statutory law",
        "Contract law",
        "Case law",
      ],
      correctIndex: 3,
      explanation: "The source calls case law judge-made or case-made law. It is derived from judicial decisions in actual cases, particularly when legal questions are interpreted at the appellate level.",
    },
  ],
  "ch-03": [
    {
      level: "foundation",
      stem: "A work-related fatality occurs at a manufacturing site. Which reporting deadline does the reference identify for notifying OSHA?",
      options: [
        "Within 8 hours",
        "Within 24 hours",
        "Within 3 calendar days",
        "At the end of the calendar year",
      ],
      correctIndex: 0,
      explanation: "The source states that work-related fatalities must be reported to OSHA within 8 hours. In-patient hospitalization, amputation, and loss of an eye have a separate 24-hour deadline.",
    },
    {
      level: "homework-level",
      stem: "An employee sustains a work-related cut from a sharp object contaminated with another person's blood. How should the employee's identity be handled on the OSHA 300 Log?",
      options: [
        "List the full name and diagnosis in the public annual summary.",
        "Omit the entire incident because it is confidential.",
        "Enter “privacy case” in place of the employee's name while retaining the required record.",
        "Record it only if the employee misses at least one workday.",
      ],
      correctIndex: 2,
      explanation: "The book identifies contaminated-needle and sharp-object injuries as privacy cases. The event is recorded, but “privacy case” replaces the employee's name on the OSHA 300 Log.",
    },
    {
      level: "application",
      stem: "A company is preparing its annual injury-and-illness summary. Which posting schedule follows the reference?",
      options: [
        "Post the OSHA 300A only during the first week of January.",
        "Post it no later than February 1 and keep it posted through April 30.",
        "Post it only after an OSHA inspection.",
        "Post it for five years in the payroll office.",
      ],
      correctIndex: 1,
      explanation: "The chapter states that the certified OSHA 300A annual summary is posted in a conspicuous location no later than February 1 and remains posted until April 30.",
    },
    {
      level: "foundation",
      stem: "A company has 12 employees and is checking its basic OSHA injury-and-illness recordkeeping duty. What does the source chapter say?",
      options: [
        "Employers with 10 or more employees are required to maintain occupational-injury records.",
        "Records are required only after a workplace fatality.",
        "Employees, rather than the employer, must decide whether to keep the records.",
        "The employer may wait until an annual OSHA inspection before creating records.",
      ],
      correctIndex: 0,
      explanation: "The chapter's key information states that employers with 10 or more employees are required to maintain records of occupational injuries. Specific regulatory exemptions still need to be checked when they apply.",
    },
    {
      level: "application",
      stem: "A remote employee is injured while carrying employer-provided equipment during assigned work at home. Under the chapter's recordkeeping guidance, what fact controls whether the event is work related?",
      options: [
        "Whether the employee owns the home",
        "Whether a supervisor witnessed the event",
        "Whether the injury was directly related to performing work rather than the general home environment",
        "Whether the employee had worked from home for more than one year",
      ],
      correctIndex: 2,
      explanation: "The source explains that an injury or illness occurring at home is recordable and reportable when it is directly related to the performance of work, rather than to the general home environment or setting.",
    },
  ],
  "ch-04": [
    {
      level: "foundation",
      stem: "A safety manager cites the OSH Act provision requiring an employer to keep the workplace free from recognized serious hazards when no specific standard applies. Which provision is being used?",
      options: [
        "Section 6(b), the rulemaking clause",
        "Section 11(c), the retaliation clause",
        "29 CFR 1904, the recordkeeping rule",
        "Section 5(a)(1), the General Duty Clause",
      ],
      correctIndex: 3,
      explanation: "The reference identifies Section 5(a)(1) of the OSH Act as the General Duty Clause.",
    },
    {
      level: "homework-level",
      stem: "An employer receives an OSHA citation and corrects the cited condition the next day. What posting rule still applies to the citation?",
      options: [
        "Remove it as soon as the condition is corrected.",
        "Post it conspicuously for 3 days or until abatement, whichever is longer.",
        "Post it only if an employee asks to see it.",
        "Keep it confidential until the contest period expires.",
      ],
      correctIndex: 1,
      explanation: "The book states that an employer must post a received citation in a conspicuous location for 3 days or until the violation is abated, whichever is longer.",
    },
    {
      level: "application",
      stem: "A facility has a written respirable-crystalline-silica exposure-control plan. Which action is required to keep that plan current?",
      options: [
        "Review and evaluate its effectiveness at least annually, then update it as necessary.",
        "Replace it only after a citation is issued.",
        "Archive it after the first employee training session.",
        "Limit it to a list of personal protective equipment.",
      ],
      correctIndex: 0,
      explanation: "The source requires the written silica exposure-control plan to be reviewed and evaluated at least annually and updated when needed.",
    },
    {
      level: "foundation",
      stem: "Which worker category is identified in the chapter as generally outside OSHA regulations' coverage?",
      options: [
        "A private-sector employer with one employee",
        "A self-employed individual",
        "A manufacturing employee",
        "An employee working for a covered private contractor",
      ],
      correctIndex: 1,
      explanation: "The chapter explains that OSHA regulations generally cover private-sector employers, while listing self-employed individuals among the groups to which the regulations do not apply.",
    },
    {
      level: "homework-level",
      stem: "An employer wants to challenge an OSHA citation after receiving it 12 working days ago. What action preserves the employer's right to contest under the chapter's procedure?",
      options: [
        "Make an oral objection during the next inspection.",
        "Wait for OSHA to reopen the citation automatically.",
        "Send a written Notice of Contest to the OSHA Area Director within 15 working days.",
        "Ask affected employees to select a new penalty amount.",
      ],
      correctIndex: 2,
      explanation: "The source states that an employer has 15 working days after receiving the citation or proposed penalty to notify the OSHA Area Director in writing. An oral disagreement is not sufficient.",
    },
    {
      level: "foundation",
      stem: "An employee with occupational bloodborne-pathogen exposure declines the offered hepatitis B vaccination. What documentation is required by the chapter?",
      options: [
        "A personal note explaining why the employee dislikes vaccines",
        "A monthly medical clearance from the employee's supervisor",
        "A request to remove the employee permanently from the job",
        "A signed refusal statement maintained on file by the employer",
      ],
      correctIndex: 3,
      explanation: "When an occupationally exposed employee refuses hepatitis B vaccination, the reference requires a signed refusal statement that the employer maintains on file.",
    },
    {
      level: "application",
      stem: "A records coordinator is setting the retention period for bloodborne-pathogen employee medical records. What period follows the source chapter?",
      options: [
        "The duration of employment plus 30 years",
        "One year after the employee leaves",
        "Five calendar years from the incident",
        "Until the next annual OSHA summary is posted",
      ],
      correctIndex: 0,
      explanation: "The source states that employee medical records under the Bloodborne Pathogen Standard must be retained for the duration of employment plus 30 years.",
    },
    {
      level: "application",
      stem: "A new silica-generating task is added to a facility's written exposure-control plan. Which information must the plan describe for that task?",
      options: [
        "Only the department's annual safety budget",
        "The engineering controls, work practices, and respiratory protection used to limit exposure",
        "The names of the newest employees assigned to the task",
        "Only the number of prior OSHA citations at the facility",
      ],
      correctIndex: 1,
      explanation: "For each task involving respirable crystalline silica, the written exposure-control plan must describe the engineering controls, work practices, and respiratory protection used to limit employee exposure.",
    },
  ],
  "ch-05": [
    {
      level: "foundation",
      stem: "A concentration is written as 0.00072. Which scientific-notation form preserves its value?",
      options: [
        "7.2 × 10⁴",
        "7.2 × 10³",
        "7.2 × 10⁻⁴",
        "7.2 × 10⁻⁵",
      ],
      correctIndex: 2,
      explanation: "Moving the decimal four places to the right gives 7.2, so the original small quantity is 7.2 × 10⁻⁴.",
    },
    {
      level: "homework-level",
      stem: "An airflow equation is Q = VA, where Q is volumetric flow and V is air velocity. If Q and V are known, which rearrangement correctly solves for duct area A?",
      options: [
        "A = Q / V",
        "A = V / Q",
        "A = QV",
        "A = Q − V",
      ],
      correctIndex: 0,
      explanation: "Divide both sides of Q = VA by V to isolate area: A = Q/V. Formula transposition is a core purpose of the chapter.",
    },
    {
      level: "application",
      stem: "A diagonal brace spans a rectangular opening that is 9 ft high and 12 ft wide. Ignoring connection offsets, what minimum brace length is required?",
      options: [
        "3 ft",
        "10.5 ft",
        "14 ft",
        "15 ft",
      ],
      correctIndex: 3,
      explanation: "Apply the Pythagorean equation: √(9² + 12²) = √225 = 15 ft.",
    },
    {
      level: "foundation",
      stem: "What value should be used for 0! in a safety calculation that includes factorials?",
      options: [
        "0",
        "1",
        "Undefined",
        "10",
      ],
      correctIndex: 1,
      explanation: "The math-review chapter specifically notes that 0! is always 1. This convention is important when evaluating factorial expressions in probability and other calculations.",
    },
    {
      level: "foundation",
      stem: "Which engineering-notation prefix represents 10⁻⁶?",
      options: [
        "Milli",
        "Nano",
        "Micro",
        "Mega",
      ],
      correctIndex: 2,
      explanation: "The source's engineering-notation table identifies micro, symbol μ, as the prefix for 10⁻⁶. Milli is 10⁻³ and nano is 10⁻⁹.",
    },
    {
      level: "homework-level",
      stem: "A rectangular duct is 8 in. wide and 6 in. high. After converting both dimensions to feet, what is its cross-sectional area?",
      options: [
        "0.111 ft²",
        "0.250 ft²",
        "0.500 ft²",
        "0.333 ft²",
      ],
      correctIndex: 3,
      explanation: "Convert first: 8 in. = 8/12 ft and 6 in. = 6/12 ft. The area is (8/12)(6/12) = 48/144 = 0.333 ft². The chapter stresses unit conversion before applying safety equations.",
    },
    {
      level: "homework-level",
      stem: "A triangular warning-zone layout has a 14-ft base and a perpendicular height of 5 ft. What area does it cover?",
      options: [
        "35 ft²",
        "19 ft²",
        "70 ft²",
        "140 ft²",
      ],
      correctIndex: 0,
      explanation: "Triangle area is one-half times base times height: ½ × 14 ft × 5 ft = 35 ft². Area must be reported in square units.",
    },
    {
      level: "application",
      stem: "A 900-lb load is supported symmetrically by two slings, each at 30° above horizontal. Ignoring sling weight, what tension is carried by each sling leg?",
      options: [
        "450 lb",
        "900 lb",
        "1,039 lb",
        "1,800 lb",
      ],
      correctIndex: 1,
      explanation: "Each leg must provide half of the 900-lb vertical load, or 450 lb. With a 30° sling angle, T sin 30° = 450 lb, so T = 450/0.5 = 900 lb per leg.",
    },
  ],
  "ch-06": [
    {
      level: "foundation",
      stem: "Two atoms of the same element have different numbers of neutrons. What property still identifies them as the same element?",
      options: [
        "Their atomic mass is identical.",
        "Their atomic number, or number of protons, is identical.",
        "They have the same number of valence electrons in every state.",
        "They must have the same molecular formula.",
      ],
      correctIndex: 1,
      explanation: "The chapter defines atomic number as the number of protons in the nucleus. Neutron differences produce isotopes, not a different element.",
    },
    {
      level: "homework-level",
      stem: "Which statement correctly distinguishes ionic from covalent bonding?",
      options: [
        "Both require neutrons to be shared.",
        "Ionic bonding occurs only between identical atoms.",
        "Ionic bonding transfers electrons; covalent bonding shares electrons.",
        "Covalent bonding transfers protons between nuclei.",
      ],
      correctIndex: 2,
      explanation: "The reference describes ionic bonding as electron transfer from one atom to another and covalent bonding as electron sharing.",
    },
    {
      level: "application",
      stem: "A fixed amount of gas is at 2 atm and 2 L. At constant temperature, it expands to 4 L. What pressure follows from Boyle's law?",
      options: [
        "1 atm",
        "2 atm",
        "4 atm",
        "8 atm",
      ],
      correctIndex: 0,
      explanation: "At constant temperature, P₁V₁ = P₂V₂. Thus P₂ = (2 atm × 2 L)/4 L = 1 atm.",
    },
    {
      level: "foundation",
      stem: "Approximately how many atoms or molecules are represented by one mole of a substance?",
      options: [
        "6.02 × 10²³",
        "6.02 × 10⁶",
        "3.14 × 10⁸",
        "9.81 × 10²",
      ],
      correctIndex: 0,
      explanation: "The source identifies Avogadro's number as 6.02 × 10²³ atoms and states that one mole equals 6.02 × 10²³ atoms.",
    },
    {
      level: "foundation",
      stem: "Which electrons are called valence electrons in the chapter's atomic-structure review?",
      options: [
        "Electrons inside the nucleus",
        "Electrons that have been converted into neutrons",
        "Electrons shared only during ionic bonding",
        "Electrons in an atom's outer shell",
      ],
      correctIndex: 3,
      explanation: "Valence electrons are the electrons in an atom's outer shell. The source also notes that a complete number in a shell creates a more stable atom.",
    },
    {
      level: "homework-level",
      stem: "Using the chapter's listed atomic weights of hydrogen = 1 and oxygen = 16, what is the molecular weight of H₂O?",
      options: [
        "16",
        "18",
        "17",
        "32",
      ],
      correctIndex: 1,
      explanation: "Water contains two hydrogen atoms and one oxygen atom, so its molecular weight is 2(1) + 16 = 18.",
    },
    {
      level: "application",
      stem: "At the chapter's ventilation standard temperature and pressure, a plenum contains 2,000 ft³ of air. Using 0.075 lb/ft³, what is the air mass?",
      options: [
        "15 lb",
        "75 lb",
        "150 lb",
        "2,000 lb",
      ],
      correctIndex: 2,
      explanation: "At ventilation STP of 70°F and 1 atm, the source gives air density as 0.075 lb/ft³. Multiply 2,000 ft³ by 0.075 lb/ft³ to obtain 150 lb.",
    },
    {
      level: "application",
      stem: "A hygienist is using an industrial-hygiene gas equation that specifies standard temperature and pressure. Which reference condition matches the chapter?",
      options: [
        "0°C and 1 atm",
        "25°C and 1 atm",
        "70°F and 1 atm",
        "100°C and 1 atm",
      ],
      correctIndex: 1,
      explanation: "The chapter distinguishes several standard conditions. For industrial-hygiene equations, STP is 25°C and 1 atm; 70°F and 1 atm is the ventilation convention.",
    },
  ],
  "ch-07": [
    {
      level: "foundation",
      stem: "A risk assessment considers both a solvent's ability to harm and the realistic worker exposure during a task. Which statement correctly separates hazard from risk?",
      options: [
        "Hazard is the final numerical probability, while risk is only a descriptive label.",
        "Risk exists only after a worker has developed illness.",
        "Risk is the chemical's inherent ability to harm an organism.",
        "Hazard is the potential for harm, while risk is a quantitative measurement or estimate of that hazard.",
      ],
      correctIndex: 3,
      explanation: "The book defines hazard as the potential for a substance to cause harm and risk as a quantitative measurement or estimate of a hazard. Exposure information is essential to a meaningful workplace-risk assessment.",
    },
    {
      level: "homework-level",
      stem: "Researchers classify workers by whether they were exposed to a process chemical and then follow them to compare disease occurrence. What study design is this?",
      options: [
        "Cross-sectional study",
        "Cohort study",
        "Case-control study",
        "Ames test",
      ],
      correctIndex: 1,
      explanation: "A cohort study follows groups defined by exposure status to compare later outcomes. The chapter contrasts it with case-control and cross-sectional approaches.",
    },
    {
      level: "application",
      stem: "Before investing in a more extensive toxicology program, a laboratory needs a screening test for whether a new chemical can cause mutations. Which test is most appropriate?",
      options: [
        "An audiogram",
        "A spirometry test",
        "An Ames test",
        "A time-weighted-average calculation",
      ],
      correctIndex: 2,
      explanation: "The chapter identifies Ames testing as a procedure used to determine whether a chemical is a mutagen.",
    },
    {
      level: "foundation",
      stem: "An abrasive-blasting workforce is being prioritized for renal-health surveillance. Which metal exposure is the chapter's most direct concern?",
      options: [
        "Chromium",
        "Beryllium",
        "Nickel",
        "Cadmium",
      ],
      correctIndex: 3,
      explanation: "The toxicology reference links cadmium from abrasive blasting with renal damage. That source-specific association makes cadmium the exposure to investigate in this scenario.",
    },
    {
      level: "homework-level",
      stem: "A worker in ore processing develops CBD, a chronic lung condition described in the chapter. Which occupational exposure is most directly implicated?",
      options: [
        "Beryllium",
        "Creosote coal tar",
        "Benzene",
        "Arsenic",
      ],
      correctIndex: 0,
      explanation: "The source identifies beryllium from ore processing as a cause of chronic beryllium disease (CBD), also termed berylliosis.",
    },
    {
      level: "homework-level",
      stem: "A demolition crew removes legacy insulation. Which set of serious outcomes is associated with asbestos exposure in the chapter?",
      options: [
        "Renal damage, cataracts, and hearing loss",
        "Asbestosis, lung cancer, and mesothelioma",
        "Granulocytic leukemia and myelogenous leukemia",
        "Chronic beryllium disease and hemoglobinuria",
      ],
      correctIndex: 1,
      explanation: "The reference associates asbestos used as insulation and in many other products with asbestosis, lung cancer, and mesothelioma.",
    },
    {
      level: "application",
      stem: "A wood-preservation operation uses creosote coal tar. Which health outcome should the exposure assessment recognize?",
      options: [
        "Tetanus",
        "Noise-induced hearing loss",
        "Lung cancer",
        "Heat syncope",
      ],
      correctIndex: 2,
      explanation: "The source specifically identifies creosote coal tar from wood preservatives as a lung-cancer hazard. That association belongs in the operation's health-risk assessment.",
    },
    {
      level: "application",
      stem: "A nickel-processing operation is reviewing which cancer endpoints warrant special attention. Which association is supported by the chapter?",
      options: [
        "Lung and nasopharyngeal cancer",
        "Renal damage only",
        "Chronic beryllium disease",
        "Granulocytic leukemia only",
      ],
      correctIndex: 0,
      explanation: "The toxicology chapter lists nickel as a cause of lung and nasopharyngeal cancer. The other choices correspond to different source-listed occupational toxicants.",
    },
  ],
  "ch-08": [
    {
      level: "foundation",
      stem: "An industrial hygienist attaches a calibrated sampler to a worker for the worker's normal full-shift duties. What sampling approach is being used?",
      options: [
        "Personal sampling",
        "Area sampling",
        "Grab sampling",
        "Blank sampling",
      ],
      correctIndex: 0,
      explanation: "Personal sampling places the air sampler on the employee during normal work. Area sampling uses a stationary device.",
    },
    {
      level: "homework-level",
      stem: "A pump is calibrated at 2.00 L/min before sampling and 2.12 L/min afterward. What should be done with the sample under the source's flow-rate criterion?",
      options: [
        "Accept it because any post-calibration change is normal.",
        "Correct the result by subtracting 0.12 L/min.",
        "Use it only as an area sample.",
        "Discard it because the post-sampling flow differs by more than ±5%.",
      ],
      correctIndex: 3,
      explanation: "The change is 6%. The chapter requires discarding samples when the post-sampling flow rate lies outside ±5% of the pre-sampling rate.",
    },
    {
      level: "application",
      stem: "A survey targets an airborne organic solvent vapor for laboratory analysis. Which collection medium is the source's primary match for gases and vapors?",
      options: [
        "A particulate filter cassette",
        "A sorbent tube",
        "A bare microscope slide",
        "A wet-bulb thermometer",
      ],
      correctIndex: 1,
      explanation: "The book identifies filter media primarily for particulates and sorbent tubes for sampling gases and vapors.",
    },
    {
      level: "foundation",
      stem: "After a local exhaust system is installed, what is one valid reason to repeat air sampling?",
      options: [
        "To replace all equipment-maintenance inspections",
        "To monitor whether the implemented controls are working",
        "To determine employees' job seniority",
        "To eliminate the need to identify the contaminant",
      ],
      correctIndex: 1,
      explanation: "The source lists monitoring implemented control measures as a reason for air sampling. Sampling can show whether the control is actually reducing workplace exposure as intended.",
    },
    {
      level: "homework-level",
      stem: "A technician collects a known volume of air in a container for laboratory analysis at a defined point in time. What sampling approach is this?",
      options: [
        "Area sampling",
        "Grab sampling",
        "Integrated sampling",
        "Personal sampling",
      ],
      correctIndex: 1,
      explanation: "Grab sampling is the collection of a known volume of air in a container for laboratory analysis, or measurement by a direct-reading instrument.",
    },
    {
      level: "homework-level",
      stem: "A hygienist combines results from several sequential samples to estimate a worker's 8-hour time-weighted average exposure. What type of sampling is being used?",
      options: [
        "Blank sampling",
        "Area sampling",
        "Integrated sampling",
        "Grab sampling",
      ],
      correctIndex: 2,
      explanation: "Integrated sampling combines one or more samples to estimate the worker's 8-hour time-weighted average exposure.",
    },
    {
      level: "application",
      stem: "A laboratory result is statistically distinguishable from a blank, but the analyst cannot yet report a quantitative result with the stated confidence. Where does the result fall?",
      options: [
        "Above the limit of detection but below the limit of quantification",
        "Below both the limit of detection and the blank value",
        "Above the limit of quantification by definition",
        "Outside the need for any calibration check",
      ],
      correctIndex: 0,
      explanation: "The limit of detection is the lowest level statistically different from a blank. The limit of quantification is the concentration above which quantitative results can be obtained with stated confidence.",
    },
    {
      level: "application",
      stem: "Before using a battery-powered sampling pump in a potentially explosive area, what verification is required?",
      options: [
        "The pump has a color label matching the work area.",
        "The pump is the newest model available.",
        "The pump was borrowed from another department.",
        "The manufacturer classifies the sampling equipment as intrinsically safe.",
      ],
      correctIndex: 3,
      explanation: "The chapter directs the hygienist to ensure that sampling equipment used in a potentially explosive environment is classified by its manufacturer as intrinsically safe before use.",
    },
  ],
  "ch-09": [
    {
      level: "foundation",
      stem: "A bench operation releases a contaminant at one predictable point. Which ventilation approach best targets the contaminant before it disperses into the workroom?",
      options: [
        "Natural ventilation only",
        "General dilution ventilation only",
        "Local exhaust ventilation",
        "Respiratory protection as the sole permanent control",
      ],
      correctIndex: 2,
      explanation: "The source describes local ventilation as a way to remove contaminants at the source before they enter the workplace.",
    },
    {
      level: "homework-level",
      stem: "A plain round hood opening is 12 inches in diameter. According to the chapter's stated limitation, up to what distance is its capture-velocity equation intended to be accurate?",
      options: [
        "6 inches",
        "18 inches",
        "24 inches",
        "36 inches",
      ],
      correctIndex: 1,
      explanation: "The equation is accurate for a limited distance of 1.5 times the duct diameter or side length. For 12 inches, 1.5 × 12 = 18 inches.",
    },
    {
      level: "application",
      stem: "A technician compares static-pressure readings on an exhaust fan. Which pattern is expected by the reference?",
      options: [
        "Both sides of the fan are negative.",
        "Both sides of the fan are positive.",
        "The upstream side is positive and the downstream side is negative.",
        "The upstream side is negative and the downstream side is positive.",
      ],
      correctIndex: 3,
      explanation: "The book states that static pressure is negative upstream of the fan and positive downstream of it.",
    },
    {
      level: "foundation",
      stem: "A local-exhaust system has branch ducts of different sizes and needs its airflow balanced. Which component is used for that adjustment?",
      options: [
        "A blast gate",
        "A wet-bulb thermometer",
        "A sorbent tube",
        "A pressure-relief valve",
      ],
      correctIndex: 0,
      explanation: "The ventilation chapter states that blast gates are used to balance airflow in ducts of different sizes.",
    },
    {
      level: "homework-level",
      stem: "A hood must pull a contaminant plume toward its opening before the material disperses into the room. What is the name for the minimum hood-induced air speed needed to do that?",
      options: [
        "Transport velocity",
        "Face velocity",
        "Capture velocity",
        "Static pressure",
      ],
      correctIndex: 2,
      explanation: "Capture velocity is defined in the chapter as the minimum velocity of hood-induced air necessary to capture the contaminant.",
    },
    {
      level: "homework-level",
      stem: "When calculating a hood's static pressure, which sign should be expected for SPh under the source convention?",
      options: [
        "It is always negative.",
        "It is always positive.",
        "It must equal zero.",
        "Its sign is determined only by fan-blade direction.",
      ],
      correctIndex: 1,
      explanation: "The reference explicitly notes that hood static pressure, SPh, is always positive when calculated under the chapter's convention.",
    },
    {
      level: "application",
      stem: "An engineer is choosing the primary fan type for a local exhaust ventilation system that must move contaminants from a source. Which choice follows the chapter?",
      options: [
        "An axial ceiling fan",
        "A natural-draft stack only",
        "A portable room circulator",
        "A centrifugal fan",
      ],
      correctIndex: 3,
      explanation: "The chapter identifies centrifugal fans as the best fan type for local exhaust ventilation systems.",
    },
    {
      level: "application",
      stem: "For an efficiency-focused local-exhaust fan selection, which blade configuration does the chapter identify as the most efficient?",
      options: [
        "Backward-curved blades",
        "Forward-curved blades",
        "Straight radial blades",
        "No blades; only a diffuser",
      ],
      correctIndex: 0,
      explanation: "According to the ventilation key information, backward-curved fan blades are the most efficient.",
    },
  ],
  "ch-10": [
    {
      level: "foundation",
      stem: "A worker's measured occupational noise exposure is 85 dBA. What hearing-conservation-program decision follows from the reference?",
      options: [
        "Include the worker in the program because exposure at or above 85 dBA meets the criterion.",
        "Exclude the worker unless exposure reaches 90 dBA.",
        "Wait until an audiogram shows hearing loss.",
        "Include the worker only if the job involves impulse noise.",
      ],
      correctIndex: 0,
      explanation: "The source states that employees with occupational exposure equal to or exceeding 85 dBA, or a 50% dose, must be included in the hearing conservation program.",
    },
    {
      level: "homework-level",
      stem: "Compared with baseline, a worker's hearing thresholds change by 13 dB at 2,000 Hz, 7 dB at 3,000 Hz, and 10 dB at 4,000 Hz in one ear. How should this be classified under the chapter's STS definition?",
      options: [
        "Not an STS because one frequency changed by less than 10 dB.",
        "Not an STS because the total change is less than 40 dB.",
        "An STS because the three-frequency average change is 10 dB.",
        "An STS only if both ears change by 10 dB.",
      ],
      correctIndex: 2,
      explanation: "The average change is (13 + 7 + 10)/3 = 10 dB. The source defines an STS as an average shift of 10 dB or more at 2,000, 3,000, and 4,000 Hz in either ear.",
    },
    {
      level: "application",
      stem: "Which instrument specification meets the chapter's minimum standard for determining employee noise exposure?",
      options: [
        "A Type 0 sound-level meter with ±5 dB accuracy",
        "A Type 2 sound-level meter with ±1 dB accuracy",
        "A smartphone microphone without field verification",
        "An octave-band analyzer used only to estimate total dose",
      ],
      correctIndex: 1,
      explanation: "The reference identifies a Type 2 sound-level meter as the minimum standard for determining employee exposure and gives its accuracy as ±1 dB.",
    },
    {
      level: "foundation",
      stem: "Before a scheduled audiometric test, how long does the chapter require an employee to be away from a noisy environment?",
      options: [
        "8 hours",
        "12 hours",
        "14 hours",
        "24 hours",
      ],
      correctIndex: 2,
      explanation: "The source states that 14 hours away from a noisy environment are required before audiometric testing.",
    },
    {
      level: "foundation",
      stem: "Which OSHA regulation number is identified as the hearing conservation standard?",
      options: [
        "29 CFR 1910.1030",
        "29 CFR 1910.134",
        "29 CFR 1910.157",
        "29 CFR 1910.95",
      ],
      correctIndex: 3,
      explanation: "The chapter identifies OSHA's hearing conservation standard as 29 CFR 1910.95.",
    },
    {
      level: "homework-level",
      stem: "According to the chapter's cited hearing-conservation schedule, how often is monitoring required by 29 CFR 1910.95?",
      options: [
        "Every month",
        "Every 2 years",
        "Every 5 years",
        "Only after a standard threshold shift",
      ],
      correctIndex: 1,
      explanation: "The key information for the chapter states that monitoring under 29 CFR 1910.95 is required every 2 years.",
    },
    {
      level: "homework-level",
      stem: "A 250-ft² sound-absorbing surface has a noise reduction coefficient of 0.80. How many sabins does it provide?",
      options: [
        "200 sabins",
        "250 sabins",
        "312.5 sabins",
        "1,000 sabins",
      ],
      correctIndex: 0,
      explanation: "A sabin equals surface area times the noise reduction coefficient. Thus, 250 ft² × 0.80 = 200 sabins.",
    },
    {
      level: "application",
      stem: "Which reference acoustic power is used when calculating sound power levels in the chapter?",
      options: [
        "10⁻⁶ W",
        "10⁻⁹ W",
        "10⁻¹² W",
        "1 W",
      ],
      correctIndex: 2,
      explanation: "The source gives 10⁻¹² W as the reference acoustic power for sound power levels.",
    },
  ],
  "ch-11": [
    {
      level: "foundation",
      stem: "A worker handles goat hair, wool, and hides and is being evaluated for an occupational biological hazard. Which etiological agent is specifically associated with anthrax in the chapter?",
      options: [
        "Y. pestis",
        "B. anthracis",
        "M. tuberculosis",
        "C. tetani",
      ],
      correctIndex: 1,
      explanation: "The book identifies B. anthracis as the etiological agent for anthrax and notes the occupational relevance of handling animal materials such as goat hair, wool, and hides.",
    },
    {
      level: "homework-level",
      stem: "A laboratory works with agents that may be transmitted by the respiratory route and can cause serious, potentially lethal infection. Which biosafety level is described for that work?",
      options: [
        "Biosafety Level I",
        "Biosafety Level II",
        "Biosafety Level IV only",
        "Biosafety Level III",
      ],
      correctIndex: 3,
      explanation: "The source describes Biosafety Level III for indigenous or exotic agents with potential respiratory transmission that may cause serious and potentially lethal infection, with controlled access and biological safety cabinets or enclosed equipment.",
    },
    {
      level: "application",
      stem: "A new biological-safety program funds only laboratory training and PPE. What additional control category must be included for the program to reflect the chapter's three primary preventive measures?",
      options: [
        "Facility construction and design",
        "Financial loss reserves",
        "Personal fitness testing only",
        "Noise exposure monitoring",
      ],
      correctIndex: 0,
      explanation: "The chapter groups primary biological-safety prevention into laboratory practices and techniques, safety equipment, and facility construction and design.",
    },
    {
      level: "foundation",
      stem: "Which regulation number contains OSHA's Bloodborne Pathogen Standard?",
      options: [
        "29 CFR 1910.95",
        "29 CFR 1910.1030",
        "29 CFR 1910.1200",
        "29 CFR 1926.501",
      ],
      correctIndex: 1,
      explanation: "The biological-hazards chapter identifies OSHA's Bloodborne Pathogen Standard as 29 CFR 1910.1030.",
    },
    {
      level: "homework-level",
      stem: "Which infectious disease of animals and humans is caused by the bacterium Y. pestis?",
      options: [
        "Anthrax",
        "Tetanus",
        "Plague",
        "Tuberculosis",
      ],
      correctIndex: 2,
      explanation: "The source identifies Y. pestis as the bacterium that causes plague in animals and humans.",
    },
    {
      level: "homework-level",
      stem: "A puncture-wound scenario raises concern for the nervous-system disease known as lockjaw. Which organism causes that disease?",
      options: [
        "B. anthracis",
        "M. tuberculosis",
        "Y. pestis",
        "C. tetani",
      ],
      correctIndex: 3,
      explanation: "The chapter states that tetanus, also called lockjaw, is a disease of the nervous system caused by C. tetani.",
    },
    {
      level: "application",
      stem: "A workplace is assessing person-to-person transmission of hepatitis A. Which route is identified as the primary means of spread in the United States?",
      options: [
        "Fecal-oral transmission",
        "Ultraviolet radiation exposure",
        "Sound-pressure exposure",
        "Contact with energized equipment",
      ],
      correctIndex: 0,
      explanation: "The source identifies person-to-person transmission through the fecal-oral route as the primary means of hepatitis A spread in the United States.",
    },
    {
      level: "application",
      stem: "A grain-handling employee has substantial mold exposure. Which illness is associated with Aspergillus in the chapter?",
      options: [
        "Asbestosis",
        "Aspergillosis",
        "Berylliosis",
        "Heat syncope",
      ],
      correctIndex: 1,
      explanation: "The biological-hazards chapter identifies Aspergillus as a fungus (mold) that can cause aspergillosis in farmers and grain workers.",
    },
  ],
  "ch-12": [
    {
      level: "foundation",
      stem: "A worker standing near a hot furnace becomes warmer without touching the furnace or receiving a stream of hot air. Which heat-transfer mechanism is primarily involved?",
      options: [
        "Conduction",
        "Convection",
        "Radiation",
        "Evaporation",
      ],
      correctIndex: 2,
      explanation: "Radiation transfers thermal energy between bodies without direct contact. Conduction requires contact, while convection involves movement of a heated liquid or air.",
    },
    {
      level: "homework-level",
      stem: "A fire starts in a commercial deep fryer containing cooking oil. Which NFPA fire classification applies?",
      options: [
        "Class K",
        "Class A",
        "Class C",
        "Class D",
      ],
      correctIndex: 0,
      explanation: "The source identifies NFPA fire classifications A, B, C, D, and K. Class K applies to cooking-media fires such as commercial cooking oils and fats.",
    },
    {
      level: "application",
      stem: "A vapor concentration is measured below the substance's lower flammability limit. Which conclusion is supported?",
      options: [
        "The mixture is too rich to burn.",
        "The mixture is too lean to be flammable under the stated conditions.",
        "The mixture will ignite without an ignition source.",
        "The mixture is necessarily above its upper flammability limit.",
      ],
      correctIndex: 1,
      explanation: "The chapter defines the LFL or LEL as the leanest mixture that is still flammable or explosive. Below that concentration, the mixture is too lean to propagate flame.",
    },
    {
      level: "foundation",
      stem: "Which complete set of elements must be present to sustain combustion under the fire-tetrahedron model?",
      options: [
        "Fuel, oxygen, heat, and a chemical chain reaction",
        "Fuel, water, heat, and nitrogen",
        "Oxygen, pressure, steam, and a spark",
        "Fuel, carbon dioxide, cooling, and a chain reaction",
      ],
      correctIndex: 0,
      explanation: "The chapter presents the fire tetrahedron as fuel, oxygen, heat, and a chain reaction. Removing or interrupting any one of these components can stop sustained combustion.",
    },
    {
      level: "homework-level",
      stem: "A fire involves energized motor-control equipment. Which classification and initial extinguishing-agent concern are most appropriate?",
      options: [
        "Class A; use water as the preferred agent.",
        "Class C; use an agent rated for energized electrical equipment rather than water.",
        "Class D; use ordinary foam because all metals burn alike.",
        "Class K; use a wet-chemical kitchen agent.",
      ],
      correctIndex: 1,
      explanation: "Class C fires involve energized electrical equipment. The chapter specifically cautions that water should not be used on a Class C fire because it presents a shock hazard.",
    },
    {
      level: "homework-level",
      stem: "A sprinkler system is needed in an unheated loading canopy where freezing temperatures are expected. Which system is the best match in the chapter?",
      options: [
        "Wet pipe, because water should remain in the piping at all times",
        "Deluge, because every sprinkler head must remain open continuously",
        "Foam-water, because freezing is eliminated by foam concentrate",
        "Dry pipe, because water is not in the piping until the system is triggered",
      ],
      correctIndex: 3,
      explanation: "The chapter describes dry-pipe systems for areas where freezing could make a water-filled system inoperable. Water is not present in the piping until activation.",
    },
    {
      level: "application",
      stem: "A data center needs automatic fire protection but must minimize the risk of an accidental water discharge. Which sprinkler arrangement is most appropriate?",
      options: [
        "A pre-action system activated by fire detection before water enters the distribution piping",
        "A wet-pipe system with no detection devices",
        "A dry-pipe system that cannot use a water-supply valve",
        "A Class K wet-chemical system for cooking oil",
      ],
      correctIndex: 0,
      explanation: "The source describes pre-action systems as hybrids that use a detection system to open a water-supply valve. They are typically used where accidental discharge is undesirable, including data centers.",
    },
    {
      level: "application",
      stem: "A solvent vapor has a vapor density of 1.6. Where should a ventilation intake be located to best address the expected vapor movement?",
      options: [
        "At the highest point of the room only",
        "Inside a sealed office away from the spill",
        "Near the floor or lower level of the area",
        "Above the roof with no connection to the release area",
      ],
      correctIndex: 2,
      explanation: "The chapter explains that gases and vapors with density greater than or equal to one are heavier than air and tend to sink. For those materials, ventilation should be located near the floor or lower level.",
    },
  ],
  "ch-13": [
    {
      level: "foundation",
      stem: "A worker receives heat from molten metal across open space without direct contact. Which source of body heat is involved?",
      options: [
        "Metabolic heat",
        "Convection",
        "Conduction",
        "Radiation",
      ],
      correctIndex: 3,
      explanation: "Radiant heat is thermal radiation between objects and does not require direct contact. The chapter lists radiation, convection, conduction, and metabolism as sources of heat.",
    },
    {
      level: "homework-level",
      stem: "For indoor work with no solar load, which expression is the chapter's WBGT equation?",
      options: [
        "WBGT = 0.7 WB + 0.2 GT + 0.1 DB",
        "WBGT = 0.7 WB + 0.3 GT",
        "WBGT = WB + GT + DB",
        "WBGT = 0.3 WB + 0.7 DB",
      ],
      correctIndex: 1,
      explanation: "For indoor conditions without solar load, the reference gives WBGT = 0.7 WB + 0.3 GT. The outdoor solar-load equation also includes globe and dry-bulb weighting.",
    },
    {
      level: "application",
      stem: "Which group of measures best reflects the chapter's stated approach to preventing heat-related injuries?",
      options: [
        "A single annual medical exam and no exposure controls",
        "Only insulated clothing, regardless of the task",
        "Physical conditioning, fluid replacement, training, and an appropriate work/rest cycle",
        "Waiting for a heat illness before changing the job",
      ],
      correctIndex: 2,
      explanation: "The chapter identifies physical conditioning, fluid replacement, training, and adherence to a work/rest cycle as measures that prevent heat-related injuries.",
    },
    {
      level: "foundation",
      stem: "Which source of heat is generated inside the body as a result of performing work?",
      options: [
        "Radiation",
        "Convection",
        "Conduction",
        "Metabolic heat",
      ],
      correctIndex: 3,
      explanation: "Metabolic heat is generated from within the body through work. The chapter identifies it as a major concern because it can contribute substantially to body overheating.",
    },
    {
      level: "foundation",
      stem: "Why does high humidity increase heat strain during physically demanding work?",
      options: [
        "It stops the body from producing any sweat.",
        "It decreases sweat evaporation, reducing the body's effective cooling.",
        "It guarantees greater convective cooling.",
        "It prevents metabolic heat from being generated.",
      ],
      correctIndex: 1,
      explanation: "When humidity is high, sweat evaporates less readily. The source explains that if sweat is not removed from the skin by evaporation, it does not effectively cool the body.",
    },
    {
      level: "homework-level",
      stem: "Outdoor work has solar load. The natural wet-bulb temperature is 78°F, globe temperature is 98°F, and dry-bulb temperature is 88°F. What is WBGT using the chapter's outdoor equation?",
      options: [
        "78.0°F",
        "83.0°F",
        "88.0°F",
        "96.0°F",
      ],
      correctIndex: 1,
      explanation: "For outdoor conditions with solar load, WBGT = 0.7 WB + 0.2 GT + 0.1 DB. The calculation is 0.7(78) + 0.2(98) + 0.1(88) = 54.6 + 19.6 + 8.8 = 83.0°F.",
    },
    {
      level: "homework-level",
      stem: "A new employee is beginning work in an extremely hot area. Which acclimatization plan follows the chapter's rule of thumb?",
      options: [
        "Assign full heat exposure on the first day so the worker adapts quickly.",
        "Expose the worker only after a heat illness has occurred.",
        "Keep the worker at exactly the same exposure every day for a month.",
        "Increase exposure or work demand by about 20% each day for 5 days while monitoring the worker.",
      ],
      correctIndex: 3,
      explanation: "The source describes acclimatization as gradual and gives a rule of thumb of approximately 20% more exposure each day for 5 days. New employees should also be closely monitored for heat-related signs and symptoms.",
    },
    {
      level: "application",
      stem: "Cold wind strips the warmed air next to a worker's skin and replaces it with colder air. Which heat-loss mechanism is primarily involved?",
      options: [
        "Convection",
        "Radiation",
        "Conduction",
        "Metabolism",
      ],
      correctIndex: 0,
      explanation: "The chapter explains that convection removes heat when moving air replaces the warmed layer at the body's surface with colder air. Wind chill is a practical example of this mechanism.",
    },
    {
      level: "application",
      stem: "A worker in extreme heat becomes confused, collapses, and has a core temperature above 104°F. How should the condition be treated?",
      options: [
        "As ordinary fatigue; allow the worker to rest alone and return when ready.",
        "As heat rash; dry the skin and continue the task.",
        "As a medical emergency consistent with heat stroke.",
        "As a routine acclimatization response that needs no intervention.",
      ],
      correctIndex: 2,
      explanation: "The source describes heat stroke as a medical emergency. Mental confusion, collapse, and a core temperature above 104°F require immediate emergency response and cooling rather than continued work.",
    },
  ],
};
