import type { FormulaEntry } from "./studyLibraryData";

/**
 * Formula and reference-constant families present in the supplied 23-page
 * ASP Formula Sheet but not covered by the original formula library.
 *
 * The source includes a few rounded constants and legacy/typographical
 * expressions. Those are identified in each card's common-error note rather
 * than silently taught as exact modern values.
 */
export const ADDITIONAL_FORMULA_ENTRIES: readonly FormulaEntry[] = [
  {
    id: "formula-conv-length",
    category: "Conversions",
    name: "Length equivalents",
    formula: "1 in = 2.54 cm; 1 ft = 30.48 cm; 1 μm = 10⁻⁴ cm; 1 mile = 5,280 ft",
    variables: ["in = inch", "ft = foot", "μm = micrometre", "cm = centimetre"],
    units: "in, ft, cm, μm, or mile",
    whenToUse: "Convert linear dimensions before applying area, volume, velocity, or exposure equations.",
    commonError: "Apply a length conversion twice for area and three times for volume; do not use a linear factor unchanged.",
    workedExample: "6 ft × 30.48 cm/ft = 182.88 cm.",
    sourcePage: "ASP Formula Sheet p. 2",
  },
  {
    id: "formula-conv-volume",
    category: "Conversions",
    name: "Litre volume equivalents",
    formula: "1 L = 1.06 qt = 61.02 in³ = 0.03531 ft³",
    variables: ["L = litre", "qt = US liquid quart", "in³ = cubic inch", "ft³ = cubic foot"],
    units: "L, qt, in³, or ft³",
    whenToUse: "Convert liquid or gas volume to the unit system required by a flow, density, or gas-law calculation.",
    commonError: "The quart value is rounded and refers to a US liquid quart, not an imperial quart.",
    workedExample: "2 L × 0.03531 ft³/L = 0.07062 ft³.",
    sourcePage: "ASP Formula Sheet p. 2",
  },
  {
    id: "formula-conv-mass",
    category: "Conversions",
    name: "Mass equivalents",
    formula: "1 kg ≈ 2.2 lb; 1 lb ≈ 454 g",
    variables: ["kg = kilogram", "lb = pound-mass", "g = gram"],
    units: "kg, lbm, or g",
    whenToUse: "Convert mass before using mechanics, dose, concentration, or material-balance equations.",
    commonError: "These PDF values are rounded; distinguish pound-mass from pound-force in mechanics problems.",
    workedExample: "5 kg × 2.2 lb/kg ≈ 11 lb.",
    sourcePage: "ASP Formula Sheet p. 2",
  },
  {
    id: "formula-ref-water-density",
    category: "Reference Constants",
    name: "Density and weight density of water",
    formula: "ρwater = 1 g/cm³ = 1.94 slug/ft³; γwater = 62.4 lbf/ft³",
    variables: ["ρ = mass density", "γ = weight density", "slug = US coherent unit of mass"],
    units: "g/cm³, slug/ft³, or lbf/ft³",
    whenToUse: "Relate water pressure, head, mass, and weight in hydrostatic calculations.",
    commonError: "Mass density ρ and weight density γ are different quantities; γ = ρg.",
    workedExample: "Two cubic feet of water weigh 2 × 62.4 = 124.8 lbf.",
    sourcePage: "ASP Formula Sheet p. 2",
  },
  {
    id: "formula-conv-angle",
    category: "Conversions",
    name: "Radians and degrees",
    formula: "1 rad = 180°/π; θdeg = θrad(180/π)",
    variables: ["θdeg = angle in degrees", "θrad = angle in radians"],
    units: "degrees or radians",
    whenToUse: "Convert angles before evaluating a trigonometric function in the calculator's selected mode.",
    commonError: "A correct equation gives a wrong result when the calculator is in degree mode but the input is radians, or vice versa.",
    workedExample: "π/2 rad × 180°/π = 90°.",
    sourcePage: "ASP Formula Sheet p. 2",
  },
  {
    id: "formula-conv-light",
    category: "Conversions",
    name: "Illuminance equivalents",
    formula: "1 cd = 1 lm/sr; 1 fc = 10.764 lx",
    variables: ["cd = candela", "lm = lumen", "sr = steradian", "fc = foot-candle", "lx = lux"],
    units: "cd, lm/sr, fc, or lx",
    whenToUse: "Convert lighting measurements or relate luminous intensity to flux per solid angle.",
    commonError: "The PDF equates foot-candles with candela/m², which is dimensionally wrong: foot-candle and lux are illuminance; cd/m² is luminance.",
    workedExample: "25 fc × 10.764 lx/fc = 269.1 lx.",
    sourcePage: "ASP Formula Sheet p. 2 (corrected dimensional label)",
  },
  {
    id: "formula-conv-magnetic-field",
    category: "Conversions",
    name: "Tesla and gauss",
    formula: "1 T = 10,000 G",
    variables: ["T = tesla", "G = gauss"],
    units: "T or G",
    whenToUse: "Convert magnetic flux density between SI and cgs-style units.",
    commonError: "Do not confuse gauss, a flux-density unit, with oersted, a magnetic-field-strength unit.",
    workedExample: "0.25 T × 10,000 G/T = 2,500 G.",
    sourcePage: "ASP Formula Sheet p. 2",
  },
  {
    id: "formula-conv-energy-charge",
    category: "Conversions",
    name: "Energy, charge, and power equivalents",
    formula: "1 Btu ≈ 1,055 J; 1 cal = 4.19 J; 1 Fd ≈ 9.65×10⁴ C; 1 Ah = 3,600 C; 1 W = 1 J/s = 1 A·V; 1 kWh = 3.6×10⁶ J",
    variables: ["Btu = British thermal unit", "cal = gram-calorie", "Fd = faraday", "C = coulomb", "Ah = ampere-hour"],
    units: "J, Btu, cal, C, Ah, W, or kWh",
    whenToUse: "Move among thermal, electrical, and mechanical energy or charge units.",
    commonError: "A kilowatt-hour is energy, not power; the PDF values for Btu, calorie, and faraday are rounded.",
    workedExample: "2 kWh × 3.6×10⁶ J/kWh = 7.2×10⁶ J.",
    sourcePage: "ASP Formula Sheet p. 2",
  },
  {
    id: "formula-ref-molar-volume",
    category: "Reference Constants",
    name: "Ideal-gas molar volume at reference conditions",
    formula: "Vm ≈ 22.4 L/mol at 0°C and 1 atm; Vm ≈ 24.45 L/mol at 25°C and 1 atm",
    variables: ["Vm = molar volume", "mol = gram-mole", "atm = atmosphere"],
    units: "L/mol",
    whenToUse: "Select the reference molar volume for gas-volume or ppm–mass concentration conversions.",
    commonError: "Use the value matching the stated temperature; 24.45 L/mol is not the 0°C STP value.",
    workedExample: "At 25°C and 1 atm, 2 mol occupy approximately 2 × 24.45 = 48.90 L.",
    sourcePage: "ASP Formula Sheet pp. 2 and 6 (gas-constant table)",
  },
  {
    id: "formula-ref-physical-constants",
    category: "Reference Constants",
    name: "Physical constants",
    formula: "g₀ = 9.80665 m/s² ≈ 32.2 ft/s²; c = 2.998×10⁸ m/s; h = 6.62607015×10⁻³⁴ J·s; NA = 6.02214076×10²³ mol⁻¹",
    variables: ["g₀ = standard gravity", "c = speed of light", "h = Planck constant", "NA = Avogadro constant"],
    units: "m/s², ft/s², m/s, J·s, or mol⁻¹",
    whenToUse: "Supply a physical constant when it is not given in a quantitative problem.",
    commonError: "The PDF uses rounded values and prints Avogadro's constant as 6.024×10²³; use 6.022×10²³ unless the exam explicitly directs otherwise.",
    workedExample: "A 20 kg mass has standard weight W = 20 × 9.80665 ≈ 196.1 N.",
    sourcePage: "ASP Formula Sheet p. 2 (modern accepted constants shown)",
  },
  {
    id: "formula-ref-standard-conditions",
    category: "Reference Constants",
    name: "Reference standard conditions",
    formula: "Physical-science STP: 0°C, 1 atm; ventilation standard air: 70°F, 1 atm, ρ = 0.075 lb/ft³; IH reference: 25°C, 1 atm",
    variables: ["STP = standard temperature and pressure", "ρ = air density", "IH = industrial hygiene"],
    units: "°C, °F, atm, and lb/ft³",
    whenToUse: "Choose the correct reference basis for gas, ventilation, or industrial-hygiene calculations.",
    commonError: "STP is context-dependent in this sheet; do not use 22.4 L/mol in a 25°C industrial-hygiene conversion.",
    workedExample: "A 25°C, 1-atm vapor conversion uses Vm ≈ 24.45 L/mol rather than 22.4 L/mol.",
    sourcePage: "ASP Formula Sheet p. 2",
  },
  {
    id: "formula-math-right-triangle",
    category: "Mathematics & Logic",
    name: "Right-triangle ratios",
    formula: "sin A = a/c; cos A = b/c; tan A = a/b; a² + b² = c²",
    variables: ["a = side opposite A", "b = side adjacent to A", "c = hypotenuse"],
    units: "Ratios are dimensionless; sides use any consistent length unit",
    whenToUse: "Resolve a right triangle into slopes, forces, heights, or distances.",
    commonError: "Identify the hypotenuse and the angle of interest before labeling opposite and adjacent sides.",
    workedExample: "For a 3–4–5 triangle with a = 3 and b = 4, sin A = 3/5 = 0.60.",
    sourcePage: "ASP Formula Sheet pp. 3 and 12",
  },
  {
    id: "formula-math-law-cosines",
    category: "Mathematics & Logic",
    name: "Law of cosines",
    formula: "c² = a² + b² − 2ab cos C",
    variables: ["a, b, c = triangle side lengths", "C = angle opposite side c"],
    units: "Any consistent length unit; C in calculator-compatible angle units",
    whenToUse: "Solve a non-right triangle when two sides and their included angle, or all three sides, are known.",
    commonError: "The angle C must be opposite c and included between sides a and b.",
    workedExample: "With a = 5, b = 7, and C = 60°, c = √(25 + 49 − 35) = √39 ≈ 6.245.",
    sourcePage: "ASP Formula Sheet p. 3",
  },
  {
    id: "formula-math-law-sines",
    category: "Mathematics & Logic",
    name: "Law of sines",
    formula: "a/sin A = b/sin B = c/sin C",
    variables: ["a, b, c = triangle side lengths", "A, B, C = their opposite angles"],
    units: "Any consistent length unit; sine ratios are dimensionless",
    whenToUse: "Solve an oblique triangle with a known opposite side-angle pair.",
    commonError: "Pair every side with its opposite angle; the SSA case can have two possible triangles.",
    workedExample: "If a = 10, A = 30°, and B = 90°, then b = 10 sin90°/sin30° = 20.",
    sourcePage: "ASP Formula Sheet p. 3",
  },
  {
    id: "formula-logic-boolean-identities",
    category: "Mathematics & Logic",
    name: "Boolean algebra identities",
    formula: "A+B=B+A; A·B=B·A; A(BC)=(AB)C; A+(B+C)=(A+B)+C; A(B+C)=AB+AC; A+BC=(A+B)(A+C); A+0=A; A·1=A; A+Ā=1; A·Ā=0; A+A=A; A·A=A",
    variables: ["+ = logical OR", "· = logical AND", "Ā = logical NOT A", "A, B, C = Boolean variables"],
    units: "Dimensionless binary logic",
    whenToUse: "Simplify logic expressions in controls, fault trees, or digital-system questions.",
    commonError: "The PDF scan corrupts some overbars and identity symbols; use the canonical identities shown here, not the OCR text.",
    workedExample: "A + A·B = A(1 + B) = A by absorption.",
    sourcePage: "ASP Formula Sheet p. 3 (scan-normalized notation)",
  },
  {
    id: "formula-math-quadratic",
    category: "Mathematics & Logic",
    name: "Quadratic formula",
    formula: "x = (−b ± √(b² − 4ac)) / (2a)",
    variables: ["a, b, c = coefficients in ax² + bx + c = 0", "x = solution"],
    units: "Same implied units as the modeled variable",
    whenToUse: "Solve a second-degree equation that does not factor conveniently.",
    commonError: "The entire numerator is divided by 2a; evaluate the discriminant before taking the square root.",
    workedExample: "For x² − 5x + 6 = 0, x = (5 ± 1)/2, so x = 2 or 3.",
    sourcePage: "ASP Formula Sheet p. 3",
  },
  {
    id: "formula-mech-friction",
    category: "Mechanics",
    name: "Friction force",
    formula: "Ff = μN",
    variables: ["Ff = limiting or kinetic friction force", "μ = applicable coefficient of friction", "N = normal force"],
    units: "N or lbf",
    whenToUse: "Estimate sliding resistance or the force required to overcome friction under the stated model.",
    commonError: "N is the normal force, not automatically the object's weight on an incline or under another applied vertical force.",
    workedExample: "With μ = 0.30 and N = 500 N, Ff = 150 N.",
    sourcePage: "ASP Formula Sheet pp. 3 and 14",
  },
  {
    id: "formula-mech-displacement",
    category: "Mechanics",
    name: "Constant-acceleration displacement",
    formula: "s = v₀t + ½at²",
    variables: ["s = displacement", "v₀ = initial velocity", "a = constant acceleration", "t = elapsed time"],
    units: "m, ft, m/s, ft/s, and matching time units",
    whenToUse: "Find displacement over time when acceleration is constant.",
    commonError: "Square only time in the acceleration term, and assign signs consistently with the chosen positive direction.",
    workedExample: "v₀ = 2 m/s, a = 3 m/s², and t = 4 s give s = 8 + 24 = 32 m.",
    sourcePage: "ASP Formula Sheet pp. 3 and 15",
  },
  {
    id: "formula-mech-velocity-distance",
    category: "Mechanics",
    name: "Velocity–distance relation",
    formula: "v² = v₀² + 2as",
    variables: ["v = final velocity", "v₀ = initial velocity", "a = constant acceleration", "s = displacement"],
    units: "m/s or ft/s with a consistent length-time system",
    whenToUse: "Relate speed and displacement when elapsed time is not given.",
    commonError: "Take the physically appropriate square-root sign after solving for v².",
    workedExample: "From rest with a = 2 m/s² over 9 m, v = √(36) = 6 m/s.",
    sourcePage: "ASP Formula Sheet pp. 3 and 15",
  },
  {
    id: "formula-mech-gravitational-pe",
    category: "Mechanics",
    name: "Gravitational potential energy",
    formula: "PEg = mgh",
    variables: ["PEg = gravitational potential energy", "m = mass", "g = gravitational acceleration", "h = vertical height change"],
    units: "J in SI or ft·lbf in US customary units",
    whenToUse: "Calculate energy stored by elevating a mass in an approximately uniform gravitational field.",
    commonError: "Use vertical height, not distance traveled along a ramp.",
    workedExample: "A 10 kg mass raised 3 m gains PEg = 10 × 9.8 × 3 = 294 J.",
    sourcePage: "ASP Formula Sheet p. 3",
  },
  {
    id: "formula-mech-elastic-pe",
    category: "Mechanics",
    name: "Elastic potential energy",
    formula: "PEs = ½kx²",
    variables: ["PEs = elastic potential energy", "k = spring constant", "x = displacement from equilibrium"],
    units: "J when k is N/m and x is m",
    whenToUse: "Estimate energy stored in an ideal linear spring.",
    commonError: "Displacement is squared and must be measured from the spring's equilibrium position.",
    workedExample: "For k = 200 N/m and x = 0.10 m, PEs = ½(200)(0.10²) = 1.0 J.",
    sourcePage: "ASP Formula Sheet p. 3",
  },
  {
    id: "formula-mech-momentum",
    category: "Mechanics",
    name: "Linear momentum",
    formula: "p = mv",
    variables: ["p = linear momentum", "m = mass", "v = velocity"],
    units: "kg·m/s or slug·ft/s",
    whenToUse: "Quantify motion for collision, impulse, or moving-load problems.",
    commonError: "Momentum is a vector; opposite travel directions require opposite signs.",
    workedExample: "A 75 kg worker moving at 4 m/s has p = 300 kg·m/s.",
    sourcePage: "ASP Formula Sheet p. 3",
  },
  {
    id: "formula-elec-resistivity",
    category: "Electricity",
    name: "Conductor resistance from resistivity",
    formula: "R = ρL/A",
    variables: ["R = resistance", "ρ = material resistivity", "L = conductor length", "A = cross-sectional area"],
    units: "Ω when ρ is Ω·m, L is m, and A is m²",
    whenToUse: "Estimate resistance from conductor material and geometry.",
    commonError: "Do not confuse electrical resistivity ρ with density; match area units to the resistivity unit system.",
    workedExample: "ρ = 1.68×10⁻⁸ Ω·m, L = 10 m, and A = 2×10⁻⁶ m² give R = 0.084 Ω.",
    sourcePage: "ASP Formula Sheet p. 3",
  },
  {
    id: "formula-elec-capacitance-networks",
    category: "Electricity",
    name: "Capacitors in series and parallel",
    formula: "1/Cseries = Σ(1/Ci); Cparallel = ΣCi",
    variables: ["Cseries = equivalent series capacitance", "Cparallel = equivalent parallel capacitance", "Ci = individual capacitance"],
    units: "F, μF, or another consistent capacitance unit",
    whenToUse: "Reduce a network of ideal capacitors connected purely in series or parallel.",
    commonError: "Capacitor combination rules are the reverse of resistor rules.",
    workedExample: "6 μF and 3 μF give 2 μF in series and 9 μF in parallel.",
    sourcePage: "ASP Formula Sheet p. 3",
  },
  {
    id: "formula-elec-inductance-networks",
    category: "Electricity",
    name: "Uncoupled inductors in series and parallel",
    formula: "Lseries = ΣLi; 1/Lparallel = Σ(1/Li)",
    variables: ["Lseries = equivalent series inductance", "Lparallel = equivalent parallel inductance", "Li = individual inductance"],
    units: "H, mH, or another consistent inductance unit",
    whenToUse: "Reduce ideal uncoupled inductors connected purely in series or parallel.",
    commonError: "These relations assume negligible mutual magnetic coupling between inductors.",
    workedExample: "2 H and 3 H give 5 H in series and 1.2 H in parallel.",
    sourcePage: "ASP Formula Sheet p. 3",
  },
  {
    id: "formula-ergo-rwl-si-expanded",
    category: "Ergonomics",
    name: "Revised NIOSH lifting equation—SI expansion",
    formula: "RWLkg = 23(25/H)[1−0.003|V−75|][0.82+4.5/D](1−0.0032A)FM·CM",
    variables: ["H, V, D = centimetres", "A = asymmetry angle in degrees", "FM = frequency multiplier", "CM = coupling multiplier"],
    units: "kg",
    whenToUse: "Calculate the recommended weight limit in metric units for a task within the lifting equation's scope.",
    commonError: "Use centimetres in this form and obtain FM and CM from the correct duration, height, frequency, and coupling table cells.",
    workedExample: "At H=25 cm, V=75 cm, D=25 cm, A=0°, FM=1, and CM=1, RWL = 23 kg.",
    sourcePage: "ASP Formula Sheet p. 4",
  },
  {
    id: "formula-ergo-rwl-us-expanded",
    category: "Ergonomics",
    name: "Revised NIOSH lifting equation—US expansion",
    formula: "RWLlb = 51(10/H)[1−0.0075|V−30|][0.82+1.8/D](1−0.0032A)FM·CM",
    variables: ["H, V, D = inches", "A = asymmetry angle in degrees", "FM = frequency multiplier", "CM = coupling multiplier"],
    units: "lb",
    whenToUse: "Calculate the recommended weight limit in US customary units for a task within the equation's scope.",
    commonError: "Do not mix centimetres with the US coefficients; the 51 lb load constant does not make every lift acceptable.",
    workedExample: "At H=10 in, V=30 in, D=10 in, A=0°, FM=1, and CM=1, RWL = 51 lb.",
    sourcePage: "ASP Formula Sheet p. 4",
  },
  {
    id: "formula-ih-mixture-tlv",
    category: "Industrial Hygiene & Gases",
    name: "Equivalent limit for a vapor mixture",
    formula: "TLVm = 1 / Σ(fi/TLVi)",
    variables: ["TLVm = equivalent mixture limit", "fi = component fraction of the mixture", "TLVi = exposure limit for component i"],
    units: "Same concentration unit as the component TLVs",
    whenToUse: "Apply the formula-sheet mixture method when component fractions and compatible vapor limits are given.",
    commonError: "Fractions must sum to 1 and all TLVi values must use the same concentration basis; this is not the usual additive-exposure index Σ(Ci/TLVi).",
    workedExample: "For f1=f2=0.50 with TLV1=100 ppm and TLV2=50 ppm, TLVm=1/(0.005+0.010)=66.7 ppm.",
    sourcePage: "ASP Formula Sheet p. 6",
  },
  {
    id: "formula-ih-mixture-lel",
    category: "Industrial Hygiene & Gases",
    name: "Lower flammable/explosive limit of a gas mixture",
    formula: "LFLm = 1 / Σ(fi/LFLi) (equivalently LELm = 1 / Σ(fi/LELi))",
    variables: ["LFLm/LELm = mixture lower flammable/explosive limit", "fi = fuel fraction among combustible components", "LFLi/LELi = pure-component lower limit"],
    units: "vol% or decimal volume fraction, used consistently",
    whenToUse: "Estimate a multicomponent fuel mixture's LEL using Le Chatelier's mixing rule.",
    commonError: "Use normalized combustible-gas fractions, not each gas's percentage in the total air mixture.",
    workedExample: "For f1=0.60 at LEL1=2% and f2=0.40 at LEL2=4%, LELm=1/(0.30+0.10)=2.5%.",
    sourcePage: "ASP Formula Sheet p. 6",
  },
  {
    id: "formula-vent-total-pressure",
    category: "Ventilation",
    name: "Duct total pressure",
    formula: "TP = SP + VP",
    variables: ["TP = total pressure", "SP = static pressure", "VP = velocity pressure"],
    units: "in. H₂O or Pa, used consistently",
    whenToUse: "Relate the three pressure components at one duct location.",
    commonError: "Preserve the sign of static pressure on the suction side; velocity pressure is nonnegative.",
    workedExample: "SP = −2.0 in. H₂O and VP = 0.5 in. H₂O give TP = −1.5 in. H₂O.",
    sourcePage: "ASP Formula Sheet pp. 6 and 19",
  },
  {
    id: "formula-vent-fan-static-pressure",
    category: "Ventilation",
    name: "Fan static pressure",
    formula: "SPfan = SPout − SPin − VPin",
    variables: ["SPfan = fan static pressure", "SPout = outlet static pressure", "SPin = inlet static pressure", "VPin = inlet velocity pressure"],
    units: "in. H₂O or Pa, used consistently",
    whenToUse: "Determine fan static pressure from inlet and outlet duct measurements under the formula-sheet convention.",
    commonError: "A negative inlet SP is subtracted algebraically; do not discard its sign.",
    workedExample: "SPout=1.5, SPin=−2.0, and VPin=0.5 in. H₂O give SPfan=3.0 in. H₂O.",
    sourcePage: "ASP Formula Sheet pp. 6 and 19",
  },
  {
    id: "formula-vent-hood-entry",
    category: "Ventilation",
    name: "Hood entry coefficient and loss",
    formula: "V = 4005Ce√SPh; Ce = √(VP/SPh); he = [(1−Ce²)/Ce²]VP; SPh = VP + he",
    variables: ["Ce = hood entry coefficient", "SPh = hood static pressure magnitude", "he = hood entry loss", "VP = velocity pressure"],
    units: "V in fpm and pressures in in. H₂O for the 4005 constant",
    whenToUse: "Relate hood static pressure, entry loss, velocity pressure, and entry velocity at standard air density.",
    commonError: "Use the magnitude of suction pressure with these exam relations and do not omit Ce; V=4005√VP is the duct relation.",
    workedExample: "Ce=0.80 and SPh=1.00 in. H₂O give V=3,204 fpm, VP=0.64, and he=0.36 in. H₂O.",
    sourcePage: "ASP Formula Sheet p. 6; velocity relation repeated on p. 19",
  },
  {
    id: "formula-vent-evaporation-dilution",
    category: "Ventilation",
    name: "Dilution flow from liquid evaporation rate",
    formula: "Q = 403×10⁶(SG)(ER)(K)/(MW·C)",
    variables: ["Q = dilution airflow", "SG = liquid specific gravity", "ER = evaporation rate", "K = safety or mixing factor", "MW = molecular weight", "C = target concentration in ppm"],
    units: "cfm under the formula-sheet US-unit convention",
    whenToUse: "Solve the formula-sheet liquid-evaporation dilution problem when inputs use its prescribed US units.",
    commonError: "The coefficient is unit-specific and the PDF does not fully label ER on-page; verify ER units from the problem/reference before using this shortcut.",
    workedExample: "With SG=1, ER=0.001, K=2, MW=100, and C=100 ppm, Q=80.6 cfm under the stated convention.",
    sourcePage: "ASP Formula Sheet p. 6 (unit-specific legacy coefficient)",
  },
  {
    id: "formula-vent-transient-buildup",
    category: "Ventilation",
    name: "Well-mixed contaminant buildup",
    formula: "C(t)=G/Q′+(C₀−G/Q′)e^(−Q′t/V); if C₀=0, C(t)=(G/Q′)[1−e^(−Q′t/V)]",
    variables: ["C(t) = concentration at time t", "C₀ = initial concentration", "G = generation rate", "Q′ = effective clean-air flow", "V = room volume"],
    units: "G/Q sets the concentration basis; Q and V must give inverse-time in the exponent",
    whenToUse: "Estimate approach to steady state in a perfectly mixed room with constant generation and ventilation.",
    commonError: "The PDF prints only a special-case arrangement; retain the C₀ term unless the room starts at zero concentration.",
    workedExample: "If C₀=0, G/Q′=100 ppm, and Q′t/V=1, C=100(1−e⁻¹)=63.2 ppm.",
    sourcePage: "ASP Formula Sheet p. 6 (general initial-condition form supplied)",
  },
  {
    id: "formula-vent-transient-clearance",
    category: "Ventilation",
    name: "Well-mixed concentration change and clearance",
    formula: "ln[(G−Q′C₁)/(G−Q′C₂)] = (Q′/V)(t₂−t₁); when G=0, ln(C₁/C₂)=(Q′/V)Δt",
    variables: ["C₁, C₂ = concentrations at times t₁, t₂", "G = generation rate", "Q′ = effective airflow", "V = room volume"],
    units: "Q′/V in reciprocal time; concentration ratios are dimensionless",
    whenToUse: "Solve time, airflow, or final concentration during a well-mixed transition or post-release purge.",
    commonError: "The PDF's scanned ratio/order can imply the wrong sign; the corrected form must predict decreasing C when G=0.",
    workedExample: "With G=0, Q/V=0.5 h⁻¹, C₁=100 ppm, and Δt=2 h, C₂=100e⁻¹=36.8 ppm.",
    sourcePage: "ASP Formula Sheet p. 6 (ratio/sign normalized to the mass balance)",
  },
  {
    id: "formula-rad-buildup-attenuation",
    category: "Radiation",
    name: "Attenuation with buildup factor",
    formula: "I = βI₀e^(−μx)",
    variables: ["I = transmitted intensity", "I₀ = unshielded intensity", "β = buildup factor", "μ = linear attenuation coefficient", "x = shield thickness"],
    units: "β is dimensionless; μ and x use reciprocal units",
    whenToUse: "Apply an assigned buildup factor to an exponential shielding estimate.",
    commonError: "β depends on energy, material, geometry, and thickness; it is not a universal constant and is normally at least 1.",
    workedExample: "I₀=100, β=2, μ=0.5 cm⁻¹, and x=2 cm give I=200e⁻¹=73.6.",
    sourcePage: "ASP Formula Sheet p. 7",
  },
  {
    id: "formula-rad-nonionizing-aperture",
    category: "Radiation",
    name: "Circular-aperture power density",
    formula: "W = 16P/(πD²) = 4P/A",
    variables: ["W = average power density at the aperture", "P = power", "D = circular aperture diameter", "A = πD²/4"],
    units: "W/m² when P is W and dimensions are m",
    whenToUse: "Estimate average power density over a uniformly illuminated circular aperture using the sheet's relation.",
    commonError: "This aperture-average relation is not the inverse-square far-field equation.",
    workedExample: "P=100 W and D=2 m give W=16(100)/(π·2²)=127.3 W/m².",
    sourcePage: "ASP Formula Sheet p. 7",
  },
  {
    id: "formula-rad-nonionizing-far-field",
    category: "Radiation",
    name: "Far-field RF power density",
    formula: "W = GP/(4πr²) = AP/(λ²r²)",
    variables: ["W = power density", "G = numeric antenna gain", "P = transmitted power", "r = distance", "A = effective aperture", "λ = wavelength"],
    units: "W/m² when P is W and r is m",
    whenToUse: "Estimate far-field power density from an antenna under free-space assumptions.",
    commonError: "Use numeric gain, not gain in dB; the OCR can corrupt the alternate AP/(λ²r²) denominator into unrelated symbols.",
    workedExample: "G=10, P=100 W, and r=10 m give W=1,000/(400π)=0.796 W/m².",
    sourcePage: "ASP Formula Sheet p. 7",
  },
  {
    id: "formula-rad-effective-irradiance",
    category: "Radiation",
    name: "Spectrally weighted effective irradiance",
    formula: "Eeff = Σ(EλSλΔλ)",
    variables: ["Eλ = spectral irradiance", "Sλ = relative spectral effectiveness", "Δλ = wavelength-band width"],
    units: "Effective irradiance, with units determined by Eλ and Δλ",
    whenToUse: "Combine ultraviolet or optical spectral bands using an assigned hazard weighting function.",
    commonError: "Apply Sλ to each band before summing and keep wavelength units consistent with spectral irradiance.",
    workedExample: "Bands (E,S,Δλ)=(4,0.5,1) and (3,0.2,1) give Eeff=2.0+0.6=2.6 effective units.",
    sourcePage: "ASP Formula Sheet p. 7",
  },
  {
    id: "formula-rad-wave-relation",
    category: "Radiation",
    name: "Wave speed, wavelength, and frequency",
    formula: "c = λf = λ/T",
    variables: ["c = wave speed", "λ = wavelength", "f = frequency", "T = period"],
    units: "m/s, m, Hz, and s",
    whenToUse: "Convert wavelength, frequency, or period for electromagnetic radiation.",
    commonError: "Convert nanometres or micrometres to metres before using c in m/s.",
    workedExample: "λ=500 nm and f=6.0×10¹⁴ Hz give c=(5.0×10⁻⁷)(6.0×10¹⁴)=3.0×10⁸ m/s.",
    sourcePage: "ASP Formula Sheet p. 7",
  },
  {
    id: "formula-econ-annuity-future",
    category: "Engineering Economy",
    name: "Uniform-series future worth",
    formula: "F = A[((1+i)ⁿ − 1)/i]",
    variables: ["F = future worth", "A = equal end-of-period payment", "i = interest per period", "n = number of periods"],
    units: "Currency",
    whenToUse: "Accumulate a uniform end-of-period series to the end of period n.",
    commonError: "This is an ordinary annuity; beginning-of-period payments require multiplying the result by (1+i).",
    workedExample: "$1,000 deposited each year for 3 years at 5% accumulates to $3,152.50.",
    sourcePage: "ASP Formula Sheet pp. 7 and 22",
  },
  {
    id: "formula-econ-annuity-present",
    category: "Engineering Economy",
    name: "Uniform-series present worth",
    formula: "P = A[((1+i)ⁿ − 1)/(i(1+i)ⁿ)]",
    variables: ["P = present worth", "A = equal end-of-period payment", "i = interest per period", "n = number of periods"],
    units: "Currency",
    whenToUse: "Discount a uniform end-of-period payment series to time zero.",
    commonError: "Do not use the future-worth annuity factor when the requested equivalent date is today.",
    workedExample: "$1,000 per year for 3 years discounted at 5% has P≈$2,723.25.",
    sourcePage: "ASP Formula Sheet pp. 7 and 22",
  },
  {
    id: "formula-econ-capital-recovery",
    category: "Engineering Economy",
    name: "Capital recovery payment",
    formula: "A = P[i(1+i)ⁿ/((1+i)ⁿ − 1)]",
    variables: ["A = equal end-of-period payment", "P = present principal", "i = interest per period", "n = periods"],
    units: "Currency per period",
    whenToUse: "Convert present capital into an equivalent uniform repayment series.",
    commonError: "Match the interest period to the payment period and enter percentage rates as decimals.",
    workedExample: "$10,000 recovered over 5 years at 6% requires A≈$2,373.96 per year.",
    sourcePage: "ASP Formula Sheet pp. 7 and 22",
  },
  {
    id: "formula-noise-acoustic-intensity",
    category: "Noise",
    name: "Plane-wave acoustic intensity",
    formula: "I = pᵣₘₛ²/(ρc)",
    variables: ["I = acoustic intensity", "pᵣₘₛ = root-mean-square sound pressure", "ρ = medium density", "c = sound speed"],
    units: "W/m² when p is Pa, ρ is kg/m³, and c is m/s",
    whenToUse: "Relate RMS pressure to intensity for a progressive plane wave.",
    commonError: "Pressure must be squared; the PDF scan/extraction makes the superscript easy to miss.",
    workedExample: "p=2 Pa, ρ=1.2 kg/m³, and c=343 m/s give I=4/411.6=0.00972 W/m².",
    sourcePage: "ASP Formula Sheet p. 7 (superscript restored)",
  },
  {
    id: "formula-noise-sound-power-level",
    category: "Noise",
    name: "Sound power level",
    formula: "LW = 10log₁₀(W/W₀)",
    variables: ["LW = sound power level", "W = sound power", "W₀ = reference sound power, commonly 10⁻¹² W"],
    units: "dB",
    whenToUse: "Express a source's sound power as a logarithmic level.",
    commonError: "The PDF summary mislabels LW as sound pressure level; sound power uses 10log, while pressure uses 20log.",
    workedExample: "W=10⁻⁶ W and W₀=10⁻¹² W give LW=10log₁₀(10⁶)=60 dB.",
    sourcePage: "ASP Formula Sheet pp. 7 and 21 (label corrected)",
  },
  {
    id: "formula-noise-sound-pressure-level",
    category: "Noise",
    name: "Sound pressure level",
    formula: "Lp = 20log₁₀(p/p₀)",
    variables: ["Lp = sound pressure level", "p = RMS sound pressure", "p₀ = reference pressure, 20 μPa in air"],
    units: "dB",
    whenToUse: "Convert an RMS acoustic pressure ratio to decibels.",
    commonError: "Use 20log for pressure amplitude and 10log for power or intensity.",
    workedExample: "p=0.2 Pa and p₀=20 μPa give Lp=20log₁₀(10,000)=80 dB.",
    sourcePage: "ASP Formula Sheet pp. 7 and 21",
  },
  {
    id: "formula-noise-dose-sum",
    category: "Noise",
    name: "Cumulative noise dose",
    formula: "D = 100Σ(Ci/Ti)",
    variables: ["D = dose percent", "Ci = actual exposure time at level i", "Ti = allowable time at that level"],
    units: "%",
    whenToUse: "Combine multiple noise-level intervals under one criterion and exchange-rate scheme.",
    commonError: "Every Ti must come from the same criterion level and exchange rate used for the dose assessment.",
    workedExample: "2 h where 4 h is allowed plus 4 h where 8 h is allowed gives D=100(2/4+4/8)=100%.",
    sourcePage: "ASP Formula Sheet p. 7",
  },
  {
    id: "formula-noise-absorption-change",
    category: "Noise",
    name: "Level reduction from added room absorption",
    formula: "NR = 10log₁₀(A₂/A₁)",
    variables: ["NR = estimated level reduction", "A₁ = original total absorption", "A₂ = revised total absorption"],
    units: "dB; A values in consistent sabin units",
    whenToUse: "Estimate reverberant-field level reduction after changing a room's total absorption.",
    commonError: "The result is a reduction magnitude when A₂>A₁; reversing the ratio changes the sign.",
    workedExample: "Doubling absorption from 100 to 200 sabins gives NR=10log₁₀2=3.01 dB.",
    sourcePage: "ASP Formula Sheet p. 7",
  },
  {
    id: "formula-noise-lined-duct",
    category: "Noise",
    name: "Lined-duct attenuation estimate",
    formula: "NR/L = 12.6Pα¹·⁴/A",
    variables: ["NR/L = attenuation per duct length", "P = lined perimeter", "α = absorption coefficient", "A = duct cross-sectional area"],
    units: "dB/ft when P and A are in compatible foot units",
    whenToUse: "Apply the formula-sheet empirical estimate for attenuation in a lined duct.",
    commonError: "P is perimeter, not acoustic power or pressure; this empirical relation is geometry- and lining-dependent.",
    workedExample: "P=10 ft, α=0.50, and A=4 ft² give NR/L≈11.9 dB/ft by the sheet equation.",
    sourcePage: "ASP Formula Sheet p. 7",
  },
  {
    id: "formula-heat-conduction",
    category: "Heat Transfer",
    name: "Steady one-dimensional conduction",
    formula: "H = Q/t = kA(T₁−T₂)/L",
    variables: ["H = heat-transfer rate", "Q = heat transferred", "k = thermal conductivity", "A = area", "L = thickness"],
    units: "W in SI when k is W/(m·K), A is m², and L is m",
    whenToUse: "Estimate steady conduction through a plane homogeneous layer.",
    commonError: "This simplified form assumes constant k, one-dimensional flow, and steady conditions; use temperature difference, not absolute temperature.",
    workedExample: "k=0.5 W/(m·K), A=10 m², ΔT=20 K, and L=0.2 m give H=500 W.",
    sourcePage: "ASP Formula Sheet p. 7",
  },
  {
    id: "formula-hyd-pressure",
    category: "Hydraulics",
    name: "Pressure from force and area",
    formula: "p = F/A",
    variables: ["p = pressure", "F = normal force", "A = loaded area"],
    units: "Pa=N/m² or psi=lbf/in²",
    whenToUse: "Convert a distributed normal load into average pressure.",
    commonError: "Use the area normal to the force and convert squared length units correctly.",
    workedExample: "1,000 N over 0.010 m² produces p=100,000 Pa=100 kPa.",
    sourcePage: "ASP Formula Sheet p. 7",
  },
  {
    id: "formula-hyd-pressure-head",
    category: "Hydraulics",
    name: "Pressure head",
    formula: "hp = p/γ",
    variables: ["hp = pressure head", "p = pressure", "γ = fluid weight density"],
    units: "ft of fluid or m of fluid",
    whenToUse: "Express fluid pressure as an equivalent column height.",
    commonError: "Divide by weight density γ, not mass density ρ, unless g is included separately.",
    workedExample: "Water pressure of 624 lbf/ft² divided by 62.4 lbf/ft³ equals 10 ft of head.",
    sourcePage: "ASP Formula Sheet p. 7",
  },
  {
    id: "formula-hyd-velocity-head",
    category: "Hydraulics",
    name: "Velocity head",
    formula: "hv = v²/(2g)",
    variables: ["hv = velocity head", "v = mean fluid velocity", "g = gravitational acceleration"],
    units: "m or ft with a consistent unit system",
    whenToUse: "Express kinetic energy per unit weight as a fluid head.",
    commonError: "Velocity is squared; do not substitute volumetric flow without first dividing by area.",
    workedExample: "At v=10 m/s, hv=100/(2×9.8)=5.10 m.",
    sourcePage: "ASP Formula Sheet p. 7",
  },
  {
    id: "formula-hyd-static-residual-flow",
    category: "Hydraulics",
    name: "Fire-flow extrapolation from static and residual pressure",
    formula: "Q₂ = Q₁[(S−R₂)/(S−R₁)]⁰·⁵⁴",
    variables: ["Q₁ = measured flow", "Q₂ = predicted flow", "S = static pressure", "R₁, R₂ = residual pressures"],
    units: "Any consistent flow and pressure units",
    whenToUse: "Extrapolate available hydrant or water-supply flow to a different residual pressure using the sheet's empirical exponent.",
    commonError: "Use pressure drops S−R, not residual pressures alone; preserve the 0.54 exponent.",
    workedExample: "Q₁=500 gpm, S=100 psi, R₁=80 psi, and R₂=60 psi give Q₂=500(2⁰·⁵⁴)≈727 gpm.",
    sourcePage: "ASP Formula Sheet pp. 7 and 17",
  },
  {
    id: "formula-hyd-bernoulli-loss",
    category: "Hydraulics",
    name: "Extended Bernoulli equation with head loss",
    formula: "vA²/(2g)+pA/γ+zA = vB²/(2g)+pB/γ+zB+hAB",
    variables: ["v = mean velocity", "p = pressure", "γ = fluid weight density", "z = elevation head", "hAB = head loss from A to B"],
    units: "Every term expressed as length of fluid",
    whenToUse: "Balance mechanical energy between two points in steady incompressible flow with losses.",
    commonError: "Keep one elevation datum and one gauge/absolute pressure convention; head loss is positive in the flow direction.",
    workedExample: "From a reservoir surface 20 m above an outlet with 5 m loss and equal atmospheric pressure, vB=√[2g(15)]≈17.1 m/s.",
    sourcePage: "ASP Formula Sheet p. 7",
  },
  {
    id: "formula-hyd-system-curve",
    category: "Hydraulics",
    name: "Quadratic flow–pressure relation",
    formula: "P = (Q/K)²",
    variables: ["P = pressure or head-loss term", "Q = flow", "K = system coefficient for the selected units"],
    units: "Determined by the definition and units of K",
    whenToUse: "Model a resistance-dominated system where pressure loss varies approximately with flow squared.",
    commonError: "K is unit- and system-specific; this is not a universal pump curve and may require a static-head term.",
    workedExample: "If Q=500 and K=50 in compatible units, P=(500/50)²=100 pressure units.",
    sourcePage: "ASP Formula Sheet p. 7",
  },
  {
    id: "formula-stat-population-sd",
    category: "Statistics & Probability",
    name: "Population standard deviation",
    formula: "σ = √[Σ(xi−μ)²/N]",
    variables: ["σ = population standard deviation", "xi = observation", "μ = population mean", "N = population size"],
    units: "Same as the observations",
    whenToUse: "Measure dispersion when the data constitute the full population of interest.",
    commonError: "Use N for a population; the sample estimator uses n−1.",
    workedExample: "For population {2,4,6}, μ=4 and σ=√(8/3)=1.633.",
    sourcePage: "ASP Formula Sheet p. 8",
  },
  {
    id: "formula-stat-pearson-correlation",
    category: "Statistics & Probability",
    name: "Pearson product–moment correlation",
    formula: "x=X−X̄; y=Y−Ȳ; r = [NΣXY−(ΣX)(ΣY)]/√{[NΣX²−(ΣX)²][NΣY²−(ΣY)²]} = Σxy/√[(Σx²)(Σy²)]",
    variables: ["X,Y = paired observations", "x=X−X̄ and y=Y−Ȳ", "N = number of pairs", "r = correlation coefficient"],
    units: "Dimensionless, from −1 to +1",
    whenToUse: "Measure the strength and direction of a linear association between paired quantitative variables.",
    commonError: "Correlation does not establish causation and can be distorted by outliers or nonlinear relationships.",
    workedExample: "Pairs (1,2), (2,4), and (3,6) lie exactly on a positive line, so r=1.00.",
    sourcePage: "ASP Formula Sheet p. 8",
  },
  {
    id: "formula-stat-spearman-rank",
    category: "Statistics & Probability",
    name: "Spearman rank correlation without ties",
    formula: "rs = 1 − 6ΣDi²/[N(N²−1)]",
    variables: ["rs = Spearman rank coefficient", "Di = difference between paired ranks", "N = number of pairs"],
    units: "Dimensionless, from −1 to +1",
    whenToUse: "Measure monotonic association from ranks when the no-ties shortcut applies.",
    commonError: "Tied ranks require average ranks and, for exact work, a tie-aware correlation calculation.",
    workedExample: "With N=5 and ΣD²=2, rs=1−12/[5(24)]=0.90.",
    sourcePage: "ASP Formula Sheet p. 8",
  },
  {
    id: "formula-stat-chi-square",
    category: "Statistics & Probability",
    name: "Pearson chi-square statistic",
    formula: "χ² = Σ[(Oj−Ej)²/Ej]",
    variables: ["Oj = observed count in cell j", "Ej = expected count in cell j"],
    units: "Dimensionless",
    whenToUse: "Compare observed categorical counts with expected counts in a goodness-of-fit or contingency-table test.",
    commonError: "Use counts rather than percentages and check that expected counts and degrees-of-freedom assumptions are appropriate.",
    workedExample: "Observed {40,60} versus expected {50,50} gives χ²=100/50+100/50=4.00.",
    sourcePage: "ASP Formula Sheet p. 8; critical-value table p. 11",
  },
  {
    id: "formula-stat-permutations",
    category: "Statistics & Probability",
    name: "Permutations",
    formula: "nPk = n!/(n−k)!",
    variables: ["n = available distinct items", "k = ordered selections", "! = factorial"],
    units: "Count",
    whenToUse: "Count selections when order matters and items are not replaced.",
    commonError: "Use combinations, not permutations, when different orders represent the same outcome.",
    workedExample: "Five candidates filling two distinct offices can be arranged in 5P2=5!/3!=20 ways.",
    sourcePage: "ASP Formula Sheet p. 8",
  },
  {
    id: "formula-stat-combinations",
    category: "Statistics & Probability",
    name: "Combinations",
    formula: "nCk = n!/[k!(n−k)!]",
    variables: ["n = available distinct items", "k = unordered selections", "! = factorial"],
    units: "Count",
    whenToUse: "Count selections when order does not matter and items are not replaced.",
    commonError: "Do not multiply by k! after using the combination formula; that would turn the result into permutations.",
    workedExample: "Choosing 2 committee members from 5 gives 5C2=5!/(2!3!)=10.",
    sourcePage: "ASP Formula Sheet p. 8",
  },
] as const;

export const ADDITIONAL_FORMULA_ENTRY_IDS = ADDITIONAL_FORMULA_ENTRIES.map(
  ({ id }) => id,
) as readonly string[];
