import type { BilingualText } from "./hazardData";
import type { SceneOverlay, SceneShape, SceneVisualizationConfig } from "./hazardTypes";

const t = (en: string, ar: string): BilingualText => ({ en, ar });
const ellipse = (cx: number, cy: number, rx: number, ry: number): SceneShape => ({ type: "ellipse", cx, cy, rx, ry });
const path = (d: string, arrow = false): SceneShape => ({ type: "path", d, arrow });
const rect = (x: number, y: number, width: number, height: number): SceneShape => ({ type: "rect", x, y, width, height });
const overlay = (id: string, label: BilingualText, description: BilingualText, role: SceneOverlay["role"], semantic: SceneOverlay["semantic"], point: SceneOverlay["point"], shapes: SceneShape[], extra: Partial<SceneOverlay> = {}): SceneOverlay => ({ id, label, description, role, semantic, point, shapes, ...extra, ...(extra.marker ? { marker: [Math.max(100, Math.min(900, extra.marker[0])), Math.max(100, Math.min(900, extra.marker[1]))] as const } : {}) });

/** Educational geometry, not calculated boundaries, force vectors, dose or incident energy. */
export const HAZARD_SCENES = {
  arc: {
    kind: "worker-scene", status: "implemented", template: "electrical-panel-worker",
    description: t("Worker beside an open electrical cabinet. Select the arc source, heat, light, pressure or secondary impact.", "عامل بجانب لوحة كهربائية مفتوحة. اختر مصدر القوس أو الحرارة أو الضوء أو الضغط أو الصدمة الثانوية."),
    overlays: [
      overlay("arc-source", t("Arc event / source", "حدث القوس / المصدر"), t("An electric arc releases energy from energized equipment. The burst marks the source, not an incident-energy calculation.", "يطلق القوس الكهربائي طاقة من معدات مكهربة. يحدد الوميض المصدر ولا يمثل حسابًا لطاقة الحادث."), "primary", "source", [575, 435], [{ type: "burst", cx: 575, cy: 435, radius: 110 }], { energy: "electrical", marker: [760, 320] }),
      overlay("thermal-exposure", t("Thermal exposure", "التعرض الحراري"), t("Heat can reach the worker and ignite clothing, causing severe burns.", "قد تصل الحرارة إلى العامل وتشعل الملابس وتسبب حروقًا شديدة."), "primary", "worker", [330, 420], [ellipse(325, 425, 135, 160), path("M565 435 Q470 340 350 380", true)], { energy: "thermal", marker: [155, 400], consequences: [t("Severe burns.", "حروق شديدة.")] }),
      overlay("intense-light", t("Intense light", "الضوء الشديد"), t("Light from the arc can injure the eyes. The line identifies the exposure direction.", "قد يؤذي ضوء القوس العينين. يوضح الخط اتجاه التعرض."), "secondary", "path", [345, 210], [path("M575 435 L345 210", true)], { marker: [180, 180], consequences: [t("Eye injury.", "إصابة العين.")] }),
      overlay("blast-pressure", t("Blast / pressure", "الانفجار / الضغط"), t("A pressure wave can reach nearby workers. The illustrated wave is qualitative.", "قد تصل موجة ضغط إلى العاملين القريبين. الموجة المرسومة توضيحية فقط."), "secondary", "path", [490, 555], [path("M550 345 Q365 440 520 590"), path("M515 310 Q275 440 470 645"), path("M535 470 L370 530", true)], { marker: [725, 615], consequences: [t("Pressure-related trauma or hearing injury.", "إصابة بسبب الضغط أو إصابة السمع.")] }),
      overlay("secondary-impact", t("Secondary impact", "الصدمة الثانوية"), t("Loss of balance or displacement may cause a fall or impact with surrounding objects.", "قد يؤدي فقدان التوازن أو الإزاحة إلى السقوط أو الاصطدام بالأجسام المحيطة."), "possible", "zone", [255, 880], [ellipse(265, 895, 150, 55)], { marker: [135, 785], consequences: [t("Fall or impact injury.", "إصابة بسبب السقوط أو الاصطدام.")] }),
    ],
  },
  scaffold: {
    kind: "worker-scene", status: "implemented", template: "scaffold-worker",
    description: t("An elevated worker on a scaffold with an open front edge. Paths and zones identify potential falls and falling objects.", "عامل على سقالة مرتفعة ذات حافة أمامية مفتوحة. تحدد المسارات والمناطق السقوط المحتمل وسقوط الأجسام."),
    overlays: [
      overlay("unprotected-edge", t("Unprotected edge", "الحافة غير المحمية"), t("The highlighted opening has no guardrail in this example. Protection must suit the scaffold and work.", "الفتحة المحددة بلا حاجز حماية في هذا المثال. يجب أن تناسب الحماية السقالة والعمل."), "primary", "source", [610, 365], [path("M445 365 L685 383"), rect(550, 230, 140, 140)], { marker: [805, 300] }),
      overlay("fall-path", t("Fall path", "مسار السقوط"), t("A worker can pass beyond the open edge and strike a lower level. This is a possible trajectory, not a calculated fall distance.", "قد يتجاوز العامل الحافة المفتوحة ويصطدم بمستوى أدنى. هذا مسار محتمل وليس حسابًا لمسافة السقوط."), "primary", "path", [620, 375], [path("M620 375 C800 405 820 660 785 840", true)], { energy: "gravity", marker: [830, 490], consequences: [t("Serious injury or death from a fall.", "إصابة خطيرة أو وفاة بسبب السقوط.")] }),
      overlay("lower-level", t("Lower-level impact zone", "منطقة الاصطدام بالمستوى الأدنى"), t("The shaded landing area identifies a possible impact location below the opening.", "تحدد المنطقة المظللة موضع اصطدام محتمل أسفل الفتحة."), "primary", "zone", [775, 870], [ellipse(765, 870, 100, 45)], { marker: [815, 935] }),
      overlay("falling-object-zone", t("Falling-object zone", "منطقة سقوط الأجسام"), t("Tools or materials may fall to people below. Edge containment and restricting access below address this separate hazard.", "قد تسقط الأدوات أو المواد على أشخاص في الأسفل. يعالج احتواء الأجسام عند الحافة وتقييد الدخول أسفلها هذا الخطر المنفصل."), "secondary", "zone", [540, 875], [ellipse(520, 880, 145, 45), path("M585 390 L585 835", true)], { energy: "gravity", marker: [410, 940] }),
      overlay("worker", t("Worker at elevation", "العامل على ارتفاع"), t("Worker position relates the open edge to the work area; the illustration is not an approved scaffold design.", "يربط موضع العامل الحافة المفتوحة بمنطقة العمل؛ الرسم ليس تصميمًا معتمدًا للسقالة."), "possible", "worker", [510, 225], [ellipse(510, 220, 65, 150)], { marker: [750, 115] }),
    ],
  },
  forklift: {
    kind: "equipment-scene", status: "implemented", template: "forklift-warehouse",
    description: t("A counterbalance forklift with an elevated load, operator and nearby pedestrian. Select stability, movement or crush-zone overlays.", "رافعة شوكية موازنة تحمل حمولة مرتفعة مع مشغل وشخص قريب. اختر طبقات الثبات أو الحركة أو منطقة السحق."),
    overlays: [
      overlay("unstable-load", t("High / unstable load", "حمولة مرتفعة / غير مستقرة"), t("Load height and distribution affect stability. Travel with an elevated load can increase the risk of overturning.", "يؤثر ارتفاع الحمولة وتوزيعها في الثبات. قد يزيد السير بحمولة مرتفعة خطر الانقلاب."), "primary", "equipment", [210, 230], [rect(40, 65, 300, 325)], { energy: "gravity", marker: [470, 155] }),
      overlay("center-of-gravity", t("Raised center of gravity", "ارتفاع مركز الثقل"), t("Raising the load moves the combined center of gravity upward and forward. This marker is illustrative, not a computed balance point.", "يرفع رفع الحمولة مركز الثقل المشترك ويحركه للأمام. العلامة توضيحية وليست نقطة اتزان محسوبة."), "primary", "condition", [420, 515], [ellipse(420, 515, 38, 38), path("M420 690 L420 475", true)], { energy: "gravity", marker: [650, 330] }),
      overlay("turn-speed", t("Turn / speed", "الانعطاف / السرعة"), t("Abrupt turning, acceleration or braking can shift the combined center of gravity and destabilize the truck.", "قد يغير الانعطاف أو التسارع أو الفرملة المفاجئة مركز الثقل المشترك ويخل بثبات الرافعة."), "secondary", "path", [575, 885], [path("M350 910 Q570 970 740 865", true)], { energy: "mechanical", marker: [540, 965] }),
      overlay("tip-zone", t("Tip direction / crush zone", "اتجاه الانقلاب / منطقة السحق"), t("Loss of stability can overturn the truck into the shaded area. The zone is conceptual and is not a clearance specification.", "قد يؤدي فقدان الثبات إلى انقلاب الرافعة نحو المنطقة المظللة. المنطقة مفاهيمية وليست مواصفة لمسافة أمان."), "primary", "zone", [795, 870], [ellipse(795, 890, 125, 48), path("M630 470 Q880 525 795 840", true)], { marker: [865, 950], consequences: [t("Crushing injuries to the operator or people nearby.", "إصابات سحق للمشغل أو الأشخاص القريبين.")] }),
      overlay("pedestrian", t("Pedestrian interaction", "التفاعل مع المشاة"), t("People near the truck may be struck by the truck or load. Separate pedestrian and vehicle movement.", "قد تصدم الرافعة أو الحمولة الأشخاص القريبين. افصل حركة المشاة عن حركة المركبات."), "secondary", "worker", [885, 640], [ellipse(885, 650, 62, 195)], { marker: [925, 440] }),
      overlay("slope-edge", t("Ramp / slope / edge", "منحدر / ميل / حافة"), t("Not active in this scene. The same template can display a configured grade or edge for another scenario.", "غير نشط في هذا المشهد. يمكن للقالب نفسه عرض ميل أو حافة عند إعداد سيناريو آخر."), "inactive", "condition", [320, 890], [path("M170 900 L370 840 L475 900")], { marker: [120, 870] }),
    ],
  },
  confined: {
    kind: "process-diagram", status: "implemented", template: "confined-space-vessel",
    description: t("Cutaway vessel with entrant, attendant, monitor, isolation valve and ventilation. Equipment shown does not establish safe entry.", "وعاء بمقطع توضيحي مع داخل ومراقب وجهاز قياس وصمام عزل وتهوية. وجود المعدات في الرسم لا يثبت أمان الدخول."),
    overlays: [
      overlay("atmosphere", t("Oxygen-deficient atmosphere", "جو ناقص الأكسجين"), t("Insufficient oxygen can incapacitate or kill an entrant. Shading identifies the atmosphere; oxygen deficiency is not visible.", "قد يؤدي نقص الأكسجين إلى عجز الداخل أو وفاته. يحدد التظليل الجو؛ نقص الأكسجين لا يُرى."), "primary", "condition", [435, 515], [rect(305, 315, 260, 540)], { energy: "atmospheric", marker: [200, 325], consequences: [t("Incapacitation, asphyxiation or death.", "العجز أو الاختناق أو الوفاة.")] }),
      overlay("monitor", t("Atmospheric monitor", "جهاز قياس الجو"), t("Test and monitor conditions under the entry program. A drawn monitor does not confirm acceptable conditions.", "افحص الظروف وراقبها وفق برنامج الدخول. وجود جهاز مرسوم لا يؤكد أن الظروف مقبولة."), "secondary", "control", [335, 625], [rect(312, 595, 40, 55)], { marker: [185, 740] }),
      overlay("ventilation", t("Ventilation", "التهوية"), t("The airflow path follows the duct into the vessel. Ventilation does not replace hazard evaluation, isolation or verification.", "يتبع مسار الهواء الخرطوم إلى داخل الوعاء. لا تحل التهوية محل تقييم المخاطر أو العزل أو التحقق."), "secondary", "control", [555, 565], [path("M850 865 Q655 895 650 640 L640 290 Q620 180 560 285 L555 710", true)], { marker: [715, 620] }),
      overlay("isolation", t("Isolation point", "نقطة العزل"), t("Connected equipment and material sources need appropriate isolation. The valve symbol alone is not proof of isolation.", "تحتاج المعدات المتصلة ومصادر المواد إلى عزل مناسب. رمز الصمام وحده ليس دليلًا على العزل."), "secondary", "control", [140, 515], [ellipse(140, 520, 55, 65)], { marker: [100, 520] }),
      overlay("entrant", t("Entrant / exposure", "الداخل / التعرض"), t("The worker is within the process boundary. This educational cutaway is not permission to enter a hazardous atmosphere.", "العامل داخل حدود العملية. هذا المقطع التعليمي ليس إذنًا بدخول جو خطر."), "primary", "worker", [440, 670], [ellipse(440, 675, 55, 165)], { marker: [585, 935] }),
      overlay("entry-rescue", t("Entry / rescue concept", "مفهوم الدخول / الإنقاذ"), t("Plan entry, egress and rescue before work. Rescue equipment and arrangements must suit the space and hazards.", "خطط للدخول والخروج والإنقاذ قبل العمل. يجب أن تناسب معدات وترتيبات الإنقاذ المكان والمخاطر."), "possible", "path", [435, 260], [path("M440 535 L440 100", true), ellipse(435, 260, 83, 24)], { marker: [250, 135] }),
      overlay("attendant", t("Attendant", "المراقب"), t("The attendant remains outside the space and supports communication and the planned emergency response.", "يبقى المراقب خارج المكان ويدعم الاتصال والاستجابة المخططة للطوارئ."), "secondary", "control", [745, 245], [ellipse(745, 235, 62, 150)], { marker: [900, 165] }),
    ],
  },
  loto: {
    kind: "process-diagram", status: "implemented", template: "loto-energy-machine",
    note: t("Arrows identify potential energy connections, not energized status or verified isolation.", "تحدد الأسهم وصلات الطاقة المحتملة، ولا تثبت حالة التشغيل أو تحقق العزل."),
    description: t("Electrical, hydraulic and pneumatic energy paths meet a motor and pump. Isolation, lockout, residual energy and verification are separate selectable concepts.", "تصل مسارات طاقة كهربائية وهيدروليكية وهوائية إلى محرك ومضخة. العزل والقفل والطاقة المتبقية والتحقق مفاهيم منفصلة قابلة للاختيار."),
    overlays: [
      overlay("electrical-energy", t("Electrical energy", "الطاقة الكهربائية"), t("Trace the electrical supply through its disconnect toward the motor. The path identifies a source that requires control.", "تتبع الإمداد الكهربائي عبر جهاز الفصل نحو المحرك. يحدد المسار مصدرًا يحتاج إلى التحكم."), "primary", "path", [150, 215], [path("M30 215 L110 215"), path("M245 210 L360 210 L460 300", true)], { energy: "electrical", marker: [90, 75] }),
      overlay("hydraulic-energy", t("Hydraulic energy", "الطاقة الهيدروليكية"), t("Fluid pressure can remain after shutdown. The illustrated valve and flow identify another energy source.", "قد يبقى ضغط السائل بعد الإيقاف. يحدد الصمام والمسار المرسومان مصدر طاقة آخر."), "primary", "path", [150, 495], [path("M25 495 L105 495"), path("M225 515 L290 515 L290 890 L935 890 L935 560", true)], { energy: "hydraulic", marker: [80, 415] }),
      overlay("pneumatic-energy", t("Pneumatic energy", "الطاقة الهوائية"), t("Compressed gas is a separate source. Identify isolation and release arrangements in the equipment-specific procedure.", "الغاز المضغوط مصدر منفصل. حدد ترتيبات العزل والتفريغ في الإجراء الخاص بالمعدات."), "secondary", "path", [150, 735], [path("M25 735 L105 735"), path("M220 745 L255 745 L255 940 L970 940 L970 650", true)], { energy: "pneumatic", marker: [80, 880] }),
      overlay("isolation-device", t("Isolation device / lockout", "جهاز العزل / القفل"), t("Energy-isolating devices separate equipment from sources. Locks and tags identify and secure the isolation under the applicable procedure.", "تفصل أجهزة عزل الطاقة المعدات عن المصادر. تحدد الأقفال والوسوم العزل وتؤمّنه وفق الإجراء المعمول به."), "secondary", "control", [235, 255], [rect(205, 210, 58, 190)], { marker: [365, 115] }),
      overlay("stored-energy", t("Stored / residual energy", "الطاقة المخزنة / المتبقية"), t("Stored energy can remain in the accumulator or moving parts after sources are isolated. Address it before servicing.", "قد تبقى طاقة مخزنة في المراكم أو الأجزاء المتحركة بعد عزل المصادر. عالجها قبل الصيانة."), "primary", "condition", [875, 225], [ellipse(875, 225, 55, 90)], { energy: "hydraulic", marker: [905, 95], consequences: [t("Unexpected movement or release of pressure.", "حركة غير متوقعة أو انطلاق ضغط.")] }),
      overlay("verification", t("Verification", "التحقق"), t("Before servicing, verify isolation and control of energy using the equipment-specific procedure. A stopped machine is not sufficient evidence.", "قبل الصيانة، تحقق من العزل والتحكم في الطاقة باستخدام الإجراء الخاص بالمعدات. توقف الآلة وحده ليس دليلًا كافيًا."), "secondary", "control", [485, 345], [ellipse(485, 345, 67, 43)], { marker: [625, 165] }),
      overlay("equipment", t("Equipment / unexpected movement", "المعدات / الحركة غير المتوقعة"), t("The coupled motor and pump connect the energy paths to equipment where servicing exposes a worker to movement or pressure.", "يربط المحرك والمضخة المقترنان مسارات الطاقة بالمعدات التي قد يتعرض العامل عند صيانتها للحركة أو الضغط."), "possible", "equipment", [650, 540], [ellipse(650, 540, 110, 100)], { energy: "mechanical", marker: [650, 815] }),
    ],
  },
  radiation: {
    kind: "concept-diagram", status: "implemented", template: "radiation-source-shield-worker",
    description: t("Source on the left, shield in the middle and worker on the right. Explore time, distance and shielding; no dose or exposure limit is calculated.", "المصدر يسارًا والدرع في الوسط والعامل يمينًا. استكشف الزمن والمسافة والتدريع؛ لا تُحسب جرعة أو حد تعرض."),
    overlays: [
      overlay("time", t("TIME · Less time", "الزمن · وقت أقل"), t("Reducing time near a radiation source reduces accumulated exposure, with other conditions unchanged.", "تقليل الوقت قرب مصدر إشعاع يقلل التعرض المتراكم مع ثبات الظروف الأخرى."), "primary", "principle", [865, 530], [ellipse(865, 535, 75, 270)], { energy: "radiation", icon: "clock", marker: [825, 130] }),
      overlay("distance", t("DISTANCE · Farther away", "المسافة · ابتعد أكثر"), t("Increasing distance from the source reduces exposure. This drawing is not a scale or dose calculation.", "زيادة المسافة عن المصدر تقلل التعرض. هذا الرسم ليس مقياسًا أو حسابًا للجرعة."), "secondary", "principle", [490, 905], [path("M200 905 L845 905", true), path("M200 880 L200 930 M845 880 L845 930")], { energy: "radiation", icon: "distance", marker: [490, 890] }),
      overlay("shielding", t("SHIELDING · Between source and worker", "التدريع · بين المصدر والعامل"), t("Place suitable shielding between source and worker. Material and thickness depend on the radiation and task.", "ضع تدريعًا مناسبًا بين المصدر والعامل. تعتمد المادة والسماكة على الإشعاع والمهمة."), "secondary", "principle", [530, 495], [rect(410, 225, 240, 560), path("M295 665 L408 575", true), path("M295 665 L408 675", true), path("M295 665 L408 770", true)], { energy: "radiation", icon: "shield", marker: [520, 115] }),
      overlay("radiation-source", t("Ionizing radiation source", "مصدر إشعاع مؤين"), t("The source is shown for orientation. Exposure can damage tissue and increase cancer risk; the image does not specify source activity.", "يظهر المصدر لتوضيح الموضع. قد يضر التعرض بالأنسجة ويزيد خطر السرطان؛ لا يحدد الرسم نشاط المصدر."), "possible", "source", [280, 670], [ellipse(195, 675, 145, 135)], { energy: "radiation", marker: [185, 490], consequences: [t("Tissue damage and increased cancer risk.", "تضرر الأنسجة وزيادة خطر السرطان.")] }),
    ],
  },
} satisfies Record<string, SceneVisualizationConfig>;
