/**
 * Original study notes informed by the chapter-end priorities in the supplied
 * W. David Yates, Safety Professional's Reference and Study Guide (3rd ed.).
 * These are independent learning aids, not a reproduction of the book.
 */

export type KeyInformationChapter = {
  chapter: number;
  title: string;
  takeaways: readonly string[];
};

export const KEY_INFORMATION: readonly KeyInformationChapter[] = [
  { chapter: 1, title: "The Safety Profession and Exam Preparation", takeaways: ["Match your study plan to the current exam blueprint and your weakest domains.", "Use active retrieval, timed practice, and error review instead of passive rereading.", "Verify certification eligibility, application requirements, and examination policies from BCSP."] },
  { chapter: 2, title: "Regulations", takeaways: ["Know the OSH Act framework: duties, rights, inspections, citations, and appeals.", "Connect HazCom, bloodborne pathogens, energy control, confined spaces, PPE, respirators, falls, and recordkeeping to their practical employer duties.", "Distinguish an OSHA recordable case from first aid, and calculate rates from actual hours worked."] },
  { chapter: 3, title: "Math Review", takeaways: ["Apply the order of operations before entering a calculation.", "Preserve units, signs, exponents, and scientific notation through every step.", "Rearrange the governing equation before substituting values, then perform a reasonableness check."] },
  { chapter: 4, title: "Particulates and Gases", takeaways: ["Use absolute temperature and pressure in gas-law calculations.", "Separate concentration units, exposure limits, and flammability limits; each answers a different question.", "For mixtures, evaluate the combined contribution rather than treating each component in isolation."] },
  { chapter: 5, title: "Toxicology", takeaways: ["Exposure route, dose, duration, and target organ shape toxic effect and control strategy.", "Differentiate acute from chronic effects, local from systemic effects, and additive from interactive chemical effects.", "Use epidemiologic and toxicologic evidence carefully; association alone does not establish causation."] },
  { chapter: 6, title: "Industrial Hygiene Air Sampling", takeaways: ["Start with anticipation and recognition, then select sampling that answers the exposure question.", "Personal sampling should represent the breathing zone and task pattern of the worker.", "Calibrate pumps, document conditions, and protect sample integrity so the result is defensible."] },
  { chapter: 7, title: "Ventilation", takeaways: ["Select local exhaust when a contaminant can be captured at its source; dilution is not a universal substitute.", "Keep airflow, pressure, hood, duct, and fan relationships clear when diagnosing a system.", "Verify performance by measurement, not by assuming installed ventilation is effective."] },
  { chapter: 8, title: "Noise and Hearing Conservation", takeaways: ["Noise dose depends on both sound level and duration, and decibels combine logarithmically.", "Control noise at the source or along the path before relying only on hearing protection.", "A hearing-conservation program requires exposure assessment, audiometry, training, protection, and follow-up."] },
  { chapter: 9, title: "Biological Hazards", takeaways: ["Assess the agent, task, route of transmission, and susceptible population together.", "Break the chain of infection through containment, hygiene, safe work practices, immunization where appropriate, and PPE.", "Treat bloodborne and airborne exposures as time-sensitive events requiring a defined response process."] },
  { chapter: 10, title: "Fire Protection and Prevention", takeaways: ["Fire prevention controls fuel, ignition, and oxidizer conditions before a fire starts.", "Choose suppression, alarm, evacuation, and emergency actions based on the hazard and training level.", "Classify hazards correctly before selecting an extinguisher or fixed fire-protection system."] },
  { chapter: 11, title: "Thermal Stressors", takeaways: ["Heat strain depends on environment, metabolic workload, clothing, acclimatization, and individual factors.", "Use work-rest cycles, hydration, acclimatization, shade or cooling, and monitoring as an integrated heat-stress plan.", "Cold stress can impair judgment and dexterity before severe injury becomes obvious."] },
  { chapter: 12, title: "Personal Protective Equipment", takeaways: ["PPE is the final layer of control, not the first substitute for eliminating or engineering out a hazard.", "Selection must follow a documented hazard assessment and account for fit, compatibility, limitations, and maintenance.", "Respiratory protection requires the correct device, medical evaluation, fit testing when required, training, and program oversight."] },
  { chapter: 13, title: "Statistics for the Safety Professional", takeaways: ["Choose the statistic that fits the data type and decision being made.", "Separate descriptive measures from inference, and do not confuse correlation with causation.", "Report rates and comparisons with their denominator, time period, and limitations visible."] },
  { chapter: 14, title: "Electrical Safety", takeaways: ["Electrical injury severity depends on current path, duration, voltage, environment, and available fault energy.", "De-energization and verified energy isolation are preferred over exposure to energized parts.", "Use grounding, bonding, overcurrent protection, guarding, and qualified-person practices together."] },
  { chapter: 15, title: "Mechanics", takeaways: ["Force, work, energy, power, momentum, and friction should be tied to the actual system boundary.", "Draw the problem, identify knowns and unknowns, and keep vectors and units consistent.", "Use conservative assumptions when mechanics informs a safety decision."] },
  { chapter: 16, title: "Hydrostatics and Hydraulics", takeaways: ["Fluid pressure rises with depth, and flow behavior changes with area, velocity, and resistance.", "Stored hydraulic energy can remain hazardous after motion stops; isolate, relieve, and verify zero energy.", "Check pressure ratings, hose condition, fittings, and leaks before work begins."] },
  { chapter: 17, title: "Training", takeaways: ["Training begins with a performance need, not simply a presentation or attendance record.", "Define observable objectives, use an appropriate delivery method, and verify learning and transfer to the job.", "Supervision, feedback, and reinforcement keep trained behaviors in place."] },
  { chapter: 18, title: "Engineering Economics", takeaways: ["Compare alternatives over matching time periods and use the time value of money deliberately.", "Present value, future value, annual worth, and return measures answer different decision questions.", "Include safety benefits, uncertainty, and lifecycle effects instead of relying only on purchase price."] },
  { chapter: 19, title: "Management Theories", takeaways: ["Management systems perform best when leadership, accountability, worker participation, and feedback are connected.", "Motivation is not one-size-fits-all; meaningful work, recognition, capability, and conditions influence performance.", "Use continuous-improvement cycles to turn safety information into action and verification."] },
  { chapter: 20, title: "Accident Causation and Investigation Techniques", takeaways: ["Investigate to learn and prevent recurrence, not to stop at the last visible error.", "Preserve evidence, establish the timeline, identify contributing conditions, and test causal explanations.", "Corrective actions should address system controls and be verified for effectiveness."] },
  { chapter: 21, title: "Workers' Compensation", takeaways: ["Workers' compensation rules are jurisdiction-specific and generally operate on a no-fault basis for covered work injuries.", "Prevention, early reporting, appropriate care, and safe return-to-work reduce human and financial loss.", "Experience modifiers reflect loss experience but never replace hazard control."] },
  { chapter: 22, title: "Ergonomics", takeaways: ["Design work for neutral posture, manageable force, reduced repetition, and adequate recovery.", "Use ergonomic assessment tools as screening aids, then validate the real task and worker conditions.", "Redesign the task, tool, workstation, or material flow before depending on individual technique alone."] },
  { chapter: 23, title: "Construction Safety", takeaways: ["Construction controls must address changing conditions, multiple employers, competent-person duties, and site coordination.", "Prioritize falls, excavation, lifting, scaffolds, electrical work, hot work, and moving equipment.", "Inspect before use, establish exclusion zones, and stop work when protective systems are inadequate."] },
  { chapter: 24, title: "Risk Assessment and Management", takeaways: ["Risk combines likelihood and consequence; rank it only after the scenario and assumptions are explicit.", "Identify hazards first, then select controls using the hierarchy and feasibility criteria.", "Implement, communicate, supervise, and reassess controls because risk changes with the work."] },
  { chapter: 25, title: "Hazardous Materials Management", takeaways: ["Classify chemical and physical hazards before storage, handling, transport, or emergency planning decisions.", "Use labels, safety data sheets, training, compatibility controls, monitoring, and decontamination as an integrated program.", "Know the roles of RCRA, CERCLA, EPCRA, HazCom, and HAZWOPER without treating compliance as the only objective."] },
  { chapter: 26, title: "Radiation Safety", takeaways: ["For ionizing radiation, reduce exposure through time, distance, shielding, and source control.", "Match dosimetry, monitoring, shielding, and PPE to the radiation type and energy.", "Nonionizing radiation and lasers require their own exposure controls, especially for eye and skin protection."] },
  { chapter: 27, title: "Walking and Working Surfaces", takeaways: ["Maintain safe access, housekeeping, ladder use, scaffold condition, and fall protection before elevated work starts.", "Prevent falls where possible; use passive prevention before personal fall arrest.", "Include falling-object protection and rescue planning whenever people can be exposed below or after a fall."] },
  { chapter: 28, title: "Materials Handling and Storage", takeaways: ["Reduce manual handling through layout, mechanical aids, packaging, and load design.", "Operate powered industrial trucks only with trained operators, suitable equipment, and controlled travel routes.", "Store materials so stability, access, fire protection, and traffic hazards remain controlled."] },
  { chapter: 29, title: "Safety Management System", takeaways: ["A safety management system needs policy, planning, implementation, evaluation, and management review.", "Worker participation and leadership accountability are operating requirements, not decorative statements.", "Use leading and lagging information to learn, prioritize, and improve the system."] },
  { chapter: 30, title: "Site Security", takeaways: ["Use layered security: people, procedures, physical barriers, lighting, access control, and monitoring.", "Plan for workplace violence through prevention, reporting, threat assessment, response, and recovery.", "Security controls should protect people while preserving emergency access and operational practicality."] },
  { chapter: 31, title: "Behavior-Based Safety", takeaways: ["Observe behavior to understand work conditions and strengthen safe choices, not to assign blame.", "Feedback must be timely, specific, respectful, and connected to barriers workers can actually change.", "Trend observations alongside system conditions; behavior data alone cannot explain every incident."] },
  { chapter: 32, title: "Measuring Health and Safety Performance", takeaways: ["Use leading indicators to monitor prevention work and lagging indicators to understand outcomes.", "A useful measure is valid, understandable, timely, and tied to a decision or corrective action.", "Avoid rewarding low reporting or treating a zero-injury number as proof that risk is absent."] },
  { chapter: 33, title: "Safety Program Auditing Techniques and Checklist", takeaways: ["An audit evaluates management-system conformance and effectiveness more deeply than a routine inspection.", "Define scope, criteria, evidence, findings, owners, due dates, and follow-up before the audit begins.", "Independence and objectivity improve credibility, while verification closes the corrective-action loop."] },
  { chapter: 34, title: "Environmental Management", takeaways: ["Identify environmental aspects, legal duties, operational controls, monitoring needs, and emergency conditions.", "Prevent pollution at the source where possible rather than managing waste after it is created.", "Use objectives, records, audits, and management review to drive measurable environmental improvement."] },
  { chapter: 35, title: "BCSP Code of Ethics", takeaways: ["Protect people, act within competence, communicate truthfully, and avoid conflicts that compromise professional judgment.", "Maintain confidentiality while escalating imminent or serious hazards through appropriate channels.", "Document decisions and seek qualified help when a problem exceeds your authority or expertise."] },
];
