export type BodySystemId = "brain" | "lungs" | "heart" | "liver" | "kidneys" | "digestive" | "skin" | "blood" | "systemic";

export type BodySystem = { id: BodySystemId; label: string; shortLabel: string; color: string };

export const BODY_SYSTEMS: readonly BodySystem[] = [
  { id: "brain", label: "Brain & nervous system", shortLabel: "Brain", color: "#8655a8" },
  { id: "lungs", label: "Lungs & airways", shortLabel: "Lungs", color: "#438aa3" },
  { id: "heart", label: "Heart & circulation", shortLabel: "Heart", color: "#d8655d" },
  { id: "liver", label: "Liver", shortLabel: "Liver", color: "#b9863a" },
  { id: "kidneys", label: "Kidneys", shortLabel: "Kidneys", color: "#4e789b" },
  { id: "digestive", label: "Digestive system", shortLabel: "Digestive", color: "#d17c56" },
  { id: "blood", label: "Blood & lymphatic system", shortLabel: "Blood", color: "#b74e64" },
  { id: "skin", label: "Skin & mucosa", shortLabel: "Skin", color: "#ce7f75" },
  { id: "systemic", label: "Whole-body / systemic", shortLabel: "Systemic", color: "#6a947b" },
] as const;

export type QuestionSceneKind = "ladder-rule" | "ladder-platform" | "crane-vault" | "crane-side-pull" | "excavation-rain" | "excavation-wall" | "biosafety-cabinet" | "bio-routes" | "cadmium-kidney" | "asbestos-synergy";
export type SceneHotspot = { id: string; label: string; observation: string; x: number; y: number };
export type QuestionScene = { kind: QuestionSceneKind; title: string; beforePrompt: string; afterPrompt: string; answerConnection: string; hotspots: readonly SceneHotspot[] };

const scene = (kind: QuestionSceneKind, title: string, beforePrompt: string, afterPrompt: string, answerConnection: string, hotspots: readonly SceneHotspot[]): QuestionScene => ({ kind, title, beforePrompt, afterPrompt, answerConnection, hotspots });

const SCENES: Readonly<Record<string, QuestionScene>> = {
  "D1-012": scene("excavation-rain", "Excavation after rainfall", "Inspect the changing conditions. Select each observation that would change the decision before anyone enters.", "The scene now marks the evidence that turns this into a stop-and-reassess decision.", "Fresh edge cracking, rain-affected conditions, and spoil close to the edge are coupled warning signs. The safe first action is to stop entry and have the excavation reassessed before work continues.", [
    { id: "crack", label: "Fresh edge crack", observation: "A new crack parallel to the edge can indicate ground movement and loss of support.", x: 43, y: 32 }, { id: "rain", label: "Overnight rain", observation: "Rain can change soil behavior and the reliability of yesterday’s inspection.", x: 77, y: 20 }, { id: "spoil", label: "Spoil surcharge", observation: "Material close to the edge adds load where the ground is already showing distress.", x: 24, y: 43 }, { id: "entry", label: "Worker entry", observation: "Entry is the exposure that must be controlled while the condition is uncertain.", x: 53, y: 70 },
  ]),
  "D1-015": scene("ladder-platform", "Choose the work position", "Compare the worker’s task with each access option. Which one actually supports the work, not only the climb?", "The highlighted task demands show why an access ladder and a work platform are not interchangeable.", "A 40-minute, two-handed task with several tools calls for a stable work position. The scene separates climbing access from a platform that supports the worker and materials.", [
    { id: "hands", label: "Two-handed task", observation: "The task itself requires both hands, so a handhold cannot be assumed available.", x: 67, y: 39 }, { id: "tools", label: "Tools to carry", observation: "Tools change the access and work-position demands.", x: 72, y: 63 }, { id: "duration", label: "40-minute duration", observation: "Duration changes a brief climb into sustained elevated work.", x: 48, y: 22 }, { id: "platform", label: "Supported work surface", observation: "A platform can provide a stable surface for the actual task when properly selected and used.", x: 27, y: 61 },
  ]),
  "D1-016": scene("crane-vault", "Crane lift beside a utility vault", "Trace the load through the ground. What information is missing even though the chart shows crane capacity margin?", "The active evidence shows why chart capacity alone cannot clear the lift.", "The load chart addresses the crane configuration, not unknown vault-roof capacity or ground bearing strength. The next step is verification by qualified people before the lift proceeds.", [
    { id: "load", label: "Suspended load", observation: "The load is transmitted through the crane supports into the ground.", x: 59, y: 67 }, { id: "outrigger", label: "Outrigger reaction", observation: "Ground pressure concentrates beneath the crane support points.", x: 27, y: 79 }, { id: "vault", label: "Unknown vault roof", observation: "A buried structure can have a load limit that a crane chart does not describe.", x: 62, y: 82 }, { id: "ground", label: "Unverified bearing", observation: "Soil strength and support conditions must be verified for this specific setup.", x: 82, y: 78 },
  ]),
  "D1-030": scene("ladder-rule", "Set the ladder base", "Move the base and watch the ratio. The upper support is 20 ft above the base level—where does a 4-to-1 setup place the feet?", "The measurement is now locked to the 4-to-1 result.", "For every 4 ft of working length to the upper support, set the base 1 ft out. At 20 ft, the correct horizontal distance is 5 ft.", [
    { id: "height", label: "20 ft vertical rise", observation: "This is the measurement the rule uses as the four-part height.", x: 75, y: 34 }, { id: "base", label: "Base distance", observation: "Drag this position to test the horizontal one-part distance.", x: 35, y: 80 }, { id: "ratio", label: "4 : 1 relationship", observation: "The rule is a relationship between vertical rise and horizontal setback.", x: 52, y: 48 },
  ]),
  "D1-036": scene("crane-side-pull", "Keep the load vertical", "Toggle the proposed movement. What changes when the hook is no longer directly over the load?", "The side-pull vector is exposed: the planned movement is no longer a normal vertical lift.", "Dragging the suspended load sideways creates unplanned side loading. Reposition the crane or use equipment designed for horizontal movement rather than relying on chart margin.", [
    { id: "hook", label: "Hook line", observation: "A normal lift keeps the line aligned over the load.", x: 55, y: 31 }, { id: "vector", label: "Side-pull force", observation: "A horizontal component appears when the load is dragged sideways.", x: 68, y: 62 }, { id: "load", label: "Load path", observation: "The intended final position does not make an unplanned travel path safe.", x: 78, y: 78 }, { id: "exclusion", label: "Worker exposure", observation: "Workers near a moving suspended load are exposed to crush and struck-by hazards.", x: 31, y: 77 },
  ]),
  "D1-047": scene("excavation-wall", "Excavation beside masonry", "Select the wall-side conditions that standard soil sloping does not resolve.", "The highlighted structure-ground relationship is why this needs qualified engineering input.", "Unknown footing geometry, adjacent surcharge, soil movement, support/underpinning, sequencing, and monitoring are a coupled soil-structure problem—not a routine sloping decision.", [
    { id: "wall", label: "Masonry wall", observation: "Older masonry can be especially sensitive to movement when its support conditions change.", x: 22, y: 35 }, { id: "footing", label: "Unknown footing", observation: "The depth and geometry of support are unknown in the question.", x: 32, y: 75 }, { id: "cut", label: "Excavation cut", observation: "Excavation can remove lateral or bearing support close to the wall.", x: 56, y: 69 }, { id: "monitor", label: "Monitoring point", observation: "Movement thresholds must be planned before work begins, not after damage is observed.", x: 42, y: 29 },
  ]),
  "HW-CH07-02": scene("asbestos-synergy", "Asbestos + tobacco co-exposure", "Select the two exposures in the question, then inspect what the combined-risk prompt is actually asking.", "The two highlighted exposures are a classic synergy example—not merely two unrelated respiratory irritants.", "The question asks for the classic co-exposure with a synergistic increase in lung-cancer risk among asbestos-exposed workers: tobacco smoke.", [
    { id: "asbestos", label: "Asbestos fibers", observation: "The existing occupational exposure named in the stem.", x: 28, y: 50 }, { id: "smoke", label: "Tobacco smoke", observation: "The co-exposure whose interaction is being tested.", x: 67, y: 34 }, { id: "lungs", label: "Shared target tissue", observation: "The question concerns a combined effect on lung-cancer risk.", x: 52, y: 60 },
  ]),
  "HW-CH07-06": scene("cadmium-kidney", "Cadmium target-organ clue", "Select the highlighted structure in the kidney model. Which organ-system clue is the question asking you to recognize?", "The model isolates the renal-tubule clue behind the correct option.", "Occupational cadmium exposure is classically associated with early chronic renal tubular injury, making kidneys—particularly renal tubules—the strongest answer.", [
    { id: "kidney", label: "Kidney", observation: "The target organ named by the chronic-exposure clue.", x: 48, y: 56 }, { id: "tubules", label: "Renal tubules", observation: "The question is more specific than a generic organ label.", x: 63, y: 62 }, { id: "exposure", label: "Chronic exposure", observation: "The timing cue distinguishes the target-organ relationship being tested.", x: 30, y: 28 },
  ]),
  "RV-CH07-05": scene("cadmium-kidney", "Cadmium and protein in urine", "Follow the clue from protein in urine to the target organ. Select the relevant structure.", "The selected evidence connects proteinuria with renal tubular injury.", "Protein in urine after chronic cadmium exposure strongly points to kidney injury, particularly renal tubular damage.", [
    { id: "kidney", label: "Kidney", observation: "The organ most directly supported by the question’s finding.", x: 48, y: 56 }, { id: "tubules", label: "Renal tubules", observation: "Cadmium’s classic early chronic target-organ effect involves these structures.", x: 63, y: 62 }, { id: "urine", label: "Urinary finding", observation: "Proteinuria is evidence, not a separate exposure route.", x: 35, y: 77 },
  ]),
  "HW-CH11-07": scene("biosafety-cabinet", "Trace the cabinet airflow", "Turn on airflow and trace what happens to particles before they leave the cabinet. Which component is actually tested?", "The exhaust path is now highlighted from the work zone through the final filter.", "The question asks which technology removes airborne particles from biological-safety-cabinet exhaust air: HEPA filtration.", [
    { id: "workzone", label: "Work opening", observation: "Airflow control starts at the opening where the work is performed.", x: 38, y: 60 }, { id: "plenum", label: "Cabinet airflow path", observation: "Particles are carried through a designed internal path rather than left to room dilution.", x: 58, y: 46 }, { id: "hepa", label: "HEPA exhaust filter", observation: "This is the named technology in the correct answer.", x: 74, y: 27 },
  ]),
  "RV-CH11-03": scene("biosafety-cabinet", "Control aerosol-generating work", "Trace the aerosol from the specimen. Which piece of equipment provides the primary containment described in the options?", "The cabinet’s containment path is shown around the aerosol-generating work step.", "For aerosol-generating work with human blood, an appropriate certified biological safety cabinet is the direct primary-containment control in the correct option.", [
    { id: "aerosol", label: "Aerosol-generating step", observation: "The task—not the specimen’s appearance—creates the airborne exposure concern.", x: 39, y: 63 }, { id: "workzone", label: "Primary containment", observation: "The cabinet surrounds and controls the immediate work zone.", x: 57, y: 48 }, { id: "hepa", label: "Filtered exhaust", observation: "Cabinet design includes a controlled exhaust path.", x: 74, y: 27 },
  ]),
  "HW-CH11-09": scene("bio-routes", "Routes of biological entry", "Select every body entry route shown in the scene, then compare the complete set with the answer choices.", "The highlighted routes match the recognized occupational entry routes in the correct list.", "Recognized routes include inhalation, ingestion, mucous-membrane or skin contact, and inoculation—not hearing, vibration, radiation, or temperature change.", [
    { id: "airway", label: "Inhalation", observation: "Airborne material can enter through the respiratory tract.", x: 50, y: 30 }, { id: "mucosa", label: "Mucous membrane", observation: "Eyes, nose, and mouth are exposure surfaces, not just skin.", x: 38, y: 22 }, { id: "skin", label: "Skin contact", observation: "Vulnerable or broken skin can be relevant to the task and agent.", x: 29, y: 61 }, { id: "inoculation", label: "Inoculation", observation: "Percutaneous exposure can occur through a sharps injury such as a needlestick.", x: 72, y: 59 }, { id: "ingestion", label: "Ingestion", observation: "Hand-to-mouth transfer is a recognized route in the right conditions.", x: 59, y: 38 },
  ]),
  "HW-CH11-10": scene("biosafety-cabinet", "Containment layers", "Select the layers around the work. Which answer includes practices, safety equipment, and facility design together?", "The nested layers show why a label or employee immunity alone is not containment.", "Containment is a coordinated system of work practices, safety equipment or primary barriers, and facility design or secondary controls that limits exposure and release.", [
    { id: "practice", label: "Work practices", observation: "The worker’s method is one layer of the containment system.", x: 34, y: 69 }, { id: "barrier", label: "Safety equipment", observation: "Primary barriers control the immediate task exposure.", x: 56, y: 48 }, { id: "facility", label: "Facility design", observation: "Secondary containment extends beyond one piece of equipment.", x: 79, y: 28 },
  ]),
};

export function getQuestionScene(questionId?: string): QuestionScene | undefined { return questionId ? SCENES[questionId] : undefined; }

export const HAZARD_BODY_SYSTEMS: Readonly<Record<string, readonly BodySystemId[]>> = {
  "bio-anthrax": ["lungs", "skin"], "bio-brucellosis": ["systemic"], "bio-leptospirosis": ["kidneys", "liver"], "bio-plague": ["systemic"], "bio-tetanus": ["brain"], "bio-tuberculosis": ["lungs"], "bio-tularemia": ["systemic", "lungs"], "bio-cat-scratch-disease": ["blood"], "bio-hepatitis-a": ["liver"], "bio-hepatitis-b": ["liver", "blood"], "bio-orf": ["skin"], "bio-rabies": ["brain"], "bio-psittacosis": ["lungs"], "bio-rocky-mountain-spotted-fever": ["systemic", "skin"], "bio-q-fever": ["systemic", "lungs", "liver", "heart"], "bio-aspergillosis": ["lungs"], "bio-candidiasis": ["skin"], "bio-coccidioidomycosis": ["lungs"], "bio-histoplasmosis": ["lungs"],
  "tox-asbestos": ["lungs"], "tox-benzene": ["blood"], "tox-cotton-dust": ["lungs"], "tox-arsenic": ["skin", "brain", "liver"], "tox-beryllium": ["lungs"], "tox-cadmium": ["kidneys", "lungs"], "tox-hexavalent-chromium": ["skin", "lungs"], "tox-coal-dust": ["lungs"], "tox-cobalt": ["lungs", "skin"], "tox-formaldehyde": ["lungs", "skin"], "tox-lead": ["brain", "kidneys", "blood"], "tox-mercury": ["brain"], "tox-manganese": ["brain"], "tox-silica": ["lungs"], "tox-zinc-fumes": ["lungs"], "tox-aluminum-dust": ["lungs"], "tox-antimony": ["lungs", "heart", "digestive"], "tox-organophosphate-carbamate-pesticides": ["brain", "lungs", "digestive"],
};
export function getHazardBodySystems(hazardId: string): readonly BodySystemId[] { return HAZARD_BODY_SYSTEMS[hazardId] ?? ["systemic"]; }
